### ISSUE TITLE
How to sort ES6 getters?

### ISSUE THREAD

**Issue by dugokontov** [yannickcr/eslint-plugin-react#100]
If I extend `React.Component` using ES6 classes, how can I set `order` of `react/sort-comp` to put getters before render? For example 

``` js
import React from 'react';

class Test extends React.Component {
    get something() {
        return 'something';
    }

    render() {
        const options = this.something;
        return <span>{options}</span>;
    }
}
```

**Comment by yannickcr** [comment]
`react/sort-comp` do not take the method type (`static`, `get`, `set`) into account, the sorting rule is only based on the method name (here `something`). So for now you do not have the possibility to "force" the getters to be before the render method, unless you use a different naming convention for setters, getters, etc.

Maybe it can be a future rule enhancement.

**Comment by dugokontov** [comment]
It would be nice to have this enhancement, since it is hard to force some naming convention for properties.

**Comment by djalmajr** [comment]
+1

**Comment by lencioni** [comment]
I did something similar for static methods in #429, if you are looking for an example of how this might be accomplished.

**Comment by aequasi** [comment]
Oy yeah. Unfortunate. I have a lot of getters and setters that i dont want to be randomly sorted throughout my class.
