### ISSUE TITLE
Rule proposal: disallow accessing `this` in `getDefaultProps`

### ISSUE THREAD

**Issue by mlee** [yannickcr/eslint-plugin-react#1001]
`getDefaultProps` is called before there is a component instance; `this` does not reference the component instance, resulting in the following problem:

```
const MyComponent = React.createClass({
  propTypes: {
    onClose: React.PropTypes.func
  },

  getDefaultProps() {
    return {
      onClose: this.doSomething // this.doSomething is undefined!
    };
  },

  doSomething() {
    ...
  },

  render() {
    ...
  }
});
```

**Comment by ljharb** [comment]
Wouldn't this throw the instant the component is used to create an element? Given that `React.createClass` is deprecated over `class`-based components, is it worth adding a lint rule specifically for a legacy form?

**Comment by mlee** [comment]
If it's a requirement that a rule apply to `class`-based components then I am happy to close this issue.

**Comment by ljharb** [comment]
@mlee it's not at all a requirement! I'm mainly asking how valuable this will be, given that anyone using `React.createClass` is already ignoring best practices.

**Comment by TheSavior** [comment]
I know that many prefer using the `class` syntax over the `React.createClass` syntax but I have not seen anything official say that createClass approach is deprecated or not "best practice".

Here are the references to `createClass` I was able to find in the docs, none of which seem to imply what you are saying. 

https://facebook.github.io/react/docs/react-api.html#components
https://facebook.github.io/react/docs/react-without-es6.html

**Comment by ljharb** [comment]
Fair enough. I assumed they were officially deprecated, but it seems only unofficially. createClass components are much much slower than other components because of the autobinding, so it's not just syntax.

At any rate I'm still not saying we can't have a createClass rule, I'm just questioning the value of this one in particular.
