### ISSUE TITLE
[react/prop-types][react/no-unused-prop-types] ignores props in function of element inside jsx attributes

### ISSUE THREAD

**Issue by umidbekkarimov** [yannickcr/eslint-plugin-react#1012]
Here how ide highligts errors

<img width="447" alt="screen shot 2017-01-03 at 20 19 38" src="https://cloud.githubusercontent.com/assets/4734297/21614228/1060c09a-d1f2-11e6-8b5d-3cc2ec4a1290.png">

Code
```
import React from 'react'

export const Foo = (props) => (
    <div
        bar={props.bar}
        onClick={() => props.bar(props.baz)}
    />
)

export const Hello = (props) => {
    return (
        <div foo={(
            <div
                bar={props.bar}
                onClick={() => props.bar(props.baz)}
            />
        )}>

            <div>
                <div onClick={() => props.quoz()}/>
            </div>
        </div>
    )
}
```

**Comment by alex-deas** [comment]
I also get the same issue which looks to be related:

```javascript
type Option =
    {|
        value: string;
        id: string;
    |}

type PropType =
    {|
        someText: string;
        someMoreText: string;
        options: Option[];
    |}

const Component = (props: PropType) => (
    <div>
        { props.someText }
        { props.options.map(({ value, id }) =>
            <span key={id}>{value}</span>
            <span>{props.someMoreText}</span>
        }
    </div>
)
```

eslint will raise an error for the values destructured by mapping over `options` and for `props.someMoreText`.

Destructuring `props` resolves the issue. Although it's not idea as I like to make the source of values transparent.

**Comment by ljharb** [comment]
@umidbekkarimov can you provide command line output? How your IDE highlights things is an issue with your IDE; only the command line is important here.

@alex-deas I believe there might already be an open issue specifically around nested flow types, and another around prop usage inside callbacks.

**Comment by umidbekkarimov** [comment]
@ljharb oh, guess it fixed already, can not reproduce it
