### ISSUE TITLE
react/react-in-jsx-scope doesn't understand `this`

### ISSUE THREAD

**Issue by solmsted** [yannickcr/eslint-plugin-react#1014]
Using the pragma syntax
```JavaScript
/** @jsx this.createElement */
```
it errors on every occurrence of JSX in the source file saying `'this' must be in scope when using JSX`.

The JSX code is within a function so `this` is in scope.

**Comment by ljharb** [comment]
`this` at the top level of a Module is undefined, and i believe jsx transforms need to be to use something that's defined at the module level.

If you can provide a repro with the latest version of the plugin, that's also an example of code that babel successfully transforms, I'll be happy to reopen.
