### ISSUE TITLE
'jsx-sort-prop-types' rule is missing.

### ISSUE THREAD

**Issue by tommai78101** [yannickcr/eslint-plugin-react#1028]
I get this message:

`Definition for rule 'react/jsx-sort-prop-types' was not found`

I know it has been [deprecated](https://github.com/yannickcr/eslint-plugin-react/pull/688) for a while ago, but I'm still getting this message. 

Not sure what's wrong.

**Comment by ljharb** [comment]
The rule was renamed to just "react/sort-prop-types". Perhaps you're using an outdated config?

**Comment by tommai78101** [comment]
I'm not sure where to change that. Do you know where to change this?

**Comment by ljharb** [comment]
It's in the change log for v6, https://github.com/yannickcr/eslint-plugin-react/issues/549

**Comment by ljharb** [comment]
I'd check your .eslintrc file, as well as if you're using a shared config, update to the latest version. If you are, `npm ls` is probably complaining.

**Comment by tommai78101** [comment]
Yeah, I saw that, but I can't seem to figure out how to "change" it.

**Comment by tommai78101** [comment]
Yep, found it in `.eslintrc`. Just renaming the rule name fixes it. Thanks.
