### ISSUE TITLE
require-default-props without prop-types

### ISSUE THREAD

**Issue by KulakovSerg** [yannickcr/eslint-plugin-react#1030]
Is it possible to add new rule for to use _**require-default-props**_ without checking **_prop-types_**?
We have rather big project with defaultProps and it would be very sad to add redundant prop-types everywhere.

**Comment by ljharb** [comment]
How are they redundant?

`propTypes` tells React what kind of thing to expect (if it's required, or if it's not `undefined`); `defaultProps` tells React what to substitute if the prop provided is `undefined`.

**Comment by KulakovSerg** [comment]
In a lot of cases list of default props is good enough. When really many components already has default props described it is not so necessary to spend time on propTypes.
But eslint do nothing when some of them changes and it is sad for me

**Comment by ljharb** [comment]
In no cases do I think defaultProps is good enough - without propTypes, the wrong value can be passed and you'll never know it.

It is *always* necessary to spend time on propTypes. It would be far better to never use defaultProps, then to ever omit propTypes.
