### ISSUE TITLE
forbid-prop-types doesn't forbid any, array, and object inside shapes

### ISSUE THREAD

**Issue by e-wang** [yannickcr/eslint-plugin-react#1036]
The following pattern is not considered a warning with `'react/forbid-prop-types': ['error', { forbid: ['any', 'array', 'object'] }]`.
```
static propTypes = {
  forbidden: React.PropTypes.shape({
    any: React.PropTypes.any,
    array: React.PropTypes.array,
    object: React.PropTypes.object
  })
};
```

**Comment by alexzherdev** [comment]
I verified that this is supported and there is a (similar) test case https://github.com/yannickcr/eslint-plugin-react/blob/9bd3456a920cf3a85da3d4bded5d7a43b2254f13/tests/lib/rules/forbid-prop-types.js#L688-L700
