### ISSUE TITLE
PropTypes and default export

### ISSUE THREAD

**Issue by guywald1** [yannickcr/eslint-plugin-react#1042]
This:

```jsx
export default App = ({ children }) => <div>{children}</div>
App.propTypes = {
  children: React.PropTypes.node.isRequired
}
```

will trigger: `children is missing in props validation`

Yet, this:

```jsx
export const App = ({ children }) => <div>{children}</div>
App.propTypes = {
  children: React.PropTypes.node.isRequired
}
```
*won't* trigger.

**Comment by ljharb** [comment]
Because you can't export a default like that. You have to do it in 3 lines.

**Comment by ljharb** [comment]
iow, you're creating a global App variable. You need 1 statement to make the component, 1 to assign propTypes, and 1 to export default (or, 1 statement but using `export default Object.assign(function App() {}, { propTypes: … });`

**Comment by guywald1** [comment]
Thanks for the reply. I am aware, yet for a second there I thought this was unwanted behavior. Appreciate the clarification.
