### ISSUE TITLE
Make JSX as independant eslint-plugin

### ISSUE THREAD

**Issue by Swizz** [yannickcr/eslint-plugin-react#1044]
Hi there !

As the use of JSX grow into the non react community, how about making the JSX rules as independant plugin ?

I am aware of the existance of [jkroso/eslint-plugin-jsx](/jkroso/eslint-plugin-jsx) but it looks really deprecated and far behind your proposals.

Cheers,

**Comment by ljharb** [comment]
You can easily use this plugin and only enable the jsx rules, or we could add an exported config that only contains those - there's not really a benefit in having it be a separate plugin.

**Comment by Swizz** [comment]
I got it. So I took the time to read all the configuration stuffs.
I did not wanted first to include all the things due to size load.

But.. I will work on a shareable config.

Thank you.

**Comment by ljharb** [comment]
Size doesn't really matter for dev deps.
