### ISSUE TITLE
jsx-boolean-value: don't warn if the value attribute of an <option> tag

### ISSUE THREAD

**Issue by sdemjanenko** [yannickcr/eslint-plugin-react#1052]
In my opinion the plugin should not warn when the JSX is something like `<option value={ true }>True</option>`

**Comment by ljharb** [comment]
Why? `<option value>` is equivalent and more concise.

**Comment by sdemjanenko** [comment]
React's output for `<option value>` ends up resulting in `<option value="true">` since React is casting that prop to `true`.  I prefer having my React syntax match the output HTML syntax as closely as possible when rendering base-level V-DOM nodes.

I don't mind if this isn't the default setting but I would at least like a control to turn on warning in this case.

**Comment by ljharb** [comment]
`<option value={true} />` should be outputting the same thing. In other words, if you want the syntaxes to match you should do `<option value={String(true)} />` instead of relying on React to coerce for you.

I don't think an option to allow this case is a good idea.

**Comment by sdemjanenko** [comment]
Actually thats totally valid.  `<option value={ "true" } />` is strictly better for matching the DOM output.  Thanks for the recommendation.

**Comment by ljharb** [comment]
In that case I'm going to close this; happy to reopen if you want to continue making the case for the option.
