### ISSUE TITLE
prop-types and es7.objectRestSpread

### ISSUE THREAD

**Issue by mtscout6** [yannickcr/eslint-plugin-react#106]
I'm currently getting a lint warning saying that a prop is not defined with the following example:

``` jsx
import React from 'react';
import SharedPropTypes from './SharedPropTypes';

export default class A extends React.Component {
  render() {
    return (
      <span
        a={this.props.a}
        b={this.props.b}
        c={this.props.c}>
        {this.props.children}
      </span>
    );
  }
}

A.propTypes = {
  a: React.PropTypes.string,
  ...SharedPropTypes // eslint-disable-line object-shorthand
};
```

The propTypes are getting assigned utilizing the experimental Stage 1 feature from Babel es7.objectRestSpread.
- http://babeljs.io/docs/usage/experimental/
- https://github.com/sebmarkbage/ecmascript-rest-spread

I already have to disable one line as it is not yet supported in eslint as per eslint/eslint#2514.

I don't know if this is a limiting issue due to eslint not supporting this ES7 feature yet or not.

**Comment by mathieumg** [comment]
Even if it were supported today, I imagine the fact that they're getting imported would be a limitation for static analysis?

**Comment by mtscout6** [comment]
Sadly true, unless something like [ternjs](https://github.com/marijnh/tern) or any other comprehensive static code analyzer could be used but that would be a core eslint issue to address.

I'm just trying to wrap my head around a clean way to share propType definitions across multiple components in an ES6 world. With ES5 using a Mixin would be the preferred means. However, seeing as React proper has not explicitly declared deprecation of `React.createClass` it still seems as though it's on the horizon at some point. My hopes in presenting this is partly to see if there is an existing solution or any prescribed methods to address such a use case.

**Comment by yannickcr** [comment]
One similar case was already discussed in #68 but I do not have any real solution for this case right now (beside disabling the `react/prop-types` rule for this class).

For now the linter only works file by file so we can't know what is declared in other imported files. I don't know if we could use a static analysis tool to get around this limitation but it is an idea worth investigating.

**Comment by Coobaha** [comment]
this should work

```
A.propTypes = Object.assign(...SharedPropTypes, {
  a: React.PropTypes.string,
});
```

**Comment by jquense** [comment]
So eslint 1.0. does support spread, and as of a few versions ago babel-eslint also exposes the original babel ast node type on the translated eslint node as `._babelType` which is also helpful for getting spread info.

However as @yannickcr said if the value is being imported from another file, eslint just doesn't expose cross file info like babel could. The more unlikely case of defining the proptypes, to be spread, in the current module, could be resolved to not error in _most_ cases.

**Comment by niftylettuce** [comment]
Same as this maybe? <https://discuss.reactjs.org/t/spread-operator-enabled-locally-but-not-on-my-ci-server/2078>

**Comment by niftylettuce** [comment]
@Coobaha that didn't work for me

**Comment by rafaelchiti** [comment]
Meanwhile would be useful if we can set an exception so we can disable this linting when using spread operators, does that make sense?

**Comment by yannickcr** [comment]
I fixed a crash related to the spread operator (#389). Components propTypes validation is now ignored if propTypes are using the spread operator (since in this case we cannot determine what propTypes are defined or not).
