### ISSUE TITLE
jsx-handler-names doesn't detect methods defined as es7 class properties

### ISSUE THREAD

**Issue by alexkrolick** [yannickcr/eslint-plugin-react#1069]
https://babeljs.io/docs/plugins/transform-class-properties/

<img width="419" alt="screen shot 2017-02-12 at 3 43 14 pm" src="https://cloud.githubusercontent.com/assets/1571667/22867289/806f5ea2-f13a-11e6-95a1-a242182a6bd9.png">

**Comment by alexkrolick** [comment]
It does with babel-eslint

**Comment by ljharb** [comment]
That's because class properties aren't "es7", they're a stage 2 proposal, and as such, eslint core doesn't parse them yet.
