### ISSUE TITLE
error App is defined but never used (no-unused-vars)

### ISSUE THREAD

**Issue by simonewebdesign** [yannickcr/eslint-plugin-react#107]
We ran across this problem reproducible here: https://github.com/simonewebdesign/eslint-plugin-react-bug

However this seems to be fixed in master. Can you please bump up the version and publish the package on npm?

**Comment by yannickcr** [comment]
I think it's the same problem as #96. It's fixed but I did not released a new version since.

I will release a new version this week-end with the bugfix and a few more improvements.

**Comment by yannickcr** [comment]
Fixed in `v2.5.2`

**Comment by simonewebdesign** [comment]
Thanks!
