### ISSUE TITLE
Make the jsx-no-undef option that increases strictness the default

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#1072]
As discussed in https://github.com/yannickcr/eslint-plugin-react/pull/1013#discussion_r101341243, it seems like this should be the default behavior for this rule. As part of the next major release, we should remove this option and just make it the default.

**Comment by ljharb** [comment]
I've updated the PR to be `allowGlobals` and default to `false`, so this is covered.
