### ISSUE TITLE
Support excetions for no-unused-vars

### ISSUE THREAD

**Issue by vicentedealencar** [yannickcr/eslint-plugin-react#108]
I'm working on a fork of react-starter-kit and the first line of every component is
`import React, { PropTypes } from 'react'; // eslint-disable-line no-unused-vars`

I've been using eslint for a short time and love it, but having to use eslint-disable-line repeatedly is pretty annoying. I was using `// eslint-disable-line new-cap` to work with Immutablejs, then I figured out I could add this rule to .eslintrc:
`"new-cap": [2, { "capIsNewExceptions": ["List", "Map"] }]`

Is it possible to have something similar to no-unused-vars rule?

As an example, the comments on [this file](https://github.com/kriasoft/react-starter-kit/blob/master/src/components/ContactPage/ContactPage.js) would not be necessary with something like this:
`"no-unused-vars": [2, { "varsIsNewExceptions": ["React", "styles", "withStyles"] }]`

**Comment by AlexKVal** [comment]
You are probably posting issue to the wrong project :wink: 
http://eslint.org/docs/rules/no-unused-vars

--
As for your example
https://github.com/kriasoft/react-starter-kit/blob/master/src/components/ContactPage/ContactPage.js
That file uses ES7 syntax.
`eslint` project won't support ES7 (untill it is standard).
So you need those `eslint-disable-line` if you want to use ES7 syntax.

--
https://github.com/eslint/eslint/issues?q=is%3Aissue+ES7+is%3Aclosed
almost in every issue with ES7 syntax
you'll find the answer 'We do not support experimental features at this point.`

:cherries:

**Comment by yannickcr** [comment]
@AlexKVal is right, the issue here come from the ESLint `no-unused-vars` rule and there is not much we can do here.

But concerning the `React` variable marked as unused, you can use the [`react/jsx-uses-react`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md) rule to mark it as used if you are using JSX in your file.

**Comment by vicentedealencar** [comment]
Hmm... I didn't know about that, thanks for you responses

So I am sticking with this comments for a while
