### ISSUE TITLE
react/no-unused-prop-types error when using the props as function arguments

### ISSUE THREAD

**Issue by idangozlan** [yannickcr/eslint-plugin-react#1095]
My Case:

```
  static propTypes = {
    params: PropTypes.object.isRequired
  };

  state = this.getInitialState();

  getInitialState(props = this.props) {
    const { email } = props.params;
    return {
      email
    };
  }

  componentWillReceiveProps(nextProps) {
    this.setState(this.getInitialState(nextProps));
  }
```

Generate the following error:

```
error  'params' PropType is defined but prop is never used  react/no-unused-prop-types
```

**Comment by ljharb** [comment]
If instead of overloading getInitialState, you made getInitialState and cWRP both call into the same shared closed-over function, would everything work?

I'm not sure supporting any arguments to getInitialState (which takes none, and is part of the severely deprecated React.createClass pattern) is a good idea.

**Comment by idangozlan** [comment]
I can't understand your solution, can you demonstrate with a code sample?

**Comment by ljharb** [comment]
Ah, I'd misunderstood - this isn't `React.createClass`, you're just using the method name "getInitialState".

```js
function getInitialState(props) {
  const { email } = props.params;
    return {
      email
    };
}

class Foo extends React.Component {
  static propTypes = {
    params: PropTypes.object.isRequired
  };

  state = getInitialState(this.props);

  componentWillReceiveProps(nextProps) {
    this.setState(getInitialState(nextProps));
  }
}
```

**Comment by idangozlan** [comment]
yep.. any solution :)?

**Comment by ljharb** [comment]
Using the default value means it's branched on using both, and that's not something that can be statically determined.

**Comment by littlemooon** [comment]
This is not just the case when using default arguments.

This class throws three `no-unused-prop-types` errors, one for each test prop:
```
import React, { Component, PropTypes } from 'react'

export class TestClass extends Component {

  static propTypes = {
    test1: PropTypes.string,
    test2: PropTypes.string,
    test3: PropTypes.string,
  }

  passPropsFunction(props) {
    return props.test1
  }

  passPropsProperty = p => p.test2

  passPropsDefault = (p = this.props) => p.test3

  render() {
    return (
      <div>
        {this.passPropsFunction(this.props)}
        {this.passPropsProperty(this.props)}
        {this.passPropsDefault()}
      </div>
    )
  }
}
```

While this stateless function does not throw any error:
```
const passProps = p => p.test

const TestFunction = p => <div>{passProps(p)}</div>

TestFunction.propTypes = {
  test: PropTypes.string,
}

export default TestFunction
```

**Comment by ljharb** [comment]
Passing the entire props object around is an antipattern anyways. Destructure it and pass things as separate arguments.

**Comment by littlemooon** [comment]
Valid point 👍  It is sometimes damn convenient though :P

Might as well close this issue?
