### ISSUE TITLE
2.5.1 release has breaking changes

### ISSUE THREAD

**Issue by mtscout6** [yannickcr/eslint-plugin-react#110]
2.5.0 is working as expected.

We are seeing a lot of failures in [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) failing the rule no-unused-vars when it is clearly used.

One such failing file is: https://github.com/react-bootstrap/react-bootstrap/blob/master/docs/examples/TooltipInCopy.js

It states that the variable LinkWithTooltip is not used, but it is used here: https://github.com/react-bootstrap/react-bootstrap/blob/master/docs/examples/TooltipInCopy.js#L15

**Comment by yannickcr** [comment]
OMG, I'm so sorry for this.

I'll investigate and shortly publish a fixed version.

**Comment by yannickcr** [comment]
Just published version `2.5.2` with a bugfix. Hope it will fix your issue.

**Comment by AlexKVal** [comment]
There is still 2.5.1 version on npm 
https://www.npmjs.com/package/eslint-plugin-react

**Comment by yannickcr** [comment]
It's published for real now :)

**Comment by AlexKVal** [comment]
Thank you :cherries:  :smile:

**Comment by AlexKVal** [comment]
I've checked it - all is working fine, again. :tada:

**Comment by mtscout6** [comment]
Thanks for the quick turn around on this :)
