### ISSUE TITLE
Unable to fix Parsing error: The keyword 'import' is reserved after migration

### ISSUE THREAD

**Issue by alburritos** [yannickcr/eslint-plugin-react#1100]
Currently this is my eslintrc.json file
```
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "settings": {
    "react": {
      "version": "15.3.2"
    }
  },
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "mocha": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "arrowFunctions": true,
      "blockBindings": true,
      "classes": true,
      "defaultParams": true,
      "destructuring": true,
      "forOf": true,
      "generators": false,
      "modules": true,
      "objectLiteralComputedProperties": true,
      "objectLiteralDuplicateProperties": false,
      "objectLiteralShorthandMethods": true,
      "objectLiteralShorthandProperties": true,
      "spread": true,
      "superInFunctions": true,
      "templateStrings": true,
      "restParams": true,
      "jsx": true
    }
  },
```
I'm running 2.6.0.

However, when I lint, I get hundreds of errors that say

`  1:1  error  Parsing error: The keyword 'import' is reserved `

**Comment by ljharb** [comment]
With babel-eslint, you don't need any of those parserOptions.

I'm not sure why you're getting that error tho - is this on the command line, with a locally installed eslint?

**Comment by ljharb** [comment]
Also, upgrade to eslint 3 - v2 is obsolete.

**Comment by alberth8** [comment]
@ljharb It's an npm script where it just runs `eslint --fix ./myDir`

**Comment by alberth8** [comment]
@ljharb Out of curiosity, what's wrong with keeping v2? Also, if I rember the parserOptions stuff, I still the same error.

**Comment by ljharb** [comment]
Good, eslint shouldn't be installed globally :-)

what's wrong with keeping v2 is that it's not the latest, and you should always strive to be on the latest version of things.

what version of babel-eslint is it?

**Comment by akshaymodi9** [comment]
@alburritos  Any update on how to solve this issue 'Unable to fix Parsing error: The keyword 'import' is reserved after migration #1100'
I too am facing the same issue

**Comment by ljharb** [comment]
@akshaymodi9 same solution - upgrade to latest everything, and make sure sourceType is set to "module" somewhere in your config.

**Comment by trusktr** [comment]
I had `modules: true`, but then I landed here to find that `sourceType: 'module'` is needed too. It's not obvious. Can we make these things true by default? Is it safe to assume most people use modules nowadays (when using ESLint)?

**Comment by ljharb** [comment]
No, we can’t; no, it’s not; this is something you have to configure for yourself in your own app.

This has been answered; closing.
