### ISSUE TITLE
Function above component blocking linting for defaultProps

### ISSUE THREAD

**Issue by wwselleck** [yannickcr/eslint-plugin-react#1102]
Version: 6.10.0

This is an extremely simplified version of a component I'm working on. The `require-default-props` rule is turned on.

```javascript
//demo.js
function createElement (Component = 'strong') {
  return React.createElement(Component);
}

function MyComponent (props) {
  const el = createElement('a')
  return <el className={props.className}></el>;
}

MyComponent.propTypes = {
  className: React.PropTypes.string,
};

MyComponent.defaultProps = {
};

export default MyComponent;
```

When I run `eslint ./demo.js`, I get no warnings, despite `props.className` not having a `defaultProp` value and it not being marked as required in `propTypes`. When I remove the `createElement` function, however....

```javascript
//demo.js
function MyComponent (props) {
  const el = 'a'
  return <el className={props.className}></el>;
}

MyComponent.propTypes = {
  className: React.PropTypes.string,
};

MyComponent.defaultProps = {
};

export default MyComponent;
```
I get a warning about `className` not having a default value. Also, when I move the function to the bottom of the file..., 

```javascript
//demo.js
function MyComponent (props) {
  const el = createElement('a')
  return <el className={props.className}></el>;
}

MyComponent.propTypes = {
  className: React.PropTypes.string,
};

MyComponent.defaultProps = {
};

function createElement (Component = 'strong') {
  return React.createElement(Component);
}
export default MyComponent;
```

I again get the warning I'm expecting. So it looks like this function existing and being at the top of the file (or maybe just above the component) is blocking the `require-default-props` rule from triggering. 

Here is a simplified version of the `.eslintrc` file

```
{
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "jasmine": true
  },
  "globals": {
    "React": false,
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "es6": true,
      "modules": true,
      "jsx": true,
    }
  },
  "plugins": [
    "react",
  ],
  "rules": {
    "react/prop-types": [2],
    "react/require-default-props": 2,
  },
  "settings": {
    "react": {
      "pragma": "React"
    }
  }
}
```

**Comment by ljharb** [comment]
We don't have any way to hook into your custom `createElement` function (see #1074). So, because you're not using jsx, or real React.createElement directly, there's no way for static analysis to figure out the rules should apply.

Your solution (until #1074 happens) is to use jsx and the jsx pragma, or, use the standard createElement instead of a custom one.
