### ISSUE TITLE
void-dom-elements-no-children  performance issue?

### ISSUE THREAD

**Issue by dylang** [yannickcr/eslint-plugin-react#1126]
For some reason `void-dom-elements-no-children` is far slower than my other rules:

Any idea why?

```
Rule                                      | Time (ms) | Relative
:-----------------------------------------|----------:|--------:
react/void-dom-elements-no-children       |  5310.099 |    38.8%
react/prefer-stateless-function           |  1063.330 |     7.8%
react/no-unused-prop-types                |   664.536 |     4.9%
react/no-direct-mutation-state            |   653.098 |     4.8%
react/require-render-return               |   650.664 |     4.8%
react/require-default-props               |   641.757 |     4.7%
react/prop-types                          |   631.518 |     4.6%
react/no-string-refs                      |   630.059 |     4.6%
react/display-name                        |   602.454 |     4.4%
react/jsx-no-bind                         |   598.411 |     4.4%
import/order                              |   248.288 |     1.8%
no-unused-vars                            |   159.331 |     1.2%
indent                                    |   103.186 |     0.8%
max-len                                   |    90.043 |     0.7%
no-unmodified-loop-condition              |    72.887 |     0.5%
object-shorthand                          |    68.125 |     0.5%
key-spacing                               |    59.022 |     0.4%
no-useless-return                         |    51.422 |     0.4%
camelcase                                 |    46.810 |     0.3%
keyword-spacing                           |    44.470 |     0.3%
graphql/template-strings                  |    41.008 |     0.3%
no-implicit-globals                       |    40.464 |     0.3%
react/no-deprecated                       |    39.062 |     0.3%
no-global-assign                          |    30.971 |     0.2%
max-statements-per-line                   |    30.682 |     0.2%
react/no-danger-with-children             |    27.418 |     0.2%
semi-spacing                              |    26.208 |     0.2%
comma-dangle                              |    21.898 |     0.2%
space-in-parens                           |    20.042 |     0.1%
func-call-spacing                         |    19.813 |     0.1%
react/jsx-curly-spacing                   |    19.613 |     0.1%
constructor-super                         |    18.558 |     0.1%
no-unreachable                            |    18.216 |     0.1%
quote-props                               |    17.752 |     0.1%
no-implied-eval                           |    17.670 |     0.1%
no-dupe-keys                              |    17.575 |     0.1%
no-regex-spaces                           |    17.314 |     0.1%
semi                                      |    17.189 |     0.1%
---cut---
```

via `TIMING=1 yarn run lint` which normally only shows top 10, i changed it to show more.

**Comment by benstepp** [comment]
I did some quick digging, and the main culprit is the `array.prototype.find` polyfill is astronomically slow. 

Granted, it's a polyfill so it has to remain spec compliant, but it may be better to use a for loop where we understand the specific implementation (ie. here where we know attributes is an array and we only care whether or not the item is in the array). Maybe there is a fast Array.prototype.includes polyfill, but I doubt anything can compete with the good ol for loops.

```
hasChildrenOrDanger()
find x 139,589 ops/sec ±1.13% (85 runs sampled)
for loop x 47,992,374 ops/sec ±0.95% (90 runs sampled)
Fastest is for loop


isVoidDomElement()
has x 26,597,863 ops/sec ±1.21% (87 runs sampled)
Object.prototype.hasOwnProperty.call x 40,696,192 ops/sec ±1.11% (91 runs sampled)
Array.indexOf x 32,855,569 ops/sec ±1.01% (90 runs sampled)
Array.prototype.indexOf.call x 20,368,539 ops/sec ±0.91% (90 runs sampled)
switch case x 68,476,140 ops/sec ±6.89% (84 runs sampled)
Fastest is switch case
```

If you want to run these benchmarks, they are [on this branch here](https://github.com/benstepp/eslint-plugin-react/tree/bs-benchmark-void-elem)

**Comment by ljharb** [comment]
140k runs per second is not slow in absolute terms, only relative to 47M. How many void elements is it looking at??

**Comment by ljharb** [comment]
Also, in what version of node are you running this? In node 4+, that polyfill should be returning the native implementation (if it's not; that's something I can fix today)

**Comment by benstepp** [comment]
Upon further inspection, array.prototype.find is slow because there are a ton of calls to is-callable.

is-callable is first called to validate that array.prototype.find function is given a predicate.
The big one though is es-abstract/es6.Call also calls is-callable on EVERY iteration of the for loop implementation of array.prototype.find.

The biggest perf bottle neck by far is the needless calls to is-callable in the loop with the same function over and over. I'm not sure how you would want to change this.

As far as is-callable is concerned, the only real perf bottleneck I can see is the regex replacing in isEs6ClassFn. Just dropping that piece improved perf on is-callable fairly significantly. I want to explore how to get those tests to still pass while remaining performant.

```
# is-callable
npm x 494,495 ops/sec ±1.17% (86 runs sampled)
current x 1,949,650 ops/sec ±3.35% (80 runs sampled)
Fastest is current
```

**Comment by ljharb** [comment]
hmm, i'm not sure how to avoid the IsCallable check on every iteration since `ES.Call` has no idea if `IsCallable` has been called before.

**Comment by benstepp** [comment]
I think inlining the implementation of ES.Call in array.prototype.find without the check and throw the license information next to it is the only real option without exposing a new API. It's just two lines and the perf gains would be significant.

**Comment by ljharb** [comment]
@benstepp I've just published v2.0.4 of `array.prototype.find` which uses the native implementation when present/compliant - if you update that, do the performance issues go away in node 4+?

If so, please file an issue on the repo for `array.prototype.find` (and findIndex, ideally) about these benchmarks and we can look into inlining the `ES.Call` calls; additionally, please file an issue on `es-abstract` about the performance of `ES.Call`. Thanks!

**Comment by benstepp** [comment]
👍

array.prototype.find is now much closer to what you would expect compared to a for loop now.

@dylang can you rm -rf your node_modules, reinstall, and rerun eslint again?

```
💁  [eslint-plugin-react]  node benchmarks
find x 3,021,463 ops/sec ±0.79% (90 runs sampled)
for loop x 47,695,155 ops/sec ±1.18% (88 runs sampled)
Fastest is for loop
```

**Comment by EvHaus** [comment]
I'm seeing a similar performance issue on `eslint@7.25.0` and `eslint-plugin-react@7.23.2`.

```
Rule                                | Time (ms) | Relative
:-----------------------------------|----------:|--------:
react/void-dom-elements-no-children | 56199.660 |    12.6%
react/prefer-stateless-function     | 23538.112 |     5.3%
react/no-deprecated                 | 18867.354 |     4.2%
react/require-default-props         | 18832.880 |     4.2%
react/no-typos                      | 18481.612 |     4.2%
react/no-access-state-in-setstate   | 18107.430 |     4.1%
react/sort-comp                     | 17790.689 |     4.0%
react/no-string-refs                | 17619.680 |     4.0%
react/jsx-no-bind                   | 17590.505 |     4.0%
react/require-render-return         | 17551.676 |     4.0%
```
