### ISSUE TITLE
disable propTypes rules

### ISSUE THREAD

**Issue by garmjs** [yannickcr/eslint-plugin-react#1129]
In my next project i want to use Flow instead of propTypes, Is there a way i can disable PropTypes in `.eslintrc`

**Comment by ljharb** [comment]
You could use `no-restricted-properties` I suppose. However, Flow is not a complete replacement for propTypes - it can't do nearly as many things - so I wouldn't recommend that.

**Comment by garmjs** [comment]
@ljharb thanks :)

**Comment by ljharb** [comment]
To be clear, what I'm not recommending is the "instead of" part. If you want to use Flow, great - but you should use it *in conjunction with* propTypes, whenever Flow isn't sufficient.
