### ISSUE TITLE
Have react/sort-prop-types override base ESLint sort-keys

### ISSUE THREAD

**Issue by rsolomon** [yannickcr/eslint-plugin-react#1133]
I'd like my project to enforce alphabetization on all objects, *except* within propTypes, which should be sorted first by `isRequired`, and second by alphabetization.

It doesn't seem like this is possible now because `sort-keys` will flag `propTypes` regardless of how `sort-prop-types` is configured.

**Comment by ljharb** [comment]
eslint does not allow any rule to affect any other.
