### ISSUE TITLE
require-default-props , usage-question

### ISSUE THREAD

**Issue by gabor** [yannickcr/eslint-plugin-react#1140]
sometimes i have code like this:
```
function header(props) {
    if (props.user) {
        return <div>hello {user}</div>;
    } else {
        return null;
    }
}

header.propTypes = {
    user:PropTypes.string,
};
```

this does not get through `require-default-props`, because the `user` attribute is not required, so, in theory, requires a default-prop. but there is no suitable default value. it not being here is important.
what is the recommended approach in such situations?

technically we can make it more explicit, and add a required boolean prop saying `isUserAvailable`, but then still you will have a string-prop that is not required, so the problem remains.

**Comment by ljharb** [comment]
Of course there is; an empty string.

**Comment by gabor** [comment]
i disagree about using empty-string for value-does-not-exist, but ok, in that simple case it could work.

perhaps a different example better illustrates the issue:
```
header.propTypes = {
    user: PropTypes.shape {
        name: PropTypes.string.isRequired,
        messageCount: PropTypes.number.isRequired,
        favoriteFood: PropTypes.oneOf(['steak', 'hamburger']).isRequired,
    },
}
```

what is the default-value in this case?

**Comment by ljharb** [comment]
`null`, of course - it has the same typeof value for a reason.
