### ISSUE TITLE
Rule proposal: react/no-will-mount

### ISSUE THREAD

**Issue by jacobrask** [yannickcr/eslint-plugin-react#1147]
There are few use cases for `componentWillMount` that cannot be handled in the constructor.

It is a common mistake to put asynchronous requests in `componentWillMount` which could potentially cause hard to find errors.

**Comment by ljharb** [comment]
I disagree; i think everything that's not initializing state belongs in `componentWillMount`.

Async requests in the constructor have the same issues; neither us often a problem in practice.

I'm a strong -1.

**Comment by jacobrask** [comment]
Wouldn't most async requests in practice set state on completion?

From my POV the question here is if there are a reasonable number of developers considering putting asynchronous requests in `componentWillMount` a problem, and that most other use cases can be handled in the constructor.

I think the [React docs](https://facebook.github.io/react/docs/react-component.html#componentwillmount) imply this.
> Avoid introducing any side-effects or subscriptions in this method.
> ...
> Generally, we recommend using the constructor() instead.

My understanding (which is very limited, so please correct me if I'm wrong) is that async rendering with fibers means that an async request might complete before mount and sometimes after (maybe the mount could even be aborted?).

(I would be willing to implement this if I can be reasonably sure that it would be accepted.)

**Comment by ljharb** [comment]
Side effects in JS *never* belong in constructors. If React advises that, they are wrong.

**Comment by jacobrask** [comment]
My quotation was a bit confusing, those were excerpts from different paragraphs.

**Comment by ljharb** [comment]
Indeed, fiber may change the timing of some of these things. But fiber isn't out yet, and if the issue is doing async things prior to the first render, then constructor vs componentWillMount has the same problem.

In other words, I'm still not seeing a reason to discourage componentWillMount - you've only talked about async setStates initiated prior to mounting.

**Comment by lukeapage** [comment]
tracking: https://github.com/facebook/react/issues/7671

**Comment by jacobrask** [comment]
It seems like a significant number of React developers agree that using this method should be discouraged. If you do not agree it's of course fine to not use the rule.

Are you opposed to (me?) adding the rule at all to this project?

**Comment by ljharb** [comment]
I'm not sure where you get "significant number" - that github issue is full of people who simply don't see a need for the method, with very very few claiming that its use should be discouraged.

So yes, I'm opposed to adding the rule at all.

**Comment by jacobrask** [comment]
Ok

**Comment by ljharb** [comment]
I'm not the only collaborator; this should remain open pending the others' thoughts.

**Comment by abritinthebay** [comment]
Given it's an official FB recommendation (quoted above)

> Generally, we recommend using the constructor() instead.

It would make sense to have this as an *optional* linting rule. Certainly shouldn't be a recommended one but a lot of the core devs seem pro-deprecation and have mentioned that post-fiber it would make sense to examine the issue more.

Most linting rules are completely subjective, this seems to at least be a reasonable suggestion for an optional rule.

**Comment by ljharb** [comment]
Afaik there's still active discussions going on with core devs about it; I don't believe they've made a compelling case. Note that Facebook doesn't server-render, and their position on `componentWillMount` is one that is not shared by other stakeholders that do server-render.

**Comment by abritinthebay** [comment]
Sure, there are plenty of active discussions about many things - including things where rules already exist in this package.

That's what best practice debates are composed of 😄 

My point is more - this kind of rule is a _classic_ optional linting step feature. God knows there are exist rules in this package that I'm _never_ going to turn on because they don't work for me or my projects. This rule would be no different to those.

Side note: I extensively use server-rendering and honestly, the story there is not as complex as some in that discussion would make it. Though yes, there are complexities involved and for those components perhaps turning the rule off makes sense - but that's *good*, as it requires intentionality.

**Comment by ljharb** [comment]
My [comment](https://github.com/yannickcr/eslint-plugin-react/issues/1147#issuecomment-293383261) stands, as does [this one](https://github.com/yannickcr/eslint-plugin-react/issues/1147#issuecomment-301810066).

**Comment by abritinthebay** [comment]
Indeed, your preference is clear. If the rule existed you'd not use it/turn it off. 👍

**Comment by ljharb** [comment]
To clarify; my preference is to not include the rule, so that nobody is ever able to turn it on.

**Comment by noahgrant** [comment]
this is a different context/discussion and a different rule, but now that React 16.3 is going to be deprecating `cWM`, `cWRP` and `cWU`, i'd love to have a linting rule that we could put in place to prevent using these methods as we migrate away from them. should we create a new discussion for it?

**Comment by Hypnosphi** [comment]
Here they are: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by abritinthebay** [comment]
Oh that's a quite nice generalized rule, could even have a recommended/default set.

**Comment by ljharb** [comment]
This seems handled by #1750.
