### ISSUE TITLE
Make flowtype `props` before `defaultProps`

### ISSUE THREAD

**Issue by xareelee** [yannickcr/eslint-plugin-react#1154]
I want the flowtype `props` implemented before all other methods, for example,

```js
class Loading extends React.Component {
  props: {
    text: string,
    loading: boolean,
  };

  static defaultProps = {
    text: 'Loading...',
    loading: false,
  };

  ...
}
```

but I got error when linting

```
  18:3  error  props should be placed after componentDidMount  react/sort-comp
```

How can I fix it?

**Comment by elgubenis** [comment]
You can change the order yourself, documented here: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md#rule-options
