### ISSUE TITLE
Sort-comp `constructor`

### ISSUE THREAD

**Issue by Cellule** [yannickcr/eslint-plugin-react#116]
I was wondering if it would be a good addition to include `constructor` in the lifecycle group in rule `sort-comp` since it replaces a few lifecycle methods with es6 classes.

**Comment by mathieumg** [comment]
Duplicate of https://github.com/yannickcr/eslint-plugin-react/issues/97

**Comment by Cellule** [comment]
Indeed and now that I think about it, I think I already read the other issue... my bad
