### ISSUE TITLE
Add jsx-no-bind to recommended config

### ISSUE THREAD

**Issue by acontreras89** [yannickcr/eslint-plugin-react#1160]
The `recommended` configuration is supposed to enforce React good practices. Shouldn't it include `jsx-no-bind`?

This has been recommended [over](https://facebook.github.io/react/docs/handling-events.html) [and](http://benchling.engineering/performance-engineering-with-react/#functionbindinlineanonymousfunctions) [over](https://blog.vixlet.com/react-at-light-speed-78cd172a6411#483f).

**Comment by ljharb** [comment]
It should perhaps be recommended when allowing arrow functions; but it's too heavy imo to make it recommended when it blocks all new function creation, since `.bind` is the primary source of performance issues.

**Comment by acontreras89** [comment]
@ljharb, to be honest I haven't used the rule and I have no idea how strict it is. Can you please provide some examples?

Besides performance implications, declaring functions in props makes `PureComponent`s to render unnecessarily. This is one of the reasons why adhering to this rule a _good practice_.

**Comment by ljharb** [comment]
From an ideological standpoint, yes. But unnecessary renders aren't that slow in practice.

**Comment by acontreras89** [comment]
Feel free to close this if it does not make sense to you. Just brought it up because this is generally considered a good practice.

**Comment by ljharb** [comment]
Adding things to "recommended" is a breaking change; if we ever do a semver-major, we'll audit every rule and make sure it's present in the recommended config if it makes sense.
