### ISSUE TITLE
no-direct-mutation-state still allows direct assignments

### ISSUE THREAD

**Issue by ndresx** [yannickcr/eslint-plugin-react#1164]
I came across the `no-direct-mutation-state` rule some days ago and have to say it's a bit weird of how it works. I would like to refer to this issue (https://github.com/yannickcr/eslint-plugin-react/issues/832) where, especially in the constructor, there shouldn't be any problem at all to mutate/change `this.state`.

Nothing unexpected should happen during that time and solving this issue by using `this.setState()` instead - like the error description suggests - is not allowed in this case. While mutating it directly is also not allowed, this rule still allows doing something like `this.state = { newKey: value };` throughout the component, which also shouldn't be allowed? _(Is this a limitation of how ESLint works in general?)_

_If there is any good explanation or reason for why setting up the state in multiple steps has to be strictly avoided, I would be happy to hear it!_

**Comment by valentin-radulescu-hs** [comment]
I think this will be fixed in https://github.com/yannickcr/eslint-plugin-react/pull/1223

**Comment by ljharb** [comment]
Closed in #1223.
