### ISSUE TITLE
react/no-array-index-key wrongly triggered when using immutablejs map

### ISSUE THREAD

**Issue by jdeniau** [yannickcr/eslint-plugin-react#1170]
```js
import { fromJS } from 'immutable';

function foo() {
    return fromJS({ a: 'A' })
      .map((value, key) => <div key={key} />)
    ;
}
```

This code will throw `Do not use Array index in keys (react/no-array-index-key)`, but my key is not an array , it's will be `a` in this example.

**Comment by ljharb** [comment]
There's no way for the rule to know if `.map` is being called on an array or not; you'd have to disable the rule overall, or override it for this one case.
