### ISSUE TITLE
Missing Image import not throwing an error

### ISSUE THREAD

**Issue by pke** [yannickcr/eslint-plugin-react#1171]
When using jsx `<Image src="./test.jpg"/>` without importing `import Image from "./Image"` eslint does not complain because it seems to thread `image` as `window.Image`.
But since `Image` is clearly a component the missing import should be an error.

**Comment by ljharb** [comment]
This is fixed in v7 - the new `allowGlobals` option will default to false. Setting it to `true` will replicate the current behavior.

This also happens with Text, for example.
