### ISSUE TITLE
Check that ES6 static propTypes/defaultProps are not functions?

### ISSUE THREAD

**Issue by victor-homyakov** [yannickcr/eslint-plugin-react#1174]
It is possible to erroneously define `propTypes` and `defaultProps` in ES6 class as function. In that case React will silently ignore them. See first component in example at https://jsbin.com/jidupehebu/edit?js,console 

Is it possible to add a rule to check that `propTypes` and `defaultProps` are properly defined (either static property initializers from ES7 proposal or static property getters, but not functions)?

**Comment by yannickcr** [comment]
If you enable the [`require-default-props`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md) rule it will warn you if your `defaultProps` are not defined correctly.

The [`prop-types`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md) rule should do the same for `propTypes`, but after testing it seems there is a bug here and it consider a static function as valid `propTypes` definition, which is incorrect.

I will fix the `prop-types` rule then by enabling theses two rules you should get the desired behavior.

**Comment by victor-homyakov** [comment]
What if I do not want to enforce `defaultProps` or `propTypes`?

**Comment by ljharb** [comment]
Then you would disable the rules - but since it's a massive best practice across the entire ecosystem to have them, I don't recommend it.

**Comment by victor-homyakov** [comment]
:(

In case of existing medium-sized project with missing/wrong `propTypes` and missing `defaultProps` I do not want to fix all of them and make massive code changes.

It looks too restrictive to enforce these rules and add `propTypes` everywhere just in order to check if existing ones are written properly.

**Comment by ljharb** [comment]
Then enable the rules in the files that have them.

No matter how large the project, even if adding propTypes everywhere is a massive change, then that's what's needed.
