### ISSUE TITLE
Definition for rule 'react/no-will-update-set-state' was not found

### ISSUE THREAD

**Issue by joetidee** [yannickcr/eslint-plugin-react#1186]
I am getting the following error thrown in the terminal:

> 1:1  error  Definition for rule 'react/no-will-update-set-state' was not found react/no-will-update-set-state

what does this mean?

p.s. my rule definition in .eslintrc is `"react/no-will-update-set-state": "error"`

**Comment by ljharb** [comment]
Any chance you're using the airbnb eslint config (which doesn't yet support v7 of eslint-plugin-react) and v7 of eslint-plugin-react? If so, `npm ls` should tell you your dependencies are invalid.

If not, what version of eslint-plugin-react are you using?

**Comment by joetidee** [comment]
I have the following packages installed:

> "eslint-config-airbnb": "^14.0.0"
> "eslint-plugin-react": "^6.10.3"

**Comment by ljharb** [comment]
That rule only exists in v7 - it was added in #1139.

You won't be able to enable it until `eslint-config-airbnb` releases a new semver-major that supports v7 of `eslint-plugin-react`.

**Comment by joetidee** [comment]
ok, thanks for that.
