### ISSUE TITLE
Allow default arguments on functional component to count as defaultProps

### ISSUE THREAD

**Issue by singpolyma-shopify** [yannickcr/eslint-plugin-react#1188]
When using Flow, this is the suggested pattern (https://flow.org/en/docs/frameworks/react/):

```
type CardProps = { wrapInSection?: bool };

function Card({ wrapInSection = true }: CardProps) {
    // ...
}
```

But eslint says:

` error  propType "wrapInSection" is not required, but has no corresponding defaultProp declaration`

**Comment by ljharb** [comment]
Duplicate of #1184
