### ISSUE TITLE
Rule to prevent `static PropTypes`

### ISSUE THREAD

**Issue by rsolomon** [yannickcr/eslint-plugin-react#1189]
I've noticed this a few places, where people are recording propTypes under a static `PropTypes` member instead of the correct camelCase `static propTypes`. It would be helpful if there were a lint rule that checks for this, as using `PropTypes` doesn't fail, it just silently doesn't check.

**Comment by ljharb** [comment]
That sounds like a good idea. It should probably check for any case variant of `propTypes` and `defaultProps` and `contextTypes` etc, and ensure that none of them exist unless they're the proper casing.

**Comment by ljharb** [comment]
We could call it `no-static-typos` or something

**Comment by jseminck** [comment]
I will take a look at this.

**Comment by DianaSuvorova** [comment]
@ljharb I think this issue should be closed.

**Comment by ljharb** [comment]
(Fixed in #1209)
