### ISSUE TITLE
Wrong (?) rule for prop-types ("prop-types" instead of "react/prop-types") in docs

### ISSUE THREAD

**Issue by markus-willems** [yannickcr/eslint-plugin-react#1191]
I assume there is a small mistake in the docs for the prop-types rule: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md

`
...
"prop-types": [<enabled>, { ignore: <ignore>, customValidators: <customValidator> }]
...
`

When I use this rule with `eslint`, `babel-eslint`, `eslint-plugin-react`, and `eslint-loader` for Webpack I get the following message:

`Definition for rule 'prop-types' was not found  prop-types`

However, when I change it to `"react/prop-types": ...` everything is working as expected.

Can anyone confirm? If so, I'd be happy to file a PR :)

**Comment by ljharb** [comment]
Correct, all rules need a "react/" prefix. A PR is welcome.

**Comment by ljharb** [comment]
Fixed in #1192.

**Comment by suwigyarathore** [comment]
this issue  is still there

**Comment by ljharb** [comment]
@suwigyarathore no it's not? https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md#rule-options

The issue was in the docs; `prop-types` in your eslint config will never work.
