### ISSUE TITLE
Rule Suggestion : setState function 

### ISSUE THREAD

**Issue by seeliang** [yannickcr/eslint-plugin-react#1196]
Hi, all, big fan of this repo.
thank you all for update and maintaining eslint-react.

Do we have (or will have) a rule about the setState

To avoid 
this.setState({...})

and use
this.setState( (state, props) => { return ... })

https://www.reddit.com/r/reactjs/comments/5zqgsb/react_fiber_functional_setstate/

**Comment by yannickcr** [comment]
I think @relekang is working a on a rule for this, see #943.
