### ISSUE TITLE
wrap-multilines - TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by bebraw** [yannickcr/eslint-plugin-react#120]
0. git clone git@github.com:survivejs/webpack_react.git
0. cd webpack_react
0. git checkout broken-multilines
0. cd project_source/05_webpack_and_react/kanban_app/
0. npm i
0. npm run lint

```bash
node_modules/eslint-plugin-react/lib/rules/wrap-multilines.js:33
    return node.loc.start.line !== node.loc.end.line;
                         ^
TypeError: Cannot read property 'line' of undefined
```

Note that if you run lint against chapter 4, it works. Something in chapter 5 broke it.

I also tried this against the newest versions of ESLint and eslint-plugin-react with the same results. Note that in this case you'll need to tweak `"always"` and `.eslintrc` as `1` for ESLint to work.

**Comment by aruberto** [comment]
I am also getting the same error. Did some tinkering with dependencies. eslint-plugin-react depends on babel-core which in turn depends on acorn-jsx. Downgrading acorn-jsx to 1.0.3 (1.1.0 was released about 1.5 hours ago) and the problem goes away.

**Comment by choonkending** [comment]
@aruberto What a champion! I had the same issue and downgrading acorn-jsx to 1.0.3 works! Thanks heaps.

**Comment by giogonzo** [comment]
:+1:

**Comment by yannickcr** [comment]
According to RReverser/acorn-jsx/issues/24 Acorn introduced an API change between `1.0.3` and `1.2.2`.

@RReverser unpublished acorn-jsx `1.1.0` from the npm registry (and bumped to `2.0.0`), so if you re-install your dependencies acorn-jsx `1.0.3` will be used and everything should work again.

```bash
$ rm -rf node_modules
$ npm i
```

**Comment by bebraw** [comment]
Alright, feel free to close. :+1:
