### ISSUE TITLE
Enforcing use of `prop-types` lib

### ISSUE THREAD

**Issue by trotzig** [yannickcr/eslint-plugin-react#1204]
We're in the process of making our codebase ready for React 16. As part of that, we're replacing `React.PropTypes` with the `prop-types` lib. Is there a way to enforce this through eslint somehow? My initial attempts at googling for this doesn't result in anything useful, and if I'm reading the readme correctly, it doesn't seem like this project could help either (right now).

**Comment by ljharb** [comment]
The `no-deprecated` rule should handle this.

**Comment by trotzig** [comment]
Ah, thanks for the pointer! That's exactly what I need.
