### ISSUE TITLE
Checking for PropTypes iso React.PropTypes

### ISSUE THREAD

**Issue by sharbel-keyvalue** [yannickcr/eslint-plugin-react#1208]
Hi

In the latest version of react you are supposed to use PropTypes from https://www.npmjs.com/package/prop-types instead of React.PropTypes. I has already started throwing up deprecation warnings.

But switching to the new format throws up ESLint warnings. I think the same applies for forbid-prop-types rule as well. 

Regards
Sharbel

**Comment by ljharb** [comment]
Can you provide examples of what warnings you get with `prop-types` that you don't get with `React.PropTypes`?

**Comment by sharbel-keyvalue** [comment]
Hi

I think it was 'react/require-default-props.

Regards
Sharbel

*Sharbel Cherian*
*Founder & CEO*
*Key**Value*
*Software Systems.*(91) 9446-084-504
*sharbel@ <sharbel@clearfoodinc.com>keyvalue.systems*

**Comment by ljharb** [comment]
We'd need the actual component code that was causing warnings.

**Comment by ipiz** [comment]
@ljharb 
I'm not sure if this may help:
![image](https://cloud.githubusercontent.com/assets/1954163/26816755/f0b33942-4ac5-11e7-84f6-44463fb798ac.png)

**Comment by ipiz** [comment]
@ljharb  I'm not sure if this is the same issue
![image](https://cloud.githubusercontent.com/assets/1954163/26816831/4968a54a-4ac6-11e7-8f7a-034ebbbdc5e0.png)

**Comment by ljharb** [comment]
@ipiz it's `Button.propTypes`, not `Button.PropTypes`.

**Comment by ipiz** [comment]
My bad. Thanks @ljharb  That solves my issues.

**Comment by ljharb** [comment]
@sharbel-keyvalue could you provide the actual component code that's causing your warnings?

**Comment by ljharb** [comment]
This seems solved; please file a new issue if you're still having trouble with the latest version of the plugin.
