### ISSUE TITLE
make sort-comp fix natively with eslint --fix

### ISSUE THREAD

**Issue by tsheaff** [yannickcr/eslint-plugin-react#1214]
Why require a 3rd party codemod that needs to be installed and configured manually? I tried using this in my app but found it to be buggy and liable to become stale (this is the whole point of npm / yarn).  Can `sort-comp` and other rules that require react-codemod to be fixed just do so natively when I call `eslint --fix`?  Would be super handy and way more robust / simple 😄

**Comment by ljharb** [comment]
I'm not sure what react-codemod has to do with anything.

It sounds like a great idea to make this rule autofixable, but I think it might be complex because eslint's autofixing can only do text replacement, so it might require multiple passes to sort properly.

**Comment by ljharb** [comment]
A PR to improve or add autofixing is always great, but I'm going to close this.
