### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by SimenB** [yannickcr/eslint-plugin-react#1225]
Tried searching, couldn't find an issue on it... Sorry if it exists already!

I was investigating why our eslint run is super slow, and it seems like eslint-plugin-react has the 3 worst offenders, by almost an order of magnitude (totalling 3/4 of our runtime). Is this known?

This is using `eslint-plugin-react@6.10.3`, if improvements have been made in 7, that's great!

```
$ TIMING=1 node_modules/.bin/eslint . --ext js,jsx
Rule                    | Time (ms) | Relative
:-----------------------|----------:|--------:
react/prop-types        |  2276.690 |    24.9%
react/no-multi-comp     |  2141.514 |    23.4%
react/sort-comp         |  2107.674 |    23.0%
max-len                 |   309.908 |     3.4%
indent                  |   284.646 |     3.1%
no-unused-vars          |   191.424 |     2.1%
keyword-spacing         |   119.781 |     1.3%
object-shorthand        |    80.173 |     0.9%
camelcase               |    69.895 |     0.8%
no-unexpected-multiline |    64.387 |     0.7%
```

Config: https://gist.github.com/SimenB/0d5a3f1db680364399c019eede0a713a

**Comment by jseminck** [comment]
Just out of curiosity, how large is your project? 

I see a lot of differences with my output, e.g. for me `no-unused-vars` is much slower but `react/no-unused-prop-types` and `react/sort-comp` are much faster.

```
Rule                           | Time (ms) | Relative
:------------------------------|----------:|--------:
import/no-nodejs-modules       |  6059.752 |    27.7%
react/no-unused-prop-types     |  1304.725 |     6.0%
react/prop-types               |  1191.717 |     5.4%
no-unused-vars                 |  1151.751 |     5.3%
react/no-direct-mutation-state |  1041.367 |     4.8%
react/no-string-refs           |   986.259 |     4.5%
max-len                        |   943.344 |     4.3%
react/sort-comp                |   655.701 |     3.0%
indent                         |   651.466 |     3.0%
react/no-deprecated            |   580.024 |     2.7%
```

This project has about 40k lines of code in 1000 files for the source. And about 50k lines of code in 750 files for the tests. Number of React components is around 225.

**Comment by SimenB** [comment]
Doing `cloc` gives:
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                     352           3891           1039          23763
```

**Comment by ljharb** [comment]
While there's always performance improvements to be had, unfortunately we didn't act on these helpful benchmarks back in 2017, so I'm going to close this. I'm happy to reopen it with updated benchmarks, if it's still an issue with the latest version.
