### ISSUE TITLE
Another `void-dom-elements-no-children` bug?

### ISSUE THREAD

**Issue by moimikey** [yannickcr/eslint-plugin-react#1230]
eslint-plugin-react @ 7.0.1
eslint @ 3.19.0

I've noticed that there have been a commit or two to fix the empty ` void-dom-elements-no-children` bug, but I'm unfortunately having this issue in a very different light, which is concerning:

```
// this is _not_ React.createElement.
// I literally named the function this.
const createElement = (props) => <SomeComponent {...props} />;
```

the linter sees `createElement` as `React.createElement`. If props are withheld, I get the following lint error:

```
TypeError: Cannot read property 'value' of undefined
    at EventEmitter.CallExpression (/Users/mhertzberg/Gizmodo/kinja-mantle/packages/kinja-components/node_modules/eslint-plugin-react/lib/rules/void-dom-elements-no-children.js:106:34)
    at emitOne (events.js:101:20)
```

If I pass an arbitrary prop, it doesn't fail anymore (which is expected, `React.createElement()` should not work, but `React.createElement(withArgs)` would)

After renaming `createElement` to `stubElement`, the error goes away.

**Comment by moimikey** [comment]
not the fairest of caveats, but if I were to open a PR to remove this check, would that suffice? or is this a caveat of using this plugin now? or is it more complex than simply removing those few lines.

**Comment by ljharb** [comment]
It's more complex. It needs to work with `const { createElement } = React; … createElement(…)`.

**Comment by moimikey** [comment]
@ljharb so all tests PASS when I made the following change to `util/Components.js`:

```diff
      var calledDirectly = (
        node &&
        node.callee &&
-       node.callee.name === 'createElement'
+       node.callee.name === 'createElement' &&
+       node.arguments.length > 0
      );
```

with these additional tests to `tests/void-dom-elements-no-children.js`:

```js
    }, {
      code: [
        'import React from "react";',
        'const createElement = () => {};',
        'createElement()'
      ].join('\n')
    }, {
      code: [
        'const createElement = () => {};',
        'createElement()'
      ].join('\n')
    }
```

**Comment by ljharb** [comment]
@moimikey that works great when it's invoked with zero arguments - but it wouldn't address that `createElement(props)` would trigger the same logic, no?

**Comment by moimikey** [comment]
@ljharb bah. touché. i guess the only alternative here really is to consider `createElement` as a "reserved word," so to speak.

**Comment by ljharb** [comment]
I'd think so, since there's a pragma setting to rename it if you like - ie, you can make "MyCreateElement" be your React.createElement function, but then *that* becomes a reserved word.
