### ISSUE TITLE
Use template literals in tests

### ISSUE THREAD

**Issue by jseminck** [yannickcr/eslint-plugin-react#1240]
This is a development related question. Since eslint has to support Node 4, and Node 4 seemingly has support for template literals (see http://node.green/). Is it ok to use this syntax in eslint-plugin-react? It would be much nicer to write:

```js
code: `
   component MyHugeComponent {
   ...
}`
```

Instead of the current approach - which is pretty annoying when writing big components:

```js
code: [
  'component MyHudeComponent {',
  '...',
  '}'
].join('\n\)
```

Also it seems eslint itself already uses the template literals: https://github.com/eslint/eslint/blob/master/tests/lib/rules/newline-after-var.js#L329

**Comment by ljharb** [comment]
Yes, absolutely it would. The change to drop node < 4 is recent, and we just haven't gone through and updated everything to use patterns node 4 supports.

We also have to go through and convert every `var` to `const` or `let`, for example, as well as convert inline function callbacks to arrows.

**Comment by jseminck** [comment]
Cool. It would be really nice to see the code-base more "modern". :) 

I have been doing some `var` to `const`/`let` changes recently. I should hopefully get around to finishing that on Thursday or Friday.

**Comment by ljharb** [comment]
All the tests have been converted at this point.
