### ISSUE TITLE
False indentation, when use jsx-closing-bracket-location --fix

### ISSUE THREAD

**Issue by dzhytomyrsky** [yannickcr/eslint-plugin-react#1247]
Hello! Used fixer for this code: 

        `const stack = notifications.map((notification, index) =>
            (<Notification
                actions = { actions }
                content = { notification.get('content') }
                heading = { notification.get('heading') }
                icon = { notification.get('icon') }
                id = { notification.get('id') }
                index = { index }
                key = { notification.get('id') }
                theme = { notification.get('theme') }
            />)
        );`

Closing `/>)` line was indented not properly, need additional space before `/>)`, which was not added. Using last version of eslint-plugin-react with prettier (prettier + prettier-eslint + prettier-eslint-cli).

**Comment by dzhytomyrsky** [comment]
Fixed with 

react/jsx-closing-bracket-location: [1, {"selfClosing": "line-aligned", nonEmpty: "after-props"}]

**Comment by sahanatroam** [comment]
@dzhytomyrsky did you add this piece of code to the package settings ?

**Comment by AtlasMaxima** [comment]
@sahanatroam you add the code to `eslintrc.js` or your `estlin` config file.
