### ISSUE TITLE
npm package release with jsx-max-props-per-line --fix

### ISSUE THREAD

**Issue by dzhytomyrsky** [yannickcr/eslint-plugin-react#1248]
Hello! 

Guys, when will you update npm package with jsx-max-props-per-line --fix, which was added 20 days ago? It will be cool to get this feature via npm package, because it is super-duper useful! 

As I see from https://github.com/yannickcr/eslint-plugin-react/pull/949 and https://github.com/yannickcr/eslint-plugin-react/issues/1243 it is ready and valuable!

**Comment by yannickcr** [comment]
Released in `v7.1.0`, sorry for the delay.
