### ISSUE TITLE
prop-types: 'children' is missing in props validation for ..component

### ISSUE THREAD

**Issue by AndrewRevinsky** [yannickcr/eslint-plugin-react#126]
Isn't `children' a sort of ever-present property? Why warning then?

**Comment by AlexKVal** [comment]
You are not the first who asks it :smile: 
I am too: https://github.com/yannickcr/eslint-plugin-react/issues/54

**Comment by AlexKVal** [comment]
Issue should be closed now :wink:

**Comment by yannickcr** [comment]
The rule is enforcing prop-types for all used props in your component (for documentation and debugging purpose), if you do not use the `children` props you will not get any warning.

You can still use the [ignore option](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md#rule-options) if you really do not want to set it for `children`.
