### ISSUE TITLE
Getting an error when explicitly turning off reservedFirst or noSortAlphabetically on jsx-sort-props

### ISSUE THREAD

**Issue by cjhoward92** [yannickcr/eslint-plugin-react#1267]
versions:

`"eslint-plugin-react": "7.1.0"`
`"babel-eslint": "7.2.2"`
`"eslint": "3.19.0"`

When I try to run the following config I get two errors:

`"react/jsx-sort-props": [2, { "reservedFirst": false, "noSortAlphabetically": false }]`

Error:

```javascript
Configuration for rule "react/jsx-sort-props" is invalid:
 Value "data["0"].reservedFirst" has additional properties.
 Value "data["0"].noSortAlphabetically" has additional properties.

at validateRuleOptions (C:\Dev\MyProject\build\node_modules\eslint\lib\config\config-validator.js:115:15)
at Object.keys.forEach.id (C:\Dev\MyProject\build\node_modules\eslint\lib\config\config-validator.js:162:13)
at Array.forEach (native)
at Object.validate (C:\Dev\MyProject\build\node_modules\eslint\lib\config\config-validator.js:161:35)
at Object.load (C:\Dev\MyProject\build\node_modules\eslint\lib\config\config-file.js:522:19)
at loadConfig (C:\Dev\MyProject\build\node_modules\eslint\lib\config.js:63:33)
at getLocalConfig (C:\Dev\MyProject\build\node_modules\eslint\lib\config.js:130:29)
at Config.getConfig (C:\Dev\MyProject\build\node_modules\eslint\lib\config.js:256:22)
at hashOfConfigFor (C:\Dev\MyProject\build\node_modules\eslint\lib\cli-engine.js:599:41)
at executeOnFile (C:\Dev\MyProject\build\node_modules\eslint\lib\cli-engine.js:648:32)
```

I have tried many different configurations, like:

```javascript
"react/jsx-sort-props": [2, { "reservedFirst": [0, []] }]
"react/jsx-sort-props": [2, { "reservedFirst": [0, false] }]
"react/jsx-sort-props": [2, { "reservedFirst": [2, []] }]
```

The reason I am explicitly setting the rule is because it appears that `reservedFirst` breaks the default rules. We used to have our config set to

`"react/jsx-sort-props": 2`

for alphabetical sorting, but with this new option it appears that reserved props are always taken into account, and our linter is throwing errors because of it. The linter always looks for the following props

```javascript
var RESERVED_PROPS_LIST = [
  'children',
  'dangerouslySetInnerHTML',
  'key',
  'ref'
];
```

Let me know if you need more info.

**Comment by ljharb** [comment]
Just to confirm; are you sure you're not inheriting settings from anywhere else?

`reservedFirst` can only be an array or a boolean; it defaults to `false`.

Can you confirm that `npm ls` exits successfully?

**Comment by cjhoward92** [comment]
`npm ls` fails on some internal packages.

**Comment by ljharb** [comment]
When `npm ls` exits nonzero, nothing can be expected to work properly, and often in the eslint ecosystem people can have incorrect peer deps installed.

**Comment by cjhoward92** [comment]
I believe my peer dependencies to be correct for `eslint` and all of my plugins. I made a point to verify that. However I will do some digging into why `npm ls` fails and see if that resolves the issues.

**Comment by ljharb** [comment]
Alternatively, if you can come up with test cases that don't [already exist](https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/jsx-sort-props.js) that fail, that would be super helpful!

**Comment by cjhoward92** [comment]
When I get back to this I will definitely verify the test cases. If I find anything I will submit a PR.

**Comment by ljharb** [comment]
Happy to accept PRs with test cases, but absent those, I'll close this.
