### ISSUE TITLE
Use PropTypes from prop-types package instead of react

### ISSUE THREAD

**Issue by dferber90** [yannickcr/eslint-plugin-react#1283]
This is a proposal for a new rule which warns when `PropTypes` is imported from `react`.

#### Reasoning behind rule
As stated in the [docs](https://facebook.github.io/react/docs/typechecking-with-proptypes.html):

> Note: React.PropTypes is deprecated as of React v15.5. Please use the prop-types library instead. 

Developers should not use the deprecated import.

#### Implementation
```js
module.exports = function(context) {
  return {
    ImportDeclaration: function(node) {
      if (node.source.value !== 'react') return;
      node.specifiers.forEach(importSpecifier => {
        // filter out ImportDefaultSpecifier
        if (importSpecifier.type !== 'ImportSpecifier') return;

        if (importSpecifier.imported.name === 'PropTypes')
          context.report(
            importSpecifier,
            'Deprecated. Import from "prop-types" instead.'
          );
      });
    },
  };
};
```

#### Questions
- Would you accept a PR adding this rule? If so, is there a name suggestion?
- Should support for `require` be added as well?

**Comment by jseminck** [comment]
Maybe it can be added under the `no-deprecated` rule? There is already support to error using `myProp: React.PropTypes.string`.

**Comment by dferber90** [comment]
Wasn't aware of `no-deprecated` and we didn't upgrade our React version in the shared settings. Closing as it works now 🙌
