### ISSUE TITLE
display-name check target to non-component

### ISSUE THREAD

**Issue by eugeny-dementev** [yannickcr/eslint-plugin-react#1295]
When `react/display-name` configured as 
```js
'react/display-name': ['error', { ignoreTranspilerName: true }]
```
eslint produce `Component definition is missing display name  react/display-name` error for that:
```js
import React from 'react';

import Comp from './Component.jsx';

export default {
  someFunctionName(arg) {
    return (
      <Comp
        arg={arg}
      />
    );
  },
};
```
If set `ignoreTranspilerName` to false then it's ok, no errors

**Comment by ljharb** [comment]
In this case, `someFunctionName` is an object method that returns an element - ie, it's a component. I'm not sure why you're not just exporting the function directly?

However, are you expecting that the concise method name would be "someFunctionName" when `ignoreTranspilerName` is `true`?

**Comment by eugeny-dementev** [comment]
It shaped as object with function because it used as mixin.

I expect that `displayName` with `ignoreTranspilerName: true` option should be required only for components created as ES6 class with `extend React.Component` or with 'create-react-class' module. 
And method names probably shouldn't be handled at all, because `render` method can be placed in mixin for example.

Of course using mixin already marked as deprecated feature but unfortunately legacy is still so legacy.

**Comment by ljharb** [comment]
I'm not sure I understand the use case for mixing in a component; and renderFoo methods (functions that return jsx) should instead be components, in every case.

**Comment by eugeny-dementev** [comment]
For example it can be that way: 
```js
const headerMixin = {
  renderHeader () { return <div>Title</div>; },
};
const contentMixin = {
  renderContent () { return <div>Content</div>; },
};
const renderMixin = {
  render () {
    return (
      <div>
        {this.renderHeader()}
        {this.renderContent()}
      </div>
    );
  },
};
const Page1 = createReactClass({
  displayName: 'CoolPage',
  mixins: [
    renderMixin,
    headerMixin,
    contentMixin,
  ],
});
```

But it's not the point. I'm just saying that it's strange from something that cannot be used as react component (plain object with method that returns jsx) receive errors for react component.

**Comment by ljharb** [comment]
There's no way for a jsx linter plugin to differentiate between "a function that returns an element" and "a component". Thus, this project has chosen to consider all functions that return elements, "components".

You can disable the rule with config or override comments if it doesn't work for you.

Totally separately, I'd strongly discourage your mixin pattern; `renderContent` and `renderHeader` should be separate components (SFCs, ideally), and you shouldn't be using `createReactClass` at all, since it's been deprecated since React v0.14.

**Comment by eugeny-dementev** [comment]
I didn't say that this pattern with mixins is something good. Just example.
