### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined in jsx-no-target-blank 

### ISSUE THREAD

**Issue by green-arrow** [yannickcr/eslint-plugin-react#1296]
I'm getting this error after upgrading `react-scripts` to the latest version. Example code:

```js
<a target="_blank" rel="noreferrer noopener" href="https://www.example.com">
```

The source line from the error is line 28, where it does `attr.name.name`.

**Comment by ljharb** [comment]
That's an unclosed element; what's the full source?

**Comment by green-arrow** [comment]
Sorry about that, here's the full source:

```js
<a
  {...css(
    styles.muted,
    styles.footerItem,
    styles.fullWidthOnMobile
  )}
  target="_blank"
  rel="noopener noreferrer"
  href="https://www.company.com/about"
>
  about company
</a>
```

**Comment by green-arrow** [comment]
FWIW, I can't replicate this on a freshly created `create-react-app`. It only occurs after upgrading from 1.0.4 to 1.0.10.

**Comment by ljharb** [comment]
Any chance the upgrade isn't bumping eslint-plugin-react? If you do the upgrade and then npm install eslint-plugin-react, what happens?

**Comment by green-arrow** [comment]
I compared `yarn.lock` files between a fresh app and my upgraded one, and the version numbers for eslint and eslint-plugin-react match up between the two.

Here is the result of upgrading `react-scripts`:

<img width="377" alt="screen shot 2017-07-12 at 2 53 39 pm" src="https://user-images.githubusercontent.com/2180127/28134823-2856c9f0-6712-11e7-9e01-a586b9014af8.png">

It looks like `eslint-plugin-react` was updated to the latest version alright.

When running `npm install eslint-plugin-react` after doing the upgrade above, I still get the `TypeError`.

**Comment by ljharb** [comment]
It's likely the spread that's doing it.

**Comment by ljharb** [comment]
Can you confirm by removing it temporarily?

**Comment by green-arrow** [comment]
@ljharb - you're completely right, removing the spread on `css` fixes the issue.

Any way to work around this?

**Comment by ljharb** [comment]
I don't think there's a workaround short of disabling the rule entirely for that file.

**Comment by jseminck** [comment]
Working on a fix.

**Comment by green-arrow** [comment]
Thanks for the fix, you all are awesome! :smile:
