### ISSUE TITLE
no-typos doesn't seem to exist

### ISSUE THREAD

**Issue by dajomu** [yannickcr/eslint-plugin-react#1300]
Hi, I'm using v7.1.0 and when I add the rule `"react/no-typos"` to my .eslintrc it says that it doesn't exist.
I don't think I'm missing something as I've successfully added other rules. Am I getting the naming of the rule wrong?

**Comment by ljharb** [comment]
That rule has been merged but not yet released.

**Comment by DianaSuvorova** [comment]
@ljharb should we close this then 😉
