### ISSUE TITLE
no-literals: only check strings

### ISSUE THREAD

**Issue by davidyorr** [yannickcr/eslint-plugin-react#1301]
should the no-literals rule check if the `node.value` is a string? with the new `{ "noStrings": true }` option (https://github.com/yannickcr/eslint-plugin-react/pull/1202) I'm getting errors for explicitly set boolean and number props `booleanprop={true}` `numberprop={100}`

**Comment by ljharb** [comment]
With that option turned off, do you still see the errors?

If enabling the option creates new warnings for non-strings, then yes, that's a bug.

**Comment by davidyorr** [comment]
with `{ "noStrings": false }` the errors are not there. i can fix it by adding the type check and submit a PR

**Comment by ljharb** [comment]
Thanks, that'd be great!

**Comment by davidyorr** [comment]
https://github.com/yannickcr/eslint-plugin-react/pull/1302

**Comment by davidyorr** [comment]
oh i put the wrong issue # in the commit message -__-

**Comment by davidyorr** [comment]
ok i fixed it, let me know if there's anything i need to change
