### ISSUE TITLE
Typo in master document jsx-no-bind

### ISSUE THREAD

**Issue by egberts** [yannickcr/eslint-plugin-react#1306]
In the following excerpt in https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md:

```
<div onClick={() => console.log('Hello!'))}></div>
```

There is an imbalance (uneven) set of parenthesis.

**Comment by ljharb** [comment]
Thanks, want to make a PR correcting it? :-)

**Comment by DianaSuvorova** [comment]
@ljharb , let's close this 🙂

**Comment by ljharb** [comment]
Closed in #1316
