### ISSUE TITLE
react/no-direct-mutation-state does not throw warning when using Object.assign to mutate state.

### ISSUE THREAD

**Issue by manulaggarwal** [yannickcr/eslint-plugin-react#1307]
If I try and mutate the state like : -  **this.state.foo = 'bar'** then react/no-direct-mutation-state throws a warning **Do not mutate state directly. Use setState()  react/no-direct-mutation-state** which is fine. 
However, If I try to mutate the state using Object.assign() like :- **Object.assign(this.state.foo,'bar') then  react/no-direct-mutation-state does not throw any warning**. 
I believe this is not handled in the library. If there is any other explanation to this please share else I believe it's a minor bug.

**Comment by ljharb** [comment]
There's no easy way to handle Object.assign that wouldn't fail to handle _.assign, for example. Some kinds of mutation can't be linted against.

**Comment by manulaggarwal** [comment]
Can this be handled with the help of ES6 Proxy object? Since the setter on this.state is getting called through which the change can be detected! 
Just a thought.

**Comment by ljharb** [comment]
Proxy is a runtime thing - not something a linter can do - and is both not supported on all platforms, and incredibly slow.
