### ISSUE TITLE
Feature request: no-unnecessary-curly

### ISSUE THREAD

**Issue by Billy-** [yannickcr/eslint-plugin-react#1310]
I'd like to suggest a new rule which disallows this:

`<MyComponent someProp={'foo'} />`

where it should be:

`<MyComponent someProp="foo" />`

And the same for children/nodes:

`<MyComponent>{'Foo'}</MyComponent>`

Where it should be:

`<MyComponent>Foo</MyComponent>`

**Comment by ljharb** [comment]
I feel convinced this already exists, but can't find it anywhere.

This is an essential thing to cover; it definitely should be a rule.

It would need to be separately configurable for props and children (curlies are often needed for children for explicit whitespace) to require, forbid, or ignore.

**Comment by jackyho112** [comment]
Hello @ljharb, I would like to give this one a shot. Hopefully, I won't run into a lot of difficulties. I would appreciate any pointer though especially regarding the last thing you mentioned in your comment. Thank you!

**Comment by ljharb** [comment]
@jackyho112 essentially what I mean is that the rule configuration must allow an option like `{ props: 'always', children: 'never' }` (where always/never/ignore are the three valid values)

**Comment by jackyho112** [comment]
Hello @ljharb, I am working on this right now and I have one question. Regarding your suggestion, do `always`, `never` and `ignore` mean `always have curly braces`, `never have unnecessary curly braces` and `ignore the rule` or `always check for unnecessary curly braces`, `never check for unnecessary curly braces` and `ignore the rule`?

**Comment by ljharb** [comment]
I mean the former - "always require", "always prohibit", and "ignore the rule"

**Comment by jackyho112** [comment]
@ljharb 

Thanks for replying! I will make the changes.

**Comment by ljharb** [comment]
Thanks! (It'd be great if you reused #1349 instead of opening up a new PR)

**Comment by jackyho112** [comment]
Will do!

**Comment by jseminck** [comment]
Very cool rule! 😄 

Just out of interest, is there a technical reason that the fixer only works for one of the options (only for `never` but not for `always`) ?

**Comment by jackyho112** [comment]
@jseminck, @ljharb, 

Based on the [eslint doc](http://eslint.org/docs/developer-guide/working-with-rules)

**Comment by jackyho112** [comment]
@jseminck 
Nvm. I misinterpreted the eslint docs. I think I can fix for `always` as well.

**Comment by alexzherdev** [comment]
I think this can be closed (via #1349)

**Comment by ljharb** [comment]
Yes, thanks - closed by #1349.
