### ISSUE TITLE
[Question] Is there any rule to enforce each JSX node to be placed on the new line?

### ISSUE THREAD

**Issue by miraage** [yannickcr/eslint-plugin-react#1321]
Not sure if the question is clear. Let me share err/ok example.
```jsx
// error
const Component = () => (
  <div className="Component">
    <h1>Heading</h1> // <<-- error
  </div>
);
```
```jsx
// ok
const Component = () => (
  <div className="Component">
    <h1>
      Heading
    </h1>
  </div>
);
```

// EDIT

```jsx
const Component = () => (
  <div className="Component">
    <h1>Heading</h1> // <<-- error
    <i className="fa fa-plus" /> // <<-- ok
    <i
      className="fa fa-plus"
      onClick={callback}
    /> // <<-- ok
  </div>
);
```

**Comment by ljharb** [comment]
So you want to ban single-line elements? What about `<div />`?

**Comment by miraage** [comment]
@ljharb nope. Only for elements with closing tags.

**Comment by ljharb** [comment]
Thanks, I think that's clear now.

What's the rationale for this rule? How would you propose the inverse behave, when someone wants to force one-line elements, and how would that interact with `max-len`?

**Comment by miraage** [comment]
Not quite sure if there is any rationale behind. I prefer such syntax due to decreased overall line length.
The main reasons why I personally would like to have a such rule:
* static text in components is potential subject to change and might surpass `max-len`
* multiple components in single line hurt my eyes; also new props may be added - `max-len` issues again.

**Comment by ljharb** [comment]
For one, I would certainly be in favor of a rule that prevented multiple components in a single line - ie, preferring `<div />\n<span />` over `<div /><span />`, regardless of length.

Regarding length issues, wouldn't the `max-len` warn on lines that are too long?

**Comment by miraage** [comment]
When you open inspector in any browsers devtools all tags are placed on the new line.
Probably I'd like to have such behavior, while text nodes may be excluded from this rule.

**Comment by ljharb** [comment]
I see `<div class="clear"></div>` and `<div class="comment-form-error js-comment-form-error" style="display:none">There was an error creating your Issue.</div>` on this very page in Safari on one line.

In general I prefer writing a component on a single line whenever it's possible to do so - and while there's plenty of rules that don't conform to my personal style, I find that deciding how the rule could be built and configured via options such that i *would* use it, is a useful process. I'm trying to understand the value beyond "i want it that way".

**Comment by SBRK** [comment]
I second this, I would like this rule, for better readability in our code
