### ISSUE TITLE
Cannot read property 'type' of undefined require-default-props

### ISSUE THREAD

**Issue by wwwdata** [yannickcr/eslint-plugin-react#1324]
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at /Users/somebody/Development/whatever/node_modules/eslint-plugin-react/lib/rules/require-default-props.js:196:24
    at Array.filter (native)
    at getPropTypesFromTypeAnnotation (/Users/somebody/Development/whatever/node_modules/eslint-plugin-react/lib/rules/require-default-props.js:195:30)
    at Object.handleStatelessComponent (/Users/somebody/Development/whatever/node_modules/eslint-plugin-react/lib/rules/require-default-props.js:305:42)
    at EventEmitter.updatedRuleInstructions.(anonymous function) (/Users/somebody/Development/whatever/node_modules/eslint-plugin-react/lib/util/Components.js:624:75)
```

The crashing code looks like this

```js
var props = properties.filter(function(property) {
  return property.type === 'ObjectTypeProperty';
});
```

with this piece of code I can let it crash:
```js
/* @flow */

type FooFing = { foo: number };
type Something = string;
type AnotherTing = Something & FooFing;

const SomeWeirdComponent = (props: Something | AnotherTing) => "test";
```

Versions used:

```json
    "eslint": "^3.18.0",
    "eslint-plugin-react": "^7.1.0",
```

**Comment by ljharb** [comment]
Looks like it might be an issue with union types?

Do you get the same bug with the latest eslint 3, and with eslint 4?

**Comment by wwwdata** [comment]
yes, I also upgraded to the latest version of eslint yesterday and the same problem happens in there as well. But it only makes sense because it was caused by `eslint-plugin-react`

**Comment by AKFourSeven** [comment]
This issue seems to be outstanding and not just with flow types as I still get this error even with the latest version of `eslint-plugin-react`

**Comment by ljharb** [comment]
@AKFourSeven can you provide code that errors that’s not using flow?

**Comment by AKFourSeven** [comment]
Sorry my error was slightly different, it is not `type of undefined`, but `range of undefined` and apparently it has more to do with `babel-eslint`

**Comment by ljharb** [comment]
The original code does not crash.
