### ISSUE TITLE
jsx-wrap-multilines option for always newlining 

### ISSUE THREAD

**Issue by planttheidea** [yannickcr/eslint-plugin-react#1328]
There are a few other issues related to this concept, where the autofix for `jsx-wrap-multilines` results in something like this:

```javascript
return (<div>
  foo
</div>);
```

This happens in specific scenarios (when there is no indentation set), but this always happens with multiline self-closing tags:

```javascript
return (<SomeChildlessComponent
  foo="foo"
  bar="bar"
/>);
```

It would be really handy if there was an option added to `jsx-wrap-multiline` that always newlined the wrapped output on autofix, so that tag alignment was maintained:

```javascript
return (
  <SomeChildlessComponent
    foo="foo"
    bar="bar"
  />
);
```

Since the whole point is that wrapping the element enhances readability, this option would help greatly.

**Comment by jseminck** [comment]
I believe this was already requested here: https://github.com/yannickcr/eslint-plugin-react/issues/1207#issuecomment-302906085 

Although that comment is a bit hidden...

**Comment by ljharb** [comment]
Does #1475 cover this?

**Comment by jseminck** [comment]
I think it does. See example below, using autofixer on save + `jsx-ident` rule.  Not sure why `hello world` does not get indented, but that's not part of this rule but `jsx-indent` instead.

![jsx-wrap-multilines](https://user-images.githubusercontent.com/9586897/32979578-58999e9a-cc60-11e7-93cf-963d27cd6d2c.gif)
