### ISSUE TITLE
jsx-closing-bracket-location with 'props-aligned' violates ESLint indent rule

### ISSUE THREAD

**Issue by IanVS** [yannickcr/eslint-plugin-react#1333]
I'd like to write my non-empty tags like this:

```js
<foo
    prop='bar'
    >
    Text
</foo>
```

And it seems that `react/jsx-closing-bracket-location:  ['error',  {nonEmpty: 'props-aligned'}]` would get me exactly what I want, but then I get an error thrown from eslint 4.3.0 saying it wants this style:

```js
<foo
    prop='bar'
>
    Text
</foo>
```

Is it possible that `props-aligned` is just not possible to use along with the `indent` rule now?

**Comment by ljharb** [comment]
Yes. In eslint 4, you have to configure the indent rule to ignore JSX if you want anything besides what they enforce by default.

**Comment by IanVS** [comment]
Ok, looks like we'll need to wait for https://github.com/eslint/eslint/issues/8594.  Thanks.

**Comment by jprosevear** [comment]
eslint/eslint#8594 has landed.
