### ISSUE TITLE
`no-unused-state` rule doesn't handle dynamic keys

### ISSUE THREAD

**Issue by EvHaus** [yannickcr/eslint-plugin-react#1361]
@wbinnssmith The following code:

```javascript
_handleUpdate = (stateName, active) => {
	this.setState({[stateName]: active});
};
```

Gives out an `Unused state field: 'stateName'` error from the `no-unused-state` rule.

I think it's probably best to have `no-unused-state` rule ignore dynamic object keys since it will be too difficult to detect whether or not they're really being used. But at the very least, it shouldn't use the variable name as the key to look for.

**Comment by ljharb** [comment]
I agree that this is a bug - it should entirely ignore computed property keys when the contents aren't a string literal.

**Comment by jseminck** [comment]
@EvHaus it seems like this can be closed? (linked PR is merged)

**Comment by EvHaus** [comment]
@jseminck Indeed. Closing!
