### ISSUE TITLE
'space-before-function-paren' returns error/warning for functions defined as object attributes

### ISSUE THREAD

**Issue by darrenklein** [yannickcr/eslint-plugin-react#1362]
I'm using ESLint v. 4.4.1, and I'm getting the following warning:

`2:32  warning  Unexpected space before function parentheses  space-before-function-paren`

for this code:

    const errorProcessing = {
        "processErrorOnForm": function(param, otherParam) {
            if (param) {
                // DO SOMETHING...
	        } else {
                // OTHER STUFF...
		}
	     }
    };

But as you can see, there is no space before the function parentheses.

The documentation is very thorough - http://eslint.org/docs/rules/space-before-function-paren - but does not cover this particular scenario, where a function is an attribute of an object.

It's not a critical issue... but any advice?

**Comment by ljharb** [comment]
What's your `space-before-function-paren` set to?

**Comment by darrenklein** [comment]
Sorry, I meant to include that - thanks for reminding me.

`"space-before-function-paren": [1, "never"]`

**Comment by darrenklein** [comment]
Oh shoot - this is the wrong repo - meant to post this in https://github.com/eslint/eslint
