### ISSUE TITLE
Arrow functions in functional component and jsx-no-bind rule

### ISSUE THREAD

**Issue by Palisand** [yannickcr/eslint-plugin-react#1379]
For a **stateless, functional component** that breaks the `jsx-no-bind` rule like the following:

``` javascript
const Foo = ({callback, baz}) => (
  <Bar onClick={() => callback(baz)} />  // allowArrowFunctions: false
);
```
changing it to the following will remove the lint warning:
``` javascript
const Foo = ({callback, baz}} => {
  const handleClick = () => callback(baz);
  return (
    <Bar onClick={handleClick} />
  );
};
```
Does this actually improve performance by preventing the creation of a function on re-render (as stated in the [rule description](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md)) or has the rule not taken this into account?

**Comment by ljharb** [comment]
No, it does not.

The *only* proper solution (even with class properties) is:
```jsx
class Foo extends React.Component {
  constructor (...args) { super(...args); this.handleClick = this.handleClick.bind(this); } // if not using class properties
  handleClick = this.handleClick.bind(this); // if using class properties

  handleClick() {
    const { callback, baz } = this.props;
    callback(baz);
  }

  render() {
    return <Bar onClick={this.handleClick} />;
  }
}
```

**Comment by Palisand** [comment]
@ljharb Thanks. So in this case, **a class component is preferred over a functional one**. How come airbnb allows refs and arrow functions, is the performance benefit not great enough to warrant these lint checks? In your opinion, is it always best to refactor a stateless component into a class when dealing with arrow functions, even with the planned functional component performance optimizations?

**Comment by Palisand** [comment]
@ljharb Also, (as you know) newer syntax allows your solution to be re-written without `bind`:
``` javascript
class Foo extends React.Component {

  handleClick = () => {...}

  render() {...}
}
```
Does the following revert to the original problem?
``` javascript
class Foo extends React.Component {

  handleClick = (quux) => () => {...}

  render() {
    return (
      <div>
         <Bar onClick={this.handleClick(baz)} />
         <Bar onClick={this.handleClick(qux)} />
      </div>
    );
  }
}
```

**Comment by ljharb** [comment]
@Palisand specifically, the bound `handleClick` is state, and as such, you need a stateful component.

It's impossible for a linter to cover everything that might be in a style guide, so we have no requirement to lint for everything in the guide. Things that require human judgement often go unlinted, intentionally.

SFC optimizations don't change the fact that the *child component* you're rendering might not have those optimizations - and the parent component shouldn't possess that knowledge about the child.
