### ISSUE TITLE
Warn when prop is *supplied* that isn't specified in PropTypes

### ISSUE THREAD

**Issue by jonathanglasmeyer** [yannickcr/eslint-plugin-react#140]
I wonder if this behaviour is already integrated? By supplied i mean that a caller would call React.createElement with the given component, supplying a 'wrong' prop, i.e. one that isn't defined in the component's PropTypes.
I think this behaviour is pretty crucial to assist rename refactorings of props.

**Comment by mathieumg** [comment]
Do you mean on a `React.createElement` call that directly wraps a `React.createClass` call? Otherwise, this would be pretty difficult.

**Comment by jonathanewerner** [comment]
I'm sorry, but I don't really get the question. I basically mean iterating
over all keys in this.props in a given component and warn if I find one
that is not specified in the proptypes.

Mathieu M-Gosselin <notifications@github.com> schrieb am Fr., 3. Juli 2015
18:48:

**Comment by mathieumg** [comment]
That is a runtime thing unfortunately, it's out of the scope of ESLint and its plugins.

**Comment by jonathanewerner** [comment]
I see. Well the scope of its capabilities wasn't that clear to me, that's
why I asked.

Mathieu M-Gosselin <notifications@github.com> schrieb am Sa., 4. Juli 2015
08:55:

**Comment by robcolburn** [comment]
To be clear, we mean something like

```js
propTypes: {
  cat: PropTypes.string,
  blob: PropTypes.shapeOf({
    name: PropTypes.string
  })
}
render(){
  return <Dog name={this.props.blob.name} {...this.props.dog} />
}
```

```
dog is not specified as a propType
```

That would be awesome! But, yeah, that does seem difficult with just an AST.

**Comment by DianaSuvorova** [comment]
@ljharb, can we close? [prop-types] takes care of this.
