### ISSUE TITLE
... is missing in props validation, except it's not missing!

### ISSUE THREAD

**Issue by shawninder** [yannickcr/eslint-plugin-react#1421]
I am getting this error for prop types which are indeed defined, though perhaps not in a way the linter expects. Here is how I define my prop types:

```javascript
MyComponent.propTypes = anArray.reduce((prev, item) => {
  const next = {
    ...prev,
  };
  next[`${item}_versions`] = PropTypes.object;
  return next;
}, {
  env: PropTypes.string,
});
```
As you can see, the `env` prop is there (you can check this by inspecting the resulting `MyComponent.propTypes` which indeed has an `env` key), but I still get a linting error saying `'env' is missing in props validation (react/prop-types)`.

This is in Atom by the way, though I doubt it makes any difference.

**Comment by ljharb** [comment]
Because you're using `reduce` to build up `propTypes` with metaprogramming, there's no way for static analysis to figure out what your prop types are.

I strongly suggest explicitly hand-writing them out.

**Comment by shawninder** [comment]
hmm, that means that whenever I change myArray, I would need to remember to change this code too... It feels weird to write lesser quality code just to avoid a linting limitation.

**Comment by ljharb** [comment]
If your prop types are coupled such that changing one array causes a corresponding change to cascade through your component hierarchy, you may want to use hardcoded prop names precisely so that's not the case.

It's not just a linting limitation; one of the points of propTypes is to serve as documentation, and the more explicit you can be, the better - for humans, not just for the linter.

**Comment by shawninder** [comment]
This array is used not only by various components but also by various backend services. The file holding it is the documentation, not the prop types of all components using it. I'm not sure how I can be more explicit without ending up with multiple sources of truth for this array.

**Comment by shawninder** [comment]
I'm just going to close this since it has become obvious this is a problem with my code, not with this package.
