### ISSUE TITLE
`prop-types` fails with destructuring

### ISSUE THREAD

**Issue by MatthewHerbst** [yannickcr/eslint-plugin-react#1422]
The [`prop-types`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md) rule fails when presented with destructuring:

**package.json**
```json
{
  "dependencies": {
    "eslint": "^4.6.1",
    "eslint-plugin-react": "^7.3.0",
    "proptypes": "^1.1.0",
    "react": "^15.6.1"
  }
}
```

**.eslintrc**
```json
{
  "env": {
    "es6": true,
    "node": true
  },
  "parserOptions": {
    "sourceType": "module"
  },
  "plugins": ["eslint-plugin-react"],
  "rules": {
    "react/prop-types": 2
  }
}
```

**Examples.jsx**
```js
import React from 'react';
import PropTypes from 'proptypes';

// FAIL: Should error that `bar` is missing in propTypes
class DestructuredDeepMissing extends React.PureComponent {
  render () {
    const {
      foo: {
        bar,
      },
    } = this.props;

    const it = bar;
  }
}
DestructuredDeepMissing.propTypes = {
  foo: PropTypes.shape({}).isRequired,
};

// Interestingly, non-deep destructuring works just fine
// PASS: Should error
class DestructuredMissing extends React.PureComponent {
  render () {
    const {
      foo,
    } = this.props;

    const it = foo;
  }
}
DestructuredMissing.propTypes = {};
```
Related: #296
Possibly related: #1346 

Also possibly related is that `no-unused-prop-types` (without using Flow) fails on destructuring as well, which is behavior I was able to replicate (though there seem to be a plethora of tickets related to this, especially in the Flow context).

**Comment by ljharb** [comment]
Shape props have known bugs; do you have skipShapeProps enabled?

**Comment by MatthewHerbst** [comment]
@ljharb no - we use Relay, so basically 95% of our props are within a shape (`viewer.x`, or deeper). Enabling that option would be akin to turning this rule off for us. I know that `no-unused-prop-types` has issues with shapes since it mentions that in the description, but there is no such warning in the `prop-types` rule (though makes sense that the two rules would share some issues).

**Comment by jseminck** [comment]
We have this test case:

```js
      code: [
        'class Hello extends React.Component {',
        '  render() {',
        '    this.props.a.b',
        '    return <div>Hello</div>;',
        '  }',
        '}',
        'Hello.propTypes = {',
        '  a: PropTypes.shape({',
        '  })',
        '};'
      ].join('\n'),
      errors: [{
        message: '\'a.b\' is missing in props validation'
      }]
```

Judging from that, it seems some basic shapes support exists and the example should actually be supported.

Indeed when I try the following snippet I actually get an error. But the destructuring doesn't work with the shapes...

```js
class DestructuredDeepMissing extends React.PureComponent {
  render () {
    this.props.foo.bar;
  }
}
DestructuredDeepMissing.propTypes = {
  foo: PropTypes.shape({}).isRequired,
};
```

**Comment by Tokimon** [comment]
I have sort of the same error, but not with any `PropTypes.shape`, but with a rest a destructuring.

#### My example
```jsx
class MyComponent extends React.Component {
  static displayName = 'MyComponent';
  static propTypes = {
    name: PropTypes.string
  }

  render() {
    const { name, title, ...rest } = this.props;
    return (
      <div {...rest}>
        <h1>{name}</h1>
      </div>
    );
  }
}
```

Here it fails to detect `title` as not defined in the `propTypes`. It is most likely linked to the fact that ESLint (babel-eslint i guess) doesn't throw when you have unused variables but end with a desctructuring, like: `const { name, title, ...rest } = this.props;`.
But the strange thing, though, is that even if you take `title` out of the desctrucuturing it still doesn't catch the undefined prop `title`:

```jsx
render() {
    const { name, ...rest } = this.props;
    const title = this.props.title; // <-- this is still not catched as an error
    return (
      <div {...rest}>
        <h1>{name}</h1>
        <h2>{title}</h2>
      </div>
    );
}
```

Again probably linked to the destructuring, but what to do about it so it still catches this undefined property?

**Comment by sstern6** [comment]
@ljharb looked into this tonight locally with latest master, it actually looks like this has been fixed in a commit between last release and today.  The code above is erroring correctly.  I believe this should be fixed when you publish a new version.  Can you confirm?

Thanks

**Comment by sstern6** [comment]
Sure! @ljharb

**Comment by sstern6** [comment]
@ljharb https://github.com/yannickcr/eslint-plugin-react/pull/2029.  When youre ready
