### ISSUE TITLE
jsx-indent: indent the first component differently

### ISSUE THREAD

**Issue by byohay** [yannickcr/eslint-plugin-react#1425]
- eslint 4.5.0
- eslint-plugin-react 7.3.0

Settings:
```js
rules
  react/jsx-indent: [ error, 2 ]
```

I would like to be able to indent the first component in a JSX specification differently (4 spaces) than its child components (2 spaces). For example:
```js
    return (
        <View style={[styles.container, this.props.style]}>
          <View />
        </View>
    );
```

Results in the error:
```
81:9   error  Expected indentation of 6 space characters but found 8  react/jsx-indent
```

**Comment by ljharb** [comment]
I'm not sure I understand. What indentation do you use for your JS, and why would you want that to be different for JSX?

**Comment by byohay** [comment]
At the moment I'm not using any indentation rules for JS, but I do want to indent the JSX components with 2 more spaces than their parent.
The root component doesn't have a parent so I want the rule to ignore it (In the example above, I want it to ignore the indentation of the first `View`).

**Comment by ljharb** [comment]
I'm confused why you'd want to enforce indentation rules in jsx if you're not already enforcing them in JS?

**Comment by byohay** [comment]
Even if I were to use indentation rules for JS, there would still be a problem. Assuming I use these rules:
```
  indent: [error, 4, {'ignoredNodes': ['JSXElement *']}]
  react/jsx-indent: [error, 2]
```

Then the example above still generates an error. In fact, I cannot satisfy both `indent` and `react/jsx-indent` in this scenario.

**Comment by ljharb** [comment]
Try setting ignoredNodes to `['JSXElement', 'JSXElement *']`?

**Comment by byohay** [comment]
I've made a mistake, `indent` will ignore the first component so this will work:
```js
    return (
      <View style={[styles.container, this.props.style]}>
        <View />
      </View>
    );
```

However, what I initially wanted is to have first component indented with 4 spaces and nested components indented with 2 spaces. That is, I want the first component to conform to `indent` rule and not `react/jsx-indent`.

**Comment by ljharb** [comment]
Right, but the first component is `jsx` - I'm still having trouble understanding why you'd want any part of your code to have inconsistent indentation with any other part.

**Comment by byohay** [comment]
To me it doesn't look inconsistent. The way I view it the indentation should be determined by the "outer scope". The outer scope of the first component is the `return` in the case above, so it should be handled by `indent` rule. For a nested component its outer scope is the component above it in the hierarchy, so it should be handled by `react/jsx-indent`. 
`indent` rule can also be configured this way; For example, If I had the linter configured with:
`indent: [error, 2, {'ArrayExpression': 1, 'ObjectExpression': 2}]`
then these examples pass the linter:
```js
var foo = [
  bar,
  baz,
  qux
];
```

```js
var foo = {
    bar,
    baz,
    qux
};
```

The indentation of  `bar`, `baz`, `qux` depends solely on whether they are in an array or object declaration, their "outer scope".

**Comment by ljharb** [comment]
I do understand that you *can* configure that; but I still don't understand why anyone would want to configure the `indent` rule such that every expression wasn't set to `1`.

It seems like to achieve what you want, we'd need an additional option for `initialIndentationLevel`, which defaulted to `1`. I'm still pretty -1 on adding it tho.

**Comment by dlahyani** [comment]
@ljharb consider this JS code for example:
```javascript
fech(request)
    .then((response) => {
        if (response.headers.contentType && 
            response.headers.contentType.includes("application/json")) {
          return response.json();
        }
        throw new TypeError("Oops, we haven't got JSON!");
    })
    .then((json) => {
      let object = MyJSONObjectParser.parseSomeReallyLongNamedObject(
          json,
          additionalParsingParameters
      );
    })
    .catch((error) => {
      // Handle the error.
    });
```

In this code you can see we have 2 different indentations:
- 2 spaces is the normal indentation which is used when open opening a new block of code (the body of the callbacks and the if block).
- 4 spaces is used when you break line in the middle of an expression, for example in the middle of function call, before each of the promise operators (`then` and `catch`) and in the boolean expression of the `if` statement.


The following code returning a JSX element is similar to breaking line in the middle of an expression and hence we want the indentation to be 4 spaces and not 2, but when the nested component `ComponentB` should only be nested 2 spaces from its parent as this is more like nested code blocks.
```javascript
render() {
  return (
      <ComponentA foo="foo">
        <ComponentB bar="bar" />
      </ComponentA>
  );
}
```

**Comment by ljharb** [comment]
Having a different indentation for continuations is super weird imo; it's common in Java, and sometimes in Ruby, but almost never appears in JS. However, that does explain your use case a bit - although "JS → JSX" isn't a continuation.

**Comment by Honga1** [comment]
I second the requirement for this (a business requirement, not personal). However I can see that since there's been very little movement from 2017 we must be the niche case. 

@byohay Did you ever find an adequate solution?

**Comment by ljharb** [comment]
To summarize the state of things: there's certainly idioms in some languages where line continuations have different indentation standards than every other line. However, (thankfully,) in JavaScript this has simply never become an acceptable style. No styleguides handle it, and eslint's indent rule doesn't support it.

I don't think it would make sense to start supporting it here.
