### ISSUE TITLE
"react/prop-types" not being caught

### ISSUE THREAD

**Issue by idahogurl** [yannickcr/eslint-plugin-react#1428]
I ran my React component file against ESLint and it fails to catch missing propTypes.  My config for "react/prop-types" is set to the default. I am using IDEAj for Mac OS for my editor.

Here is my file: [ag_select_campaign_item.txt](https://github.com/yannickcr/eslint-plugin-react/files/1297691/ag_select_campaign_item.txt)

These are the ESLint packages I have installed.

"babel-eslint": "^7.2.3",
    "eslint": "^4.6.1",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.3.0",

**Comment by ljharb** [comment]
What's your `.eslintrc`?

<details>
<summary>contents of the file, so nobody has to download it</summary>

```jsx
import React from 'react';
import { getIconName } from '../../helpers';

const Foundation = window.Foundation;

const AgSelectCampaignItem = React.createClass({

  propTypes: {
    onChangeCampaign: React.PropTypes.func.isRequired,
    item: React.PropTypes.object.isRequired
  },

  selectCampaignItem(e) {
    e.preventDefault();

    const { item, onChangeCampaign } = this.props;
    onChangeCampaign(item);
    Foundation.libs.dropdown.closeall();
  },


  render() {
    const { item, hasPla } = this.props;
    let icon = null;

    if (this.props.hasPla) icon = <i className={`fa fa-${getIconName(item, hasPla)}`} />;
    return (<li key={item.id}>
      <a href="" onClick={this.selectCampaignItem}>
        {icon} {item.display_name}
      </a>
    </li>);
  },


});

export default AgSelectCampaignItem;
```
</details>

Note that createClass is deprecated as of React 15, and so you may need to specify the pragma to "createClass" per https://github.com/yannickcr/eslint-plugin-react#configuration

**Comment by jseminck** [comment]
If I change the code to `const AgSelectCampaignItem = createReactClass({` then the missing prop-type is detected.

In order to properly detect `React.createClass` you have to use this setting:

```
settings: {
  react: {
    createClass: 'createClass' // default is createReactClass
  }
}
```

**Comment by jseminck** [comment]
BTW we have a lot of tests for `React.createClass` but none of them use this setting. Doesn't that mean these are all invalid as component detection isn't working for them? I can imagine this may be overlooked when the `createClass` setting was introduced...

**Comment by idahogurl** [comment]
Thanks, guys. I put in the setting for "createClass" in my .eslintrc file and now it picks it up.
