### ISSUE TITLE
disabling react/jsx-no-literals does not work in files

### ISSUE THREAD

**Issue by ambewas** [yannickcr/eslint-plugin-react#1440]
**Expected behaviour**
Adding `/* eslint-disable react/jsx-no-literals */` to the top of the file should disable the rule for the file in question. 

**Actual behavior**
The rule still gets triggered when running gulp-eslint. 

**More information**
Other rules (eslint default rules, or from this plugin) can be disabled just fine. Only trying to disable this specific rule does not work.

This behaviour started today -- last friday everything was still fine. Gulp-eslint has not been updated since.

**Comment by jseminck** [comment]
That's very weird. I'd expect this to be related to ESLint. They had a new version that was released before the weekend so if your version of ESLint was not locked down it could be related to that?

On the other hand it seems specific to this particular rule, but I don't really understand how/why...

**Comment by ambewas** [comment]
Problem was with the last release of eslint itself. Pinning eslint down to v4.6.1 resolves the issue for now.

I'm closing this and opening an issue with eslint.

**Comment by jseminck** [comment]
There's already an issue that looks related: https://github.com/eslint/eslint/issues/9318

**Comment by ambewas** [comment]
yep, I'm going to add to that 👍
