### ISSUE TITLE
react/prop-types throws error if variable name is `props`

### ISSUE THREAD

**Issue by inferusvv** [yannickcr/eslint-plugin-react#1443]
Case 1.

```
  method = (props) => {
    const { someProp } = props;
  }
```

Case 2.

```
    const props = {
      a: 1,
      b: 2,
    };
    const { a, b } = props;
```

This will throw an error, that `someProp` is missing in props validation, but `props` is just a variable/constant name

**Comment by ljharb** [comment]
In case 1, does `method` return JSX? If so, it's a component according  to this plugin, so "props" isn't just a name.
