### ISSUE TITLE
Using React as a global variable, how to disable "react-in-jsx-scope"?

### ISSUE THREAD

**Issue by Nemsae** [yannickcr/eslint-plugin-react#1451]
Hi guys,

On this project I have React as a global. I am getting this error:

![screen shot 2017-09-26 at 4 10 11 pm](https://user-images.githubusercontent.com/20247504/30888412-3fb043b6-a2d5-11e7-9ad0-33e063a3a88c.png)

What is the syntax for disabling this rule, 'react-in-jsx-scope' in JSON format?

Thanks,

**Comment by yannickcr** [comment]
Setting the `react/react-in-jsx-scope` rule to `off` in your `.eslintrc` should be enough to disable it:

```json
{
  "rules": {
    "react/react-in-jsx-scope": "off"
  }
}
```

[ESLint documentation](https://eslint.org/docs/user-guide/configuring#configuring-rules)
