### ISSUE TITLE
ES6 array methods on prop fail prop-types rule

### ISSUE THREAD

**Issue by thetalecrafter** [yannickcr/eslint-plugin-react#146]
If a prop is validated as `React.PropTypes.array` using the `find` method on the array causes the react/prop-types rule to fail.

The ES6 methods should not need to be declared in prop types.

**Comment by yannickcr** [comment]
Do you still have the problem with the latest version ? In `2.7.0` we removed some limitations to be more permissive about authorized methods on `string`, `array`, `number`, `boolean` and `function`

**Comment by thetalecrafter** [comment]
I was using `2.6.4`. I updated to `2.7.0` and now I get:

```
node_modules/eslint-plugin-react/lib/rules/prop-types.js:474
          propTypes.parent.type !== 'AssignmentExpression' &&
                          ^
TypeError: Cannot read property 'type' of undefined
    at markPropTypesAsDeclared (node_modules/eslint-plugin-react/lib/rules/prop-types.js:474:27)
    at node_modules/eslint-plugin-react/lib/rules/prop-types.js:596:9
    at Array.forEach (native)
    at EventEmitter.ObjectExpression (node_modules/eslint-plugin-react/lib/rules/prop-types.js:592:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (node_modules/eslint/lib/eslint.js:724:25)
    at Controller.__execute (node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (node_modules/eslint/lib/eslint.js:717:24)
```

**Comment by yannickcr** [comment]
Ho. Can you post the source code that trigger this error ?

**Comment by thetalecrafter** [comment]
Now I gotta track it down, that was linting my whole product's source code...

**Comment by thetalecrafter** [comment]
ok, looks like it was one of my distribution files that was supposed to be ignored that caused the error. I'm pretty sure giving you 827 KB of minified code isn't going to be very helpful.

Properly ignoring that file, `2.7.0` fixes the original reported problem. Thank you!

**Comment by lambert-velir** [comment]
Is this a problem again?  I have 3.1.0 installed `eslint-plugin-react@3.1.0`.

I have a line: `const product = this.props.products.find((p) => p.id === id);`
that has a lint error `"products.find' is missing in props validation (react/props-types)`

**Comment by rbardini** [comment]
I'm also facing this issue in `eslint-plugin-react@3.3.1`.

```js
var column = this.props.metadata.find(column => column.name === filterColumn.name);
```

results in `'metadata.find' is missing in props validation` even though the `metadata` prop type is specified as `PropTypes.arrayOf(PropTypes.object)`.

**Comment by yannickcr** [comment]
Seems to be a specific problem with the `find` method.

We only allow methods defined on `Array.prototype`, but since `Array.prototype.find` is not yet implemented in v8 we do not allow it.

I will publish a patch for this.

**Comment by gothraven** [comment]
done here #2477
