### ISSUE TITLE
'react/jsx-pascal-case' always complains when underscore is used

### ISSUE THREAD

**Issue by dviry** [yannickcr/eslint-plugin-react#1472]
Hi, not sure if this is really expected (no samples like this in the Docs), but the following examples throw the 'Imported JSX component Site_globalsite must be in PascalCase' error:

<My_Icon />
<MyIcon_IsHere />

I can understand if it would be <My_icon/>, but it seems no matter what I put after the underscore it complains. Is this the expected ruling?

Thanks in advance

**Comment by ljharb** [comment]
Yes, camelCase does not include any underscores whatsoever.

**Comment by yacinehmito** [comment]
@ljharb I found this issue while searching for another one. I think it can be closed as the behaviour seems sensible.
