### ISSUE TITLE
Template string with special character are getting inappropriately autofix to quoted string

### ISSUE THREAD

**Issue by riwu** [yannickcr/eslint-plugin-react#1479]
```<input placeholder={`line1\nline2`} ></input>``` gets autofix into 
`<input placeholder="line1\nline2" />` which treats the `\n` literally. 

Versions:
    "eslint-config-airbnb": "^16.0.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0"

**Comment by ljharb** [comment]
cc @jackyho112

**Comment by jackyho112** [comment]
@ljharb Thanks for tagging me! I think this bug will be fixed in https://github.com/yannickcr/eslint-plugin-react/pull/1458/files#diff-a9ba802868aa552c39802228bac37c08R174 because with the new update, the rule will identify the backslash and bail out instead of incorrectly fixing the code.
