### ISSUE TITLE
no-typos rule doesn't support `isRequired` when destructuring

### ISSUE THREAD

**Issue by ranneyd** [yannickcr/eslint-plugin-react#1488]
I have the following:

```
const { func } = PropTypes;
Component.propTypes = {
   prop: func.isRequired,
}
```

The plugin is marking `isRequired` as invalid, saying
> Typo in declared proptype: isRequired (react/no-typos)

Perhaps there's some regular expression thing that's checking after the first `.`, aka assuming it begins with `PropTypes`?

**Comment by ljharb** [comment]
Duplicate of #1389.
