### ISSUE TITLE
Additional option or modification to jsx-closing-tag-location

### ISSUE THREAD

**Issue by tomprats** [yannickcr/eslint-plugin-react#1495]
Right now I'm using "line-aligned" and like how it works on self-closing elements. For non-empty elements, I feel differently depending on how long the contents are.

If an element only has a short line of content, I'd still prefer to place the closing tag on the same line as the closing bracket

```
// Lots of extra space
<Say
  firstName="John"
  lastName="Smith"
>
  Hello
</Say>;

// Can be hard to see when props end and content begins
<Say
  firstName="John"
  lastName="Smith" >
  Hello
</Say>;

// My preference for shorter content
<Say
  firstName="John"
  lastName="Smith"
>Hello</Say>;

// My preference for longer content
<Say
  firstName="John"
  lastName="Smith"
>
  Hello
  <Multiple />
  <Children />
</Say>;
```

When I try my same-line syntax with "line-aligned" I get: 
> Closing tag of a multiline JSX expression must be on its own line

**Comment by ljharb** [comment]
So it looks like you like line-aligned for elements with multiple children, but for elements with single children only, you want that inline variant? What about if the single child is particularly long?

**Comment by tomprats** [comment]
For a longer child I would line-align

**Comment by ljharb** [comment]
How would you determine “longer”? Rules dont have access to the config of other rules, like “max-len” for example.

**Comment by tomprats** [comment]
If it's on one line, then I think I'd leave it up to other rules to deter that behavior. So maybe adding an option to allow single-line syntax in combination with the current closing tag options would work?

**Comment by ljharb** [comment]
That might make it not autofixable; since max-len has no autofix, this rule (with your new option)'s autofix might leave the codebase in a state where it'd be impossible to satisfy both rules.

A new option might work; i'm a soft -1 on adding it, however.

**Comment by tomprats** [comment]
Could the autofix just do the current behavior, but it just wouldn't be flagged if it were a one-liner? I appreciate you working this out with me. I might try to build it to get some more experience and understand if it's not something that'll make it in

**Comment by ljharb** [comment]
Yes, that's a possibility; since it's a case that *wouldn't* be flagged, but would have no autofix to make it happen.

**Comment by tomprats** [comment]
After working with this for the past year and a half, I've since changed my mind and think the rule looks good as-is.
