### ISSUE TITLE
Markdown files should have their negative counter examples bold annotated

### ISSUE THREAD

**Issue by felicio** [yannickcr/eslint-plugin-react#1503]
To continue where the conversation on pull request #1467 thread left off, I'd like to propose two interventions to the style of files documenting individual rules.

1. Word negating sentence of a counter code example should be bold to increase overall orientation in text.
2. Newly created files should follow this rule.

I'm willing to make the change in current files. However, I have a couple of questions:

- In bold should only be the adverb (i.e. **not**) or a verb too (e.g. **are not**)?
- Where in a style guide should be made a record of this rule?

**Comment by ljharb** [comment]
Let's start just bolding the adverb, and let's add the instructions to a CONTRIBUTING.md?
