### ISSUE TITLE
Error message: Definition for rule 'react/display-name' was not found

### ISSUE THREAD

**Issue by DanielSundberg** [yannickcr/eslint-plugin-react#152]
I get an error message directly after installing eslint-plugin-react
<pre>
C:\code> npm install --save-dev eslint-plugin-react
eslint-plugin-react@2.7.0 node_modules\eslint-plugin-react
</pre>

<pre>
c:\code> .\node_modules\.bin\eslint -o "eslint.txt" --no-color .\src
c:\code\node_modules\eslint\lib\eslint.js:646
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'react/display-name' was not found.
    at c:\code\node_modules\eslint\lib\eslint.js:646:27
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (c:\code\node_modules\eslint\lib\eslint.js:619:16)
    at processText (c:\code\node_modules\eslint\lib\cli-engine.js:201:27)
    at processFile (c:\code\node_modules\eslint\lib\cli-engine.js:226:12)
    at c:\code\node_modules\eslint\lib\cli-engine.js:322:26
    at c:\code\node_modules\eslint\lib\util\traverse.js:61:17
    at Array.forEach (native)
    at traverse (c:\code\node_modules\eslint\lib\util\traverse.js:41:54)
    at c:\code\node_modules\eslint\lib\util\traverse.js:63:17
c:\code [local/implement-logging]>
</pre>

EsLint version: v0.24.1

My .eslintrc:
<pre>
{
    "parser": "babel-eslint",

    "env": {
        "browser": true,
        "node": true,
        "es6": true,
        "jasmine": true,
        "jquery": true,
    },

    {
        "plugins": [
            "react"
        ]
    },

    "ecmaFeatures": {
        "modules": true,
    },

    "rules": {
        "quotes": [0],
        "comma-dangle": [0],
        "no-underscore-dangle": [0],
        "eol-last": [0],
        "no-unused-vars": [0], 

        "react/display-name": 1,
        "react/jsx-boolean-value": 1,
        "react/jsx-no-undef": 1,
        "react/jsx-quotes": 1,
        "react/jsx-sort-prop-types": 1,
        "react/jsx-sort-props": 1,
        "react/jsx-uses-react": 1,
        "react/jsx-uses-vars": 1,
        "react/no-danger": 1,
        "react/no-did-mount-set-state": 1,
        "react/no-did-update-set-state": 1,
        "react/no-multi-comp": 1,
        "react/no-unknown-property": 1,
        "react/prop-types": 1,
        "react/react-in-jsx-scope": 1,
        "react/require-extension": 1,
        "react/self-closing-comp": 1,
        "react/sort-comp": 1,
        "react/wrap-multilines": 1,
    },

}

</pre>

**Comment by yannickcr** [comment]
Your `.eslintrc` file is incorrect, it should be:

```json
"plugins": [
    "react"
],
```

instead of:

```json
{
    "plugins": [
        "react"
    ]
},
```

**Comment by DanielSundberg** [comment]
Ok that solves the problem, I just copied the section from the readme. 

My excuse will have to be that the format for the "plugins" section was slightly different from the other sections.
