### ISSUE TITLE
react/jsx-curly-spacing config doesn't work

### ISSUE THREAD

**Issue by chrisbutler** [yannickcr/eslint-plugin-react#1528]
none of the options from the guide work: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md

just wasted an hour trying to enforce spacing on children but not props

**Comment by ljharb** [comment]
The features on master haven't been released yet. https://github.com/yannickcr/eslint-plugin-react/blob/v7.4.0/docs/rules/jsx-curly-spacing.md is the latest released docs.

**Comment by jomasti** [comment]
If you're using a version of the plugin earlier than `7.1.0`, you won't have the latest options available for that rule, as well.

**Comment by chrisbutler** [comment]
@ljharb @jomasti i don't think either of you are addressing the issue...

the config examples in `7.4.0` link are identical to the ones in `7.1.0`, but I was using `7.2.0` and they don't work

also, in the latest version, the config examples don't work. only the ones in this section: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md#shorthand-options

but I can't see how to set the options for children

**Comment by jomasti** [comment]
If you're wanting to only enforce the rule without worrying about the props:
`"react/jsx-curly-spacing": ["error", { when: "always", attributes: false, children: true }]`

When I ran the above on my code base with eslint@7.2.0, it only reports issues with the children. By default, it will ignore the children and check the attributes, so this setting is the opposite.

If you want to disallow it for props, then it would be this:
`"react/jsx-curly-spacing": ["error", { when: "always", attributes: { when: "never" }, children: true }]`

But I can see where the rule details documentation can be a bit confusing.

**Comment by chrisbutler** [comment]
@jomasti yeah, the fact that `attributes` (seemingly, from your examples) has to be present isn't documented anywhere

**Comment by jomasti** [comment]
@chrisbutler Yeah, it's not explicit. But the docs do say this: `true enables checking for the spacing using the options (default for attributes)`, so if you want to ignore them, then you need to have it set the value in the config.

**Comment by chrisbutler** [comment]
@jomasti ok well, neither of those example configs is working for me on `eslint@4.11.0` and `eslint-plugin-react@7.5.1`

**Comment by jomasti** [comment]
Odd. They both work for me. Can you provide your eslint config and an example code snippet that you expect to have an error with the rule?

**Comment by chrisbutler** [comment]
@jomasti eslint just fails to run at all, like the configurations are not valid

**Comment by ljharb** [comment]
When you are checking the docs, be sure to set the tag to match the version you have installed. If you’re still seeing an issue, please file a new one.
