### ISSUE TITLE
peerDependency causing install to fail with eslint@1.0.0-rc-1

### ISSUE THREAD

**Issue by feross** [yannickcr/eslint-plugin-react#154]
Eslint just released version `1.0.0-rc-1` which doesn't work with this plugin.

Can we switch the peerDependency to `*`? Right now I'm in dependency hell. :(

**Comment by yannickcr** [comment]
Ok to switch to `*`

**Comment by BerkeleyTrue** [comment]
What about removing peer deps entirely. NPM 3 is coming out and does away with all that non-sense in favor or dedupe's and flat trees.

**Comment by yannickcr** [comment]
Actually I'd prefer to keep it until the final version of npm 3 is released.

**Comment by yannickcr** [comment]
After testing, `*` does not seems to accept pre-release versions since npm 2.

I switched to `>=0.8.0 || ~1.0.0-rc-0`, it should do the trick.

**Comment by feross** [comment]
Thanks!

**Comment by doctyper** [comment]
I'm still seeing this issue when trying to install `eslint@^1.0.0-rc-1` + `eslint-plugin-react@^2.7.1`. Here are my dependencies for reference:

```
  "dependencies": {
    "eslint": "^1.0.0-rc-1",
    "eslint-plugin-react": "^2.7.1"
  },
  "peerDependencies": {
    "eslint-plugin-react": ">=2.x",
    "eslint": ">=0.23.0"
  }
```

And the error:

```
❯ npm install
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.13.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint@1.0.0-rc-1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-react@2.7.1 wants eslint@>=0.8.0 || ~1.0.0-rc-0
```

**Comment by doctyper** [comment]
Please ignore, I immediately saw my problem :). Needed to update my eslint in peerDependencies.
