### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by nwoltman** [yannickcr/eslint-plugin-react#1546]
There is no documentation for the `jsx-one-expression-per-line` rule (#1497).

Also, the readme is missing a link to the documentation for the `button-has-type` rule (#1525).

**Comment by jseminck** [comment]
Thanks for reporting this! I added the link to `button-has-type` rule.

@TSMMark since you wrote the code for the `jsx-one-expression-per-line` rule, would you be willing to add the documentation as well?

**Comment by TSMMark** [comment]
Sure thing. Anything I need to do other than the following?

 - add a file in docs/rules/
 - update readme with a link

**Comment by jseminck** [comment]
That's it 👍

**Comment by TSMMark** [comment]
See #1552
