### ISSUE TITLE
no-unused-prop-types throws when using setState callback

### ISSUE THREAD

**Issue by Hypnosphi** [yannickcr/eslint-plugin-react#1553]
This code make eslint job fail when using `no-unused-prop-types` rule in `7.5.0`:
```
this.setState(prevState => ({
  open: !prevState.open,
}));
```

It throws `TypeError: Cannot read property 'properties' of undefined at markPropTypesAsUsed`

Looks like `!node.params.length` should be replaced with `node.params.length <= 1` here: 
https://github.com/yannickcr/eslint-plugin-react/pull/1507/files#diff-4d3f22e69602f6d3e0d5e1cf8328dc76R969

**Comment by ljharb** [comment]
@Hypnosphi try v7.5.1? This seems like a duplicate of #1542.

**Comment by Hypnosphi** [comment]
Oh sure, thanks
