### ISSUE TITLE
Add marker for rules included in recommended to readme list of rules

### ISSUE THREAD

**Issue by pke** [yannickcr/eslint-plugin-react#1556]
It would be nice if the list of rules in the README.md and the individual rules .md files would contain a marker to quickly indicate rules that are included in the recommended set and/or are fixable.

In the rules .md files this could be done by front matter maybe and in the list of rules in the README maybe by little badges from https://shields.io

That way one would not have to look into the list of recommended rules the bottom to see if a rule one needs is already active in the recommended rules. Makers on the rules themselves would also no longer require a separate maintained list of recommended rules.

**Comment by ljharb** [comment]
Each rule documentation should already indicate whether it’s fixable; if it doesn’t, please file an issue/PR.

Either way, we’d want a separate list of recommended rules - it’s a common use case to want to know what rules you’re enabling; it’s not common to want to list all fixable rules (and there’s eslint-find-rules for that anyways).

I suppose we could indeed add info to each recommended rule indicating that it’s in that config.

**Comment by pke** [comment]
Yes isn't that what I was suggesting, something like this: 

![image](https://user-images.githubusercontent.com/164625/33029850-f47716fc-ce19-11e7-9a26-387645ab40d7.png)

**Comment by ljharb** [comment]
Ahhh so to rephrase, you want the root list to have all that info inline? That sounds like a great idea. My only concern is that it’d be ideal to have a way to make sure this info is always correct - like a test that compares the markdown to the actual rule metadata.

**Comment by pke** [comment]
Yeah a kind of check would be good to keep everything in sync.
Actually for my own project I am thinking about adding the docs to the rule file itself and extract the markdown files with some tool and use the rule metadata to annotate the documentation and create the recommended rules list based on that meta-data and inject it into the readme automatically.

**Comment by ljharb** [comment]
We now have an autogenerated table, CI to enforce it's correct, and the table indicates recommended-ness and fixability.
