### ISSUE TITLE
Component method param destructuring won't work

### ISSUE THREAD

**Issue by ardok** [yannickcr/eslint-plugin-react#1561]
```
class Test extends Component<{}, {selectedId: string}> {
  constructor(props: *) {
    super(props);
    this.state = {
      selectedId: '',
    };
  }

  onChange = ({id}: {id: string}) => { // This will say: 'id' PropType is defined but prop is never used (react/no-unused-prop-types)
    this.setState({
      selectedId: id,
    });
  };

  render() {
    const {selectedId} = this.state;
    return (
      <div>
        {selectedId}
        <select onChange={() => this.onChange({id: '1'})}>
          <option value='1'>1</option>
        </select>
      </div>
    );
  }
}
```

**Comment by julienw** [comment]
I think I get the same issue with this (maybe simpler) code:
```javascript
// @flow
import * as React from 'react';

type Props = {||};

type HoveredStackTiming = {
  depth: number,
};

class StackChartCanvas extends React.PureComponent<Props> {
  _getHoveredStackInfo({ _depth }: HoveredStackTiming) {
    return null;
  }

  render() {
    return null;
  }
}

export default StackChartCanvas;
```

**Comment by julienw** [comment]
Added a test => https://github.com/yannickcr/eslint-plugin-react/compare/master...julienw:1561-issue-with-destructuring

I'm looking I can find how to fix this.

**Comment by julienw** [comment]
I think this is not strict enough: https://github.com/yannickcr/eslint-plugin-react/blob/c7dd755c4607151d058af39ed45f60613ba16ccf/lib/util/annotations.js#L13-L24

This is called from https://github.com/yannickcr/eslint-plugin-react/blob/c7dd755c4607151d058af39ed45f60613ba16ccf/lib/rules/no-unused-prop-types.js#L944-L953.

Now I have a few questions/remarks:
* is it possible that a _method_ could be a functional component ? If not, then we can restrict this method.
* I think we can reasonnably assume that for a functional component using destructured parameters, the same problem will be caught by https://eslint.org/docs/rules/no-unused-vars too. So I believe we could actually safely ignore functions with destructured parameters in this rule. But we'll have similar issues for other rules.
* anyway, the rule doesn't associate the right props to the right component -- I don't know if other similar rules have the same issue, but it's likely.

would @yannickcr or anybody else have any more guidance here ?

**Comment by yannickcr** [comment]
> is it possible that a method could be a functional component ? If not, then we can restrict this method.

afaik no, but a _static_ method can be.

> anyway, the rule doesn't associate the right props to the right component -- I don't know if other similar rules have the same issue, but it's likely.

Yes, it's a common issue when we try to associate props to a component 😞. I will have a look but I never really used Flow so any help is welcome.

**Comment by rogerkerse** [comment]
I have the same issue. Is there any info on it?
