### ISSUE TITLE
npm error - eslint-plugin-react: "^7.1.0"

### ISSUE THREAD

**Issue by shreyashdholakia** [yannickcr/eslint-plugin-react#1564]
Getting this error when trying to install the plugin, was working a day ago but started failing from today. Any help will be appreciated

npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/var/jenkins_home/.nvm/versions/node/v4.2.3/bin/node" "/var/jenkins_home/.nvm/versions/node/v4.2.3/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: prop-types@'>=15.6.0 <16.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.2.0","15.5.0-alpha.0","15.5.0","15.5.1","15.5.2","15.5.3","15.5.4","15.5.5","15.5.6","15.5.7-alpha","15.5.7-alpha.1","15.5.7","15.5.8","15.5.9","15.5.10"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'eslint-plugin-react'
npm ERR! notarget

**Comment by ljharb** [comment]
You're using an unsupported version of node and npm. Upgrade to 4 latest, or better, 6 or 8 or 9; and you'll get a new enough npm.
