### ISSUE TITLE
propTypes wrapped with PropTypes.exact triggers react/prop-types rule

### ISSUE THREAD

**Issue by vkartaviy** [yannickcr/eslint-plugin-react#1575]
As PropTypes.exact was added https://github.com/facebook/prop-types/commit/9057907cae241b78faaa8048d6c04d60b14a4b91 it would be great if plugin support it as well.

**Comment by ljharb** [comment]
You can specify `PropTypes.exact` in `propWrapperFunctions`, but we should handle this by default.

**Comment by dustinsoftware** [comment]
I can take a stab at implementing this one

**Comment by dustinsoftware** [comment]
I'm running into an issue testing this - `PropTypes.exact` does not seem to work as expected when wrapping the proptypes object, like `forbidExtraProps` does. Still investigating, but here's a repro.

https://codepen.io/dustinsoftware/pen/BmGWXM

**Comment by dustinsoftware** [comment]
@ljharb can you take a look at the pen I linked to? I see you've commented on a few related issues in the prop-types repo, it appears that `PropTypes.exact` currently can't be used as a wrapper for the whole props object.

**Comment by ljharb** [comment]
@dustinsoftware Sorry for the delayed response. I think the current implementation in this plugin only allows a single identifier to be used; however, I would expect it to be enhanced to also support `{ property: "exact", object: "PropTypes" }`.
