### ISSUE TITLE
enforce testID in React (Native) components

### ISSUE THREAD

**Issue by matthargett** [yannickcr/eslint-plugin-react#1577]
We're interested in enforcing that every component have a testID prop set when instantiated in a render() function. Would a contribution rule for this be accepted? Are there any obvious showstoppers with this level of enforcement?

**Comment by ljharb** [comment]
I think this is something you should write in your own custom plugin; even in an environment where test IDs are used for integration tests, it would be a horrible idea to force it on every single component :-/

I also can't think of a way (that is both generic and useful) that could be added here.

**Comment by matthargett** [comment]
What if you were able to configure the component/element types you wanted to require the testID on. Then in the eslintconfig one person could mandate that all Button elements required a testID and would error if missing, Text elements would get a warning if they were missing a testID, but others would emit nothing. This would also allow for custom/native components not in the core framework to be covered by a custom policy.

**Comment by ljharb** [comment]
Certainly that makes it less hazardous, but this just doesn't sound to me like it would ever be generic enough to belong in this plugin.

**Comment by noomorph** [comment]
Anyone wrote something like that?

**Comment by frzkn** [comment]
I wrote a pretty basic one here,
https://github.com/frzkn/eslint-plugin-react-native-enforce-testid

<img width="1039" alt="Screenshot 2023-06-21 at 10 15 18 PM" src="https://github.com/jsx-eslint/eslint-plugin-react/assets/14858039/46d4d681-1b5f-4f24-aead-2363a814da78">
