### ISSUE TITLE
In jest, I accidently wrote expect(a == b) instead of expect(a).toBe(b) ... new eslint rule for this?

### ISSUE THREAD

**Issue by mo** [yannickcr/eslint-plugin-react#1585]
In jest, I accidently wrote expect(a == b) instead of expect(a).toBe(b) and all my tests passed even though the code was buggy ... new eslint rule for this?

**Comment by jomasti** [comment]
That isn't specific to React. However, there is [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) with the rule [valid-expect](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/valid-expect.md).

**Comment by mo** [comment]
@jomasti nice.. thanks for the tip!
