### ISSUE TITLE
sort-comp: 'instance-variables' doesn't work properly

### ISSUE THREAD

**Issue by ktaras** [yannickcr/eslint-plugin-react#1587]
Extracted as a separate issue from https://github.com/yannickcr/eslint-plugin-react/issues/599#issuecomment-349658024

It seems like `instance-variables` works only for `state`.
I specified following order:
```
      - static-methods
      - instance-variables
      - lifecycle
      - everything-else
      - render
```
When I declare
```
class CoolComponent extends Component {
  state = {};
  ...
}
```
it's OK, but when I add some custom property, e.g.:
```
class CoolComponent extends Component {
  state = {};
  someList = [];
  ...
}
```
it throws an error:
```
someList should be placed after componentWillUnmount
```

**Comment by silvenon** [comment]
Using latest `master` this no longer seems to be the issue. The only error I'm getting using your code is that `state` should be below `someList`, i.e. it needs to be the last instance variable. That's probably intentional because state is special.

**Comment by ljharb** [comment]
Looks like this is fixed, just awaiting a release of the plugin (ping @yannickcr).

**Comment by denkristoffer** [comment]
@yannickcr Any word on when a new release could be ready? I'd love to get the fix in master into the upcoming Create React App 2.0 release.

**Comment by m10** [comment]
still getting this on 7.6.0

**Comment by ljharb** [comment]
@m10 can you file a new issue for that?
