### ISSUE TITLE
jsx-curly-brace-presence `never` breaks multi-line strings

### ISSUE THREAD

**Issue by kripod** [yannickcr/eslint-plugin-react#1592]
Using eslint-preset-airbnb, the [`jsx-curly-brace-presence` rule](https://github.com/airbnb/javascript/blob/44dbd0bdc41d08eb5de8ad698099ae44240f4b0d/packages/eslint-config-airbnb/rules/react.js#L355) breaks multi-line strings given as props, e.g.:

```jsx
<div css={`
  background: #009688;
  transition: background 0.5s;
`}>
  Hello world!
</div>
```

Gets transformed into

```jsx
<div css="
  background: #009688;
  transition: background 0.5s;
">
  Hello world!
</div>
```

By `eslint --fix`, which is invalid. Multi-line strings given as props shall not be flagged as mistakes.

**Comment by renet** [comment]
+1 from me, this definitely is a bug.
