### ISSUE TITLE
Incorrect error reporting for <wbr> tag

### ISSUE THREAD

**Issue by mrchief** [yannickcr/eslint-plugin-react#1603]
It currently gives out `Expected corresponding JSX closing tag for <wbr>` error for this tag. 

`wbr` tag has no end tag as per the [spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-wbr-element). The rule should not report errors for this.

**Comment by jomasti** [comment]
That error isn't reported by this plugin.

**Comment by mrchief** [comment]
@jomasti Who reports it then? Is it React itself?

**Comment by mrchief** [comment]
Opened up https://github.com/facebook/react/issues/11845.
