### ISSUE TITLE
Hi All，there is a question, I want create a Animation component container, need to use the findDOMNode Api to continuely modify the container's height style, But the plugin claimed me that Line 37: Do not use findDOMNode react/no-find-dom-node, how can I deal with it?

### ISSUE THREAD

**Issue by daffy6537** [yannickcr/eslint-plugin-react#1606]
help me please, the ref can not meet my needs

**Comment by ljharb** [comment]
If the rule conflicts with your use case, override the rule for that use case.

**Comment by daffy6537** [comment]
@ljharb thank you very much !!!

**Comment by daffy6537** [comment]
@ljharb it still warn "Do not use findDOMNode  react/no-find-dom-node" when I had commited that line.

like:
let dom = findDOMNode(this); // eslint-ignore-line react/no-find-dom-node

**Comment by daffy6537** [comment]
now, only /*eslint-disable */ was effective for the whole file;

**Comment by ljharb** [comment]
That's because `eslint-ignore-line` isn't a thing; just `eslint-disable-line` and `eslint-disable-next-line`.
