### ISSUE TITLE
Suggestion: using Prettier

### ISSUE THREAD

**Issue by jaaberg** [yannickcr/eslint-plugin-react#1618]
Hi, 

I've been having fun contributing to this great project lately, thanks for being open to new contributors. But what have bothered me a bit is the code formatting. ESLint rules tend to have _a lot_ of `if/else`-statements, and there are so many ways to break them into new lines. I am used to have prettier running in my other projects, and not thinking about the formatting has been really nice. It may not seem like a big deal, but it would be really nice not needing to reason about if I am following the correct code style. 

Is Prettier something we could consider for this project? For instance running it as a pre-commit hook?

**Comment by ljharb** [comment]
No thanks. If prettier ever becomes compatible with the airbnb config, I'd support using it, but until then, eslint is the only way I think a project should be formatted.

Separately, git hooks are not an enforcement mechanism, and can never be relied on in a repo.
