### ISSUE TITLE
Add rule enforcing `props` are passed to `super` in constructor

### ISSUE THREAD

**Issue by mericsson** [yannickcr/eslint-plugin-react#1620]
Following the advice of the [React Docs react-component#constructor](https://reactjs.org/docs/react-component.html#constructor) it would be great if there was an eslint rule that would convert:

```js
constructor(props) {
  super();
  // ....
}
```

to:
```js
constructor(props) {
  super(props);
  // ....
}
```

So that we would catch cases where someone tries to use `this.props` before it is populated. Thank you!

**Comment by ljharb** [comment]
Looks like a duplicate of #626

**Comment by joetidee** [comment]
Has this rule been added?

**Comment by ljharb** [comment]
@joetidee no, see #626.
