### ISSUE TITLE
[jsx-no-bind] Customize ref callback prop names

### ISSUE THREAD

**Issue by Andarist** [yannickcr/eslint-plugin-react#1638]
When used with `ignoreRefs` it would be great to customize possible prop names. It's a common pattern to allow for custom "ref" callbacks when writing a components libraries, i.e.
- `emotion` uses `innerRef` - https://emotion.sh/docs/styled#pass-refs-down-using-innerref
- `react-textarea-autosize` uses `inputRef` - https://github.com/andreypopp/react-textarea-autosize/blob/a836fa4e00b4f6885b8593bf65450659200f9197/src/index.js#L34

**Comment by delijah** [comment]
+1

**Comment by ljharb** [comment]
The point of the rule is to avoid performance issues and rerenders. The only ref prop that matters is the one React treats specially - it does not treat `innerRef`, `inputRef`, etc special, and so using bind in these places will cause unnecessary rerenders and will defeat most memoization/pure optimizations.
