### ISSUE TITLE
no-deprecated - React.addons.TestUtils doesn't create a warning

### ISSUE THREAD

**Issue by nirnaor** [yannickcr/eslint-plugin-react#1644]
When using `React.addons.TestUtils` a warning should be thrown, since the addons entry point is deprecated as of **15.5.0** (as per the [official documentation](https://reactjs.org/docs/addons.html))

The error that should be thrown is:
**React.addons.TestUtils is deprecated since React 15.5.0, use ReactDOM.TestUtils instead.**

**Comment by ljharb** [comment]
Thanks! We'll want to make sure that only throws when the version pragma is 15.5.0 or greater.

**Comment by nirnaor** [comment]
@ljharb Great. Anything I can do to help with this verification?

**Comment by ljharb** [comment]
Nope, your PR seems solid :-)
