### ISSUE TITLE
jsx-no-literals option to allow html entities

### ISSUE THREAD

**Issue by smsenesac** [yannickcr/eslint-plugin-react#1649]
`<span>&times;</span>`

This is an error currently which is a bit of a pain. You can't wrap it in a JSX container or it will be interpreted literally.

**Comment by ljharb** [comment]
`<span>{‘&times;’}</span>` is identical; does it not function the same for you?

**Comment by smsenesac** [comment]
No, it literally renders '&times;' instead of 'x'.

**Comment by ljharb** [comment]
ah, interesting. So you'd need to use innerHTML to render it, i guess. Is there a reason you can't do `{'x'}`? that seems like it'd be more legible.

**Comment by smsenesac** [comment]
It's a stylistic concern. `&times` renders as two perpendicular bars whereas the bars that makeup the letter `x` are not perpendicular. Also, the look of the letter will vary depending on the page font while the html entity will not. When trying to create a close or cancel button, `&times` is generally preferred. It's what the bootstrap framework recommends.

**Comment by smsenesac** [comment]
I can use innerHTML, though. I use it so rarely that I forgot that it existed. Thanks!

**Comment by ljharb** [comment]
Sorry, i mean, why can’t you use the actual Unicode character for &times; ?
