### ISSUE TITLE
Rule prop-types should include nextProps checking in shouldComponentUpdate

### ISSUE THREAD

**Issue by amerryma** [yannickcr/eslint-plugin-react#1684]
Consider this example:
``` javascript
class Hello extends Component {
  static propTypes = {
    bar: PropTypes.func
  }
  shouldComponentUpdate(nextProps) {
    return nextProps.foo !== null
  }
  render() {
    return <div bar={this.props.bar} />;
  }
}
```

This is a case where we want to check to make sure that `foo` is properly defined in `propTypes`. I think this case should be included in the `prop-type` rule. Any thoughts?

Please refer to my comment here: https://github.com/yannickcr/eslint-plugin-react/issues/1636#issuecomment-364195848

I've made the changes in a forked repo and seems to work just fine. If we wanted to get this in, I'd need some help with the test cases but here is my fork: https://github.com/mindspacepdx/eslint-plugin-react/tree/am-should-component-update

**Comment by ljharb** [comment]
A PR would be great :-)
