### ISSUE TITLE
react/jsx-handler-names: can I have a list of `eventHandlerPrefix` and `eventHandlerPropPrefix`s? 

### ISSUE THREAD

**Issue by garrettmac** [yannickcr/eslint-plugin-react#1687]
questions says it all.
Can I have a list of `eventHandlerPrefix` and `eventHandlerPropPrefix`s?

**Comment by ljharb** [comment]
I’m not sure what you mean - the default values are listed [in the docs](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md#rule-options)

**Comment by EvHaus** [comment]
+1 for this. I think the request is to be able to do something like this:

```
'react/jsx-handler-names': ['warn', {
        eventHandlerPrefix: ['_handle', 'formikProps.handle', 'someOtherThing'],
        eventHandlerPropPrefix: ['on', 'handler', 'somethingElse']
}
```

Whereas at the moment `eventHandlerPrefix` and `eventHandlerPropPrefix` only support strings, not arrays.
