### ISSUE TITLE
react/prop-types doesn't work with fragment syntax

### ISSUE THREAD

**Issue by bebraw** [yannickcr/eslint-plugin-react#1694]
**Example:**

```javascript
import React from "react";

const ForAttendees = ({ page }) => (
  <>
    <section className="intro intro_attendees">{page}</section>
    <div className="grid--5col">barfoo</div>
  </>
);

export default ForAttendees;
```

`react/prop-types` does **not** capture this. If you replace the fragment syntax with divs, it detects the case.

**Comment by ljharb** [comment]
I suspect a lot of rules will need to be updated to support fragment syntax.

**Comment by ljharb** [comment]
Related: #1579, #1661

**Comment by lencioni** [comment]
@bebraw in the meantime, does this work with `<React.Fragment>` instead of `<>`?

**Comment by bebraw** [comment]
@lencioni Yeah, going with that fixes it.

**Comment by ljharb** [comment]
Since babel 7 is required for `<>`, and is not yet released, let’s leave this open until it is, so we will be sure to fix it.

**Comment by graingert** [comment]
FYI, babel 7 got released

**Comment by ljharb** [comment]
See #1956
