### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by xavierartot** [yannickcr/eslint-plugin-react#1696]
Hi,
I have a method in class and an error on the sign = at goToStore line definition
the message is 
`Parsing error: Unexpected token =`
I have no warning or error in React, where did I wrong?
```
export default class Storepicker extends React.Component {
   goToStore = (event) => {
    event.preventDefault();
    console.log('You changed the URL');
    // first grab the test from the box
    // second we're going to transition from / to /store/:storeIt
  }
  render() {
    return (
      <div>
        <form className="store-selector" onSubmit={this.goToStore}>
          {/* sss */}
          <h2>Please Enter A Store</h2>
          <input type="text" required placeholder="Store Name" defaultValue={getFunName()} />
          <button type="submit" className="btn">
            Visit Store <span role="img" aria-label="go">🔥</span>
          </button>
        </form>
      </div>
    );
  }
}
```
I lint the code in Vim 8 with Ale

**Comment by ljharb** [comment]
What’s your eslint config? Class properties aren’t part of JavaScript yet.

**Comment by xavierartot** [comment]
I found the problem, thx

**Comment by baleeds** [comment]
> I found the problem, thx

What was the fix?  I'm having the exact same issue.

**Comment by ljharb** [comment]
It’s a bug with npm and eslint. You have to pin espree at v6, i think.

**Comment by baleeds** [comment]
Could you give more details?

There's no v6 in espree?  https://www.npmjs.com/package/espree

**Comment by ljharb** [comment]
The specific solution is https://github.com/eslint/espree/issues/393#issuecomment-433348355

**Comment by baleeds** [comment]
Hmmmm.  Still no luck.

I'm using create-react-app with react-scripts 2.1.5.

My package json as it relates to dev dependencies now looks like this:
```
"devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/runtime": "7.0.0-beta.55",
    "acorn": "^6.0.2",
    "acorn-jsx": "^5.0.0",
    "cypress": "^3.1.5",
    "eslint-config-airbnb": "16.1.0",
    "espree": "^4.1.0",
    "node-sass-chokidar": "^1.3.3"
  },
```
Here's some folders from my node_modules relating to eslint:
![image](https://user-images.githubusercontent.com/9682964/53833175-ec418e00-3f55-11e9-834c-66c0e5bd6209.png)

My .eslintrc.json is:
```
{
    "extends": [
        "airbnb"
    ],
    "plugins": [
        "react"
    ],
    "rules": {
        "import/prefer-default-export": 0,
        "react/prop-types": 0,
        "react/no-danger": 0,
        "no-param-reassign": 0,
        "no-underscore-dangle": 0,
        "jsx-a11y/anchor-is-valid": [ "error", {
            "components": [ "Link" ],
            "specialLink": [ "to" ]
        }]
    },
    "env": {
        "browser": true,
        "jest": true
    },
    "globals": {
        "cy": false,
        "Cypress": false
    }
}
```

Yarn also gives these warnings:
```
warning " > eslint-config-airbnb@16.1.0" has unmet peer dependency "eslint@^4.9.0".
warning " > eslint-config-airbnb@16.1.0" has unmet peer dependency "eslint-plugin-import@^2.7.0".
warning " > eslint-config-airbnb@16.1.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.0.2".
warning " > eslint-config-airbnb@16.1.0" has unmet peer dependency "eslint-plugin-react@^7.4.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@12.1.0" has unmet peer dependency "eslint@^4.9.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@12.1.0" has unmet peer dependency "eslint-plugin-import@^2.7.0".
```

Eslint was working well for the the past 6 months or so, but I recently spun up an unrelated new project.  I'm not sure how the new project altered the eslint in this project, but it's not working correctly since, not recognizing the babel properties.

I've tried installing using yarn and npm both.  Npm is version 6.8.0.  Yarn is 1.7.0.

**Comment by ljharb** [comment]
I don’t believe the Airbnb eslint config is compatible with CRA without ejecting - the dependency warnings you’re seeing mean that nothing can be expected to work until they’re fixed.

**Comment by baleeds** [comment]
I would say that's a possibility, but it's been working without issues for 6 months.

**Comment by baleeds** [comment]
Okay, I was able to fix it without ejecting.  I'm pretty sure the warnings don't actually prevent this from working, in my case.  

I added the following to my .eslintrc:
```
"parser": "babel-eslint",
"parserOptions": {
     "ecmaVersion": 6,
     "ecmaFeatures": {
         "jsx": true
     }
 },
```

**Comment by ljharb** [comment]
The airbnb config already sets those parserOptions - only the parser change is likely needed.
