### ISSUE TITLE
Add a rule to check the default parameters instead of defaultProps for stateless components ?

### ISSUE THREAD

**Issue by christophehurpeau** [yannickcr/eslint-plugin-react#1705]
Hello,

What do you think about a new rule to check the default parameters instead of defaultProps for stateless components?

An example would be:

```js
import React from 'react';

type Props = {|
  hidden?: boolean,
|};

export default ({ hidden = false }) => (
  <span hidden={hidden}>content</span>
);
```

I could work on a PR

**Comment by ljharb** [comment]
defaultProps are different than function defaults (runtime-inspectable, for one); you’re supposed to use defaultProps - with flow as well.

**Comment by christophehurpeau** [comment]
duplicate of #1184
