### ISSUE TITLE
React v16.2 fragments don't support no-unused-vars rule

### ISSUE THREAD

**Issue by dnalborczyk** [yannickcr/eslint-plugin-react#1706]
using this rule: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md

repro:

```javascript
import React, { Component } from 'react';

export default class Container extends Component {
  render() {
    return <>foo</>;
  }
}
```

```console
1:8  error  'React' is defined but never used  no-unused-vars
```

this works just fine:

```javascript
import React, { Component } from 'react';

export default class Container extends Component {
  render() {
    return <div>foo</div>;
  }
}
```

**Comment by ljharb** [comment]
Closing in favor of #1694.

**Comment by dnalborczyk** [comment]
@ljharb  I think this bug (rule) is unrelated to #1694, though browsing through the code, the fix might be the same.

**Comment by ljharb** [comment]
It's related in that this plugin currently has no support for fragments, and any fix for that will address it for all the rules.

**Comment by dnalborczyk** [comment]
btw, is this something which need to be fixed (or added) in the babel-eslint parser?

**Comment by ljharb** [comment]
Hmm, that part I'm not sure about - I'd assume it's just a new node type that our rules aren't listening for.

**Comment by dnalborczyk** [comment]
ah, yeah, it depends on the parser.  acorn-jsx which is used by eslint as default jsx parser implemented fragments apparently already. https://github.com/RReverser/acorn-jsx/pull/84  https://github.com/eslint/eslint/issues/9662

I might be mistaken, but looking at the lib/rules code, it seems that the affected plugins would need to be fixed independently. not sure though.

**Comment by ljharb** [comment]
Yes, they would - but hopefully in the same PR :-)
