### ISSUE TITLE
Unable to disable the react/no-did-mount-set-state check

### ISSUE THREAD

**Issue by zgrossbart** [yannickcr/eslint-plugin-react#1711]
I have the following code:

```componentDidMount() {
    const elementHeight = isNaN(this.trElement.clientHeight) ? 0 : this.trElement.clientHeight;
    const elementWidth = isNaN(this.trElement.clientWidth) ? 0 : this.trElement.clientWidth;
    const firstItem = this.firstItem || this.parenNameEle;
    const firstItemWidth = isNaN(firstItem.clientWidth) ? 0 : firstItem.clientWidth;
    this.setState({ elementWidth, elementHeight, firstItemWidth });
  }
```

When I run the eslint-plugin-react over this code I get the following error:

```
71:5  error  Do not use setState in componentDidMount  react/no-did-mount-set-state
```

That is working as expected.  If I then add this line right before calling `this.setState` the error goes away:

```
/* eslint-disable react/no-did-mount-set-state */
```

However, I am unable to disable this rule in my `.eslintrc` file.  When I try the following:

```
"rules": {
    "react/no-did-mount-set-state": 0,
```

The error still happens when I run eslint.  I would expect adding this to my .eslintrc file would stop that check.

**Comment by ljharb** [comment]
What's the rest of your .eslintrc file? Do you have any other eslintrc files in your repo?

**Comment by zgrossbart** [comment]
My entire .eslintrc file looks like this:

```
{
  "root": true,
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "script"
  },
  "env": {
    "browser": false,
    "es6": true
  },
  "extends": ["airbnb"],
  "rules": {
    "max-len": [2, 130, 4],
    "no-param-reassign": [2, { "props": false }],
    "no-plusplus": 0,
    "no-underscore-dangle": 0,
    "prefer-rest-params": 0,
    "spaced-comment": 0,
    "comma-dangle": [
      "error",
      {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "always-multiline",
        "exports": "always-multiline",
        "functions": "never"
      }
    ]
  }
}
```

I don't have any other .eslintrc files in my project.  I also know I'm getting the right file because if I change `no-plusplus` check from 0 to 2 then I see errors about it and if I change it back to 0 I don't see the errors anymore.

**Comment by ljharb** [comment]
Certainly, I would expect adding `"react/no-did-mount-set-state": 0,` to the "rules" array in your eslintrc would disable the rule. How are you running eslint?

**Comment by zgrossbart** [comment]
Im running it through gulp.  Just `gulp lint`.

**Comment by ljharb** [comment]
It might be a gulp issue; can you try using `npx eslint` so that it runs a local eslint, directly?

**Comment by ljharb** [comment]
aha! What if you add `"plugins": ["react"]` to your `.eslintrc`?

**Comment by zgrossbart** [comment]
Where is the right place in the `.eslintrc` file to add that?

**Comment by ljharb** [comment]
As a sibling or “rules”

**Comment by ljharb** [comment]
It’s the same as suppressing an error on any eslint rule (with the plugin thing being the only difference). Can you run `npm ls` and confirm it’s exiting zero?

**Comment by zgrossbart** [comment]
Is it possible that this is the wrong name or the wrong format of the name of the URL?

Running `npm ls` just prints out the list of dependencies for my project.  Did you mean a different command?

**Comment by ljharb** [comment]
No, that’s the right command; if you were missing peer deps it would show errors.

This isn’t a url, it’s a rule name - the “react/“ means it’s part of eslint-plugin-react.

In addition to .eslintrc, is there any file with “eslint” in the name anywhere else in your project?

Also, can you try ` 1st”root”: true` to your eslintrc? (You might have an .eslintrc file higher up, like in your home dir)

**Comment by zgrossbart** [comment]
I'm sorry, I meant name in my last comment.  That was just a typo.  I know I'm getting the right file because I can turn off other rules like `no-plusplus` and that works fine.

**Comment by ljharb** [comment]
I’m asking if there could be other eslint config files (theres multiple supported file names) that are affecting the settings.

**Comment by zgrossbart** [comment]
**Groan**.  You were totally right.  I had a bunch of then in my node_modules files so I didn't see that there was one in the src directory.  When I change it there it works.  I feel more than a little silly now.  Thank you very much for all of your help and time.

**Comment by Abolfazl2647** [comment]
i have same issue here is my `.eslintrc.js` 
``
module.exports = {
    root: true,
    env: {
      es6: true,
      browser: true,
      node: true,
    },
    // 'plugin:react/recommended', 'jest-enzyme'
    extends: ['airbnb','prettier','prettier/react','react-app'],
    plugins: ['react','babel', 'import', 'jsx-a11y', 'prettier'],
    parser: 'babel-eslint',
    parserOptions: {
      ecmaVersion: 6,
      sourceType: 'module',
      ecmaFeatures: {
        jsx: true,
      },
    },
    settings: {
      "import/resolver": {
        "node": {
          "paths": ["src"]
        }
      },
    },
    rules: {
      "no-underscore-dangle": 0,
      'prettier/prettier': ['error'],
      "no-restricted-imports": [
        "error",
        {
          "patterns": ["@material-ui/*/*/*", "!@material-ui/core/test-utils/*"]
        }
      ],
      "react/prop-types": 0,
      "no-param-reassign": [2, { "props": false }],
      "react/jsx-no-duplicate-props": [2,{ "ignoreCase": false}],
      "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
      "import/no-extraneous-dependencies": ["error",  {"devDependencies": true}],
      "react/jsx-props-no-spreading": "off",
      'linebreak-style': 'off', // Don't play nicely with Windows.
      'arrow-parens': 'off', // Incompatible with prettier
      'object-curly-newline': 'off', // Incompatible with prettier
      'no-mixed-operators': 'off', // Incompatible with prettier
      'arrow-body-style': 'off', // Not our taste?
      'function-paren-newline': 'off', // Incompatible with prettier
      'no-plusplus': 'off',
      'space-before-function-paren': 0, // Incompatible with prettier
  
      'max-len': ['error', 150, 2, { ignoreUrls: true, }], // airbnb is allowing some edge cases
      'no-console': 'error', // airbnb is using warn
      'no-alert': 'error', // airbnb is using warn
  
      'no-param-reassign': 'off', // Not our taste?
      "radix": "off", // parseInt, parseFloat radix turned off. Not my taste.
  
      'react/require-default-props': 'off', // airbnb use error
      'react/forbid-prop-types': 'off', // airbnb use error
      // 'react/jsx-filename-extension': ['error', { extensions: ['.js'] }], // airbnb is using .jsx
  
      'prefer-destructuring': 'off',
  
      'react/no-find-dom-node': 'off', // I don't know
      'react/no-did-mount-set-state': 'off',
      // "react/no-did-mount-set-state": [1,0],
      'react/no-unused-prop-types': 'off', // Is still buggy
      'react/jsx-one-expression-per-line': 'off',
  
      "jsx-a11y/anchor-is-valid": ["error", { "components": ["Link"], "specialLink": ["to"] }],
      "jsx-a11y/label-has-for": [2, {
          "required": {
              "every": ["id"]
          }
      }], // for nested label htmlFor error
    },
  };
``
