### ISSUE TITLE
Support /* Flow comment syntax */

### ISSUE THREAD

**Issue by theneva** [yannickcr/eslint-plugin-react#1714]
I'm using Storybook with the [Storysource](https://github.com/storybooks/storybook/tree/master/addons/storysource) addon which does not support Flow syntax inside the story files.

Therefore, I want to use the [Flow comment syntax](https://flow.org/en/docs/types/comments/) to still type check the code.

Flow responds correctly to this syntax:

![image](https://user-images.githubusercontent.com/1404650/37151103-85badbbc-22d4-11e8-9a85-10860865cf7b.png)

However, `react/prop-types` is still yelling at me:

![image](https://user-images.githubusercontent.com/1404650/37151215-d6a26f7c-22d4-11e8-8703-29aceb3eb164.png)

For the record, it does work with the "regular" (non-comment) syntax:

![image](https://user-images.githubusercontent.com/1404650/37151302-3afdad60-22d5-11e8-93c1-388f1490a289.png)

It would be great if the comment syntax were supported in this plugin!

**Comment by ljharb** [comment]
I don't think this is something we can do, unless babel's eslint parser is able to pick up the type information.

Please file an issue there.
