### ISSUE TITLE
`forbid-prop-types` catch hacks for `array` and `object` types

### ISSUE THREAD

**Issue by Krustal** [yannickcr/eslint-plugin-react#1719]
I would like `forbid-prop-types` to catch a hack that I've seen used occasionally to get around this rule. If you configure `forbid-prop-types` as follows:
```
"react/forbid-prop-types": ['error', { forbid: ['any', 'array', 'object'] }]
```
I would like the above to catch each of these props as errors:
```
static propTypes = {
  tags: PropTypes.instanceOf(Array),
  config: PropTypes.instanceOf(Object),
}
```
Both of these cases are generally just workarounds for forbidden `array` and `object` types. 

Would this best be suited as part of `forbid-prop-types` or in another rule?

**Comment by ljharb** [comment]
instanceOf should probably be forbidden entirely, since instanceof doesn’t work cross-realm and isn’t robust.

**Comment by Krustal** [comment]
Hmm, I've not heard this. I've used it with native classes such as `Date` without much issue that I can recall. What do you mean by cross-realm I guess?

**Comment by ljharb** [comment]
Cross-realm means, effectively, from an `iframe` or node’s vm module.

**Comment by Krustal** [comment]
Do you have an article or other references I could look at?

**Comment by ljharb** [comment]
http://2ality.com/2014/12/es6-symbols.html section 4 mentions it a bit, for one.
