### ISSUE TITLE
no-typos: Fix failing createClass test

### ISSUE THREAD

**Issue by ljharb** [yannickcr/eslint-plugin-react#1721]
Per #1671 (https://github.com/yannickcr/eslint-plugin-react/pull/1671/files#diff-a36b384ace30edac8eacb00c170eed54R1277) and #1389, there's a commented out no-typos test that should be uncommented and fixed.

**Comment by alexzherdev** [comment]
I have a fix coming up for this, but that depends on #1827 to be merged.
I have one question though. I think the four commented out tests are really just two test cases which run with and without babel-eslint. Is that necessary in the case of `createClass`? I understood [this comment](https://github.com/yannickcr/eslint-plugin-react/pull/1827#issuecomment-397375662) to mean "one test for static properties with babel-eslint and one test for regular `Component.propTypes = ...` without babel-eslint". Do we need to also run non-babel-eslint tests _with_ babel-eslint?
