### ISSUE TITLE
react/require-default-props not support type params of React Component

### ISSUE THREAD

**Issue by Miziak** [yannickcr/eslint-plugin-react#1724]
When we define Component prop types like this:
```
type SelectProps = {
  isOpen?: boolean
}
class Select extends PureComponent<SelectProps, SelectState> {
  static defaultProps = {
    // isOpen: false,
  }
  ...
}
```
We don't get error like this:
> 17:3  error  propType "isOpen" is not required, but has no corresponding defaultProp declaration  react/require-default-props

To get this error we need to define component like this:
```
type SelectProps = {
  isOpen?: boolean
}
class Select extends PureComponent {
  props: SelectProps
  static defaultProps = {
    // isOpen: false,
  }
  ...
}
```

eslint v: `^4.17.0`
eslint-plugin-react v: `^7.6.1`

**Comment by ljharb** [comment]
Fixed by #1733.
