### ISSUE TITLE
jsx-no-bind route render

### ISSUE THREAD

**Issue by mathieug** [yannickcr/eslint-plugin-react#1725]
jsx-no-bind throws an error on the render property in:
```jsx
          <Route
            exact
            path="/dummy-route"
            render={(props) => <DummyComponent {...props} />)}
          />
```
It's the recommended way of react-router: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#render-func

**Comment by ljharb** [comment]
Indeed it is; but it's still a bad idea to create an arrow function inline. Make it a constructor-bound instance method and you'll avoid this error.

**Comment by mathieug** [comment]
I'm not sure for this case, I cannot find any example doing that with a constructor-bound instance method.

Even this post hasn't got any response: https://stackoverflow.com/questions/45042687/react-router-and-jsx-no-bind

**Comment by ljharb** [comment]
`foo(props) { return <DummyComponent {...props} />); }`, `this.foo = this.foo.bind(this)` in the constructor, and `render={this.foo}` on the Route.
