### ISSUE TITLE
exclude styled-jsx

### ISSUE THREAD

**Issue by shyamchen** [yannickcr/eslint-plugin-react#1726]
[`react/jsx-closing-tag-location`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-tag-location.md)

[Feature Request] add ignore tags for `react/jsx-closing-tag-location`

```js
// roughly like this
"react/jsx-closing-tag-location": ["error", { "ignoreTags": ["style"] }],
```

```jsx
export const Foo = () => (
  <div>
    <div className="foo">Foo</div>

    <style jsx>{`
      .foo {
        padding: 1rem;
      }
    `}</style>
  </div>
);
``` 

<img width="1011" alt="screen shot 2018-03-15 at 6 02 24 pm" src="https://user-images.githubusercontent.com/32692097/37456764-1958cf04-287b-11e8-9db0-9cb11bd91f35.png">

Fixed code is not very good looking.

```jsx
export const Foo = () => (
  <div>
    <div className="foo">Foo</div>

    <style jsx>{`
      .foo {
        padding: 1rem;
      }
    `}
    </style>
  </div>
);
```

**Comment by ljharb** [comment]
I would expect this:
```jsx
export const Foo = () => (
  <div>
    <div className="foo">Foo</div>

    <style jsx>
      {`
        .foo {
          padding: 1rem;
        }
      `}
    </style>
  </div>
);
```
