### ISSUE TITLE
Rule react/destructruring-assignement in a constructor

### ISSUE THREAD

**Issue by mathieug** [yannickcr/eslint-plugin-react#1728]
The rule `react/destructruring-assignement` should not throw in a component constructor.

![image](https://user-images.githubusercontent.com/951183/37527559-98f2da86-2932-11e8-8287-a66e386d8f20.png)

**Comment by ljharb** [comment]
I’m confused why you’d mutate the object after assigning it (it’s much slower and messier), but yes, this is a bug - specifically, it shouldn’t warn on LHS member chains off of state or props, only RHS.

**Comment by mathieug** [comment]
I need to condition which attribute I set in the state.

**Comment by leohxj** [comment]
![image](https://user-images.githubusercontent.com/1506900/37577990-b0b0b766-2b70-11e8-8d6b-a20ae100bb0b.png)

same as.

**Comment by ljharb** [comment]
@leohxj in that case, it’s correct. Do `const { name } = this.props;` before the state assignment, and do both in the constructor (iow, don’t do things in class property initializers that depend on props or state)

**Comment by leohxj** [comment]
@ljharb 

ok, but why "don’t do things in class property initializers that depend on props or state" ?
I think [Class properties transform](http://babeljs.io/docs/plugins/transform-class-properties/) can do this.

**Comment by ljharb** [comment]
@leohxj of course it will work; the reason not to do it is because it makes things much less clear when reading the code.
