### ISSUE TITLE
react/jsx-pascal-case throws warning on 2-letter components

### ISSUE THREAD

**Issue by ericblade** [yannickcr/eslint-plugin-react#1730]
I have a component that is two (upper-case) letter named (yes, I know, that's probably bad to begin with, but it's an abbreviated name for something) . . so technically it is Pascal cased, it just consists of two single letter words joined together.  Yes, I am aware I can enable all upper case, or put an ignore on this particular one, I just wanted to bring it to people's attention that it seems to be an oversight in the plugin.

**Comment by ljharb** [comment]
I don't think it's an oversight; there's no way to programmatically deal with single-letter words in a PascalCase/camelCase algorithm. I think the accepted solution is to either not use abbreviations, or to allow "all uppercase".

**Comment by ericblade** [comment]
ah, yes, I suppose I didn't think that through all the way -- i was sort of thinking "an exception for two letter names", but then what would follow from that "what if you abbreviate three words down to three letters?" .. then you add all uppercase, i guess.  Either way, doesn't matter, I just put a disable-line on it.
