### ISSUE TITLE
[jsx-no-bind] Does not support react-navigation options

### ISSUE THREAD

**Issue by windhost** [yannickcr/eslint-plugin-react#1736]
With react-navigation options, it can not pass the rule

![34203510-5e36f18a-e5b6-11e7-85e0-f348ef215618 png](https://user-images.githubusercontent.com/15258893/37759797-a74ee220-2def-11e8-8645-397b81e9487a.jpeg)

**Comment by ljharb** [comment]
Why is `navigationOptions` an arrow function instead of a static method?

**Comment by windhost** [comment]
The example in react-navigation doc is arrow function. If using static method , I do not know wether binding this is necessary.

**Comment by ljharb** [comment]
Sine the method doesn’t use “this” there’s no reason for it to be an arrow function (it’s pretty rare for static things to care about the receiver).

If you convert it to a static method, does your linting issue go away? If so, perhaps you could PR a fix into the react-navigation documentation?
