### ISSUE TITLE
Add JSXExpressionContainer as the href value type for target=_blank

### ISSUE THREAD

**Issue by ksdmitrieva** [yannickcr/eslint-plugin-react#1737]
Right now the jsx-no-target-blank rule only fires if the href is a literal string. What about the cases when the value of the href comes from a JSX expression? For example:

`<a target='_blank' href={this.props.url}></a>`

This might be even more dangerous if the URL property is provided by the user or the third-party. 

Would it make sense to add a function hasDynamicLink() like this one:
`function hasDynamicLink(element) {`
`  return element.attributes.some(attr => attr.name &&`
`      attr.name.name === 'href' &&`
`      attr.value.type === 'JSXExpressionContainer');`
`}`

And then include it in the condition for the rule:

`if (`
`          isTargetBlank(node) &&`
`          (hasExternalLink(node.parent) || hasDynamicLink(node.parent)) &&`
`          !hasSecureRel(node.parent)`
`        )`
I tested it out locally. Will be happy to help with a PR.

**Comment by ljharb** [comment]
This seems reasonable; but what about the false positive case, where the dynamic link is internal?

I'd hate to force people to disable the entire rule in that case.

**Comment by ksdmitrieva** [comment]
That is a fair point. I guess, I'm looking at it from security review point
of view. In this case, I'd rather know that the link is created
dynamically, so I can trace where the dynamic value comes from and if it
may contain untrusted input. But, yes, you're right this will generate some
number of false positives.

**Comment by ljharb** [comment]
This seems like it could be closed by #1784?
