### ISSUE TITLE
`isReactComponent()` returns false for components without `render()`

### ISSUE THREAD

**Issue by oluckyman** [yannickcr/eslint-plugin-react#174]
I have few components which `render()` method encapsulated into mixin. 
Like so:

``` jsx
var Mixin = {
  render() {
    return (
      <h1>{ this.prop.header }</h1><div>{ this._renderBody() }</div>
    );
  }
};

var Comp1 = React.createClass({
  mixins: [ Mixin ],
  _renderBody() {
    return 'comp 1';
  }
});

var Comp2 = React.createClass({
  mixins: [ Mixin ],
  _renderBody() {
    return 'comp 2';
  }
});
```

And because of that some rules are ignored (e.g. `sort-comp` rule).  
So I propose to check when there is no `render()` method inside component if the `mixins` prop is declared or not.

**Comment by yannickcr** [comment]
For ES5 classes we can simplify the detection and just rely on the React.createClass presence, it would solve your problem.

But for ES6 classes it is more difficult since there is no real difference between a standard ES6 class and a React component, that why currently we just search for a class with a render method that return some JSX (or null).

**Comment by jbrumwell** [comment]
Just ran into this same problem, we have a `render` method declared but it doesn't return a `JSXElement` directly so it gets ignored;

something along the lines of;

```
render() {
   const method = this.state.loading ? 'renderLoading' : 'renderList';

   return this[ method ]();
}
```

**Comment by epmatsw** [comment]
So I'm running into this issue in a slightly different variant. I'm actually looking at running `sort-comp` on the output from CJSX, which gives me a render which looks like
```
return React.createClass({
  render: function() {
    return React.createElement("div", null, this.props.test);
  },
  displayName : 'Table'
});
```

Because the render contains compiled JSX rather than actual JSX, it gets skipped.

**Comment by lencioni** [comment]
It might be useful to check out [react-codemod's ReactUtils](https://github.com/reactjs/react-codemod/blob/a88df9212467cf9c2df10c92dd03e91d6944503a/transforms/utils/ReactUtils.js) to see the methods they use for this kind of thing.

**Comment by ljharb** [comment]
I'm going to close this; in general, component detection needs some work, but there's been many updates since this was filed.

New issues with concrete and actionable improvements are welcome!
