### ISSUE TITLE
jsx-no-duplicate-props Default ignoreCase is set to True.

### ISSUE THREAD

**Issue by afoon** [yannickcr/eslint-plugin-react#1746]
I use `eslint-plugin-react version 6.4.1`.

```jsx 
<Component item={value} Item={Value} /> 
```
`item` and `Item` are read as duplicate props. However, ignoreCase was never set as true. According to the [docs](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-duplicate-props.md), ignoreCase is supposed to default to `false`.

**Comment by ljharb** [comment]
That’s really outdated; can you try v7.7.0?

Also please note this is the link to the docs for 6.4.1: https://github.com/yannickcr/eslint-plugin-react/blob/v6.4.1/docs/rules/jsx-no-duplicate-props.md

**Comment by afoon** [comment]
Does ignoreCase have to implicity set to false for the rule to be `false`, or is that the default setting? If it it is the default setting, it is not defaulting to the `ignoreCase: false`

**Comment by johnsenpeder** [comment]
@afoon you might've figured it out by now, but if you want your example not to error, you have to set `ignoreCase` to `true` not `false`
