### ISSUE TITLE
Add version number to rules documentation

### ISSUE THREAD

**Issue by samueljun** [yannickcr/eslint-plugin-react#1747]
It would be extremely helpful to have the version number in the documentation when each rule was added. That way I can know if the rule is supported in the version of the package that I have. That or which version of the package I'm going to need to upgrade to.

**Comment by ljharb** [comment]
Since that’s not determined until often long after the rule was added, that would complicate the release process a lot.

You can look at the documentation for any arbitrary tag on Github; here’s for the latest: https://github.com/yannickcr/eslint-plugin-react/tree/v7.7.0/docs/rules

**Comment by samueljun** [comment]
Ah that works really well thank you!
