### ISSUE TITLE
Rule proposal: allow omitting semicolons in jsx even with 'semi' enabled in eslint

### ISSUE THREAD

**Issue by le0nik** [yannickcr/eslint-plugin-react#175]
For example it's useful with new babel [`do` syntax](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Menu%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Ch2%3EMenu%3C%2Fh2%3E%0A%20%20%20%20%20%20%20%20%7Bdo%20%7B%0A%20%20%20%20%20%20%20%20%20%20if%20(user)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CUserInfo%20user%3D%7Buser%7D%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CLoginForm%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%0A%20%20%7D%0A%7D%0A&playground=false).

Right now `eslint` would highlight lines `8` and `10` if `semi` rule is enabled.

Would be great to have an option of allowing such statements in `jsx`.

**Comment by yannickcr** [comment]
As I responded for a [similar issue](https://github.com/yannickcr/eslint-plugin-react/issues/76#issuecomment-100026164):

> Sadly, as far as I know, a plugin don't have the power to silent an error reported by an ESLint rule, the only way we have to do something approaching is to replicate the ESLint rule, "patch" it to fit our needs and use it instead of the ESLint one. It is not very clean and it can be time consuming to maintain the rule in sync with the ESLint one.

So, currently we can't have such rule :(

**Comment by lencioni** [comment]
I don't think we can accomplish this, so I am closing this issue out.
