### ISSUE TITLE
react/jsx-key is triggering false positive for props defined as an object properties

### ISSUE THREAD

**Issue by awthwathje** [yannickcr/eslint-plugin-react#1753]
Sometimes it is useful to define a component call as 

`<Component {...{ key: id, id, shortTitle }} />`

instead of

`<Component key={id} id={id} shortTitle={shortTitle} />`

but in the first case ESLint gets mad about the missing `key` prop, triggering the `react/jsx-key` rule.

This is the reason why I'm turning this rule off for now. I believe this should be fixed.

**Comment by ljharb** [comment]
This is actually intentional, and in a future version of React `key` I believe won't be possible to spread, it will only be allowed statically provided.

The key should always be hardcoded; it's not a normal prop.

**Comment by awthwathje** [comment]
Then I think it is good idea to explicitly mention this in the documentation.

**Comment by ljharb** [comment]
Sure, a PR to add that to the jsx-key docs would be great!

**Comment by awthwathje** [comment]
Duh... Well, okay. Will do it.

**Comment by jeremywiebe** [comment]
@ljharb Sorry to revive an old Issue.  I was wondering if you could point to some React docs that talk about this:
> in a future version of React key I believe won't be possible to spread, it will only be allowed statically provided.

**Comment by ljharb** [comment]
https://github.com/reactjs/rfcs/pull/107

**Comment by machineghost** [comment]
Can we take a step back here?  We have a *request* for a change to React, which may *never* happen ... and because of that ESLint refuses to even provide the *option* to mark 100% valid code (today) as valid.

How does this make sense?

**Comment by ljharb** [comment]
@machineghost this is an eslint rule, as such, it's opinionated by design. The *entire* purpose of eslint rules is to choose which 100% valid code is marked as invalid - otherwise you'd just rely on syntax errors and not use eslint at all.

The intention of this rule is for `key` to be statically hardcoded inline, not spread in. If you don't like that, disable the rule.

**Comment by machineghost** [comment]
@ljharb ESLint is **FULL** of options to rules.  There are quite literally hundreds of ways to customize various ES Lint rules in existence.

So saying "ES Lint categorically refuses to allow perfectly valid code, and won't even provide an option to customize the rule to allow valid code" makes no sense.  YES, ES Lint *is* opinionated ... but it has historically never been so opinionated as to refuse an option for (again) _perfectly valid_ code

**Comment by ljharb** [comment]
You're certainly right that there's lots of options; but eslint core has in fact often refused to add options for otherwise valid code, as have various plugin maintainers. You're more than welcome to create your own plugin, compose any existing rule, and modify (or add to) the reports it generates (see `eslint-rule-composer`).

I can certainly see the rule being modified, without an option, to allow an *inline* spread static key (the OP's case), and I'd be happy to review a PR that did that.

**Comment by machineghost** [comment]
From "ES Lint doesn't want your garbage code" to "happy to review a PR" in only one comment ;)  Thank you!

**Comment by machineghost** [comment]
P.S. Why "without an option"?  Couldn't there be users who want the current behavior?  An option seems safer ...

**Comment by ljharb** [comment]
That's a fair point; the option would be needed when React makes spreading `key` invalid, might as well add it now.

**Comment by machineghost** [comment]
> That's a fair point; the option would be needed when React makes spreading `key` invalid, might as well add it now.

**IF** React makes spreading `key` invalid.  Again, nothing has happened on that for two years: if you hold your breath waiting you will pass out ;)

Never worked on an ES Lint rule before but I'll see if I can pick it up and submit a PR.

**Comment by ljharb** [comment]
React 17 hasn't come out after more than 2 years of work - so far they ship almost all their plans eventually, even if on a scale of years.

**Comment by machineghost** [comment]
Not sure if there's a better place to ask this, but when I clone the repo, `npm i`, and then `npm test`, I get:

> ✖ 210 problems (68 errors, 142 warnings)
>   68 errors and 0 warnings potentially fixable with the `--fix` option.

That includes a number of errors in the rule I was about to add to:

> eslint-plugin-react/tests/lib/rules/jsx-key.js
>    21:14   error  Unexpected trailing comma            comma-dangle
>    22:4    error  Unexpected trailing comma            comma-dangle
>    28:21   error  Unexpected trailing comma            comma-dangle
>    29:4    error  Unexpected trailing comma            comma-dangle
>    36:36   error  There should be no space after '{'   object-curly-spacing
>    36:50   error  There should be no space before '}'  object-curly-spacing
>    39:6    error  There should be no space after '{'   object-curly-spacing
>    39:19   error  There should be no space before '}'  object-curly-spacing
>    40:6    error  There should be no space after '{'   object-curly-spacing
>    40:44   error  There should be no space before '}'  object-curly-spacing
>    41:6    error  There should be no space after '{'   object-curly-spacing
>    41:23   error  There should be no space before '}'  object-curly-spacing
>    42:6    error  There should be no space after '{'   object-curly-spacing
>    42:50   error  There should be no space before '}'  object-curly-spacing
>    43:6    error  There should be no space after '{'   object-curly-spacing
>    43:69   error  There should be no space before '}'  object-curly-spacing
>    44:6    error  There should be no space after '{'   object-curly-spacing
>    44:51   error  There should be no space before '}'  object-curly-spacing
>    45:6    error  There should be no space after '{'   object-curly-spacing
>    45:62   error  There should be no space before '}'  object-curly-spacing
>    46:6    error  There should be no space after '{'   object-curly-spacing
>    46:43   error  There should be no space before '}'  object-curly-spacing
>    47:6    error  There should be no space after '{'   object-curly-spacing
>    47:39   error  There should be no space before '}'  object-curly-spacing
>    48:6    error  There should be no space after '{'   object-curly-spacing
>    48:54   error  There should be no space before '}'  object-curly-spacing
>    49:6    error  There should be no space after '{'   object-curly-spacing
>    49:34   error  There should be no space before '}'  object-curly-spacing
>    50:6    error  There should be no space after '{'   object-curly-spacing
>    50:62   error  There should be no space before '}'  object-curly-spacing
>    51:6    error  There should be no space after '{'   object-curly-spacing
>    51:51   error  There should be no space before '}'  object-curly-spacing
>    51:53   error  Unexpected trailing comma            comma-dangle
>    56:17   error  There should be no space after '{'   object-curly-spacing
>    56:68   error  There should be no space before '}'  object-curly-spacing
>    56:71   error  Unexpected trailing comma            comma-dangle
>    60:17   error  There should be no space after '{'   object-curly-spacing
>    60:68   error  There should be no space before '}'  object-curly-spacing
>    60:71   error  Unexpected trailing comma            comma-dangle
>    64:17   error  There should be no space after '{'   object-curly-spacing
>    64:68   error  There should be no space before '}'  object-curly-spacing
>    64:71   error  Unexpected trailing comma            comma-dangle
>    68:17   error  There should be no space after '{'   object-curly-spacing
>    68:71   error  There should be no space before '}'  object-curly-spacing
>    68:74   error  Unexpected trailing comma            comma-dangle
>    72:17   error  There should be no space after '{'   object-curly-spacing
>    72:71   error  There should be no space before '}'  object-curly-spacing
>    72:74   error  Unexpected trailing comma            comma-dangle
>    76:17   error  There should be no space after '{'   object-curly-spacing
>    76:71   error  There should be no space before '}'  object-curly-spacing
>    76:74   error  Unexpected trailing comma            comma-dangle
>    81:17   error  There should be no space after '{'   object-curly-spacing
>    81:71   error  There should be no space before '}'  object-curly-spacing
>    81:74   error  Unexpected trailing comma            comma-dangle
>    86:17   error  There should be no space after '{'   object-curly-spacing
>    86:71   error  There should be no space before '}'  object-curly-spacing
>    86:74   error  Unexpected trailing comma            comma-dangle
>    91:18   error  There should be no space after '{'   object-curly-spacing
>    91:47   error  There should be no space before '}'  object-curly-spacing
>    96:138  error  Unexpected trailing comma            comma-dangle
>    97:10   error  Unexpected trailing comma            comma-dangle
>    98:8    error  Unexpected trailing comma            comma-dangle
>   103:18   error  There should be no space after '{'   object-curly-spacing
>   103:47   error  There should be no space before '}'  object-curly-spacing
>   108:135  error  Unexpected trailing comma            comma-dangle
>   109:10   error  Unexpected trailing comma            comma-dangle
>   110:8    error  Unexpected trailing comma            comma-dangle
>   112:4    error  Unexpected trailing comma            comma-dangle
> 

Is this normal, or have I missed an important setup step or something?
