### ISSUE TITLE
react-in-jsx-scope does not understand fragments

### ISSUE THREAD

**Issue by dantman** [yannickcr/eslint-plugin-react#1758]
If you use `<></>` fragment syntax the `react-in-jsx-scope` rule will not declare React as in scope and the no-unused-vars will fail on the React import.

However React is required for fragment syntax as well as normal element syntax.

```js
import React from 'react';

export default () => <>fragment</>;
```

**Comment by dantman** [comment]
The fix for this appears to be extremely simple. `react-in-jsx-scope.js` just needs to apply itself to `JSXOpeningFragment` in addition to `JSXOpeningElement`.

**Comment by ljharb** [comment]
@dantman that sounds great! However, we'll also want to make sure this change only applies after whichever React version added fragment support.
