### ISSUE TITLE
Inline if incompatible with jsx curly spacing.

### ISSUE THREAD

**Issue by fpoirier1** [yannickcr/eslint-plugin-react#1763]
With this rule :
`"react/jsx-curly-spacing": ["error", "never", {"allowMultiline": true}]`

This will fail with error :
`<div className={ this.state.renderInfo ? "infoPanel col-xs-12" : "unToggled col-xs-12" } >`
```
sourceCode.getCommentsAfter is not a function
TypeError: sourceCode.getCommentsAfter is not a function at Object.fix (/node_modules/eslint-plugin-react/lib/rules/jsx-curly-spacing.js:231:42)
```

This will pass : 
`<div className={this.state.renderInfo ? "infoPanel col-xs-12" : "unToggled col-xs-12"} >`

**Comment by ljharb** [comment]
This was fixed in #1565 and #1414. I'll add your test case to master to be sure.

**Comment by alexhalf** [comment]
Has the same error with version 7.7.0

**Comment by alexhalf** [comment]
```
<XXXXX
  atr={ a && b(c) }
>
...
</XXXX>
```

**Comment by ljharb** [comment]
@alexhalf could you file a new issue for that?

**Comment by alexhalf** [comment]
```
const Fail = () => {
	const a = true;
	return <div attr={ a} />;
};

const Success = () => {
	const a = true;
	return <div attr={a} />;
};
```

**Comment by ljharb** [comment]
@alexhalf a new issue, meaning, not this closed one :-)
