### ISSUE TITLE
release for React 16.3.0 deprecation changes

### ISSUE THREAD

**Issue by obartra** [yannickcr/eslint-plugin-react#1768]
I was wondering if we could trigger a release to start using the new React 16.3.0 deprecation changes.

Thanks!

**Comment by ljharb** [comment]
There's a few more react 16 things I'd want to try to include first.

**Comment by sergei-startsev** [comment]
@obartra I suppose we could close the issue since the requested changes were releases in [v7.8.0](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.8.0).

**Comment by obartra** [comment]
sure thing!
