### ISSUE TITLE
Allow `react/forbid-dom-props` to accept an `allow` option?

### ISSUE THREAD

**Issue by kellyjosephprice** [yannickcr/eslint-plugin-react#1769]
We're using `react/forbid-dom-props` to scan for potentially dangerous attributes, ie `src`, to remind developers that it should be properly escaped if needed. It seems like a whitelist approach would be easier to maintain in the longterm. That is, in the event that new DOM attributes are added, it would, by default, catch any potentially dangerous attributes.

Does that make sense? Would a PR for that be considered?

**Comment by ljharb** [comment]
Are dangerous attributes added, typically? Web standards seem to be pretty intent on avoiding new footguns like that.

**Comment by kellyjosephprice** [comment]
Yea, I have no idea. But, I just assume it's better to be paranoid?

**Comment by ljharb** [comment]
Somewhat, but if that paranoia means people will get tons of lint errors until you update the config to allow the new attr, they might just turn off the rule - which would be worse than adding one to "forbidden" later.

**Comment by ljharb** [comment]
I don't think this is a real risk.
