### ISSUE TITLE
Can you keep a CHANGELOG?

### ISSUE THREAD

**Issue by yaycmyk** [yannickcr/eslint-plugin-react#177]
It would be helpful... it's difficult to backtrack through n commits to try and identify anything that might be a breaking change.

Thanks for your efforts!

**Comment by yaycmyk** [comment]
Nevermind, I see it's just named something different. Sorry!

**Comment by yannickcr** [comment]
You can also see the changelog on the [releases page](https://github.com/yannickcr/eslint-plugin-react/releases).

But you're [not the first](https://twitter.com/MoOx/status/582418236739829760) to miss the History.md file. I'm considering renaming it for more visibility.
