### ISSUE TITLE
react/jsx-one-expression-per-line

### ISSUE THREAD

**Issue by tjbenton** [yannickcr/eslint-plugin-react#1775]
There's a bug with the `--fix` part of this rule when you have plain text inside of the jsx element.

**Original code**:
```js
const something = () => (
  <Text>Plain text</Text>
)
```

**Result of `eslint --fix`**:
```js
const something = () => (
  <Text>
Plain text
  </Text>
)
```

**Expected result**:
```js
const something = () => (
  <Text>
    Plain text
  </Text>
)
```

**Comment by ljharb** [comment]
Indentation should be handled by the `indent` and `react/jsx-indent` rules; it's typical and common for autofixers to need to work in tandem.

**Comment by temowemo** [comment]
It looks like neither `indent` nor `react/jsx-indent` can perform the proper indentation in this case unless you wrap "Plain Text" in brackets and quotes like so:

**ESLint Rules:**

```
"react/jsx-one-expression-per-line": "error",
"react/jsx-indent": ["error", 2]
```

**Original code:**

```
const something = () => (
  <Text>{"Plain text"}</Text>
)
```

**Result of `eslint --fix`:**

```
const something = () => (
  <Text>
    {"Plain text"}
  </Text>
)
```

So while the `react/jsx-one-expression-per-line` rule should definitely not be expected to perform indentation, maybe `react/jsx-indent` should handle this indentation problem?

**Comment by ljharb** [comment]
Yes, that seems reasonable. We could perhaps add an option to jsx-indent that covered plain text?

**Comment by peter-mouland** [comment]
Would it be easy to add an option to turn off this rule for plain text content?

**Comment by ljharb** [comment]
I don’t know if it would be easy, but i think the rule definitely needs two options - one for plain text content, and another for elements with only one child.

**Comment by ljharb** [comment]
The only fix, besides someone submitting a PR here, is disabling the rule for the time being.

**Comment by hskyaw-2015** [comment]
this really bugging me, how to disable this rule??

**Comment by alexzherdev** [comment]
@ljharb I noticed this is the last (?) item blocking eslint 5 support in airbnb/javascript. I can take a break from my prop-types work and try to handle this. My understanding is that two options are necessary:
- `allowPlainTextOnly` that would leave `<Text>Plain text and nothing else</Text>` as is;
- `allowSingleChild` that would leave `<Text><OnlyOneChildHere></Text>` as is.
Is that right? Also, would `allowSingleChild` only apply for a single JSX element inside, or plain text as well, i.e. is the second option a superset of the first one?

**Comment by ljharb** [comment]
That sounds right, and that'd be great - I think that yes, `allowSingleChild` would be a superset of `allowPlainTextOnly`, so maybe better would be `allow` that can take `text` or `single-child`, where "text" covers "any non-element children"?

**Comment by alexzherdev** [comment]
`allow` sounds good.
The following would also qualify as non-element children, which I don't think an option called `text` is expected to touch though?
```jsx
<Text>{foo && <Bar />}</Text>
```
A JSXExpressionContainer could contain a lot of different content. I was assuming a single JSXExpressionContainer to qualify for `single-child` rather than `text`.

**Comment by ljharb** [comment]
ok fair, maybe just "text or numbers" for the `text` option?

**Comment by alexzherdev** [comment]
I think a single `Literal` or `JSXText` as a child should fit.

**Comment by ljharb** [comment]
in that case, let's call the options `single-child` vs `literal` vs `none` (the default)?

**Comment by alexzherdev** [comment]
Hmm let's say we `allow: 'literal'`. What about the following case:
```jsx
<Text>foo
</Text>
```
Should that still warn? Same for `single-child` with a non-literal child.

**Comment by ljharb** [comment]
Yes, I think that the option should only take effect if the single child is on the same line as opening and closing tags.
