### ISSUE TITLE
React 16 lifecycle errors appearing in a React 15 project

### ISSUE THREAD

**Issue by shockey** [yannickcr/eslint-plugin-react#1789]
I'm getting `react/no-deprecated componentWillReceiveProps` errors in a React 15 project 😢 

- Build log: https://travis-ci.org/swagger-api/swagger-ui/builds/378016142#L506
- [`react@15.6.2`](https://github.com/swagger-api/swagger-ui/blob/master/package.json#L63), [`eslint-plugin-react@^7.1.0`](https://github.com/swagger-api/swagger-ui/blob/master/package.json#L118)

**Comment by ljharb** [comment]
https://github.com/swagger-api/swagger-ui/blob/d256ae87d310b40fb9fd5cc52ec2aa7db55b28ca/.eslintrc Doesn’t specify a react version pragma, so as far as eslint is concerned, it’s a React 16.3 project.

If you specify your react version, you’ll get appropriate error messages.

**Comment by shockey** [comment]
Thanks @ljharb, I wasn't aware of the pragma setting!

From my perspective, having my linter (and therefore, my build) break due to a changing default in this plugin was not a fun thing to discover. I do see that the plugin documents its changing default React target version (`React version, default to the latest React stable release`). 

Perhaps a warning if a pragma is not present would provide a better experience than finding out the hard way when something like this happens?

**Comment by ljharb** [comment]
Adding a warning for that sounds like a great idea.

**Comment by maaydin** [comment]
We have faced same error messages with react 16.2. Adding react version to .eslintrc file fixed the problem.
 
```
{
...
  "settings": {
    "react": {
      "version": "16.2.0"
    },
  }
...
}
```

**Comment by alasdairhurst** [comment]
Adding the react version is good to know, however like @shockey said, this isn't great behaviour. Ideally, any rules that are modified to break where they didn't before should be breaking changes rather than something that gets picked - usually automatically with a minor bump

**Comment by ljharb** [comment]
@alasdairhurst there's always cases, however, where that constitutes a bugfix - ie, the bug was "it wasn't warning" and now it is.
