### ISSUE TITLE
jsx-no-literals outside of JSX code.

### ISSUE THREAD

**Issue by CalebMorris** [yannickcr/eslint-plugin-react#179]
The most recent rule I submitted `jsx-no-literals` I created to work solely inside of JSX code, but created it with the wrong literal node (using the JS parser node rather than a JSX specific one I thought it was using).
This is causing lots of non JSX code as being reporting as unwrapped strings.

I'll work on a fix as soon as I get a chance and I'm sorry for submitted something without testing it in an actual project first (not just sections of isolated JSX code).

**Comment by yannickcr** [comment]
>  I'm sorry for submitted something without testing it in an actual project first

Well, I have not tested either so, let's just call it a tie :)

I'll release a patch version as soon as I have the fix.

**Comment by yannickcr** [comment]
Fixed in #183
