### ISSUE TITLE
[prefer-stateless-function] ignores static propTypes and defaultProps

### ISSUE THREAD

**Issue by DCRichards** [yannickcr/eslint-plugin-react#1801]
Similar to the issue in #1521, I am experiencing this with both `defaultProps` and `propTypes`.

### Versions

eslint-plugin-react: 7.8.2
react-native: 0.55.3

### Example

```
export default class MyClass extends React.Component {
  static defaultProps = {
    style: null,
  }

  static propTypes = {
    style: ViewPropTypes.style,
  }

  render() { // stuff }
}
```

The following results in:

> Component should be written as a pure function.

**Comment by ljharb** [comment]
Indeed, as it should - you should do this instead:
```js
function MyClass() {
  // stuff
}
MyClass.defaultProps = {
  style: null,
};
MyClass.propTypes = {
  style: ViewPropTypes.style,
};
export default MyClass;
```

**Comment by offero** [comment]
Why is that preferred?

**Comment by ljharb** [comment]
@offero because if it doesn't need to be a `class`, it shouldn't be - functional components are always preferred because they have no inherent mutable state.
