### ISSUE TITLE
Extraneous `npm-check` dependency in published package

### ISSUE THREAD

**Issue by daltones** [yannickcr/eslint-plugin-react#1804]
I've just updated `eslint-plugin-react` from v7.8.2 to v7.9.0 and noticed a large change in my project's dependency tree.

That's because `"npm-check": "5.7.1"` appears as a dependency in the published package (although it isn't there in [tag v7.9.0](https://github.com/yannickcr/eslint-plugin-react/blob/v7.9.0/package.json#L26)).

I certainly assume it shouldn't be there, right?

**Comment by ljharb** [comment]
https://unpkg.com/eslint-plugin-react@7.9.0/package.json indeed it does.

@yannickcr did you perhaps `npm install npm-check` without `--no-save` or `--save-dev` before publishing?

**Comment by ljharb** [comment]
I've published a v7.9.1, with updated deps, and the correct package.json.

**Comment by yannickcr** [comment]
Oh, my mistake. I should have better checked the package.jon before publishing.

Thanks for the quick fix @ljharb.

**Comment by ljharb** [comment]
You may want to use `npx npm-check` rather than installing it in the future :-)
