### ISSUE TITLE
jsx-sort-default-props: unreachable path?

### ISSUE THREAD

**Issue by hornta** [yannickcr/eslint-plugin-react#1817]
Can someone explain for me why it is neccessary to check for CallExpressions in here:
https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-sort-default-props.js#L133

I want to help and contribute to this project having full coverage.

**Comment by ljharb** [comment]
cc @b0gok

**Comment by b0gok** [comment]
@hornta you're right, it's not necessary in case of default props. I think it's an artifact from here (where it's necessary of course):
https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/sort-prop-types.js#L156

So you can safely remove this case from `jsx-sort-default-props`.
👍 for attentiveness.
PR is welcome.
