### ISSUE TITLE
componentWillReceiveProps deprecation notice is triggered for React 16.2 😮

### ISSUE THREAD

**Issue by pronebird** [yannickcr/eslint-plugin-react#1833]
Hi,

I use React 16.2 and pretty happy with `componentWillReceiveProps`, however after updating to the most recent `eslint-plugin-react`, I now start seeing deprecation warnings for React 16.3. This makes no sense.

**Comment by ljharb** [comment]
What is your version pragma set to? If you don’t have one, it defaults to the latest.

**Comment by pronebird** [comment]
Alright I actually didn't know there is such option. I had impression that eslint parses it from the package.json.

Thanks @ljharb
