### ISSUE TITLE
jsx-curly-brace-presence with a single empty string child

### ISSUE THREAD

**Issue by TheSavior** [yannickcr/eslint-plugin-react#1837]
The jsx-curly-brace-presence rule wants to convert this:

```
<MyComponent>{''}</MyComponent>;
```

to

```
<MyComponent></MyComponent>;
```

but they are semantically different. In the first example, MyComponent is passed a child of an empty string, whereas in the second example MyComponent is passed a child of `null`. 

I'd expect jsx-curly-brace-presence to leave empty string single children alone.

cc @yungsters

**Comment by ljharb** [comment]
can you elaborate on what MyComponent is doing that would legitimately distinguish between these?
