### ISSUE TITLE
react/no-unused-prop-types Not working for destructed argument props in getDerivedStateFromProps

### ISSUE THREAD

**Issue by hornta** [yannickcr/eslint-plugin-react#1853]
```javascript
class MyComp {
  static propTypes = {
    myProp: PropTypes.any
  };

  static getDerivedStateFromProps({ myProp }) {
    return { 
      myStateProp: myProp.something 
    };
  }
}
```
The following code gives me: 
`[eslint] 'myProp' PropType is defined but prop is never used`
Tested with v7.9.1

**Comment by alexzherdev** [comment]
Wasn't able to reproduce this on 7.9.1 or latest master 🤔

**Comment by ljharb** [comment]
@hornta ah, have you specified your react version in your settings? gDSFP only applies in react 16.3+
