### ISSUE TITLE
Allow custom component parent classes

### ISSUE THREAD

**Issue by haggholm** [yannickcr/eslint-plugin-react#1856]
We have a shallow hierarchy of components, so very few things actually extend `React.Component` or `React.PureComponent` directly, which renders rules like `react/display-name` kind of useless. It would be very useful for us to be able to configure the detection of classes. Maybe something like `settings.pragma` could allow for a list or regex of parent classes? E.g. `Component.isES6Component` could look up a custom regex in addition to the default `^(${pragma}\\.)?(Pure)?Component$`.

(This looks pretty easy to me, though I’m not super familiar with the shared config; but if this would be welcome, I’d be happy to create a PR.)

**Comment by ljharb** [comment]
Having a hierarchy of React components is a very very big antipattern that's extremely discouraged by the React team, as well as the entire React community - you should prefer composition over inheritance.

There's a JSDoc comment that you can use to indicate to this plugin that your `class` is intending to be a React component, see https://github.com/yannickcr/eslint-plugin-react/issues/1220#issuecomment-303617161

(see #986, #1048, #827, #1220, etc)

**Comment by haggholm** [comment]
Ah, shoot. I’m doing all I can to move functionality to HOCs and decorators, but the legacy code…ah well, *c’est la vie*.

**Comment by ljharb** [comment]
The JSDoc comment will allow you to lint your legacy code while you gradually fix it :-)
