### ISSUE TITLE
Airbnb eslint with prettier-atom not indenting plain text children of JSX tags

### ISSUE THREAD

**Issue by MiLeung** [yannickcr/eslint-plugin-react#1859]
![](https://media.giphy.com/media/sRFym677YWtJxDkEPd/giphy.gif)

in my package.json:

```
  "devDependencies": {
    "babel-jest": "23.2.0",
    "babel-preset-react-native": "4.0.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "17.0.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.9.1",
    "jest": "23.2.0",
    "react-test-renderer": "16.3.1"
  }
```

**Comment by ljharb** [comment]
Can you provide output from the command line, to ensure it's not an issue with Atom?

**Comment by MiLeung** [comment]
./node_modules/.bin/eslint src/ yields:

  4:16  error  Component should be written as a pure function  react/prefer-stateless-function
  7:7   error  JSX not allowed in files with extension '.js'   react/jsx-filename-extension

I added some more stuff into my .eslintrc

{
  "extends": [
    "airbnb",
    "react"
  ],
  "plugins": [
    "babel"
  ],
  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
    "babel/new-cap": 1,
    "babel/no-invalid-this": 1,
    "babel/object-curly-spacing": "always",
    "babel/semi": 1,
    "babel/no-unused-expressions": 1
  }
}

and this problem goes away.

**Comment by MiLeung** [comment]
No

**Comment by ljharb** [comment]
Sounds like it's a bug with Atom then. I'll close, but happy to reopen if needed.

**Comment by adalbertoteixeira** [comment]
Hi. I'm getting this error using `--fix` as well, unfortunately.

It happens when `react/jsx-one-expression-per-line` is set to "error".

**Comment by ljharb** [comment]
@adalbertoteixeira with what code do you see what error on the command line?

This might be better filed on eslint-plugin-react.

**Comment by adalbertoteixeira** [comment]
I was seeing the wrong indentation when running `eslint --fix`, not just when using Atom

But you're totally right, this should be better suited as an issue in eslint-plugin-react.

**Comment by ljharb** [comment]
oh lol my bad, i got confused.

I’ll reopen.

**Comment by alexzherdev** [comment]
Isn't this the same as #1775 ?

**Comment by ljharb** [comment]
Looks like it, thanks.
