### ISSUE TITLE
Recompose's onlyUpdateForKeys and react/require-optimization.

### ISSUE THREAD

**Issue by johnunclesam** [yannickcr/eslint-plugin-react#1870]
I was wondering if this rule still make sense if I use recompose's `onlyUpdateForKeys` (https://github.com/acdlite/recompose/blob/master/docs/API.md#onlyupdateforkeys):

> Prevents the component from updating unless a prop corresponding to one of the given keys has updated. Uses shallowEqual() to test for changes.
> 
> This is a much better optimization than the popular approach of using PureRenderMixin, shouldPureComponentUpdate(), or Recompose's own pure() helper, because those tools compare every prop, whereas onlyUpdateForKeys() only cares about the props that you specify.

The rule is this (https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-optimization.md):
`Component is not optimized. Please add a shouldComponentUpdate method. (react/require-optimization)`

**Comment by ljharb** [comment]
I personally don't think `require-optimization` is a rule that should ever be enabled; too often, checking if the component should update is slower than actually rerendering.

So yes, I think it's fine to turn it off.

**Comment by johnunclesam** [comment]
I agree with you. But I'm a newbie.

**Comment by johnunclesam** [comment]
Are you going to deactivate by default the rule?

**Comment by ljharb** [comment]
I’m not sure what you mean - where is it activated by default?

**Comment by ljharb** [comment]
The rule is disabled by default. It won't be removed, no, because there are some folks that want it (for reasons I can't understand).

**Comment by johnunclesam** [comment]
> for reasons I can't understand

We can understand, RFC this?

**Comment by ljharb** [comment]
The rule won’t be removed - there’s no need to RFC anything.

**Comment by johnunclesam** [comment]
I'm using `plugin:react/all` in my `.eslintrc`. This is the reason. :D
