### ISSUE TITLE
Upgrade eslint to 1.1.0 in peerDependencies?

### ISSUE THREAD

**Issue by fantasy8-me** [yannickcr/eslint-plugin-react#188]
As eslint 1.1.0 just released.
http://eslint.org/blog/2015/08/eslint-1.1.0-released/

**Comment by tleunen** [comment]
Eslint is not an explicit dependency anymore since 3.2.2. (You still need to have it installed though).

Not sure if the best thing was to fully remove it, convert it in simple dependency, or keep it in peerDependency with a less strict version

**Comment by fantasy8-me** [comment]
As `eslint-plugin-react` itself is a plugin of eslint, and changes in eslint did have chance to break it's plugin, I think keep it in peerDependency still make sense.

Depends on the chance that changes in eslint might break `eslint-plugin-react`, use a less strict version might be a good idea. At least it gives the flexibility to user of choosing a proper `eslint` version.

For my case, eslint 1.1.0 fix a bug that border me much, so raised this issue

**Comment by yannickcr** [comment]
Like @tleunen said, eslint is no longer a peerDependency since 3.2.2 (see https://github.com/yannickcr/eslint-plugin-react/issues/178#issuecomment-129227227).
