### ISSUE TITLE
react/no-deprecated rule not working

### ISSUE THREAD

**Issue by givik** [yannickcr/eslint-plugin-react#1882]
My eslint config:

`
{
   "env": {
      "browser": true,
      "es6": true
   },
   "extends": [
      "eslint:recommended",
      "plugin:react/recommended"
   ],
   "parserOptions": {
      "ecmaFeatures": {
         "jsx": true
      },
      "ecmaVersion": 2018,
      "sourceType": "module"
   },
   "parser": "babel-eslint",
   "plugins": [
      "react"
   ],
   "rules": {
      "linebreak-style": [
         "error",
         "unix"
      ],
      "no-console": "warn"
   }
}
`

**Comment by givik** [comment]
eslint: v5.0.1
eslint-plugin-react: 7.10.0

**Comment by ljharb** [comment]
You don’t seem to be setting a React version number in settings - in what way is the rule not working for you? If you’re asking about React 16 deprecations, you’d have to be using v16.3+.

**Comment by givik** [comment]
I am using react: v16.3.0.

**Comment by ljharb** [comment]
The eslint plugin can’t know which version you’re using unless you explicitly tell it in your eslint config. See https://github.com/yannickcr/eslint-plugin-react#configuration

**Comment by givik** [comment]
Now my config is looking like, but this not working too:

{
  "env": {
    "browser": true,
    "es6": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "rules": {
    "linebreak-style": [
      "error",
      "unix"
    ],
    "no-console": "warn"
  },
  "settings": {
    "react": {
      "createClass": "createReactClass",
      "pragma": "React",
      "version": "16.3.0",
      "flowVersion": "0.53"
    },
    "propWrapperFunctions": [
      "forbidExtraProps"
    ]
  }
}

**Comment by ljharb** [comment]
ahhh - so no those methods aren't warned by this plugin yet, mainly because there's not yet a complete replacement for all of their use cases.

They'll continue to work in React 17, so there's no hurry to move away from them.

**Comment by givik** [comment]
Someone is getting error for because of this #1833 ? What about #1864 ? Can i use it?

**Comment by ljharb** [comment]
React itself might be giving these warnings, but I don't think we've enabled them here yet.

**Comment by givik** [comment]
In this case why it is mentioned in README (recommended settings)?

<img width="710" alt="screen shot 2018-07-09 at 2 06 09 am" src="https://user-images.githubusercontent.com/2458760/42424438-59f54b58-831d-11e8-9bbc-c022199b2874.png">

**Comment by ljharb** [comment]
There are many deprecated things beyond those three new lifecycle methods.

**Comment by givik** [comment]
What about this ?
<img width="969" alt="screen shot 2018-07-09 at 3 06 55 am" src="https://user-images.githubusercontent.com/2458760/42424910-e5bd4d04-8325-11e8-8b85-6c8cf6f128a9.png">

**Comment by ljharb** [comment]
ha, ok, then in that case it should be warning. What if you set your version to 16.4?

**Comment by givik** [comment]
Now I am using react 16.4.1 and still the same. It does show me warning.

**Comment by ljharb** [comment]
I mean, changing the eslint config. The version of React you’re actually using is irrelevant; the plugin only knows about what’s in your settings.

**Comment by givik** [comment]
Sure.

```json
"settings": {
    "react": {
      "createClass": "createReactClass",
      "pragma": "React",
      "version": "16.4.1",
      "flowVersion": "0.53"
    },
    "propWrapperFunctions": [
      "forbidExtraProps"
    ]
  }
```

**Comment by givik** [comment]
same result here.

**Comment by ljharb** [comment]
Can you share the entire component code that’s not warning, but should be?

**Comment by givik** [comment]
Here it is:

```javascript
import React, { Component } from 'react';
import { Segment, Form, Button } from 'semantic-ui-react';

const emptyEvent = {
  title: '',
  date: '',
  city: '',
  venue: '',
  hostedBy: ''
};

class EventForm extends Component {
  constructor(props) {
    super(props);
    this.state = {
      event: emptyEvent
    };
  }

  componentDidMount() {
    if (this.props.selectedEvent !== null) {
      this.setState({
        event: this.props.selectedEvent
      });
    }
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.selectedEvent !== this.props.selectedEvent) {
      this.setState({
        event: nextProps.selectedEvent || emptyEvent
      });
    }
  }

  onFormSubmit = evt => {
    evt.preventDefault();
    if (this.state.event.id) {
      this.props.updateEvent(this.state.event);
    } else {
      this.props.createEvent(this.state.event);
    }
  };

  onInputChange = evt => {
    const newEvent = { ...this.state.event };
    newEvent[evt.target.name] = evt.target.value;
    this.setState({
      event: newEvent
    });
  };

  render() {
    const { handleCancel } = this.props;
    const { event } = this.state;
    return (
      <Segment>
        <Form onSubmit={this.onFormSubmit}>
          <Form.Field>
            <label>Event Title</label>
            <input
              name="title"
              onChange={this.onInputChange}
              value={event.title}
              placeholder="Event Title"
            />
          </Form.Field>
          <Form.Field>
            <label>Event Date</label>
            <input
              name="date"
              onChange={this.onInputChange}
              value={event.date}
              type="date"
              placeholder="Event Date"
            />
          </Form.Field>
          <Form.Field>
            <label>City</label>
            <input
              name="city"
              onChange={this.onInputChange}
              value={event.city}
              placeholder="City event is taking place"
            />
          </Form.Field>
          <Form.Field>
            <label>Venue</label>
            <input
              name="venue"
              onChange={this.onInputChange}
              value={event.venue}
              placeholder="Enter the Venue of the event"
            />
          </Form.Field>
          <Form.Field>
            <label>Hosted By</label>
            <input
              name="hostedBy"
              onChange={this.onInputChange}
              value={event.hostedBy}
              placeholder="Enter the name of person hosting"
            />
          </Form.Field>
          <Button positive type="submit">
            Submit
          </Button>
          <Button onClick={handleCancel} type="button">
            Cancel
          </Button>
        </Form>
      </Segment>
    );
  }
}

export default EventForm;

```

**Comment by ljharb** [comment]
What happens if you extend React.Component, instead of the destructured Component?

**Comment by givik** [comment]
@ljharb Nothing changed. Still the same.

**Comment by ljharb** [comment]
This is very confusing, given the tests: https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/no-deprecated.js

**Comment by givik** [comment]
Thanks. I managed to solve this problem. Now it works. I think my (old) global eslint was conflicting with local.

**Comment by ljharb** [comment]
Definitely you want to uninstall any global eslint stuff; almost everything should only be installed locally. Glad you figured it out!
