### ISSUE TITLE
jsx-one-expression-per-line with CRLF on Windows

### ISSUE THREAD

**Issue by luissmg** [yannickcr/eslint-plugin-react#1893]
The rule always triggers, even when I have an expression per line, as the rule expects.

![imagem](https://user-images.githubusercontent.com/20660551/43066452-99d88c72-8e5c-11e8-86a3-4e15c502d4da.png)

Then I realized that I am on Windows and the line break is done with a `\r\n`(CRLF). What I did was to change it to what Linux and OSX do and make the line breack as `\n` (LF). The plugin then works as expected.

Is it supposed to work only with that type of line break?

**Comment by ljharb** [comment]
I wouldn't expect anyone on any platform, including Windows, to use anything but normal LF, since CRLF breaks so many things.

**Comment by luissmg** [comment]
Well, Git expects you, by default (at least on Windows), to use CRLF. If you don't do it, it automatically changes it. Yes, I know you can change that and add a configuration. But why? VSCode does the same. He uses the Windows CRLF. Unless you want to change that in all your files in your project, I think the rule should detect this.

**Comment by ljharb** [comment]
Yes, you should be changing that in all files in all projects, and also using git config to ensure that you convert everything to LF on clone/commit/etc.

(I also think the rule should detect it, however)

**Comment by luissmg** [comment]
Yes, I am not defending that what I am doing is the right or wrong thing to do. Just saying that are other possibilities.
Will add tests ASAP and merge them.

**Comment by Istoman** [comment]
I have the same problem on Windows yet my EOL is set to LF.

**Comment by dominic-p** [comment]
> Yes, you should be changing that in all files in all projects

I'm running into this myself, so I thought I would chime in. The default and recommended setting when installing Git on Windows is `core.autocrlf = true` which coverts line endings to CRLF on Windows and commits them as LF.

Unless I'm missing something, in that configuration, you are indeed expected to have CRLF in your files when editing on Windows.

![autocrlf](https://user-images.githubusercontent.com/1195080/59391357-e6afcd00-8d28-11e9-9e70-de0d3bedcdac.png)

**Comment by ljharb** [comment]
@dominic-p the option you want to select is the second one, imo.

**Comment by dominic-p** [comment]
@ljharb, that's understandable. I'm just pointing out that since it's the default and the Git recommendation, we're not talking about an edge case here. It might be worth supporting.

Thanks, btw, for all the work you do on this config. It's super helpful.

**Comment by ljharb** [comment]
A PR that handles line endings regardless of LF or CLRF throughout the plugin would be appreciated.

**Comment by dominic-p** [comment]
I can take a stab at it, but I've never worked with eslint code before. Any pointers on where to start?

**Comment by ljharb** [comment]
I'd start by writing the test cases :-)

**Comment by ljharb** [comment]
@luissmg is there any chance this is fixed in the latest version of the plugin?

**Comment by ljharb** [comment]
Closing, but will be happy to reopen if there's still something actionable.
