### ISSUE TITLE
Check the type of proptypes

### ISSUE THREAD

**Issue by FeralFox** [yannickcr/eslint-plugin-react#1899]
Hello,
I have a problem: The type of the propTypes is not checked. Am I doing something wrong?

Here is an example:
```jsz
// Class with proptypes
class Test extends Component {
}

Test.propTypes = {
    abc: PropTypes.number
};

class Test2 extends Component {
    render() {
        return (<Test **abc='xyz'**/>);
    }
}
```
I would expect that abc='xyz' is marked as error. However, it isn't. Is this the wanted behaviour?

Thank you in advance

**Comment by ljharb** [comment]
propTypes aren't, and can't be, checked by a linter - only at runtime via React itself.

This is something your tests need to check for.

**Comment by FeralFox** [comment]
Okay, thank you for the quick anwer!
