### ISSUE TITLE
`PropType is defined but prop is never used` - when prop is used via a decorator.

### ISSUE THREAD

**Issue by nextriot** [yannickcr/eslint-plugin-react#1912]
Hi. I'm using Flow, ESLint (with this plugin), Redux & [React Pure Lifecycle](https://github.com/planttheidea/react-pure-lifecycle) (to connect lifecycle methods to functional components).

Here's an example of the code 

    type Props = {|
      +propA: boolean
      +propB: () => Dispatch, // [eslint] 'propB' PropType is defined but prop is never used (react/no-unused-prop-types)
    |}

    const ComponentA = ({ propA }: Props) => (
      <ComponentB myProp={propA}>
          {...}
      </ComponentB>
    )

    const methods = {
      componentDidMount({ propB }: Props) {
        startSocket()
      },
    }

    const decoratedSplash = lifecycle(methods)(ComponentA)

So `propB` is being used via the lifecycle decorator, but the plugin isn't picking up its usage.
I understand this is a fringe case, but I was hoping someone had a workaround that would pacify the error without simply ignoring it.

Thanks in advance.

**Comment by ljharb** [comment]
In that case, the type is incorrect. propB doesn’t belong in the types for the inner piece - the decorator should be adding the propType itself.
