### ISSUE TITLE
destructuring-assignment of state when state is accessed in setState callback

### ISSUE THREAD

**Issue by henkvhest** [yannickcr/eslint-plugin-react#1916]
I was reworking my codebase to incorporate the destructuring of state when I ran into the following issue with the setState callback:

```
state={isAuthenticated: false}

setAuthenticated = value => {
    const { isAuthenticated } = this.state;
    this.setState({ isAuthenticated: value }, () => {
      localStorage.setItem("isAuthenticated", JSON.stringify(isAuthenticated));
    });
};

handleAuthentication = () => {
setAuthenticated(true);
};
```

Before destructuring, the localstorage item would be set to true. In this case however, false is set in localstorage instead of true. 

Now this example isn't the best maybe, since I could just pass the value param in the callback itself or perhaps do the destructuring in the callback itself. But there might be instances where one would like to access the updated state in the callback and perhaps also access state outside of setState aswell. Any ideas on how to handle that in that case?

**Comment by ljharb** [comment]
I think what you want is this:
```js
this.setState({ isAuthenticated: value }, ({ isAuthenticated }) => {
  localStorage.setItem("isAuthenticated", JSON.stringify(isAuthenticated));
});
```
(you also don't want to ever put functions in class fields, but that's unrelated to this issue)

**Comment by henkvhest** [comment]
Thanks, that is exactly what I was looking for!
