### ISSUE TITLE
Wrong indentation suggested

### ISSUE THREAD

**Issue by BreakTruth** [yannickcr/eslint-plugin-react#1917]
![grafik](https://user-images.githubusercontent.com/13135287/43771746-690670b0-9a40-11e8-9c50-cb642afc3541.png)
In multiple files, it says that the indentation is incorrect, even tho it isn't.

**Comment by ljharb** [comment]
Please provide a gist or actual copied code; screenshots aren’t really useful. Also, can you get the same output on the command line?

**Comment by BreakTruth** [comment]
https://gist.github.com/BreakTruth/4ba1b9b8fa2d72f4e5c6fe9a45cb4239
And no, the CLI doesn't give the error. Then I presume it has to do with the linter-eslint package for atom

**Comment by ljharb** [comment]
If it's only happening in atom, then it's definitely an issue with that package.

I don't personally use atom, so i can't help :-/
