### ISSUE TITLE
Create "eslint-plugin-react:recommended" for use with eslint's new "extends" property.

### ISSUE THREAD

**Issue by jimbolla** [yannickcr/eslint-plugin-react#192]
A recently added feature of eslint is [extends](http://eslint.org/docs/user-guide/configuring.html#extending-configuration-files). It would be useful if eslint-plugin-react created their own preset so that one could do this:

    {
        "extends": [ "eslint:recommended", "eslint-plugin-react:recommended" ],
    }

This would eliminate the need to add all the react rules explicitly.

**Comment by bbirand** [comment]
:+1:

**Comment by yannickcr** [comment]
Good idea :+1:

**Comment by jimbolla** [comment]
Digging through the eslint source code, I found [this line](https://github.com/eslint/eslint/blob/02c6c848d7d70c285269c54718dbc9c12d3f0720/lib/config.js#L151) where it seems to resolve that alias. It looks like right now, that functionality is hardcoded to that one name, with no obvious way of adding your own aliases. I'm guessing in v1, use of this feature would look something like:

    {
        "extends": [ "eslint:recommended", "node_modules/eslint-plugin-react/conf/recommended.json" ],
    }

And then conf/recommended.json would be something like:

    {
        "ecmaFeatures": {
            "jsx": true,
        },
        "rules": {
            "react/display-name": 1,
            "react/jsx-boolean-value": 1,
            "react/jsx-curly-spacing": 1,
            "react/jsx-max-props-per-line": 1,
            "react/jsx-indent-props": 1,
            "react/jsx-no-duplicate-props": 1,
            "react/jsx-no-undef": 1,
            "react/jsx-quotes": 1,
            "react/jsx-sort-prop-types": 1,
            "react/jsx-sort-props": 1,
            "react/jsx-uses-react": 1,
            "react/jsx-uses-vars": 1,
            "react/no-danger": 1,
            "react/no-did-mount-set-state": 1,
            "react/no-did-update-set-state": 1,
            "react/no-multi-comp": 1,
            "react/no-unknown-property": 1,
            "react/prop-types": 1,
            "react/react-in-jsx-scope": 1,
            "react/require-extension": 1,
            "react/self-closing-comp": 1,
            "react/sort-comp": 1,
            "react/wrap-multilines": 1
        }
    }

... or whatever is decided to be the "recommended" rules to use.
