### ISSUE TITLE
Trouble with react/jsx-one-expression-per-line

### ISSUE THREAD

**Issue by mdotasia** [yannickcr/eslint-plugin-react#1921]
I'm using `eslint-config-airbnb` followed by `eslint-config-prettier`. My `.eslintrc`:

```json
{
  "extends": ["airbnb", "prettier"]
}
```

I'm using v2.9.0 of `eslint-config-prettier` and the [`react/jsx-one-expression-per-line` is off](https://github.com/prettier/eslint-config-prettier/blob/v2.9.0/react.js#L13). Yet I get a ton of `react/jsx-one-expression-per-line` errors and not sure where they are coming from. I have to add `rules` to my `.eslintrc` and turn it off there.

**Comment by ljharb** [comment]
Are you sure that's the only eslintrc you're using, and are you sure you're using everything locally installed?

**Comment by mdotasia** [comment]
My bad. Config needs to be:

```
{
  "extends": ["airbnb", "prettier", "prettier/react"]
}
```
Then all is fine.

**Comment by ajschmidt8** [comment]
> My bad. Config needs to be:
> 
> ```
> {
>   "extends": ["airbnb", "prettier", "prettier/react"]
> }
> ```
> Then all is fine.

@454de6e, can you post your source for where you found that configuration? i'm having a similar issue but i don't see `prettier/react` listed in Prettier's docs or anywhere else on the web. I've followed the instructions on this page https://prettier.io/docs/en/eslint.html and my ESLint config looks like this:

```js
{
"extends": [ "airbnb", "plugin:prettier/recommended" ]
}
```

but I'm still having the `jsx-one-expression-per-line` error
