### ISSUE TITLE
Misleading comment in prop types detection code

### ISSUE THREAD

**Issue by alexzherdev** [yannickcr/eslint-plugin-react#1938]
Found this while working on the detection refactoring. This is some code extracted verbatim from the `prop-types` rule (it was originally added 3 years ago in https://github.com/yannickcr/eslint-plugin-react/commit/ddd1f66455269b38534f2d75d91a01ecd4b6d4c0)

https://github.com/yannickcr/eslint-plugin-react/blob/fb745abf5909f8f2409e232cb7e82a78e948a350/lib/util/propTypes.js#L450-L470

Despite what the comment says, the `propTypes` variable doesn't refer to the LHS in  `ClassX.propTypes.a.b.c = ...`, it refers to the RHS. So instead of triggering on cases like described in the comment, it triggers on cases like
```js
Comp2.propTypes = {
  prop2: PropTypes.arrayOf(Comp1.propTypes.prop1)
};
```
(`propTypes` would be equal to `Comp1.propTypes.prop1`)

Not sure how that assignment case has worked until now, but current code is confusing and I think is worth looking into.

**Comment by ljharb** [comment]
Let’s add test cases for that, if they’re missing, because that also seems like a case we want to handle.

**Comment by alexzherdev** [comment]
Yeah, it looks like it's covered, e.g.
https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/prop-types.js#L2159
https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/no-unused-prop-types.js#L244
But it goes through a different code path than the one that has the comment.

**Comment by ljharb** [comment]
I think what this is discussing is `A.propTypes.b.c = `, but I'm not really sure why anybody would do that, since nested objects in propTypes aren't supported.

I suspect this code can be removed.

**Comment by ljharb** [comment]
Nope, removing it fails some tests. Closing.
