### ISSUE TITLE
Fatal error when using a callback for setting state

### ISSUE THREAD

**Issue by kuroisuna** [yannickcr/eslint-plugin-react#1944]
When trying to set the state using a callback, I get a fatal error:
```js
this.setState(({ items }) => ({
  items: sortBy([...items, resolvedItem], 'order')
}));
// Error while running ESLint: Cannot read property 'properties' of undefined.
```

If I use objects to feed the state, then everything works without issues:
```js
this.setState({
  items: sortBy([...this.state.items, resolvedItem], 'order')
});
```
It seems like the cause is that I'm extending the component from a global helper:
```js
export default class WellnessScore extends WidgetComponent {
  ...
```
If I change that to `extends Component`, ESLint runs again. 🤔

------
This is my *.eslintrc.json* with `"eslint": "^4.5.0",`:
```json
{
  "extends": "airbnb",
  "env": {
    "browser": true
  },
  "rules": {
    "react/jsx-no-undef": ["error", { "allowGlobals": true }]
  },
}
```

Thanks a lot for this awesome project 🤩This seem like a problem with our code, but I appreciate any clue you guys can give us 🙏

**Comment by ljharb** [comment]
I'm confused; is `WellnessScore` a React component?

**Comment by ljharb** [comment]
so, setting aside that using inheritance in components is considered an antipattern, the react eslint plugin can't possibly know that WidgetComponent is a react component. You'd have to annotate each component with a jsdoc comment to indicate that it extends React.Component for detection to work properly.

However, the crash on "not a component" is a real bug that needs fixing.

**Comment by jzabala** [comment]
Not sure if I am testing this properly but I don't see errors with versions:

```
"eslint": "^7.4.0",
"eslint-plugin-react": "^7.20.3"
```

![Screen Shot 2020-07-11 at 10 09 09 AM](https://user-images.githubusercontent.com/1315054/87225855-f5b6e380-c35d-11ea-94ac-e27d2560ea9d.png)
