### ISSUE TITLE
The eslint-config-airbnb rule value has less length than allowed.

### ISSUE THREAD

**Issue by houys9** [yannickcr/eslint-plugin-react#1948]
/Users/gov/docroot/themes/usda/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:402
            throw e;
            ^
Error: /Users/gov/docroot/themes/usda/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/boolean-prop-naming" is invalid:
	Value "" has less length than allowed.

Referenced from: eslint-config-airbnb

**Comment by ljharb** [comment]
What does `npm ls` print out? If it exits nonzero, your dep graph is invalid.

**Comment by houys9** [comment]
AOCDCWA22000005:usda$ npm ls
usda-theme@1.0.0 /Users/gov/docroot/themes/usda
├─┬ autoprefixer@9.1.2
....
── UNMET PEER DEPENDENCY eslint@^4.19.1 || ^5.3.0
├─┬ eslint-config-airbnb@17.1.0
│ ├── UNMET PEER DEPENDENCY eslint@^4.19.1 || ^5.3.0
....
npm ERR! peer dep missing: eslint@^4.19.1 || ^5.3.0, required by eslint-config-airbnb@17.1.0
npm ERR! peer dep missing: eslint@^4.19.1 || ^5.3.0, required by eslint-config-airbnb-base@13.1.0
npm ERR! peer dep missing: eslint@2.x - 5.x, required by eslint-plugin-import@2.14.0
npm ERR! peer dep missing: eslint@^3 || ^4 || ^5, required by eslint-plugin-jsx-a11y@6.1.1
npm ERR! peer dep missing: eslint@^3.0.0 || ^4.0.0 || ^5.0.0, required by eslint-plugin-react@7.11.1
npm ERR! peer dep missing: eslint@^4.19.1 || ^5.3.0, required by eslint-config-airbnb-base@13.1.0

Seems I need to install all of missing parts.

**Comment by ljharb** [comment]
The Airbnb config has an empty string as the message, but disables the rule:  https://github.com/airbnb/javascript/blob/685f37be39fd01bcfdd349de9acdcd5a50414520/packages/eslint-config-airbnb/rules/react.js#L405

If you are enabling it, you’ll have to configure the message yourself.
