### ISSUE TITLE
Unment peer dependency when using eslint installed by another module listed in package.json.

### ISSUE THREAD

**Issue by hegelstad** [yannickcr/eslint-plugin-react#1951]
Getting error `UNMET PEER DEPENDENCY eslint@^2.0.0 || ^3.0.0`.

I am installing ESLint through `grunt-eslint` package which installs ESLint locally in the project. This error should not appear, ESLint is available as a peer dependency.

**Comment by ljharb** [comment]
This error means that something in your package graph (not this plugin) requires eslint 2 or 3, and you have, presumably, 4 or 5.

I'd strongly suggest not using grunt-eslint, but either way, peer dep issues are something you have to resolve within your own project.
