### ISSUE TITLE
ViewPropTypes can't be used with react/no-typos

### ISSUE THREAD

**Issue by vadimshvetsov** [yannickcr/eslint-plugin-react#1954]
At this moment the way we can define `View` style propTypes is with helper `ViewPropTypes` which can be imported from 'react-native' package.

But eslint consider a typo here because of rule react/no-types:
```js
AnyComponent = ({ style }) => (
  <View style={style}>
    <Text>Hi!</Text>
  </View>
);

AnyComponent.propTypes = {
  style: ViewPropTypes.style, // eslint-disable-line react/no-typos
};
```

Can be reproduced with extending .eslintrc with `qlean-react-native` config.
```sh
npm install -D eslint-config-qlean-react-native \
eslint-config-airbnb@16.1.0 \
eslint@4.9.0 \
babel-eslint@8.0.1 \
eslint-plugin-import@2.8.0 \
eslint-plugin-jsx-a11y@6.0.2 \
eslint-plugin-react@7.4.0 \
eslint-plugin-react-native@3.2.0 \
eslint-plugin-no-loops@0.3.0
```

**Comment by ljharb** [comment]
Is `ViewPropTypes` imported from somewhere?

**Comment by vadimshvetsov** [comment]
@ljharb Yep, it's imported from 'react-native' like:
```js
import { ViewPropTypes } from 'react-native';
```

**Comment by alexzherdev** [comment]
This works well in the latest version, @vadimshvetsov would you be able to update?

**Comment by vadimshvetsov** [comment]
Yes, it's working in v7.11.1, thanks @alexzherdev
