### ISSUE TITLE
[react/destructuring-assignment] Add ability to only trigger in a FunctionBody

### ISSUE THREAD

**Issue by AlicanC** [yannickcr/eslint-plugin-react#1968]
I have just completed refactoring our ~100 component project with "react/destructuring-assignment" set to ` ['error', 'always', { ignoreClassFields: true }]`. This was already an in-house rule, but we couldn't enforce it since there was no ESLint rule so thanks for the implementation 👍

I have noticed that enforcing this rule for ArrowFunctions with just an AssignmentExpression and no FunctionBody results in uglier code:
```javascript
class MyComponent extends Component {
  // What we had (good)
  renderSomething = () => <div>{this.props.something}</div>;

  // What it become (ugly)
  renderSomething = () => {
    const { something } = this.props;
    return <div>{something}</div>;
  };

  // What we had (good)
  onSomethingHappen = () => this.props.dispatch(someAction());

  // What it become (ugly)
  onSomethingHappen = () => {
    const { dispatch } = this.props;
    dispatch(someAction()); // Lack of return is intentional
  };
}
```

We already have `ignoreClassFields` enabled and TBH I can't really think of any place other than a FunctionBody that I want this rule to trigger in.

Could we also have a setting like `onlyFunctionBody` or maybe a `locations` setting defaulted to `"all"` which we can set to `["FunctionBody"]`?

**Comment by ljharb** [comment]
Personally i find the "after" examples much better and less ugly, but clearly that's subjective.

One issue is that if your `something` is a function, and you call it inline, you'd accidentally pass `this.props` as the `this` value - always destructuring all props, regardless of quantity or location, is what's safe.

(Separately, I'd encourage you to avoid renderFoo methods and prefer SFCs)

The only thing I can think of that makes sense would be an `ignore` array that takes AST selectors - but that's a lot of complexity and power to enable users to allow a sneaky footgun.

**Comment by AlicanC** [comment]
Shouldn't we have something like `react/no-call-props` to disable `this.props.func()` then?

**Comment by ljharb** [comment]
I think the `destructuring-assignment` rule is already the one to ensure that you don't do `this.props.func()` - iow, "always destructure every prop" remains the best practice.
