### ISSUE TITLE
example for named rule in conjunction to forbid-foreign-prop-types

### ISSUE THREAD

**Issue by Fandekasp** [yannickcr/eslint-plugin-react#1970]
Can we have a settings example added to https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-foreign-prop-types.md ?
It is not evident how the named rule should be added in order to match with the forbid-foreign-prop-types rule.

Thanks in advance

**Comment by ljharb** [comment]
It means to enable this rule: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/named.md which has its own documentation.

**Comment by Fandekasp** [comment]
Guess I should have been more explicit. I do not understand the relation between the 2 rules and why adding 
```
settings:
  import/ignore:
    - node_modules
```
would do anything to help with forbid-foreign-prop-types.

Are you meaning that some dependencies might use proptypes in a way that removing them would break the library, and since we have no control over node_modules, it's simpler to just ignore them ?

**Comment by ljharb** [comment]
Yes, it means enabling import/named (setting it to 1 or 2).

As for “settings”, all rules can use those.

Explicitly exported propTypes are not safe to remove, because that’s an indication that it’s safe to rely on their presence in production.
