### ISSUE TITLE
using destructuring with props disabling eslint props validation

### ISSUE THREAD

**Issue by jalal246** [yannickcr/eslint-plugin-react#1971]
It sounds that eslint cannot detect props and do validation as long there's js destructuring. However, removing three dots operation will trigger eslint about missing props validation.

**Is there anyway to use js destructuring with the benefit of eslint react/prop-types rule?**

My component 

```
export default function Example({
  someProp,
  ...other
}) {
  return (
    <div someProp={someProp} {...other} />
  );
}

Example.propTypes = {};
Example.defaultProps = {};

```

What i am expecting: `someProp is missing in props validation (react/prop-types)
`

package.json

```
"prettier": "^1.14.2",
"eslint": "^5.4.0",
"eslint-plugin-prettier": "^2.6.2",
"eslint-config-airbnb": "^17.1.0",
"eslint-config-prettier": "^3.0.1",
"eslint-plugin-import": "^2.14.0",
"eslint-plugin-jsx-a11y": "^6.1.1",
"eslint-plugin-react": "^7.11.1",
```

.eslintrc

```
{
  "parser": "babel-eslint",
  "extends": ["airbnb", "prettier"],
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "rules": {
    "react/jsx-one-expression-per-line": "off"
  }
}
```

**Comment by ljharb** [comment]
This seems like a duplicate of #1952

**Comment by jalal246** [comment]
Yeah, it is. 

Didn't see it when i opened the issue.
