### ISSUE TITLE
prohibit `&&` conditional rendering in the return statement of a component

### ISSUE THREAD

**Issue by graingert** [yannickcr/eslint-plugin-react#1979]
```jsx
// avoid
const WrapTingy = ({ cond }) => (
  cond && <Tingy/>
);
 
// that would error if cond is `undefined`, use this version instead:
 
const WrapTingy = ({ cond }) => (
  <>{cond && <Tingy/>}</>
);
```

**Comment by ljharb** [comment]
This seems like a very niche use case; if it’s trying to address the issue of conditionally rendering the wrong thing, it’s not doing enough, and if it’s only trying to address the return error, I’d say the prop-types rule would handle that - iow, this component is missing a required propType.

**Comment by graingert** [comment]
still a problem when you want to have an optional value:

```jsx
// avoid
const WrapTingy = ({ items }) => (
  items && items.length && <Tingy items={items}/>
);
WrapTingy.propTypes = {
  items: propTypes.array
}
```

**Comment by ljharb** [comment]
React.Fragment is only available in 16.2+; fragment syntax requires babel 7 - this isn’t really a broadly available solution yet.

I still feel like this is a runtime warning, not a linter warning. If we did handle it in a rule, we’d have to figure out if a propType is required or not (and this isn’t statically possible on a custom propType), and only error when it’s optional or when the propType is missing.

**Comment by graingert** [comment]
Other options without fragment are:

```js
const WrapTingy = ({ cond }) => (
  cond ? <Tingy/> : null
);
```

```js
const WrapTingy = ({ cond }) => (
  (cond && <Tingy/>) || null
);
```

**Comment by graingert** [comment]
> I still feel like this is a runtime warning

This is only a runtime error when `cond` is `undefined` in development people might not see it

**Comment by harsh-tamr** [comment]
or !!cond && <Tingy/>

**Comment by steelbrain** [comment]
Opened a PR for this @ https://github.com/yannickcr/eslint-plugin-react/pull/2888

**Comment by ljharb** [comment]
@steelbrain this issue doesn't have "help wanted" or "accepted" labels, which means the new rule isn't necessarily something we'll accept. I'll take a look at the PR, though.

**Comment by ljharb** [comment]
I'm happy to keep discussing on #2888, but I think this can be closed.
