### ISSUE TITLE
I don't see a point in having the 'destructuring assignment' rule with Flow enabled

### ISSUE THREAD

**Issue by fabis94** [yannickcr/eslint-plugin-react#1985]
![image](https://user-images.githubusercontent.com/938316/45601937-90be2b00-ba1d-11e8-8235-975961e330aa.png)

I'm guessing that this plugin does take Flow types into account and if it does I don't really see a point in destructuring this.state or this.props anywhere I access it. I mean the accepted types are already specified through the class signature so you will always know what each property of this.state and this.props will be, so whats the point of destructuring assignment in places such as the one in the screenshot?

Am I missing something?

**Comment by ljharb** [comment]
It's got nothing to do with flow types. The point of using destructuring assignment is two fold: 1) it makes it much clearer to have only one extraction point for props in a function, and 2) it prevents the footgun of `this.props.foo()` implicitly passing `this.props` as the `this` value to `this.props.foo`.

In other words, this rule is about style, clarity, and preventing bugs, and is utterly unrelated to propTypes or flow types.

**Comment by fabis94** [comment]
Okay thanks
