### ISSUE TITLE
jsx-sort-props callbacksLast missing fixer function

### ISSUE THREAD

**Issue by jakub-chatrny** [yannickcr/eslint-plugin-react#1991]
jsx-sort-props is marked as fixable but option callbacksLast seems to lack fix function [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-sort-props.js#L268)

**Comment by jakub-chatrny** [comment]
I've found comment in code explaining this is not possible due to potencional prop override
`
  // Sort props according to the context. Only supports ignoreCase.
  // Since we cannot safely move JSXSpreadAttribute (due to potential variable overrides),
  // we only consider groups of sortable attributes.
`

**Comment by ljharb** [comment]
Indeed, not all things are autofixable.

PRs to improve autofixability are always great, but ordering rules are never fully autofixable.
