### ISSUE TITLE
Add new rule for getDerivedStateFromProps

### ISSUE THREAD

**Issue by dotterian** [yannickcr/eslint-plugin-react#1999]
React enforces getDerivedStateFromProps to be static method.
When I use it as instance method i get this error in browser
![screenshot from 2018-09-27 00-59-33](https://user-images.githubusercontent.com/6250486/46088919-c8349080-c1f0-11e8-91b4-2ee8105eca22.png)

It would be great if eslint could check for this error and warn me in case I forget to place "static" before my "getDerivedStateFromProps".

I'd write this rule myself but I don't have enough free time and lack knowledge of how to write eslint rules properly.

**Comment by ljharb** [comment]
That seems reasonable (although your tests should have caught that too). Seems like something `no-typos` could handle?
