### ISSUE TITLE
How to fix function assignments?

### ISSUE THREAD

**Issue by ImanMh** [yannickcr/eslint-plugin-react#2003]
What is the best way to fix `this.props.onChangeDebounced` issue in this case?

```
class x extends React.Component {
  ...
  onChangeDebounced = debounce(
    this.props.onChangeDebounced,
    this.props.debounceRate,
  );
  ...
}
```

**Comment by ljharb** [comment]
You'd want to move the class field into `getDerivedStateFromProps`, and store it in state instead - that way it'll be updated when props change.
