### ISSUE TITLE
Rule Proposal: No props.children in PureComponent

### ISSUE THREAD

**Issue by jacobp100** [yannickcr/eslint-plugin-react#2005]
If a component accepts children, extending `PureComponent` won't be able to skip updates unless no children are passed in. Doing so will do more work than extending `Component`.

To highlight this, we could have a rule that checks for usage of `props.children` in components that extend `PureComponent` (and the recent `pure` HOC).

It's not perfect, because you could still pass in children even if they aren't used, and it'll negate it in the same way. But it'll catch a far few cases of this.

What are your thoughts?

**Comment by ljharb** [comment]
This seems more reasonable than #1710, for sure.

That said, there’s no guarantee that the consumer of the pure component *isnt* passing memoized values in as children, so I’m not sure this would really be valuable.

**Comment by jacobp100** [comment]
It’s definitely not perfect. It’s more of a hint than a lint error. Depends if you think that would be valuable. If you do, I could take a stab at implementing it

**Comment by ljharb** [comment]
I feel like if you're authoring a PureComponent, you should know why you're extending PureComponent, and what the consequences are.
