### ISSUE TITLE
"padding-line-between-statements" not working consistently within components

### ISSUE THREAD

**Issue by andyfryy** [yannickcr/eslint-plugin-react#2013]
Hello!

Unsure if my problem resides in this plugin or whether I should open an issue elsewhere. If this is the wrong place maybe someone can point me in the right direction 🙃

I'm having some problems with eslint's `padding-line-between-statements` rule in arrow function components. I'm trying to add newlines before all return statements and `--fix` if the newlines are missing. This is the rule I'm using: 

```json
// eslint.rc
// ...
"rules": {
  "padding-line-between-statements": [
    "error",
    {
      blankLine: "always",
      prev: "*",
      next: "return"
    },
  ]
}
```
And here is some example code I'm trying to lint: 

```jsx
const Example = props => {
  const renderSomething = array => {
    return array.map(string => {
      return <span>{string}</span>;
    });
  };
  return <div>{renderSomething(['hello', 'world'])}</div>;
};
```

This DOES work on the second to last line (where I'm returning the `div`), but does NOT work for the map function or the return in the map function. It will in fact delete any newlines that are added manually before those return statements. 

Any help will be appreciated! Thank you!

**Comment by ljharb** [comment]
This repo is for eslint-plugin-react; that rule is in eslint core. That it's applying to jsx doesn't change that :-) please file it there instead.
