### ISSUE TITLE
jsx-quotes must support backtick option

### ISSUE THREAD

**Issue by gajus** [yannickcr/eslint-plugin-react#202]
To align with http://eslint.org/docs/rules/quotes, "jsx-quotes" must support "backtick" option.

**Comment by yannickcr** [comment]
From what I've seen, JSX does not support backtick.

**Comment by gajus** [comment]
Sorry, you are right. It would be:

```js
<div foo={`foo`} />
```

**Comment by gajus** [comment]
I have raised an issue with babel, https://github.com/babel/babel/issues/2309. Lets keep this open until Babel decision is made.

**Comment by yannickcr** [comment]
Great! I'll keep an eye on it.

**Comment by mathieumg** [comment]
Might become moot, given https://github.com/eslint/eslint/commit/3988b47a4b17fc1277c0956e2010d07d1e665cc5 ?

**Comment by gajus** [comment]
@markdalgleish Can you be more specific?

**Comment by yannickcr** [comment]
Since ESLint now have a [jsx-quotes](http://eslint.org/docs/rules/jsx-quotes) rule since `v1.4.0`, the one in this plugin will be set as deprecated.

If JSX get support for backtick, you'll have to see with the ESLint team directly.
