### ISSUE TITLE
loop in jsx-wrap-multilines

### ISSUE THREAD

**Issue by liajoy** [yannickcr/eslint-plugin-react#2027]
Hi! What do you think about using loop rendering in this form? 
jsx-wrap-multilines rules seems don't support loop.

    return (
        <ul>
            <li>
                {
                    [1, 2, 3].map(i => (
                        <span>
                            <b>i</b>
                        </span>
                    ))
                }
            </li>
        </ul>
    );

**Comment by liajoy** [comment]
sorry. Its a eslint-react issue.

**Comment by ljharb** [comment]
What is eslint-react? This is eslint-plugin-react, which is the source of the rule in question.

**Comment by sayduck-daniel** [comment]
Same here
