### ISSUE TITLE
Allow boolean values for input elements - jsx-boolean-value

### ISSUE THREAD

**Issue by runmoore** [yannickcr/eslint-plugin-react#2034]
The rule  [react/jsx-boolean-value](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md) when confirgured with `"never"` throws when a boolean value is added to an input value.

e.g.

```
<input type="hidden" name="hasAccount" value={true} />
```

By the letter of the rule this is correct behaviour, but In my opinion this should be a specific exception. When you submit a form without an explicit value of `true`, it won't send any value for this field.

We can add an exclusion using something like  `"always", { "never": ["value"] }` but it doesn't feel right. What if we have other custom components that accept a value prop and we still want to throw an error?

**Comment by ljharb** [comment]
I’m not sure what you mean - a string is the only valid value for an input’s “value” prop.

**Comment by runmoore** [comment]
Oh ok, I didn't realise that. I just presumed that because passing a boolean in React worked, that it was valid. 

In that case, I'll can close this issue. Thanks
