### ISSUE TITLE
eslint-plugin-react doesn't work

### ISSUE THREAD

**Issue by AndreasCag** [yannickcr/eslint-plugin-react#2038]
Hello, thanks for this great plugin.

I'm trying to lint my new react project.
I configured my eslint config file:
```
/* .eslintrc.js */

module.exports = {
  /* ... */
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
  ]
};
```

But it seems that it doesn't work, eslint still can't understand jsx and throws an error:
```
error  Parsing error: Unexpected token /
```

Minimal repro: https://github.com/AndreasCag/react-eslint-issue

Steps to reproduce:
1. Download repro
2. Run `npm i`
3. Run `npm run dev`

**Comment by ljharb** [comment]
You still have to enable jsx in your eslint config yourself.

**Comment by AndreasCag** [comment]
@ljharb Thanks for fast answer!

However, I have tried to enable jsx:

```
/* .eslintrc.js */

module.exports = {
  parserOptions: {
    ecmaVersion: 9,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
  ]
};
```

And it doesnt work either:
```
error  Parsing error: Unexpected token /
```

**Comment by ljharb** [comment]
ah, this is an eslint bug. Run `npm ls` and you’ll see your dependency graph is invalid. Either downgrade to eslint 5.7, or follow [these](https://github.com/eslint/espree/issues/393#issuecomment-433348355) instructions.

(Note that parsing errors are always unrelated to a specific plugin; so this issue should have been filed on eslint itself)

**Comment by AndreasCag** [comment]
@ljharb Thanks ❤️
