### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by andrew-humu** [yannickcr/eslint-plugin-react#2046]
Sorry for the nuisance issue, but is there any chance we could get a new release cut soon?

I notice that it's been about three months since the last release now, and there appear to be several new rules, tweaks and fixes that have yet to be published.

Thanks for all the great work!

**Comment by ljharb** [comment]
There's no need to ping people individually, or even to file this issue :-). When someone has time, a release will be cut, and prior to that, a release is impossible - because nobody has the time to do it.

**Comment by peterwiebe** [comment]
@ljharb my bad :( I will note that for the future. If there is anything I can do to help lighten your load feel free to ping me.

**Comment by andrew-humu** [comment]
Sorry, I didn't mean to cause anyone any stress.

I'm just excited about some of the latest changes, and looking forward to getting my hands on them! 
 (Especially this rule, now that babel@7 has landed: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md)

I occasionally need a little nudge to remember to keep on top of projects I'm helping to maintain, so I thought maybe a polite request would be forgivable.  🙂

**Comment by ljharb** [comment]
You’re certainly free to do that, but that’s not actually helping anything - all it’s going to do is make bug reports harder to triage and solve, which will take up even more of our time.

**Comment by dimitarnestorov** [comment]
5 minutes after posting I realized that if you want to get the latest commit in your dependencies all you have to do is change your `package.json` to point to the repo like in the screenshot below and running `npm install`.
![image](https://user-images.githubusercontent.com/8790386/48655831-19a91100-ea25-11e8-9117-613871b94eed.png)

Should I unpublish the package?

**Comment by ljharb** [comment]
Good call, and yeah, I’d suggest that ¯\\\_(ツ)_/¯ since you can install from github, that seems like a much easier approach that makes it an explicit choice by the user to use an unstable version.

**Comment by dimitarnestorov** [comment]
Done

**Comment by ljharb** [comment]
[v7.12.0](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.12.0) is released.
