### ISSUE TITLE
rule for hanging />

### ISSUE THREAD

**Issue by tschaka1904** [yannickcr/eslint-plugin-react#2047]
Hi, I've been looking for a rule that deal with hanging />
Cases like:
```
<MyComponent 
    {...}
/>
```
What I would like to enforce is that it always would look like this:
```
<MyComponent 
    {...}/>
```
Is there anything like that?

**Comment by ljharb** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md
