### ISSUE TITLE
Question: Is there a rule to prevent the use of <something.MyComponent>

### ISSUE THREAD

**Issue by hornta** [yannickcr/eslint-plugin-react#2049]
In our project we have a lot of code that looks like this:
```javascript
<ReactRouterDOM.Switch>
```
Is there a rule that forces me to destructure things like that?

**Comment by ljharb** [comment]
I don’t think there is one, but some kind of rule that blocks namespaced components might make sense.

**Comment by ljharb** [comment]
Happy to review a PR, but I don't think this needs to stay open.
