### ISSUE TITLE
Feature request: Check JSX for invalid syntax

### ISSUE THREAD

**Issue by fadookie** [yannickcr/eslint-plugin-react#2050]
We have been bitten several times now by the accidental introduction of seemingly minor syntax errors in JSX, such as:
```
<View>
  <SomeComponent />,
</View>
```
or
```
<View>
  <SomeComponent />;
</View>
```

In react-native, we've seen JSX like this work just file on iOS, but cause Android to immediately crash on boot. It would be great if we could have the linter flag issues like this before they make it to master.

**Comment by ljharb** [comment]
Technically this is perfectly valid jsx; it's putting a text comma and semicolon in the markup. If Android crashes on it, that's a pretty serious bug I'd file on react native directly.

You could probably use https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-literals.md to catch these, however.

**Comment by k-funk** [comment]
I also run into this every few months when I refactor something like this contrived example:

```
const elements: React.ReactNode = [
  <MyComponent />,
  <MyOtherComponent />,
]
```
->
```
return (
  <>
    <MyComponent />,
    <MyOtherComponent />,
  </>
)
```

I know it's valid jsx, but would be great if I could have eslint warn. For me, it only ever happens with commas.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-literals.md seems like a place to start, but it doesn't appear to have a setting like `disallowedStrings: [',']`. `<SomeComponent>i like cookies{','} however{','} I like ice cream more</SomeComponent>`  would be a less-than-ideal, but acceptable solution.

**Comment by ljharb** [comment]
It’s perfectly valid to have those things in the jsx, is the problem - it wouldn’t make sense to have a rule for that.

If refactoring manually causes this problem, perhaps an automatic refactoring tool could help.

Closing, since we can’t have a rule that forbids perfectly normal jsx.
