### ISSUE TITLE
react/forbid-prop-types should be off by default

### ISSUE THREAD

**Issue by jeremypeters** [yannickcr/eslint-plugin-react#2058]
This rule is on by default, but it should be off as it states in the documentation https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md

**Comment by ljharb** [comment]
All rules are off by default, unless you extend a config that enables them.

**Comment by jeremypeters** [comment]
Ok, sorry about that. It was set by the airbnb config https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js
