### ISSUE TITLE
question on sort-props 

### ISSUE THREAD

**Issue by TongDaDa** [yannickcr/eslint-plugin-react#2060]
![141543500391_ pic](https://user-images.githubusercontent.com/23241188/49230584-fd48a380-f42a-11e8-8fc4-7fa29ef74dc8.jpg)

v accroding the alphabet should be behind o, so it gives me the error.

Ok, I put v behind o, then...

![171543500392_ pic_hd](https://user-images.githubusercontent.com/23241188/49230614-09346580-f42b-11e8-80df-fb11aa31fc92.jpg)

What should I do?  😢😢

**Comment by ljharb** [comment]
I’m not sure what the error is in the first example - can you share the command line output?

This rule can be configured, for example, to sort callbacks (“on*”) last - what is your rule config?

**Comment by TongDaDa** [comment]
``` javascript
 <SwitchSvg
                        viewBox="0 0 136 136"
                        onTouchStart={this.handleSwitchOn}
/>
```

Just above example, you can paste your editor and verify my question.

Below is my config(I use these extends of scratch), but I thought that just is `jax-sort-props` to cause by that question.

module.exports = {
    extends: ['scratch/react', 'scratch/es6'],
    env: {
        browser: true,
        jest: true
    },
    rules: {
        'react/prop-types': 0
    }
};

**Comment by ljharb** [comment]
I’m not sure what scratch is, but presumably its react config sets up the sort-props rule.

**Comment by TongDaDa** [comment]
You can close this issue, I am used `ignore` solve it, Thanks for your answers.
