### ISSUE TITLE
missing "class-memebers" in "order" for typescript-eslint-parser

### ISSUE THREAD

**Issue by dudiharush** [yannickcr/eslint-plugin-react#2066]
When I use a tsx file (typescript) with typescript-eslint-parser, and I write a class member, it always errors me for placing it before lifecycle methods. ex:
```jsx
class MyComp extends React.Component<any, any> {
private _someMember; // error: should be placed before componentWillMount eslint(react/sort-comp)

componentWillMount() {
this._someMemeber = 1;
}
render...
}
```

Can you please add "class-members" to the "order" category, or support "everything-else" in multiple places?

Thanks!

**Comment by dudiharush** [comment]
I tried it, but it didn't work.
Can you send me the values in "order"?
Maybe i'm missing something...

**Comment by ljharb** [comment]
It’s possible it doesn’t work with typescript, of course. What is your exact config?

**Comment by dudiharush** [comment]
"rules": {
                "react/sort-comp": [2, {
                      "order": [
                        "static-methods",
                        "instance-variables",
                        "lifecycle",
                        "everything-else",
                        "render"
                      ],
                      "groups": {
                        "lifecycle": [
                          "displayName",
                          "propTypes",
                          "contextTypes",
                          "childContextTypes",
                          "mixins",
                          "statics",
                          "defaultProps",
                          "constructor",
                          "getDefaultProps",
                          "state",
                          "getInitialState",
                          "getChildContext",
                          "getDerivedStateFromProps",
                          "componentWillMount",
                          "UNSAFE_componentWillMount",
                          "componentDidMount",
                          "componentWillReceiveProps",
                          "UNSAFE_componentWillReceiveProps",
                          "shouldComponentUpdate",
                          "componentWillUpdate",
                          "UNSAFE_componentWillUpdate",
                          "getSnapshotBeforeUpdate",
                          "componentDidUpdate",
                          "componentDidCatch",
                          "componentWillUnmount"
                        ]
                      }
                    }]
            }

I think there is already an open issue about this problem: [https://github.com/yannickcr/eslint-plugin-react/issues/1664](url)

**Comment by ljharb** [comment]
That issue is closed.

I think this is typescript specific - JS doesn’t use the private keyword. Separately, instance variables refers to *public* properties.

I’m not sure we support JS private fields, let alone TS ones.

**Comment by ljharb** [comment]
We now support JS private fields and methods. If there's any issue with TS's `private` declaration, please file a new issue.
