### ISSUE TITLE
react/prop-types is not working with es6/es2015 classes

### ISSUE THREAD

**Issue by iamstarkov** [yannickcr/eslint-plugin-react#207]
If you define [propTypes inside es6 class (gist)](https://gist.github.com/iamstarkov/0794ed08cae25c4dd23c), then eslint doesnt recognize them
![screen shot 2015-09-04 at 17 45 43](https://cloud.githubusercontent.com/assets/559321/9687987/d0ae3300-532c-11e5-8954-cee688f27ea7.png)

```
./node_modules/.bin/eslint -v
v1.2.1
eslint -v
v1.2.1
➜  project git:(master) npm ls | grep eslint
├─┬ babel-eslint@4.1.0
├─┬ eslint@1.2.1
├─┬ eslint-config-airbnb@0.0.7
├── eslint-config-nordnet@1.0.1
├── eslint-plugin-react@3.3.0
```

**Comment by playpauseandstop** [comment]
I believe all you need is using `static propTypes` property instead.

**Comment by yannickcr** [comment]
Same as #203, the property declaration must be followed by a `=`, not a `:`.

**Comment by iamstarkov** [comment]
static propTypes is es7 proposal only, not standard

**Comment by iamstarkov** [comment]
but I get it, thank you
