### ISSUE TITLE
JSX/Fragment file is not being installed

### ISSUE THREAD

**Issue by nicosampler** [yannickcr/eslint-plugin-react#2072]
After installing `"eslint-plugin-react": "^7.11.1",`  I can not find the file `/node_modules/eslint-plugin-react/lib/rules/jsx-fragments.js`. Is this ok? I need to define a rule like this: `"react/jsx-fragments": [2, "element"]` and it's failing with this error: `1:1  error  Definition for rule 'react/jsx-fragments' was not found  react/jsx-fragments`

**Comment by alexzherdev** [comment]
You will have to wait until the next release for this rule to become available.

**Comment by maikthomas** [comment]
Looks like this can be closed with https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.12.2
