### ISSUE TITLE
react/no-unused-state broken for class fields

### ISSUE THREAD

**Issue by tzvipm** [yannickcr/eslint-plugin-react#2076]
If a piece of state is used within an ES7 property initializer whose value is an arrow function, `react/no-unused-state` still reports the state as unused. For example:

<img width="815" alt="screen shot 2018-12-06 at 2 12 12 pm" src="https://user-images.githubusercontent.com/1950680/49606590-cb22ce80-f961-11e8-9f7e-7c9576fed8de.png">
<img width="378" alt="screen shot 2018-12-06 at 2 12 32 pm" src="https://user-images.githubusercontent.com/1950680/49606591-cb22ce80-f961-11e8-8664-35da9aca4e65.png">

**Comment by ljharb** [comment]
ES7 is ES2016 - you might be thinking of "class fields", which is a stage 3 proposal (ie, it's ES Nothing Yet).

Thanks, we'll try to repro this.
