### ISSUE TITLE
Fix noMethodSetState url's

### ISSUE THREAD

**Issue by JBallin** [yannickcr/eslint-plugin-react#2078]
@Arcanemagus's docsUrl [commit](https://github.com/yannickcr/eslint-plugin-react/blame/bf544dcfc8a35d4fbea12094e6c6305cf50fd079/lib/util/makeNoMethodSetStateRule.js#L20) didn't account for the rule naming conventions of the different method names in [/lib/util/makeNoMethodSetStateRule](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/util/makeNoMethodSetStateRule.js).

Currently `componentWillUpdate` links to [/docs/rules/componentWillUpdate](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/componentWillUpdate.md) (doesn't exist, 404) when it should be linking to [/docs/rules/no-will-update-set-state](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/no-will-update-set-state.md):

```
function makeNoMethodSetStateRule(methodName, shouldCheckUnsafeCb) {
  return {
    meta: {
      docs: {
        description: `Prevent usage of setState in ${methodName}`,
        category: 'Best Practices',
        recommended: false,
        url: docsUrl(methodName)
      },
```

I'm proposing to create a function that gets the proper url within [/lib/util/makeNoMethodSetStateRule](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/util/makeNoMethodSetStateRule.js).

I have three suggestions to propose, and wanted feedback prior to opening a PR. Do you recommend placing this function at the top, under the 'Rule Definition' header? And then I would call the function directly within the `docs` object: `url: docsUrl(getDocsTitle(methodName))`

```js
function getDocsTitle1(methodName) {
  let title;
  switch (methodName) {
    case 'componentDidMount':
      title = 'did-mount';
      break;
    case 'componentDidUpdate':
      title = 'did-update';
      break;
    case 'componentWillUpdate':
      title = 'will-update';
      break;
    default:
      throw Error(`No docsUrl for '${methodName}'`);
  }
  return `no-${title}-set-state`;
}

function getDocsTitle2(methodName) {
  return `${methodName.match(/[A-Z][a-z]+/g)
    .reduce((res, e) => `${res}-${e.toLowerCase()}`, 'no')}-set-state`;
}

function getDocsTitle3(methodName) {
  return methodName.match(/[A-Z][a-z]+/g)
    .reduce((x, y) => `no-${x.toLowerCase()}-${y.toLowerCase()}-set-state`);
}

function getDocsTitle4(methodName) {
  const map = {
    componentDidMount: 'did-mount',
    componentDidUpdate: 'did-update',
    componentWillUpdate: 'will-update',
  };
  const title = map[methodName];
  if (!title) throw Error(`No docsUrl for '${methodName}'`);
  return `no-${title}-set-state`;
}

console.log(getDocsTitle1('componentWillUpdate')); // no-will-update-set-state
console.log(getDocsTitle2('componentWillUpdate')); // no-will-update-set-state
console.log(getDocsTitle3('componentWillUpdate')); // no-will-update-set-state
console.log(getDocsTitle4('componentWillUpdate')); // no-will-update-set-state
```

**Comment by JBallin** [comment]
@ljharb great suggestion! Added above (4), let me know if there's anything else I can improve.

**Comment by ljharb** [comment]
A PR with the `4` solution seems like a good place to start, thanks!
