### ISSUE TITLE
Prop type object if forbidden [react/forbid-prop-types]

### ISSUE THREAD

**Issue by slim-hmidi** [yannickcr/eslint-plugin-react#2079]
Hi I have this component:
```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { withStyles } from '@material-ui/core/styles';
import Paper from '@material-ui/core/Paper';
import Typography from '@material-ui/core/Typography';

const styles = theme => ({
  root: {
    ...theme.mixins.gutters(),
    paddingTop: theme.spacing.unit * 2,
    paddingBottom: theme.spacing.unit * 2,
  },
});

function PaperSheet(props) {
  const { classes } = props;
  const { title, data } = props;

  return (
    <div>
      <Paper className={classes.root} elevation={1}>
        <Typography variant="h5" component="h3">
          {title}
        </Typography>
        <Typography component="p">
          {data}
        </Typography>
      </Paper>
    </div>
  );
}

PaperSheet.propTypes = {
  classes: PropTypes.object.isRequired,
  title: PropTypes.string.isRequired,
  data: PropTypes.array.isRequired,
};

export default withStyles(styles)(PaperSheet);

````
package.json:
```json
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start:dev": "webpack && webpack-dev-server"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@material-ui/core": "^3.6.1",
    "mathjs": "^5.3.1",
    "prop-types": "^15.6.2",
    "react": "^16.7.0-alpha.2",
    "react-dom": "^16.7.0-alpha.2"
  },
  "devDependencies": {
    "@babel/core": "^7.2.0",
    "@babel/preset-env": "^7.2.0",
    "@babel/preset-react": "^7.0.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.4",
    "eslint": "^5.9.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.11.1",
    "webpack": "^4.27.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  }
}
```
.eslint.rc
```
module.exports = {
    "extends": [
        "airbnb",
        "eslint:recommended",
        "plugin:react/recommended"
    ],
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaFeatures": {
          "jsx": true
        }
      }
};
```
I got eslint errors for the PropTypes object:
```jsx
PaperSheet.propTypes = {
  classes: PropTypes.object.isRequired,
  title: PropTypes.string.isRequired,
  data: PropTypes.array.isRequired,
};
```
The error mentions: `Prop type object is forbidden`
How can I fix that?

**Comment by ljharb** [comment]
@EzequielDeSimone-Reflektion the inner one should be a `shape` tho, not `object`.

**Comment by SiddharthSunchu** [comment]
PaperSheet.propTypes = {
  classes: PropTypes.InstanceOf(Array).isRequired,
  title: PropTypes.string.isRequired,
  data: PropTypes.array.isRequired,
};

This is another solution you can solve the issue

**Comment by chiragSuccessive** [comment]
> You can define as following:
> dataOptions: PropTypes.objectOf(PropTypes.object()),

PropTypes.objectOf(PropTypes.object),
PropTypes.object() is not callable.

**Comment by noobling** [comment]
Given this is the number one Google search result when searching for this eslint error is anyone able to provide an explanation to this rule or a link to an explanation?

**Comment by ljharb** [comment]
The rule is to forbid certain propTypes from being used.

A very common way to configure it is to forbid object and array, because these are very non specific types. Instead, you’d want to use objectOf and arrayOf, and provide a propType for the contents of the array.

**Comment by masihjahangiri** [comment]
Use this block code:
```javascript
Index.propTypes = {
  reqData: PropTypes.instanceOf(Object),
};
```

**Comment by ljharb** [comment]
Most definitely do not; instanceOf is unreliable and should never be used with builtin types.

**Comment by yogeshepam** [comment]
dataOptions: PropTypes.objectOf(PropTypes.object),

**Comment by LukaGiorgadze** [comment]
Easiest way:
``PropTypes.shape({}).isRequired``

**Comment by josh-wer** [comment]
Simply use this rule

`PropTypes.objectOf(PropTypes.any).isRequired`

PropTypes.any indicates the values of the object can be of any type.

**Comment by ljharb** [comment]
@josh-wer the point of this rule is that you shouldn't ever use `any` - use a more descriptive propType.

**Comment by josh-wer** [comment]
> @josh-wer the point of this rule is that you shouldn't ever use `any` - use a more descriptive propType.

Okay @ljharb , I get that. Out of curiosity can u explain how that solution is different from `PropTypes.objectOf(PropTypes.object)` or `PropTypes.oneOfType([PropTypes.object]).isRequired` suggested by other answers based on the condition you gave. Assuming the prop value is of the shape

```javascript
{
  name: "John Doe",
  age: 28,
  isAdmin: false
}
```

**Comment by ljharb** [comment]
In that case, the best is to use shape - but object is still better than any, which allows non object values.

**Comment by aoxiangsky** [comment]
> > You can define as following:
> > dataOptions: PropTypes.objectOf(PropTypes.object()),
> 
> PropTypes.objectOf(PropTypes.object),
> PropTypes.object() is not callable.

chrome warning as follow:
Warning: Failed prop type: Invalid prop `children.$$typeof` of type `symbol` supplied to `App`, expected `object`.

**Comment by ljharb** [comment]
That means you’re passing something React creates instead of a normal javascript object.

**Comment by mjchang** [comment]
I'm making a log component that can accept any arbitrary json value. What would be the best approach? Should I just disable this rule for this case?

**Comment by ljharb** [comment]
Yes.

**Comment by Cookizza** [comment]
If anyone is still hitting this issue from google (it's the top result) - here's a quick rundown..

This ESLint rule is forbidding prop types of OBJECT because they are very unspecific. Just like our function will probably expect to use certain properties from an object our prop types should expect these too. 

The way to do this is with the SHAPE function - this tells proptypes to expect an object containing at least the defined properties. 

This doesn't mean you should list every property of the inbound object, a good practice is to at least list the properties used in the specific component.

**Comment by hai-nguyen-trung** [comment]
> > You can define as following:
> > dataOptions: PropTypes.objectOf(PropTypes.object()),
> 
> PropTypes.objectOf(PropTypes.object),
> PropTypes.object() is not callable.

This one is working. Thanks.

**Comment by BashirSidi** [comment]
This will solved your prob.

PropTypes.oneOfType([PropTypes.object]).isRequired

**Comment by ljharb** [comment]
You’d want shape, not object, inside the oneOfType.

**Comment by ch264** [comment]
For me this worked: 
```media: PropTypes.objectOf(PropTypes.string)```

**Comment by Belencha** [comment]
`classes: PropTypes.objectOf(PropTypes.any).isRequired`

This is the one that worked for me.

**Comment by LaxmanPache123** [comment]
> This will solved your prob.
> 
> `PropTypes.oneOfType([PropTypes.object]).isRequired`

but it still showing warning in console  
![image](https://user-images.githubusercontent.com/97151206/201045789-61056250-8d3c-41db-86f1-625bcaaf5dc7.png)
