### ISSUE TITLE
Send warnings to STDERR, not STDOUT

### ISSUE THREAD

**Issue by docwhat** [yannickcr/eslint-plugin-react#2082]
In issue #1955 the warning is being sent to STDOUT which is messing up editors by adding the warning to the top of the file.

All warnings and errors should be sent to STDERR.

**Comment by ljharb** [comment]
Good call, this should be fixed.

**Comment by ahakanbaba** [comment]
Could there be a new release including this fix ?

**Comment by ljharb** [comment]
[v7.12.0](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.12.0) is released.

**Comment by alexzherdev** [comment]
That's a whole lot of references.
