### ISSUE TITLE
Trouble using from Sublime with global install

### ISSUE THREAD

**Issue by EdHubbell** [yannickcr/eslint-plugin-react#209]
I realize this may not be a code issue, but hopefully someone here can assist. Tore my hair out until 3:30AM the other day - Would like to keep someone else from doing the same.

My setup: Mac with npm install -g eslint and npm install -g eslint-plugin-react

I'm using the following in the SublimeLinter.sublime-settings file:
````
 "lint_mode": "background",
        "linters": {
            "eslint": {
                "@disable": false,
                "args": [],
                "ecmaFeatures": {
                    "jsx": true,
                    "modules": true
                },
                "env": {
                    "browser": true,
                    "es6": true,
                    "node": true
                },
                "excludes": [],
                "plugins": [
                    "react"
                ],
                "rules": {
                    "react/display-name": 1,
                    "react/jsx-boolean-value": 1, 
````
etc

How can I see that the react plugin is actually loading? It doesn't seem to be. All my .jsx files throw a single error. I mess them up completely according to the rules that this plugin is designed to enforce.

Not sure if this is a problem with installing it globally, my Sublime setup, or what. I'm running SublimeLinter in debug mode so I can see that eslint is loading - But it isn't clear to me that this plugin is loading. 

Any help is much appreciated - If I figure things out on my system I'll post back here. ~Ed

**Comment by yannickcr** [comment]
I don't think you can set up the eslint/eslint-plugin-react rules directly in the `SublimeLinter.sublime-settings` file, you must create a `.eslintrc` config file at the root of your project and put this configuration in it. You can find more information in the [ESLint documentation](http://eslint.org/docs/user-guide/configuring).

**Comment by EdHubbell** [comment]
You are absolutely correct - Using a local ```.eslintrc``` file solved the issue for me. Thanks, @yannickcr - I'm seeing all kinds of linting errors in my .jsx files now. Looking forward to attacking them.

Thanks for the help and the excellent library. ~Ed
