### ISSUE TITLE
autofix support of react/react-in-jsx-scope

### ISSUE THREAD

**Issue by hackwaly** [yannickcr/eslint-plugin-react#2093]
This will save a lot of time to type `import React from 'react'`

**Comment by ljharb** [comment]
That might be tricky; not everyone uses ESM, so it might need to be `const React = require(‘react’)`, for example.

**Comment by hackwaly** [comment]
Could that be an config option.

**Comment by ljharb** [comment]
Perhaps, but generally eslint rules avoid config options solely for autofixes, and anything to do with guessing the module system usually needs manual work to fix.

**Comment by wouterds** [comment]
Any news? Is this going to happen or not? Might be good to update this issue or just close as won't fix.

**Comment by ljharb** [comment]
I think I'll close, since it's not consistently and correctly autofixable.
