### ISSUE TITLE
jsx-wrap-multiline eslint crash

### ISSUE THREAD

**Issue by mjhost** [yannickcr/eslint-plugin-react#2100]
Thanks all for the great library, I use it a lot. 
Recently I have discovered a problem with the rule jsx-wrap-multiline that throws exception during eslint execution.

I have a really bad formatted file:
```jsx
import React from 'react';

export default () =>
    <div>
        with newline without parenthesys eslint crashes
    </div>
``` 
the error I receive is 
```
TypeError: Cannot read property 'range' of null
    at Object.fixer [as fix] ([...]/node_modules/eslint-plugin-react/lib/rules/jsx-wrap-multilines.js:165:51)
...
```

I'll attach a basic example 
[jsx-wrap-multiline-issue.zip](https://github.com/yannickcr/eslint-plugin-react/files/2717335/jsx-wrap-multiline-issue.zip)

There are a few ways of patching this error and I would like to send a PR for it, but I'm not sure how would you like the fix to be implemented. Also I'm not aware of possible implications.

Let me know if I can help you

**Comment by ljharb** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-wrap-multilines.js#L165 implies that either the before or after token was null, and not being checked.

Added in #1576 / cc @sharmilajesupaul

**Comment by mjhost** [comment]
in this case it was the after token

**Comment by mjhost** [comment]
there's 3 fixes that I'm aware of: 

1. changing the condition [here](https://github.com/yannickcr/eslint-plugin-react/blob/dfeeb8110c63b681ba70f6c81864e694d9cfc6c1/lib/rules/jsx-wrap-multilines.js#L159)
  from `tokenBefore.loc.end.line < node.loc.start.line`
  to `tokenBefore && tokenAfter && tokenBefore.loc.end.line < node.loc.start.line`
1. changing the parameter call of replaceTextRange [here](https://github.com/yannickcr/eslint-plugin-react/blob/dfeeb8110c63b681ba70f6c81864e694d9cfc6c1/lib/rules/jsx-wrap-multilines.js#L164-L167)
  from `[tokenBefore.range[0], tokenAfter.range[0]]`
  to `[tokenBefore.range[0], tokenAfter && tokenAfter.range[0]]`
1. changing the initialization of const tokenAfter [here](https://github.com/yannickcr/eslint-plugin-react/blob/dfeeb8110c63b681ba70f6c81864e694d9cfc6c1/lib/rules/jsx-wrap-multilines.js#L158)
  from `const tokenAfter = sourceCode.getTokenAfter(node, {includeComments: true});`
  to `const tokenAfter = sourceCode.getTokenAfter(node, {includeComments: true}) || { range: [false /*or whatever*/] };`

but maybe there's a smarter use of getTokenAfter (or maybe the bug is definitely there) or a smarter use of replaceTextRange that I'm not aware of that may be worth implementing.

anyway rule is yours, pick your favourite fix I'll be happy to send the PR

**Comment by ljharb** [comment]
I’m really not sure :-) as long as the fix comes with lots of test cases, at least some of which fail absent the fix, i think maybe 1 > 2 > 3?
