### ISSUE TITLE
react/prop-types and componentDidUpdate

### ISSUE THREAD

**Issue by brandonburkett** [yannickcr/eslint-plugin-react#2107]
This is a weird one... but I recently did npm outdated and npm update.  I did not experience this issue before the update.  I am using:
```
    "eslint": "^5.11.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-prettier": "^3.0.01",
    "eslint-plugin-react": "^7.12.0",
```

-----

**ISSUE**
I only have this issue in `componentDidUpdate`, all other lifecycle methods and class methods are fine, but eslint seems to think nearly everything is a prop in `componentDidUpdate`.

```
  componentDidUpdate(prevProps) {
    const { formLoading, pageError, orgGroup, organization } = this.props; // no issue here
    const { edit } = this.state; // eslint error

    // focus the form loading component
    if (formLoading && this.formLoadingRef && this.formLoadingRef.current) {
      this.formLoadingRef.current.messageRef.focus(); // eslint error
    }

   /* other code */
}
```

I get the following output, but none of these are props.  They are state and refs.
```
124:13  error  'state.edit' is missing in props validation                react/prop-types
124:13  error  'state.edit' is missing in props validation                react/prop-types
132:67  error  'current' is missing in props validation                   react/prop-types
133:27  error  'current' is missing in props validation                   react/prop-types
133:35  error  'messageRef' is missing in props validation                react/prop-types
133:35  error  'current.messageRef' is missing in props validation        react/prop-types
133:46  error  'focus' is missing in props validation                     react/prop-types
133:46  error  'messageRef.focus' is missing in props validation          react/prop-types
133:46  error  'current.messageRef.focus' is missing in props validation  react/prop-types
```

-----

Let me know if I can provide any additional information.

Thanks
Brandon

**Comment by brandonburkett** [comment]
And.... it looks like 7.12.1 fixed it! I must have missed it being released yesterday when I was testing.  Closing out!

**Comment by tremby** [comment]
I'm seeing the same issue in 7.12.14.

**Comment by ljharb** [comment]
@tremby could you file a new issue with repro steps?

**Comment by tremby** [comment]
Afraid not, I've changed direction. (I was in the midst of trying to upgrade the react-scripts an ejected create-react-app 1.x project to 3.x, and hitting problem after problem, of which this was one. I succumbed in the end and am going to leave it for another day.) If I come across this issue again in future, I will try to give better details.
