### ISSUE TITLE
Eslint 7.12.1 Release Still Fails

### ISSUE THREAD

**Issue by emilyrohrbough** [yannickcr/eslint-plugin-react#2108]
Reinstall eslint-plugin-react v7.12.1 still crashes when running lint for the `reportUndeclaredPropTypes` rule:

![screen shot 2019-01-02 at 9 07 14 am](https://user-images.githubusercontent.com/14099737/50597908-a5102180-0e6e-11e9-8bc7-356e202d0f4e.png)

**Comment by ljharb** [comment]
Can you provide the text output instead of the image, as well as the code on which it’s crashing?

**Comment by ljharb** [comment]
Also, #2095 may have solved it, but is not yet released.

**Comment by ljharb** [comment]
[v7.12.2](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.12.2) is now released.

Happy to reopen if it's still an issue.

**Comment by emilyrohrbough** [comment]
@ljharb Thank you. Will get this tested out.
