### ISSUE TITLE
add exception in jsx-curly-spacing for inline styles

### ISSUE THREAD

**Issue by oluckyman** [yannickcr/eslint-plugin-react#211]
It would be great to allow that definitions when `jsx-curly-spacing: [2 , "always"]`:
```jsx
<Component
  style={{ color: "black" }}
  someProp={{ one: 1, two: 2 }}
  />
```
so instead of `style={ { color: "black" } }` you can do `style={{ color: "black" }}`

**Comment by yannickcr** [comment]
The `jsx-curly-spacing` do not enforce anything inside object literals, only on JSX attributes.

I think you're looking for the ESLint [object-curly-spacing](http://eslint.org/docs/rules/object-curly-spacing) rule.

**Comment by oluckyman** [comment]
sorry I was not clear. I mean that `jsx-curly-spacing: [2, 'always']` enforce space padding inside curly braces. Like so:
```jsx
attr={ true }
```
it is ok while inside curly braces you have variables/string/numbers. But the objects are space padded too:
```jsx
obj={ { attr: true } }
```
I would like to have ability to collapse these curly braces but still have `jsx-curly-spacing: [2, 'always']`.
In other words, this snipped should be valid:  
```jsx
<Component
  key={ i }
  title={ 'Component ' + name }
  style={{ color: "black" }}
  someProp={{ one: 1, two: 2 }}
  />
```

**Comment by yannickcr** [comment]
Ho ok, I understand your need :)

I think we could add some exceptions [like in the object-curly-spacing rule](http://eslint.org/docs/rules/object-curly-spacing#exceptions).

**Comment by oluckyman** [comment]
thanks, it would be great! 🙏

**Comment by SystemParadox** [comment]
As part of this would it be possible to add an exception for closing brackets in multiline expressions?

Like this:

```
<div>
    { isFoo && (
        <Foo />
    )}
</div>
```

Thanks
