### ISSUE TITLE
Catching when using a variable not declared

### ISSUE THREAD

**Issue by mjw56** [yannickcr/eslint-plugin-react#212]
Hi!

First, thank you so much for this project. This really makes working with react so much nicer, cleaner, better!

I'm not sure if this is a general eslint question, or one more specific to this react plugin.

Say I had a setup like this:

```js
import React, {Component} from 'react';

export class Root extends Component {
  // ...
}

Root.propTypes = {
  dispatch: PropTypes.func.isRequired
}
```

So as you can see above, I am trying to use ```PropTypes``` but I haven't imported it yet. Right now, I don't believe that it will catch it. I could be wrong though.

I know that it can catch the other way, say I have declared a variable but never used it. 

I guess my question is, is this something that is currently supported and I am just not using correctly? Or is it something that isn't supported but could be added?

Any insight is appreciated. Thanks!

**Comment by yannickcr** [comment]
Hi,

You can use the ESLint [no-undef](http://eslint.org/docs/rules/no-undef) rule to detect undeclared variables usage.

**Comment by mjw56** [comment]
Thanks @yannickcr, still groking ESLint. Will read up on that link. Thanks again for making this plugin.
