### ISSUE TITLE
autofix no-unnecessary-curly missing some cases

### ISSUE THREAD

**Issue by Billy-** [yannickcr/eslint-plugin-react#2130]
I have just tried to fix this snippet using `eslint --fix`, but  it only corrected the first and last lines. I think it should have done all of them, except lines four and five which would be invalid syntax.

input:
```jsx
      <option value="=">{'='}</option>
      <option value=">">{'>'}</option>
      <option value=">=">{'>='}</option>
      <option value="<">{'<'}</option>
      <option value="<=">{'<='}</option>
      <option value="!=">{'!='}</option>
```

expected:
```jsx
      <option value="=">=</option>
      <option value=">">></option>
      <option value=">=">>=</option>
      <option value="<">{'<'}</option>
      <option value="<=">{'<='}</option>
      <option value="!=">!=</option>
```

actual:
```jsx
      <option value="=">=</option>
      <option value=">">{'>'}</option>
      <option value=">=">{'>='}</option>
      <option value="<">{'<'}</option>
      <option value="<=">{'<='}</option>
      <option value="!=">!=</option>
```

**Comment by Billy-** [comment]
Hm, I just realised that fixing this causes another error (`no-unescaped-entities`) - maybe this is why it didn't autofix? In which case, ignore me. If someone could confirm my thinking here then please feel free to close this issue.

**Comment by ljharb** [comment]
Yes, those are indeed not autofixed for that reason.

Are they warned on? I’d expect those curries to be considered necessary due to jsx syntax.

**Comment by Billy-** [comment]
Only the first and last lines are warned on, so this is the correct behaviour.

Only the lines containing `>` cause errors if not in curlies, the ones with `<` don’t but as mentioned violate `no-unescaped-entities`.
