### ISSUE TITLE
Feature: no-inline-comments: Allow exception inside JSX

### ISSUE THREAD

**Issue by alexilyaev** [yannickcr/eslint-plugin-react#2132]
Right now `no-inline-comments` will warn on any comments inside JSX.

```jsx
function App() {
  return (
    <div>
      {/* Some comment */}
      <h1>Some heading</div>
    </div>
  )
}
```

I haven't found any way to make it work, since the rule has no options:  
https://eslint.org/docs/rules/no-inline-comments

I'm not sure if it's the responsibility of this plugin or ESLint itself.  
But it makes sense to allow comments inside JSX while still disallowing inline comments in regular JS blocks.

**Comment by ljharb** [comment]
Since it's an eslint core rule, it would have to be a change in eslint itself.
