### ISSUE TITLE
New error with latest release: TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by Android3000** [yannickcr/eslint-plugin-react#2137]
I'm seeing a new linting error failing a previously working module build via Webpack after the latest update to this plugin. The error I'm seeing is:
```
Module build failed: TypeError: Cannot read property 'type' of null
    at Object.getRelatedComponent"
```

A change was added where a new check to `refId.parent.init.type !== 'Identifier'` is being made, but it appears `refId.parent.init` must be null in some cases, and there isn't null check protection in place.

The commit in question is here:
https://github.com/yannickcr/eslint-plugin-react/commit/5fc50aa9238768674cf2a2ca1d9676be629a920a#diff-bafb3355a409c4ba076a9e3d609ad65b

I can try to cobble together some files to try and reproduce this in some code if needed... I'll just have to put together a specific example to illustrate as I can't provide the existing code.

**Comment by ljharb** [comment]
Thanks; the repro code helps a lot. Any idea what file it’s crashing on?

**Comment by Android3000** [comment]
Correct. This code also does not crash:
```
let items = [];
let testData = [{a: "test1", anythingelse: "test2"}, {a: "test1", anythingelse: "test2"}];
for (let item of testData) {
     items.push({a: item.a, b: item.anythingelse});
}
return items;
```
It looks like this is coming from the rule (this makes so much more sense now): "react/display-name"

**Comment by Android3000** [comment]
Thanks for putting in a fix for this!

**Comment by jwalton** [comment]
Can we please publish this fix?  This is breaking for me, too.

**Comment by khall22** [comment]
I second that! We're broken until this is published.
