### ISSUE TITLE
Add fix support for Enforce shorthand or standard form for React fragments (react/jsx-fragments)

### ISSUE THREAD

**Issue by joshunger** [yannickcr/eslint-plugin-react#2139]
Would it be possible to add fix support for Enforce shorthand or standard form for React fragments (react/jsx-fragments)? I might be able to help implement.

**Comment by ljharb** [comment]
The rule should already be autofixable - see these tests:
 - https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/jsx-fragments.js#L124
 - https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/jsx-fragments.js#L140
 - https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/jsx-fragments.js#L151-L154
etc.

**Comment by joshunger** [comment]
Thanks, I'll debug and get you a repro steps or close.

**Comment by joshunger** [comment]
Works with the command line but didn't work with vscode and eslint extension configured with `autoFixOnSave`. 🤔 Closing.
