### ISSUE TITLE
no-array-index-key can be bypassed with toString

### ISSUE THREAD

**Issue by kognise** [yannickcr/eslint-plugin-react#2140]
You can bypass the [`no-array-index-key`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md) rule with `toString()`.

In other words, this gives an error:
```js
foo.map((bar, index) => (
  <Element key={index} bar={bar} />
))
```

But this doesn't:
```js
foo.map((bar, index) => (
  <Element key={index.toString()} bar={bar} />
))
```

**Comment by ljharb** [comment]
There’s a lot of ways to bypass it; it’s not really practical to try to catch them all. The rule is meant as a helpful warning not to rely on indexes in a key, when your items have a unique signature.

**Comment by ljharb** [comment]
I’m not sure. We can certainly detect this specific pattern, but I’m not sure how valuable it’d be, especially considering that `x.toString()` is an anti pattern (prefer `String(x)`). What do you think?

**Comment by arch-lord** [comment]
Personally, as a naive Reacter, have used `index.toString()` many times. I am slowly replacing that code with a better approach, but it would've been nice to have been warned.

**Comment by ljharb** [comment]
@kognise in all javascript, everywhere, including all "native" React (RN or React Web), `String(x)` is preferred over `x.toString()`, full stop. That said, `String(x)` is also not warned on, so that fact is moot.
