### ISSUE TITLE
[question] automatically stub out missing react/prop-types

### ISSUE THREAD

**Issue by joshunger** [yannickcr/eslint-plugin-react#2141]
Is there a way to have react/prop-types automatically stub out / fix any missing prop-types or at least provide a code snippet of all missing prop-types? Thanks.

**Comment by ljharb** [comment]
How could it possibly do that in an untyped language like JavaScript?

**Comment by joshunger** [comment]
I'm saying it would be helpful to stub out the boilerplate and you can fix the types.

**Comment by ljharb** [comment]
eslint autofixers are supposed to leave the code in a passing state, and most importantly to not change how code behaves. I'm not sure how much value this would add.

**Comment by joshunger** [comment]
Looks like someone created a vscode extension -

- https://marketplace.visualstudio.com/items?itemName=suming.react-proptypes-generate
