### ISSUE TITLE
Expected the depth of nested jsx elements to be <= 2, but found 4. 

### ISSUE THREAD

**Issue by TankRyze** [yannickcr/eslint-plugin-react#2144]
![image](https://user-images.githubusercontent.com/22748893/51657287-3b9fb080-1fdf-11e9-8546-c49f3e298fe6.png)

**Comment by TankRyze** [comment]
![image](https://user-images.githubusercontent.com/22748893/51660675-84f4fd80-1fe9-11e9-8011-b4d81bbdefa0.png)

**Comment by ljharb** [comment]
Can you share the original code as *text*? screenshots of text are nearly impossible to work with.

**Comment by TankRyze** [comment]
This is the contents of the.eslintrc file

{
  "extends": ["plugin:react/all", "airbnb"],
  "plugins": [
    "react"
  ],
  "parser": "babel-eslint",
  "rules": {
    "strict": 0,
    "no-undef": 1,
    "no-unused-vars": 1,
    "comma-daggle": 0,
    "sort-imports": 0,
    "import/first": 0,
    "import/no-extraneous-dependencies": 1,
    "class-methods-use-this": 0,
    "no-param-reassign": 1,
    "max-len": 1,
    "no-trailing-spaces": 1,
    "indent": 1,
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
    "react/require-optimization": 1,
    "react/prefer-stateless-function": 1,
    "react/jsx-no-literals": 0,
    "react/prop-types": 0,
    "react/jsx-indent": 0,
    "react/jsx-indent-props": 0,
    "react/no-multi-comp": 1,
    "react/forbid-component-props": 1,
    "react/no-set-state": 0,
    "react/no-unused-state": 0,
    "react/jsx-no-bind": 1,
    "react/no-unescaped-entities": 1
  }
}

**Comment by iiison** [comment]
@TankRyze  can you add rule for `react/jsx-max-depth` for desired length? like:
```js
"react/jsx-max-depth" : 0
```

if you don't want to get bothered about the rule?

**Comment by TankRyze** [comment]
thank you

**Comment by ljharb** [comment]
@TankRyze is your issue that you didn't like the warning, or that you think it was warning with the wrong depth?
