### ISSUE TITLE
jsx-uses-vars doesn't prevent @typescript-eslint/no-unused-vars from warning on props

### ISSUE THREAD

**Issue by andreubotella** [yannickcr/eslint-plugin-react#2149]
The [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) project provides its own implementation of `no-unused-vars`, which warns on variables which are used ony in JSX properties even when `jsx-uses-vars` is enabled. There's no such issue with `jsx-uses-react` or with variables used as JSX tag names.

The relevant versions are `eslint`: 5.10.0, `eslint-plugin-react`: 7.12.4, `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin`: 1.1.1.

**Comment by ljharb** [comment]
I assume that the mechanism our rule uses to “notify” the core rule that a var is used also needs to do the same for the typescript rule.

**Comment by MayhemYDG** [comment]
That was a regression in `@typescript-eslint/parser`: https://github.com/typescript-eslint/typescript-eslint/commit/6147de1bb20e269b1e0a650c8be5376d0f51752e

**Comment by andreubotella** [comment]
My bad, I only added Typescript to my project a few days ago and I didn't even know this was a regression. Since `typescript-eslint`'s canary version already has the fix, and it'll be included in the next release, I guess this should be considered closed.
