### ISSUE TITLE
Cannot override `react/no-danger` from "warn" to "error"

### ISSUE THREAD

**Issue by Ghusar** [yannickcr/eslint-plugin-react#2154]
By default i am using react/no-danger rule to give warning for using `dangerouslySetInnerHTML` but for current use case i want to make it give "error" instead of "warning".

Adding "react/no-danger": "error" in rules ignores the rule and still shows "warning"

**Comment by ljharb** [comment]
Share your entire eslint config?

**Comment by Ghusar** [comment]
Thanks @ljharb replying. There was a slight error in my eslint config which was causing this issue. Now it's resolved.

**Comment by morsmodr** [comment]
I know this ticket is closed but @Ghusar can you add what you got wrong in your eslint config? I am facing a similar issue. My eslint config has the following for no-danger
`"rules": {
     "react/no-danger": "error",
}`
I also tried with 2 as value instead of "error" but still not working

**Comment by ljharb** [comment]
What’s your full eslint config?

**Comment by morsmodr** [comment]
I solved the issue. There were two files .eslintrc and .eslintrc.js and I was making changes on the wrong one. Deleted .eslintrc which wasn't being used. 🤦‍♂
