### ISSUE TITLE
Cannot get react/state-in-constructor working

### ISSUE THREAD

**Issue by karolisgrinkevicius-home24** [yannickcr/eslint-plugin-react#2162]
Using ... I'm always getting the following error

```1:1   error    Definition for rule 'react/state-in-constructor' was not found                      react/state-in-constructor;```

My `.eslintrc` file currently is as follows:
```json
{
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "plugins": ["react"],
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "rules": {
    "react/state-in-constructor": 2
  },
  "env": {
    "browser": true,
    "es6": true,
    "node": true,
    "mocha": true,
    "jest": true
  }
}
```

Version of dependencies are:
```
├── eslint@5.13.0
├── eslint-plugin-react@7.12.4
└── react@16.8.1
```

**Comment by sashapwc** [comment]
Same here. It's not in the list of rules when you go to the documentation on npm. Looking at the commits, the merge seemed to fail a test on Jan 20 so maybe that is part of it

**Comment by ljharb** [comment]
That particular rule was merged in #1945, only 24 days ago, and has not yet been released to npm.

Thus, you can't enable a rule that doesn't yet exist in a released version.

**Comment by karolisgrinkevicius-home24** [comment]
@ljharb when are you going to release it on npm?

**Comment by ljharb** [comment]
There's no timeline; when a maintainer has time to do so. In this case, it'll be a minor, so I'll also look through the open PRs and make sure there's no new features or bugfixes that need merging first.
