### ISSUE TITLE
react/no-multi-comp false positives when declare class property memo keyword

### ISSUE THREAD

**Issue by vdhieu** [yannickcr/eslint-plugin-react#2164]
The eslint-plugin-react version I use is 7.12.4

![image](https://user-images.githubusercontent.com/12120998/52772245-91a9c600-306a-11e9-8a54-d8938621bc27.png)

**Comment by ljharb** [comment]
Does this only happen if the function is named `memo`?

**Comment by vdhieu** [comment]
@ljharb with the import name, too.

Actually I was used `memo` to name `memorize-one` package. I thought it might be because of the `memorize-one` so I created that `memo` function (as above) to test if it really because of the `memorize-one`

**Comment by ljharb** [comment]
Right, but I mean if you name it something that's not "memo" - because `React.memo` is a special thing - does the lint rule still warn>?

**Comment by vdhieu** [comment]
Ah, if I use other name the warning will gone.

**Comment by ljharb** [comment]
Thanks, in that case the issue is that the code checking for React.memo needs to also ensure `memo` comes from `React`.
