### ISSUE TITLE
Unused state field with conditional Destructuring 

### ISSUE THREAD

**Issue by monkindey** [yannickcr/eslint-plugin-react#2168]
**Tell us about your environment**

* **ESLint Version:**  ^5.9.0
* **Node Version:** 10.0.0
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

 Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "extends": "eslint-config-ali/react",
  "parser": "babel-eslint",
  "rules": {
    "react/forbid-prop-types": "off",
    "react/prop-types": "off",
    "semi": "off"
  }
}
```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class Test extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: '',
    };
  }

  isUpdatedByChange = false;
  
  render() {
    const { value } = this.isUpdatedByChange ? this.props: this.state;
    // it will be ok when I didn't use Destructuring
    // const value = this.isUpdatedByChange ? this.props.value: this.state.value;
    return <Select value={value} onChange={onChange}/>
  }
}
```

I use vscode

**What did you expect to happen?**

Nothing error

**What actually happened?**

Unused state field: 'value'

**Comment by ljharb** [comment]
Because you're conditionally destructuring it, in some code paths the prop will be unused, and in some the state will be unused.

Instead, unconditionally destructure it from BOTH props and state, and conditionally *use* it instead.

**Comment by monkindey** [comment]
It will be ok with this 

```js
const value = this.isUpdatedByChange ? this.props.value: this.state.value;
```

And it can pass for the `non-destructuring` form

**Comment by ljharb** [comment]
Yes; I’m suggesting you shouldn’t do either, and should instead do:
```jsx
const { value: propValue } = this.props;
const { value: stateValue } = this.state;
const value = this.isUpdatedByChange ? propValue : stateValue;
```

**Comment by monkindey** [comment]
Thanks
