### ISSUE TITLE
Deprecate jsx-quotes rule

### ISSUE THREAD

**Issue by remitbri** [yannickcr/eslint-plugin-react#217]
Since ESLint v.1.40, "jsx-quotes" exists within ESLint.

**Comment by yannickcr** [comment]
Yes, but I think I will keep it deprecated for a little while before completely removing it.

**Comment by Xurma2** [comment]
Now, what to write, instead of react / jsx-quotes?
Just jsx-quotes are not executed.

**Comment by yannickcr** [comment]
`jsx-quotes` should work if you have ESLint `>=1.4.0`

But be sure to read [the rule documentation](http://eslint.org/docs/rules/jsx-quotes), the configuration parameters are different from `react/jsx-quotes`.
