### ISSUE TITLE
sort-comp doesn't recognize instance variables declared without explicit value

### ISSUE THREAD

**Issue by ericgio** [yannickcr/eslint-plugin-react#2183]
Thanks for a very useful library. Apologies if I'm missing something obvious here, but it seems that instance variables are not recognized as such unless a value is explicitly assigned.

Given this `sort-comp` rule
```js
"react/sort-comp": [2, {
  "order": [
    "state",
    "instance-variables",
    "static-methods",
    "lifecycle",
    "render",
    "everything-else"
  ],
}],
```

and this class definition
```jsx
class MyComponent extends React.Component {
  state = {};
  foo;
  static propTypes;

  render() {
    return null;
  }
}
```
I get this error:
```
error  foo should be placed after render  react/sort-comp
```

Changing `foo;` to `foo = undefined;` solves the problem, but the behavior is confusing to me.

**Comment by ljharb** [comment]
Seems like a bug, to be sure.

**Comment by ericgio** [comment]
Thanks guys!
