### ISSUE TITLE
Support `PropTypes.elementType` in the `react/no-typos` rule

### ISSUE THREAD

**Issue by sindresorhus** [yannickcr/eslint-plugin-react#2188]
See: https://github.com/facebook/prop-types/blob/master/CHANGELOG.md#1570

**Comment by ljharb** [comment]
I'm aware of the changelog; I published it. Can you elaborate on what code is erroring and what error you receive?

**Comment by ljharb** [comment]
Note that the current rule does `Object.keys(require('prop-types'));`, so as long as you have the latest `prop-types` package installed, everything should Just Work.

**Comment by sindresorhus** [comment]
Ah, it was not clear to me you used the `prop-types` package directly. I incorrectly assumed you had hard-coded the supported keys.
