### ISSUE TITLE
Yarn PnP compatibility

### ISSUE THREAD

**Issue by fazouane-marouane** [yannickcr/eslint-plugin-react#2192]
Hello,

It seems that usage of https://github.com/browserify/resolve#readme instead of plain old `require.resolve` causes issues when trying to use `eslint-plugin-react` while passing this settings to eslint when using yarn pnp mode ( https://github.com/facebook/create-react-app/issues/6605 )

```json5
{
  //...
  "settings": {
    "react": {
      "version": "detect"
    }
  }
}
```

Would you be open to a PR to change this part https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/util/version.js#L14 into a `require.resolve('react')` ?
Thx

**Comment by ljharb** [comment]
`resolve` already has PnP compatibility (via https://github.com/browserify/resolve/pull/170). If it's not working, please file a bug on yarn.
