### ISSUE TITLE
jsx-curly-spacing --fix

### ISSUE THREAD

**Issue by lpoulter** [yannickcr/eslint-plugin-react#2194]
When run on 
`<ArticleStat message='Number of links' stat={linkShares}>`
Eslint says this rule is not fixable but docs say it should be.
using `"eslint": "^5.15.1",`

**Comment by ljharb** [comment]
What warning do you get exactly?

**Comment by lpoulter** [comment]
`
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "prettier"
  ],
`
` 13:30  error  A space is required before '}'  react/jsx-curly-spacing`
`4223 errors and 0 warnings potentially fixable with the `--fix` option.`

**Comment by ljharb** [comment]
What version of eslint-plugin-react do you have?

Also note that prettier conflicts with many eslint rules, including this one - you’ll need to also extend the prettier react config to disable those.

**Comment by lpoulter** [comment]
`"eslint-plugin-react": "^7.12.4",`

**Comment by lpoulter** [comment]
Ok I think your right about a conflict.
`"eslint --print-config . | eslint-config-prettier-check"`
```
The following rules are unnecessary or might conflict with Prettier:

- react/jsx-curly-spacing```

Do you know what i need to add to my extends?
```
 "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "prettier"
  ],```

**Comment by ljharb** [comment]
Also extend prettier/react, according to the prettier docs.

**Comment by tyrong** [comment]
@lpoulter did you find a solution to this?

**Comment by ljharb** [comment]
Closing as answered.
