### ISSUE TITLE
react/jsx-quotes rule deprecation reports as an error, causing eslint command to fail

### ISSUE THREAD

**Issue by jackwanders** [yannickcr/eslint-plugin-react#220]
Version 3.4.0 of this plugin is causing eslint tasks to fail if they use the `react/jsx-quotes`. Deprecation notices should not cause failures (sample below)

```bash
path/to/some/script.js
  1:0  error  The react/jsx-quotes rule is deprecated. Please use the jsx-quotes rule instead  react/jsx-quotes
```

The issue appears to lie here: https://github.com/yannickcr/eslint-plugin-react/blob/v3.4.0/lib/rules/jsx-quotes.js#L46

Is there a way to show a deprecation warning without causing the `eslint` task to fail entirely? As it stands, version 3.4.0 represents a breaking change.

**Comment by olalonde** [comment]
Same problem here. Is there a workaround for this?

**Comment by doctyper** [comment]
Same, I don't think a deprecation should cause an lint failure.

**Comment by yannickcr** [comment]
I'm very sorry for this, my initial thought was to only display a warning, but in the case the rule is configured in `error` level it will cause the task to fail.

I will publish a patch to simply display it in a `console.log`, this should solve your problem while keeping the warning.

**Comment by jackwanders** [comment]
@olalonde now that @yannickcr has published a patch, you could just ensure that your'e installing `3.4.1` (note that you'll continue getting deprecation messages via `console.log`. Your other options are to either update your `eslint-plugin-react` dependency to stay south of `3.4.0` (e.g. specifying `~3.3.2` in your `package.json`), or to ensure you are using an `eslint` version >= `1.4.0` and changing your `.eslintrc` to use the `jsx-quotes` instead of `react/jsx-quotes`

**Comment by olalonde** [comment]
Thanks. I'm using airbnb's eslint, so I guess I'll have to wait for this issue to be closed: https://github.com/airbnb/javascript/issues/513

**Comment by niftylettuce** [comment]
I fixed this by upgrading my global installations of eslint and eslint-plugin-react via:

```bash
npm install -g eslint eslint-plugin-react
```
