### ISSUE TITLE
react/jsx-curly-brace-presence {"children": "never"} doesn't error on multiline expressions

### ISSUE THREAD

**Issue by mplis** [yannickcr/eslint-plugin-react#2201]
```
"eslint": "^4.10.0",
"eslint-plugin-react": "^7.10.0",
```

Given this configuration:

```
'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never' }],
```

Unnecessary brackets will be detected when the start tag, children, and end tag are all on the same line, like:

```jsx
<div className={styles.myRateValuePercentSign}>{'%'}</div>
```

but they won't be detected when they're on different lines, like:

```jsx
<div className={styles.myRateValuePercentSign}>
    {'%'}
</div>
```

Is this the intended behavior?

<img width="855" alt="Screen Shot 2019-03-15 at 10 59 45 AM" src="https://user-images.githubusercontent.com/1382377/54443529-2578bb80-4717-11e9-8824-7df3f09ae2af.png">
<img width="1132" alt="Screen Shot 2019-03-15 at 10 59 24 AM" src="https://user-images.githubusercontent.com/1382377/54443527-2578bb80-4717-11e9-8adc-be964bdbc2c8.png">

**Comment by golopot** [comment]
I can reproduce this. This is likely a bug.

The relevant code is here:
https://github.com/yannickcr/eslint-plugin-react/blob/d1e79b99ee43ea60c66a7b68bcce8915958b3535/lib/rules/jsx-curly-brace-presence.js#L207-L212

**Comment by mplis** [comment]
Is there an argument to just removing that check altogether?
