### ISSUE TITLE
react/no-unknown-property incorrect `for` on none `label` tag detection

### ISSUE THREAD

**Issue by a-x-** [yannickcr/eslint-plugin-react#2204]
I have a `Table.Index` component with `for` prop.

the rule enforces me to use `htmlFor` instead and incorrectly auto replaces it when I run `eslint --fix`

**Comment by ljharb** [comment]
Hmm, this rule should be ignoring non-DOM elements. Can you provide the full code and full warning text?

**Comment by a-x-** [comment]
function Foo ({ collection }) {
  return <Table.Index for={ collection } />;
}
