### ISSUE TITLE
Rule Suggestion: Disallow using this.props within this.setState

### ISSUE THREAD

**Issue by dkrutsko** [yannickcr/eslint-plugin-react#2208]
I recently got introduced to [`no-access-state-in-setstate`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md) and after reading the React documentation about this [topic](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous), it seems to me that there should be another rule that disallows the use of `this.props` within `this.setState`. Has something like this been brought up before or has it been considered in some fashion?

**Comment by ljharb** [comment]
It hasn't been brought up before. Given that it hasn't been brought up since, I'll close it, but happy to keep discussing.
