### ISSUE TITLE
"indentLogicalExpressions": should NOT have additional properties.

### ISSUE THREAD

**Issue by ArthurKnoep** [yannickcr/eslint-plugin-react#2231]
I have created a react app with create-react-app last week (so, I guess I have the last version)

Yesterday I tried to add my custom lint rules and in my .eslintrc I add this:
```
"react/jsx-indent": ["error", "tab", {"indentLogicalExpressions": true}],
```
because I want to indent like this
```jsx
<App>
  {condition && (
  <Hello />
  )}
</App>
```

BUT, (there is always a but in an issue :smile: )

when I run eslint like this:
```
./node_modules/.bin/eslint --ext .js --ext .jsx ./src
```
eslint crash and give me this error:
```
Configuration for rule "react/jsx-indent" is invalid:
	Value {"indentLogicalExpressions":true} should NOT have additional properties.
```

eslint version: v5.12.0
eslint-plugin-react version: 7.12.4
node version: v11.10.1

PS: When I add `"checkAttributes": true,` in the rule, it works

**Comment by ljharb** [comment]
That’s because that option hasn’t been released yet. Instead of looking at the docs in master, always look at the docs for the latest tagged version.

**Comment by saiichihashimoto** [comment]
Happening for me in 7.14.3 @ljharb

**Comment by ljharb** [comment]
Please file a new issue.
