### ISSUE TITLE
Definition for rule was not found - misleading documentation

### ISSUE THREAD

**Issue by subhog** [yannickcr/eslint-plugin-react#2235]
The project readme file lists available rules, including `react/jsx-props-no-spreading` that I wanted to use. The docs for the rule are available in what seems to be the official documentation, stored on the master branch. However, after using that rule I got a warning for each file:

    warning  Definition for rule 'react/jsx-props-no-spreading' was not found  react/jsx-props-no-spreading

After spending some time debugging this issue I couldn't pinpoint the cause and decided to raise an issue here. **Only at this point**, thanks to the related issues feature of github, I found out that the official documentation is inaccurate, and that more people had this problem in the past.

This is a huge problem, and not a good way to organize your documentation. I spend my time figuring out what is happening, as did many other developers - this is an unnecessary waste.

Please fix this problem. The standard solution would be to keep `master` branch at the latest release, and using `dev` or `develop` for the work in progress. If you don't want to change your practice, another way would be to decouple the official documentation from readme, i.e. host it as a github page and point there from the readme and / or repo description.

**Comment by ljharb** [comment]
This is how every project on github organizes its documentation - any time there's anything unreleased, checking the docs on `master` will be misleading.

You should always be looking at the docs for the last tagged release, not master. The solution here is education, not a change in near-universal maintainer practice.

A PR to add a note to the top of the docs reminding people to check a tagged version would be fine, though.
