### ISSUE TITLE
ESLint doesn't validate props if they are exported to a var or module.

### ISSUE THREAD

**Issue by sergej-s** [yannickcr/eslint-plugin-react#2236]
I'm trying to apply the cenralized proptypes pattern
https://medium.freecodecamp.org/react-pattern-centralized-proptypes-f981ff672f3b
but ESLint validation doesn't work with proptypes exported or saved in a variable as shown on screenshot below

![image](https://user-images.githubusercontent.com/668587/56033143-7c7cab00-5d2c-11e9-81e3-f502db815737.png)

Could you help me to fix this?

Deps: 
"eslint-plugin-react": "^7.12.4"
"eslint": "^5.16.0"
"babel-eslint": "^10.0.1"

**Comment by ljharb** [comment]
cc @alexzherdev

**Comment by sergej-s** [comment]
Hi! Do you have any news?
