### ISSUE TITLE
Prop types validation for custom component class

### ISSUE THREAD

**Issue by lkaratun** [yannickcr/eslint-plugin-react#2244]
Hi everyone, 

in our codebase, we are using an intermediary class that implements some widely-used functionality so our component declarations look like this: 
`class MyComponent extends CustomBaseComponent ...`
and `CustomBaseComponent` inherits from `React.Component` like usual. 
The setup has been working well for us, except for the fact that `MyComponent` is not being recognized as a React component by the plugin. To fix it, I modified `node_modules/eslint-plugin-react/lib/util/Components.js->isExplicitComponent->relevantTags` to check for `CustomBaseComponent`: 
```      
const relevantTags = commentAst.tags.filter(
        tag => tag.name === 'React.Component' || tag.name === 'React.PureComponent' || tag.name === 'CustomBaseComponent'
      );
```

Unfortunately, it didn't solve the issue. 
Am I doing something wrong, or do I need to clear some cache to get the changes applied? I tried breaking the `relevantTags` function by removing the `React.Component` option but linting kept working for my components inheriting directly from `React.Component` hence the suspicion about caching. I tried reopening VSCode and running eslint from cli with no luck.

Any advice would be greatly appreciated!

**Comment by ljharb** [comment]
First of all, having any sort of inheritance chain like that is both discouraged by the react team and also almost universally derided by the community.

Second, you shouldn’t need to modify anything in node_modules; use a jsdoc extends comment to tell the linter that your thing really is a react component: see #632, #1678.

**Comment by lkaratun** [comment]
Thanks @ljharb but your workaround would require me to refactor a huge codebase or add a line to hundreds or source code files. I would much prefer modifying a single line in the plugin source code instead. 

Any chance you could answer my original question about caching?

**Comment by ljharb** [comment]
There’s no cache, I’m not sure why that’s not working.

And yes, you do need to refactor your huge codebase - it’s built in a way that defies convention and best practice, and that comment is a pretty significant allowance for this plugin to accommodate that pattern already.

Apologies if this is coming off as harsh.
