### ISSUE TITLE
react/sort-comp strange behaviour

### ISSUE THREAD

**Issue by DonVit** [yannickcr/eslint-plugin-react#2248]
I receive the following `react/sort-comp` error

```
UNSAFE_componentWillReceiveProps should be placed after setAgreementStatusFormValue
``` 

where `setAgreementStatusFormValue` is not static method

According to description [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md )

the order should be like this

```
  order: [
    'static-methods',
    'lifecycle',
    'everything-else',
    'render'
  ],

```
my method `setAgreementStatusFormValue` is under group  'everything-else'

**Comment by ljharb** [comment]
`UNSAFE_componentWillReceiveProps` isn't a static method either, it's a lifecycle method.

What version of React are you using? Have you specified that in your eslintrc?

**Comment by DonVit** [comment]
@ljharb we specify `react: { version: 'detect' }` in our eslint config because  we share it between projects on different version of React

**Comment by ljharb** [comment]
ok, and which version of react is being used on this project?

**Comment by DonVit** [comment]
React version `16.8.6`

**Comment by max-lychko** [comment]
same +1

**Comment by ljharb** [comment]
Not sure if this is still an issue, but if so, please post repro code and the full eslint config, and we can reopen.
