### ISSUE TITLE
Definition for rule 'react/static-property-placement' was not found

### ISSUE THREAD

**Issue by epodivilov** [yannickcr/eslint-plugin-react#2249]
When I try to use [static-property-placement](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/static-property-placement.md) rule, I get the following error
> Definition for rule 'react/static-property-placement' was not found

Use like this
```
...
"react/static-property-placement": 2
...
```

Version in package.json
```
"eslint": "^5.16.0",
"eslint-plugin-react": "^7.12.4",
```

In node_modules no file with the description of this rule, but in github this file exist - [static-property-placement.js](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/static-property-placement.js)

Is this some kind of mistake or has this rule not been released yet?

**Comment by ljharb** [comment]
It's not been released yet. Check the docs on the latest tag, not on master.

**Comment by nzvtrk** [comment]
Can you notice about that in readme.md and rules/static-property-placement.md ?

**Comment by ljharb** [comment]
@nzvtrk since that’s how every GitHub project works (master can always be potentially unreleased), and since doing so would be a burden since we’d have to remove that notice for every tagged release, no.

**Comment by lostm1nd** [comment]
This rule seems no to work for me in version 7.13.0.
I have the following config for it:
```javascript
"react/static-property-placement": [
      "error",
      "static public field"
    ]
```
but no error is shown
<img width="493" alt="image" src="https://user-images.githubusercontent.com/6542890/58984410-b4aae200-87e1-11e9-83c7-51edf67a46d6.png">

**Comment by ljharb** [comment]
@lostm1nd that code has defaultProps as a static public field - what error would you expect?

**Comment by lostm1nd** [comment]
@ljharb my bad. I was misled by the name to think it will enforce placement inside class bodies but now I saw it states otherwise.
Any suggestion how to get the static field at the top of the class?

**Comment by ljharb** [comment]
@lostm1nd that's a different rule - https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md
