### ISSUE TITLE
jest switch broke appveyor

### ISSUE THREAD

**Issue by ljharb** [yannickcr/eslint-plugin-react#2253]
I'm not sure why we switched to jest; jest aggressively drops support for older nodes even faster than mocha.

Either way, the jest switch broke appveyor tests.

It'd be great to do this sort of thing by PR; dropping node 4 is unacceptable to me and I intend to revert it. No testing experience is worth dropping back compat support.

**Comment by yannickcr** [comment]
The drop of Node 4 compatibility is unrelated to the switch to Jest, but I will revert it for now so we can discuss it further.
