### ISSUE TITLE
Does "react/state-in-constructor" still make sense?

### ISSUE THREAD

**Issue by frederikhors** [yannickcr/eslint-plugin-react#2260]
Does "`react/state-in-constructor`" still make sense?

**Comment by ljharb** [comment]
It was only added last fall, so of course? It will forever make sense to me. Why do you think it wouldn’t?

**Comment by frederikhors** [comment]
Yes, but with https://github.com/yannickcr/eslint-plugin-react/commit/a312b16ea41203fc02054308f590f0e65784e2c3 is active in my projects. So until now it was turned off.

I think the default way should be without constructor anyway. What do you think?

**Comment by ljharb** [comment]
It should not, because class fields isn't part of the language yet - it's stage 3.

**Comment by frederikhors** [comment]
Ok. You're right, as always. I'm using babel, so. Thanks anyway. For me we can close.

**Comment by ljharb** [comment]
Even when it's in the language, folks may still have a style preference, so the rule won't stop making sense at any point.
