### ISSUE TITLE
Cannot find module 'eslint-plugin-react' in production

### ISSUE THREAD

**Issue by likeuwill** [yannickcr/eslint-plugin-react#2270]
Just for info. 
To fix issue, `"eslint-plugin-react": "^7.13.0"` should be added to the main `dependencies` instead of `devDependencies`.

P.S. With "react-scripts": "^2.1.8" all was fine, but starting from v.3 error was founded.

**Comment by ljharb** [comment]
Why would you be running the linter in production?? linters are a dev dep, and are never installed in production.

**Comment by likeuwill** [comment]
> Why would you be running the linter in production?? linters are a dev dep, and are never installed in production.

Yes, but...
https://stackoverflow.com/questions/54677395/error-failed-to-load-plugin-import-cannot-find-module-eslint-plugin-import-w

**Comment by ljharb** [comment]
ok - since that’s a problem with CRA and not this plugin (or the rest of the eslint-using ecosystem), and since that SO question answers it, I’m going to close this.
