### ISSUE TITLE
New rule: hook-dependencies

### ISSUE THREAD

**Issue by hornta** [yannickcr/eslint-plugin-react#2277]
This rule reports on missing dependencies in **useEffect, useMemo, useCallback and useLayoutEffect**. I believe by not specifying dependencies in hooks is for the worse because of unnecessary side-effects when props or state changes unexpectedly. It can also be a performance issue by recalculating memoized values.

```javascript
// invalid
function MyComp(props) {
  useEffect(() => { ... });
  ...
}

// valid
function MyComp(props) {
  useEffect(() => { ... }, []);
  ...
}

// valid
function MyComp(props) {
  useEffect(() => { ... }, [ props.foo ]);
  ...
}
```

**Comment by petersendidit** [comment]
Is this not covered by [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) `exhaustive-deps` rule?

**Comment by hornta** [comment]
@petersendidit `exhaustive-deps` allows having no second argument. My rule would not let this pass by forcing the programmer to specify dependencies.

```javascript
// exhaustive-deps thinks this is valid
function App(props) {
  useEffect(() => {
    if(props.foo) {
      ...
    }
  });
  ...
}
```

**Comment by ljharb** [comment]
That seems like a suggested modification to eslint-plugin-react-hooks, then?

**Comment by hornta** [comment]
I rephrased a new issue to eslint-plugin-react-hooks by adding an option to the exhaustive-deps rule

**Comment by ljharb** [comment]
Closing, pending the linked issue. Thanks!

**Comment by hornta** [comment]
It seems like they don’t want such a rule and closed it Immediately. https://github.com/facebook/react/issues/15660#issuecomment-493462498

**Comment by ljharb** [comment]
Given:
> I don't agree that dependencies should always be specified

it seems like perhaps it's best not to create this rule in general.
