### ISSUE TITLE
no-unused-prop-types: change reported node to property key

### ISSUE THREAD

**Issue by golopot** [yannickcr/eslint-plugin-react#2287]
The rule [no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md) currently reports the property **value** of the unused propType. I think it is more appropriate to report the property **key**.

```js
// current behavior
Foo.propTypes = {
  neverUsed: PropType.number,
//           ~~~~~~~~~~~~~~~
// PropType is defined but never used. 
}

// proposed behavior
Foo.propTypes = {
  neverUsed: PropType.number,
//~~~~~~~~~
// PropType is defined but never used. 
}
```

**Comment by ljharb** [comment]
Sounds like a great improvement.
