### ISSUE TITLE
`react/no-direct-mutation-state` in non-React code

### ISSUE THREAD

**Issue by jerrysu** [yannickcr/eslint-plugin-react#229]
Any way to limit `react/no-direct-mutation-state` to code executed in a React component context?

I happen to use `this.state` in other types of classes and receiving lint errors on this.

**Comment by jerrysu** [comment]
Awesome. Thanks! :+1:

**Comment by yannickcr** [comment]
Thanks to you for the bug report :)

It should be fixed in `v3.5.1`

**Comment by fand** [comment]
:+1:
