### ISSUE TITLE
react/prop-types: Can propTypes definitions exist in separate files?

### ISSUE THREAD

**Issue by fernandocamargo** [yannickcr/eslint-plugin-react#2307]
Normally I separate my components like this:

```
components/
├── demo/
│   ├── index.js
│   ├── render.js
│   └── statics.js
```

**index.js**
```
import { memo } from "react";

import render from "./render";
import * as statics from "./statics";

export default memo(Object.assign(render, statics));
```

**render.js**
```
import React from "react";

export default ({ foo, bar }) => (
  <dl>
    <dt>Foo: {foo}</dt>
    <dd>Bar: {bar}</dd>
  </dl>
);
```

**statics.js**
```
import { string, bool } from 'prop-types';

export const displayName = 'Demo';

export const propTypes = {
  foo: string.isRequired,
  bar: bool
};

export const defaultProps = {
  bar: false
};
```

Just to confirm, there's not much I can do to benefit from the `react/prop-types` rule, right?

**Comment by ljharb** [comment]
Nor from any static analysis with JavaScript, I’m afraid.

That organization seems strange to me anyways - the statics are tightly  coupled to the component, as are “is it memoized” and the render method - it doesn’t make any sense to me to separate them.

**Comment by fernandocamargo** [comment]
Yeah. It's unusual, I know. 🤣

I just like the idea of having small, concise modules. Other than that it could also favor the composition by other modules by importing these definitions.

For example:

**components/list/statics.js**
```
import { arrayOf, shape } from 'prop-types';

import { propTypes as Demo } from 'components/demo';

export const displayName = 'List';

export const propTypes = {
  items: arrayOf(shape(Demo))
};

export const defaultProps = {
  items: []
};
```

But thank you for your help!

**Comment by ljharb** [comment]
Sharing propTypes is awesome, and lots of small modules is great - but you wouldn’t separate your function’s signature, body, and return value into separate files, because together they form a single unit.

Closing, since this is answered. Good luck!
