### ISSUE TITLE
Consider making state-in-constructor fixable

### ISSUE THREAD

**Issue by markalfred** [yannickcr/eslint-plugin-react#2311]
I wrote a similar rule in [eslint-plugin-no-constructor-bind](https://github.com/markalfred/eslint-plugin-no-constructor-bind/blob/master/tests/lib/rules/no-constructor-state.js), and it will convert from state in constructor to state as class property:

```js
// Before Fix:
class myClass { 
  constructor() { 
    this.state = { foo: 'bar' } 
  } 
}

// After Fix:
class myClass { 
  constructor() {}

  state = { foo: 'bar' }
}
```

It only works in this direction, but I'm curious if folks might get some use out of making this rule fixable. The rule itself feels much better suited to eslint-plugin-react than to eslint-plugin-no-constructor-bind, so I'd be in favor of dropping it from my library and deferring to this one instead. But the fact that it's fixable makes it valuable for my use case.

It wasn't easy to write this fixing code, so it may not be worth the effort here — but I figured I'd throw it out here as a potential jumping-off point.

**Comment by ljharb** [comment]
The problem is that it's not actually safely autofixable in non-base-classes, because the former uses Set and the latter uses Define.

**Comment by markalfred** [comment]
👍 I had trouble making it "safe" and even [punted on complex state assignments](https://github.com/markalfred/eslint-plugin-no-constructor-bind/blob/master/tests/lib/rules/no-constructor-state.js#L31) as a result. So that makes sense, thanks for the quick reply @ljharb!
