### ISSUE TITLE
display-name triggered on default export using React.memo

### ISSUE THREAD

**Issue by mysport12** [yannickcr/eslint-plugin-react#2324]
This issue was originally reported by @jwalton in #2133. Confirmed that issue exists in 7.13.0 and 7.14.1 (we are not using typescript in our project).

> simple solution there, use a default export :-D

In latest build, this appears to be broken for a default export (although... I'm in a typescript project, so this *might* be a problem specific to linting .tsx files):

```ts
export default React.memo(function LabelControl(props: ControlProps) {
    const control = props.control as OnDemandLabelControl;

    return (
        <ControlWrapper>
            <Translate tagName="h2" message={control.title} />
        </ControlWrapper>
    );
});
```

triggers react/display-name, but:

```ts
function LabelControl(props: ControlProps) {
    const control = props.control as OnDemandLabelControl;

    return (
        <ControlWrapper>
            <Translate tagName="h2" message={control.title} />
        </ControlWrapper>
    );
}

export default React.memo(LabelControl);
```

does not.

_Originally posted by @jwalton in https://github.com/yannickcr/eslint-plugin-react/issues/2133#issuecomment-502449263_

**Comment by jwalton** [comment]
Thanks for confirming this was in vanilla js.  :)

**Comment by TrevorSayre** [comment]
Yep, I am getting the same error with something as simple as:

```jsx
export const Foo = React.memo(
    function Foo() {
        return <div>:(</div>;
    }
);
```

However, in the React dev tools, the component has the display name `Foo` just fine. If I use an arrow function instead, then there is no display name (just shows as `Component`) and the error would be correct.

**Comment by MrJohz** [comment]
I'm also getting this error with the `forwardRef` function (e.g. as in #2269, but without the same issues with propTypes).  I'm getting this when using named exports (e.g. `export const Foo = forwardRef(...)`) and with default exports (e.g. `export default forwardRef(...)`).

In all of these cases, as best I can see, the `forwardRef` and `memo` functions use the name of the wrapped component (or component-like).  Certainly, when I look in React DevTools, I can see the correct component name in all of these cases.

**Comment by danlugo92** [comment]
Still get the same issue as @TrevorSayre

**Comment by ljharb** [comment]
Please update to v7.17, released yesterday, and file a new issue if you’re still having trouble.

**Comment by SmirnovW** [comment]
Hi There,

I'm getting the same problem, the version is 7.18.0

**Comment by ljharb** [comment]
@SmirnovW please file a new issue
