### ISSUE TITLE
Indentation issue on element with 'role' and 'aria-label' attributes

### ISSUE THREAD

**Issue by rfgamaral** [yannickcr/eslint-plugin-react#2337]
Assuming this minimal `.eslintrc` configuration:

```json
{
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "plugins": [
      "react"
    ],
    "rules": {
      "react/jsx-indent": ["error", 2]
    }
  }
```

Take the following example:

**`index.jsx`**

```jsx
function Application() {
    return (
        <div>
            <div>
                <div>
                    <div>
                        <span>
                            👋
                        </span>
                    </div>
                </div>
            </div>
        </div>
    );
}
```

Running `yarn eslint --fix index.jsx` on the command line formats the file into this:

```jsx
function Application() {
    return (
      <div>
        <div>
          <div>
            <div>
              <span>
                            👋
              </span>
            </div>
          </div>
        </div>
      </div>
    );
}
```

Every `<div>` was properly indented to 2 spaces, except the content of `<span role="img" aria-label="Waving Hand">`.

Is this a bug of some sort? Is there a workaround?

**Comment by yannickcr** [comment]
This is the same issue as https://github.com/yannickcr/eslint-plugin-react/issues/2318, you can see the explanation in https://github.com/yannickcr/eslint-plugin-react/issues/2318#issuecomment-504773825

AFAIK there is no workaround for now.

I will close this issue as duplicate but you can continue the conversation in #2318.
