### ISSUE TITLE
Add exception option in jsx-curly-newline for object literals

### ISSUE THREAD

**Issue by UncleClapton** [yannickcr/eslint-plugin-react#2344]
Hello!

Like `react/jsx-curly-spacing`, it would be nice if there was an option to specify newline behavior for object literals (or other specific types of contents) in JSX.

For example, the config:
```javascript
'react/jsx-curly-newline': ['error', {
  multiline: 'require',
  singleline: 'forbid',
}],
```
requires the following:
```jsx
<Transition
  { ...transitionProps }
  config={
    {
      clamp: true,
      friction: 25,
      tension: 350,
    }
  }>
  {
    (item) => (style) => (
      <animated.div style={ style }>
        { this.props.children(item) }
      </animated.div>
    )
  }
</Transition>
```
However I would like to express object literals like the following example, while also forcing any other types of multiline values to have newlines:
```jsx
<Transition
  { ...transitionProps }
  config={{
    clamp: true,
    friction: 25,
    tension: 350,
  }}>
  {
    (item) => (style) => (
      <animated.div style={ style }>
        { this.props.children(item) }
      </animated.div>
    )
  }
</Transition>
```

Right now I am using `multiline: consistent` to allow this, but it has the downside of allowing blocks like:
```jsx
  { (item) => (style) => (
      <animated.div style={ style }>
        { this.props.children(item) }
      </animated.div>
  ) }
```

which is something I don't want allowed.

**Comment by ljharb** [comment]
If you're going for consistency, why would you want object literals and functions to be different?

**Comment by UncleClapton** [comment]
I wasn't exactly going for consistency as much as I was trying to remove new lines that I saw as superfluous.

However now that you've mentioned it, the inconsistency would make things more confusing to those who don't see it the same way. Thanks, I didn't consider that!

I suppose this could be closed unless someone else wants this feature.

**Comment by ljharb** [comment]
I'll close it for now, unless later comments provide good reason not to.

**Comment by vescogma** [comment]
I know this is closed already, but I'd like to add my vote in for this. The react plugin already allows for specific object-curly-newline rules, which differs from func newlines, etc. I'd like to be able to differentiate between newlines in JSX expressions; I use a lot of conditionals to display certain things and find the pattern more readable, while finding the same spacing on an object attribute useless. Maybe it would be nice to have a different rule for each?

**Comment by derekjobst** [comment]
I would also advocate for this change. In the case of object literals there are two additional lines of just an opening/closing curly bracket that are unnecessary.
```javascript
config={
    {
      clamp: true,
      friction: 25,
      tension: 350,
    }
  }
```
The advantage of this rule is the separation of prop content and prop key onto different lines. Right now the only way to get this benefit without superfluous whitespace would be `require` for functions and `forbid` for object literals.

The `consistent` option is great, but allows for function blocks like the last one @UncleClapton mentioned in the issue. A fourth option to permit same-line curly braces on object literals and forbid all other usages would allow for this terse yet clear style.
