### ISSUE TITLE
[feature] react/jsx-sort-default-props is not fixable ?

### ISSUE THREAD

**Issue by sixclones** [yannickcr/eslint-plugin-react#2347]
I'm curious about the fact that the rule [`react/jsx-sort-props`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md) is fixable but not [`react/jsx-sort-default-props`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-default-props.md). Is there a reason ? Is it possible to make it fixable ?

**Comment by yannickcr** [comment]
I don't think there is any blocker that prevents us to make it fixable, it's more that no one took the time to write a fix function for it yet.

**Comment by ljharb** [comment]
Note that auto fixing of any object key sorting rule is impossible to safely cover all cases, because it is not safe to sort across a spread boundary - any autofix must only sort groups of properties that are unbroken by a spread.
