### ISSUE TITLE
Allowing use of the index in combination with other data  react/no-array-index-key

### ISSUE THREAD

**Issue by tomprats** [yannickcr/eslint-plugin-react#2356]
This is similar to why https://github.com/yannickcr/eslint-plugin-react/pull/1124 was added but I was wondering if it'd be possible to update this rule instead of just to disable it. Here's an example:

```
names = ["Tom", "Joe", "Tim", "Tom"];
names.map((name, index) => (<li key={`${name}-${index}`}>{name}</li>));
```

In a list like this, sometimes the data isn't unique by itself, but it is when combined with it's position.

Would it be possible to update the rule to allow cases like this?

**Comment by ljharb** [comment]
If you're using the index, then using other data adds *zero* value - just use the index. If you can only use the other data, then don't use the index.
