### ISSUE TITLE
Is it possible to use jsx-sort-props for components only?

### ISSUE THREAD

**Issue by Dakkers** [yannickcr/eslint-plugin-react#2362]
I'd like to use jsx-sort-props, but not for regular HTML elements, only React components. Is such a thing possible? 😮

**Comment by ljharb** [comment]
Why would you want HTML elements and custom component elements to be treated differently?

**Comment by Dakkers** [comment]
Because I don't care to put in the effort for regular HTML tags, while a
lot of component tags are multiline

**Comment by ljharb** [comment]
What effort? The rule is autofixable.
