### ISSUE TITLE
no-unused-prop-types exceptions

### ISSUE THREAD

**Issue by kimihiro64** [yannickcr/eslint-plugin-react#2373]
Feature Request/Question

Is it possible to exempt a defined propType from tripping this rule other than a lint comment? Use case is react-native + react-navigation HOC injected navigation prop. I want to always have it in the propTypes because it's useful to know if it /wasn't/ passed in indicating a bug, but not every screen actually need to use it (or hasn't been developed enough to use it yet).

**Comment by ljharb** [comment]
If a screen/component doesn’t need to use it, why is it useful to know it wasn’t passed?

**Comment by kimihiro64** [comment]
It might need it down the road. For the most part I want it as a marker that the component will have the prop when I need it, and every screen in react navigation should have it, so it can key you in early if you did something wrong if you mark it as a required prop. Similar to why I leave stubbed lifecycle functions that do nothing with their parameters, since they're effectively implementing an interface.

**Comment by kimihiro64** [comment]
Another use case, sometimes I use utility functions that operate on a component assuming it has access to navigation, so in rare cases even though the navigation prop gets used by that prop, it happens in utility logic in another file, which can't be detected by the linter.

**Comment by ljharb** [comment]
There’s a software engineering principle called YAGNI - iow, if you don’t need it now, don’t code it now.

In other words, until it’s needed, it’s a bug if it *is* passed.

**Comment by ljharb** [comment]
For those other cases; never pass around a props, state, or context object - always always destructure out what you need and pass *that* - both for clarity and for static analysis.

**Comment by jwhiddent3** [comment]
Fair enough, but I do think that knowing that some other source is going to inject a prop whether a component uses it or not is grounds to include it in the proptypes. Plenty of other lint rules use a pattern to ignore specific things that would usually be a violation but in that case we don't care.

**Comment by ljharb** [comment]
I'd suggest using https://npmjs.com/prop-types-exact or the equivalent on all your components; an extra prop should be considered a bug.
