### ISSUE TITLE
react/jsx-wrap-multilines add an option that requires to use React.Fragment instead of parentheses

### ISSUE THREAD

**Issue by gajus** [yannickcr/eslint-plugin-react#2376]
I don't see what is stylistic advantage of writing this:

```js
return (
  <PrimaryHeading>
    Event Seating Lookups
  </PrimaryHeading>
);

```

over:

```js
return <PrimaryHeading>
  Event Seating Lookups
</PrimaryHeading

```

Assuming developers want to align the attributes, then a better choice would be to use React.Fragment syntax, i.e.

```js
return <>
  <PrimaryHeading>
    Event Seating Lookups
  </PrimaryHeading
</>;

```

The benefit of this approach is that I can add a new element at the same depth without modifying the surrounding code.

**Comment by ljharb** [comment]
- the parens reinforce that jsx produces a single expression value
 - the indentation ends up looking nicer and being properly aligned
 - the fragment case costs performance and isn’t more readable, whereas the parens offer the same benefits without the downsides
 - your example is very misaligned and hard to read, which has led to confusion and bugs in the past - which is why the airbnb guide requires the parens on multiline jsx.

**Comment by gajus** [comment]
![oaky](https://user-images.githubusercontent.com/973543/62551573-2942e100-b864-11e9-8b7e-b5df00699101.png)

**Comment by ljharb** [comment]
The non-fragment example.

**Comment by gajus** [comment]
> the parens reinforce that jsx produces a single expression value

This is not a benefit.

This means that I need to add another element, I will need to change the surrounding code.

i.e. I cannot go from:

```js
return (
  <PrimaryHeading>
    Event Seating Lookups
  </PrimaryHeading>
);

```

to

```js
return (
  <PrimaryHeading>
    Event Seating Lookups
  </PrimaryHeading>
  <DebugThis />
);

```

I have to do:

```js
return <>
  <PrimaryHeading>
    Event Seating Lookups
  </PrimaryHeading>
  <DebugThis />
</>;

```

In order to understand your argument better, please name one example where it is relevant to know that a variable holds/ component returns a single React element vs React fragment and what kind of bugs it would lead to.

> the indentation ends up looking nicer and being properly aligned
> your example is very misaligned and hard to read, which has led to confusion and bugs in the past - which is why the airbnb guide requires the parens on multiline jsx.

This is referring to:

```js
return <PrimaryHeading>
  Event Seating Lookups
</PrimaryHeading

```

Not to:

```js
return <>
  <PrimaryHeading>
    Event Seating Lookups
  </PrimaryHeading
</>;

```

(This was not clear.)

> the fragment case costs performance and isn’t more readable, whereas the parens offer the same benefits without the downsides

It is just as much readable as parens approach and it has the benefit of avoiding unnecessary time refactoring code.

**Comment by ljharb** [comment]
Changing from returning 1 element to 2 is a major change; that should not be an easy refactoring because it’s not a refactor, it’s a conceptual semver-major change to your component’s api (obv the fragment makes it be not major, but, conceptual).

**Comment by ljharb** [comment]
Any component that used React.Children.only - which are legion in the ecosystem - can only accept one child.
