### ISSUE TITLE
react/react-in-jsx-scope raises issue when using ReactDOM or ReactDOMServer

### ISSUE THREAD

**Issue by jeffcharles** [yannickcr/eslint-plugin-react#238]
In React 14.0, ReactDOM and ReactDOMServer are used to render JSX. The react-in-jsx-scope rule raises an error even though all I'm doing is rendering a react component and not defining one.

**Comment by jeffcharles** [comment]
Nevermind, I misread the React documentation

**Comment by Kerumen** [comment]
Please reopen it, I faced this issue too. I only want to render a React component and I'm doing it like this:

    import ReactDOM from 'react-dom';
    import Component from './component';

    ReactDOM.render(<Component />, node);

To avoid the error I must write `import React from 'react-dom';` which is not common..

**Comment by yannickcr** [comment]
JSX is still expanding to `React.createElement`, even in 0.14, so React is needed.

The linter is right and you have an error :)

**Comment by Kerumen** [comment]
I noticed my mistake and deleted my message but you answered before, ups!
