### ISSUE TITLE
Error while configuring react/jsx-props-no-spreading

### ISSUE THREAD

**Issue by Solavon** [yannickcr/eslint-plugin-react#2387]
While setting up my eslint rules, I ran into some issues when configuring jsx-props-no-spreading

**Expected:**
Allow props spreading when the following rule is set 
```
'react/jsx-props-no-spreading': ['error', {
      html: "ignore",
      custom: "ignore",
      exceptions: [],
    }],
```

**Actual:**
Getting the following error

> Error: .eslintrc.js:
>         Configuration for rule "react/jsx-props-no-spreading" is invalid:
>         Value {"html":"ignore","custom":"ignore","exceptions":[]} should NOT be valid.

**Package versions:**
```
"eslint": "^6.2.0",
"eslint-plugin-react": "^7.14.3",
```

**Comment by ljharb** [comment]
This is intentional; there's no point in using the rule if you're ignoring everything and have no exceptions: https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-props-no-spreading.js#L48-L63

If you add an exception, or change one of the ignores to "enforce", it should work.

**Comment by Solavon** [comment]
I understand that it would be pointless, but unfortunately it's part of the airbnb rules that comes with its extension, in any case, after keeping it for a while I can already see its benefit, thank you!

**Comment by ljharb** [comment]
The airbnb config doesn’t ignore both kinds of components.

**Comment by Solavon** [comment]
No, as in, this rule came as part of the airbnb config, and I was trying to turn it off.

**Comment by ljharb** [comment]
Set it to "off" then :-)

**Comment by Solavon** [comment]
Thanks for teaching me that :P

**Comment by MichaelPretorius** [comment]
How do u switch it to off?

**Comment by MichaelPretorius** [comment]
No worries got it, thanks

**Comment by sadafk831** [comment]
Just for the record:
If you wish to use the rule and wish to ignore instead of setting it `off`. This is how you should use:
In the rule definition, all the fields are made compulsory and specially `exceptions` is suppose to have an array of string not empty, so the declaration of rules goes like follow
```
'react/jsx-props-no-spreading': ['error', {
      html: "ignore",
      custom: "ignore",
      exceptions: [""],
    }],
```

For setting it off you can use either any of the following
```
'react/jsx-props-no-spreading': ['off']
```
```
'react/jsx-props-no-spreading': 0
```

**Comment by AdamAnSubtractM** [comment]
This may seem obvious to most people but wasn't to me, this can be set up in an `eslintrc.json` or `eslintrc.js` file or in your package.json file by adding a rules object like so:

`"rules": {
      "react/jsx-props-no-spreading": 0
    }`

**Comment by imflavio** [comment]
```json
"rules": {
      "react/jsx-props-no-spreading": [
        "error",
        {
          "explicitSpread": "enforce",
          "html": "ignore",
          "custom": "ignore",
          "exceptions": []
        }
      ]
    }
```

```
Configuration for rule "react/jsx-props-no-spreading" is invalid:
	Value {"explicitSpread":"enforce","html":"ignore","custom":"ignore","exceptions":[]} should NOT be valid.
```

This doesn't work for some reason.. What am I missing? @ljharb

**Comment by ljharb** [comment]
the rule does not allow an empty exceptions array: https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-props-no-spreading.js#L66

**Comment by nix6839** [comment]
@ljharb I want to use only explicitSpread. But an error occurs. Is there another way?
```js
"rules": {
        'react/jsx-props-no-spreading': [
            'error',
            {
                html: 'ignore',
                custom: 'ignore',
                explicitSpread: 'enforce',
            },
        ],
}
```

```txt
Configuration for rule "react/jsx-props-no-spreading" is invalid:
Value {"html":"ignore","custom":"ignore","explicitSpread":"enforce"} should NOT be valid.
```

**Comment by ljharb** [comment]
@nix6839 update the to latest version of the plugin.

**Comment by divmgl** [comment]
Back in 2024 and this is not working:

```
    "react/jsx-props-no-spreading": [
      "error",
      {
        html: "ignore",
        custom: "ignore",
        explicitSpread: "enforce",
      },
    ],
```

I want to specifically _only_ ban `explicitSpread`. Is there any way to do this? Unfortunately, I'm getting 

```
Error: .eslintrc.cjs:
        Configuration for rule "react/jsx-props-no-spreading" is invalid:
        Value {"html":"ignore","custom":"ignore","explicitSpread":"enforce"} should NOT be valid.
```

**Comment by ljharb** [comment]
@divmgl what version of the plugin are you using?

**Comment by divmgl** [comment]
`7.31.11`

**Comment by divmgl** [comment]
Just updated to latest and it's still occurring unfortunately.

**Comment by ljharb** [comment]
@divmgl that's pretty ancient :-), but the [docs](https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.31.11/docs/rules/jsx-props-no-spreading.md#explicitspread) for that version imply it should still be working even without the upgrade (it's still wise to upgrade). Can you file a new issue with a test case that reproduces the problem?

**Comment by divmgl** [comment]
Sure!

**Comment by divmgl** [comment]
@ljharb https://github.com/jsx-eslint/eslint-plugin-react/issues/3799
