### ISSUE TITLE
conflict between jsx-no-literals and jsx-curly-brace-presence?

### ISSUE THREAD

**Issue by kud** [yannickcr/eslint-plugin-react#2389]
```{apiText.isErrored() && <div>💥, API error!</div>}``` -> jsx-no-literals

vs

```{apiText.isErrored() && <div>{`💥, API error!`}</div>}``` ->  jsx-curly-brace-presence

**Comment by ljharb** [comment]
Certainly there's a way to configure them so they're in conflict; unless this works with normal quotes (as opposed to backticks), i think this is working as designed.

**Comment by kud** [comment]
To be fair, I don't understand why it's saying "curly brace is not needed" here?

**Comment by ljharb** [comment]
curly-brace-presence when set to "never" warns whenever you can remove the curlies and the same thing will be rendered. That's the case here.

**Comment by kud** [comment]
I see! Thanks!
