### ISSUE TITLE
False positive for script tags in html

### ISSUE THREAD

**Issue by illfittingshoes** [yannickcr/eslint-plugin-react#239]
ESLint with this plugin seems to treat &lt;script&gt; tags in HTML files as JSX (maybe other tags with "child" content, but I don't know - I haven't done very extensive testing).

![eslint-jsx-html-script-errors](https://cloud.githubusercontent.com/assets/3780063/10370857/c97a3844-6dae-11e5-87c7-b1f57b044d56.png)

Relevant section of .eslintrc:
{
	"env": {
		"es6": true,
		"node": true,
		"browser": true,
		"mocha": true
	},
	"ecmaFeatures": {
		"modules": true,
		"jsx": true,
		"regexYFlag": true,
		"regexUFlag": true
	},
	"plugins": [
		"react"
	]
}

I haven't set any JSX/React rules, only vanilla ESLint ones. My sublime-linter config is also unmodified.

edit: installed versions
Node: 4.1.2
NPM: 3.3.6
ESLint: 1.6.0
eslint-plugin-react: 3.5.1

**Comment by yannickcr** [comment]
Seems you are trying to lint an HTML file with ESLint, well, this not gonna work :)

Maybe [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html) is what you're looking for.

Closing this issue since this has nothing to do with eslint-plugin-react
