### ISSUE TITLE
Incorrect formatting with --fix for JSX with missing parentheses (jsx-wrap-multilines)

### ISSUE THREAD

**Issue by feross** [yannickcr/eslint-plugin-react#2390]
**What version of this package are we using?**

7.14.3

**What operating system, Node.js, and npm version?**

macOS 10.14.5
node v12.8.0
npm 6.10.2

**What happened?**

It appears that `jsx-wrap-multilines` has an issue when used with `eslint --fix`. Specifically, the following happens"

Original code:

```
const Component = () =>
  <div>
    <p>Some text</p>
  </div>

export { Component as default }
```

Formatted code:

```
const Component = () => (
<div>
    <p>Some text</p>
  </div>
)export { Component as default }
```

**What did you expect to happen?**

I expected the export statement to be on a newline. Something strange is going on with the JSX formatting.

Related issue: https://github.com/standard/standard/issues/1382

**Comment by ljharb** [comment]
Good catch; the rule was probably authored assuming semicolon usage, since that's what's most common. This definitely should be fixed.
