### ISSUE TITLE
react/jsx-pascal-case incorrectly flags `$` as not being in pascal case

### ISSUE THREAD

**Issue by Haegin** [yannickcr/eslint-plugin-react#2394]
I have a component named `$` and the `react/jsx-pascal-case` rule is saying that it's not in pascal case. As $ is a symbol and not upper or lowercase letter, this shouldn't be an error.

**Comment by Haegin** [comment]
@ljharb it's just `$`. We use it for formatting currency values.

`<$>{price}</$>`

**Comment by ljharb** [comment]
Fascinating. I certainly think a standalone character of any kind should be permitted by the rule; so maybe just "bail out if the component name has 1 code point"?
