### ISSUE TITLE
Some help with react/jsx-props-no-spreading and styled-components

### ISSUE THREAD

**Issue by wight554** [yannickcr/eslint-plugin-react#2397]
Anyone can give some guidance of writing an jsx-props-no-spreading exception for styled-components
For example the following component:
```
function FormInput({ label, type, input, meta: { touched, error } }) {
  return (
    <ControlWrapper>
      <label htmlFor={input.name}>
        <LabelText>{label}</LabelText>
      </label>
      <Input {...input} type={type} placeholder={label} />
      {touched && error && <ErrorText>{error}</ErrorText>}
    </ControlWrapper>
  );
```
Passes props to the following Input styled component:
```
const Input = styled.input`
  font-size: ${props => props.theme.fontSize1};
`;
```
This doesn't seem to be antipattern to me cause Input isn't react component(afaik)
So now I'm here asking for help c:
The only idea I had was to ignore *Style components but that's not the only declaration of those

**Comment by wight554** [comment]
Actually i misunderstood the concept, the issue is related to redux form, not to styled components(When I read the doc for the first time I thought html tags props spreading is allowed)
Is it fine to disable the error or there might be some workaround?
That's the only possible way of using custom components in redux form fields afaik

**Comment by ljharb** [comment]
You don’t have to spread the props, you could explicitly reference them.
