### ISSUE TITLE
react/react-in-jsx-scope to detect jsxFactory in tsconfig

### ISSUE THREAD

**Issue by BasixKOR** [yannickcr/eslint-plugin-react#2403]
In addition to `@jsx` comments, I think detecting `jsxFactory` option in [TypeScript compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) could improve its usability.

Although it would be hard to encounter every single usage of TypeScript compiler options, covering general usages (such as `tsconfig.json`) could be enough for most cases.

**Comment by ljharb** [comment]
This seems like the sort of thing that you can easily configure in your eslint config manually. It's not really appropriate for an eslint plugin to read any settings besides eslint settings, or the contents of the files it's linting.
