### ISSUE TITLE
react/jsx-no-bind: Dealing with the state hook

### ISSUE THREAD

**Issue by kdex** [yannickcr/eslint-plugin-react#2430]
Let's assume that we have a functional (yet stateful) component like,

```js
const Button = () => {
	const [text, setText] = useState("Text A");
	const onClick = () => setText("Text B");
	return (
		<button onClick={ onClick }>{ text }</button>
	);
};
```

With `react/jsx-no-bind`, this use of `onClick` is forbidden, as it will create a new binding to `onClick` on every render.

We can't really move it out of the function either, like so:

```js
const onClick = setText => setText("Text B");
const Button = () => {
	const [text, setText] = useState("Text A");
	return (
		<button onClick={ onClick }>{ text }</button>
	);
};
```

Now, `onClick` has no chance to receive the correct `setText` parameter, as we can't control this without `.bind` or creating a new binding for `onClick` on every render by other means.

This makes me wonder if, despite its usefulness, React's state hook is just wasteful with memory to begin with, or whether I've overlooked something.

Is there a way to avoid this situation with the state hook?

**Comment by kdex** [comment]
I'll be giving an answer to my own question. This is achievable by doing event handling manually. That is, use both React's `useEffect` as well as its `useRef` hook and declare the `Button` like so:
```js
const Button = () => {
	const reference = useRef();
	const [text, setText] = useState("Text A");
	useEffect(() => {
		const onClick = () => setText("Text B");
		reference.current.addEventListener("click", onClick);
		return () => {
			reference.current.removeEventListener("click", onClick);
		};
	}, []);
	return (
		<button ref={ reference }>{ text }</button>
	);
};
```

Unfortunately though, the code has become less readable as this involves quite a bit of boilerplate.

I'm leaving this issue open just so that, if the maintainers know of a cleaner way to do this, they can add another answer before this is closed. (Otherwise, just close it.)

**Comment by kdex** [comment]
An even better solution that removes all boilerplate can be achieved by memoizing the function, which can be done using the [useCallback](https://reactjs.org/docs/hooks-reference.html#usecallback) hook.

**Comment by draperunner** [comment]
@kdex Does `jsx-no-bind` stop complaining if you're using `useCallback`? If that's the case I think the [docs for this rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md) should be updated with hooks examples. It should probably be updated with some mention about function components anyhow.

**Comment by kdex** [comment]
@draperunner Thanks a bunch for getting back to me despite this issue being closed, and yes, `jsx-no-bind` stops complaining if used with `useCallback`. :)

**Comment by ljharb** [comment]
a PR to update the docs to add hooks examples seems very useful.
