### ISSUE TITLE
False positivie on "jsx-no-useless-fragment"

### ISSUE THREAD

**Issue by kud** [yannickcr/eslint-plugin-react#2432]
```
                 {state.filtersExpanded ? (
                    <>{`Refermer les filtres`}</>
                  ):(
                    <>{`Filtrer les amendements`}</>
                  )}
```

If I remove them:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/655838/66040612-39033c80-e518-11e9-9ffc-545a90930e0f.png">

**Comment by golopot** [comment]
How about 
```js
<Text>
  {state.filtersExpanded ? (
    <>Refermer les filtres</>
  ) : (
    <>Filtrer les amendements</>
  )}
</Text>;
```

**Comment by kud** [comment]
Not the first one because eslint requires `jsx-no-literals` :)

But the second one could work yeah.

**Comment by ljharb** [comment]
The second one is the proper fix - when removing wrapping jsx, you have to be aware to remove the jsx-only curly braces as well.

That doesn't seem to be an autofix, so I'm going to close this, but happy to reopen if indeed there's something actionable here.

**Comment by kud** [comment]
Okay thank you :)
