### ISSUE TITLE
More clarification when not to use react/react-in-jsx-scope (Next.js)

### ISSUE THREAD

**Issue by NeatNit** [yannickcr/eslint-plugin-react#2440]
I think the doc page for react/react-in-jsx-scope should better detail when this rule is not to be used. For example, Next.js imports React when compiling so you don't need to do it yourself, but it doesn't *technically* "set `React` as a global variable" like described under "When Not To Use It".

**Comment by ljharb** [comment]
It's worth a mention, but there's still value in *not* doing what Next.js does, and explicitly importing React in every file.

**Comment by NeatNit** [comment]
That would be worth adding then. I'd like to know why, too...

**Comment by ljharb** [comment]
Because explicit > implicit, and relying on implicitly added globals is magic that makes it harder for new users to understand what's going on.

**Comment by foray1010** [comment]
@ljharb While I totally agree explicit > implicit, [babel v8 will automatically import react](https://blog.logrocket.com/whats-coming-in-babel-8/), it brings benefit to automatically decide whether to import from `react/jsx-runtime` or not, as a better replacement of `React.createElement()`.

I think it is a new angle to the issue. Should we reconsider to update documentation and also recommended config?

**Comment by ljharb** [comment]
That's still an RFC, and very much not a certainty (that post isn't from babel or react, ftr), and either way that's a long way off.

At the moment, you should *always* have `React` in scope when you're using jsx and react.

**Comment by karlhorky** [comment]
I guess the Babel 8 + React change to automatically import React with the new JSX transform is getting closer to reality:

https://babeljs.io/blog/2020/03/16/7.9.0#a-new-jsx-transform-11154-https-githubcom-babel-babel-pull-11154

In case this keeps going this way, it may make sense at some point in the next year or two to re-evaluate this rule.

**Comment by karlhorky** [comment]
Looks like it's getting more real (besides Gatsby and Next.js, CRA v4 will support it, and the change will also be backported to React 0.14.x, 15.x, and 16.x):

https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Comment by ljharb** [comment]
If you're using react 17, you'd simply disable this rule. As soon as React 17 is fully released, we'll update the docs page.
