### ISSUE TITLE
--fix removes curly bracket space after html

### ISSUE THREAD

**Issue by RyanPWalker** [yannickcr/eslint-plugin-react#2441]
I just upgraded from `"eslint": "^6.1.0", "eslint-plugin-react": "^7.14.2"` to `"eslint": "^6.5.1", "eslint-plugin-react": "^7.15.1"`.

Running `yarn eslint ./src --fix` removes any instance of a `{' '}` since a new line now creates a space in React jsx like:
```
<div>
    Hello
    {' '}
    World
</div>
> Hello World
```
--fix now changes to:
```
<div>
    Hello
    World
</div>
> Hello World
```
But if I have html within that, it removes the space and the newline does not create a space.   For example:
```
<div>
    Hello<sup>*</sup>
    {' '}
    World
</div>
> Hello* World
```
--fix now changes to:
```
<div>
    Hello<sup>*</sup>
    World
</div>
> Hello*World      (missing space)
```

I suspect this breaking change caused this https://github.com/yannickcr/eslint-plugin-react/pull/2422

**Comment by ljharb** [comment]
This will be fixed in #2437.
