### ISSUE TITLE
Correct syntax for doublequote in text inside a tag and <br> inside text?

### ISSUE THREAD

**Issue by Andy-QT** [yannickcr/eslint-plugin-react#2447]
> ## Context
> Package	Version
> eslint	~6.5.1
> eslint-plugin-react	~7.16.0

**1. " - syntax**

Currently i have to write:
```
<Typography component="p">
	well meaning and kindly.<br />&quot;a benevolent smile&quot;
</Typography>
```

in a previous version i could write

```
<Typography component="p">
	well meaning and kindly.<br />
	{'"a benevolent smile"'}
</Typography>
```

<br /> must be placed in the same line as the other text 
With Disabled rule: react/jsx-one-expression-per-line

**2. How to write &lt;br /&gt; between text**

With <br /> in a new line, this error appears: 
Ambiguous spacing after previous element br eslint(react/jsx-child-element-spacing) 
Error is before an after <br />

Example:

With error:
```
<Typography component="p">
	well meaning and kindly.
	<br />
	&quot;a benevolent smile&quot;
</Typography>
```

Without error:
```
<Typography component="p">
	well meaning and kindly.
	<br />
	{' '} 
	&quot;a benevolent smile&quot;
</Typography>
```

Not working conclusion:
```
<Typography component="p">
	well meaning and kindly.
	<br />
	{'\"a benevolent smile\"'} <- error: Unnecessary escape character: \".eslint(no-useless-escape)  
</Typography> 
```

The markup example comes from material-ui
[https://material-ui.com/components/cards/#simple-card](https://material-ui.com/components/cards/#simple-card)

![material-ui-cards](https://user-images.githubusercontent.com/2870154/66254282-85e34f00-e774-11e9-97b3-225e9f54e21e.jpg)

**Comment by ljharb** [comment]
You don’t need to escape double quotes inside single quotes.

**Comment by Andy-QT** [comment]
> You don’t need to escape double quotes inside single quotes.

ok, but this versions leads to an error

error: Ambiguous spacing after previous element br eslint(react/jsx-child-element-spacing)
```
<Typography component="p">
    <br />
    &quot;a benevolent smile&quot;
</Typography>
```

error: 
- Ambiguous spacing after previous element br eslint(react/jsx-child-element-spacing)
- `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.eslint(react/no-unescaped-entities)
```
<Typography component="p">
    <br />
    "a benevolent smile"
</Typography>
```

error: 
- Curly braces are unnecessary here. eslint(react/jsx-curly-brace-presence)
- Strings must use singlequote. eslint(quotes)
```
<Typography component="p">
    <br />
    {"a benevolent smile"}
</Typography>
```

error:  
- Curly braces are unnecessary here.eslint(react/jsx-curly-brace-presence)
```
<Typography component="p">
    <br />
    {'"a benevolent smile"'}
</Typography>
```

**Comment by ljharb** [comment]
Hmm. Have you tried?:
```jsx
<Typography component="p">
    <br />{"a benevolent smile"}
</Typography>
```
or
```jsx
<Typography component="p">
    <br />&quot;a benevolent smile&quot;
</Typography>
```
?

**Comment by Andy-QT** [comment]
1.
![image](https://user-images.githubusercontent.com/2870154/66485618-6c5e4200-eaa9-11e9-8970-ec0a70ce114c.png)

2.
HTML entities works, but it is not very good to read

**Comment by ljharb** [comment]
In that example, you certainly don't need any curly braces - you'd do `well meaning and kindly.</br />a benevolent smile`
