### ISSUE TITLE
Support fixable flag from esLint

### ISSUE THREAD

**Issue by carlosmmelo** [yannickcr/eslint-plugin-react#245]
With the latest version of eslint, they added the support to automatically fix errors with the [fixable](https://github.com/eslint/eslint/blob/9a58b2494b7850a69c84c29540012f87c080a5a8/docs/rules/README.md#rules) flag on the rules and passing the `--fix` thru the cli.

Are you planning to add support to this on your rules by any chance? this is a nice feature to automatically fix the most obvious and easy ones. at least.

Thanks

**Comment by yannickcr** [comment]
Yes, I'm planning to add support for the fixable flag, at least for formating rules.

But PR are welcome ;)

**Comment by lencioni** [comment]
There are a number of rules that are autofixable now. This issue can probably be closed out.
