### ISSUE TITLE
React es6 class extends instead of es5 createClass

### ISSUE THREAD

**Issue by hamiltondanielb** [yannickcr/eslint-plugin-react#247]
Is there a way to enforce

`class PageManager extends Component {...}`

instead of

`module.exports = React.createClass({...})`

I apologize if I missed something, but I can't seem to find anything about this

**Comment by yannickcr** [comment]
Sorry, there is no rule for this right now, but it could be added.

**Comment by hamiltondanielb** [comment]
OK thanks, I'm going to fork and give it a shot.
