### ISSUE TITLE
False positive with no-unused-state

### ISSUE THREAD

**Issue by shengpinghu** [yannickcr/eslint-plugin-react#2475]
I'm getting a false positive:

[eslint] Unused state field(react/no-unused-state)

when using the following:
![image](https://user-images.githubusercontent.com/16096712/67736069-2c9fd000-fa41-11e9-926c-425afa6bf71b.png)

Is there a way to bypass this warning? (I'm using the latest version).

The following will bypass it:

![image](https://user-images.githubusercontent.com/16096712/67736092-49d49e80-fa41-11e9-9b67-a798b8854f14.png)

Thanks

**Comment by ljharb** [comment]
For one, using .map but not using the return array makes no sense; use .forEach

Second, don’t dynamically access props or state - explicitly destructure each one, and the warning won’t appear.

If you insist on keeping your current approach, use an eslint override comment.
