### ISSUE TITLE
Rename ignoreStateless

### ISSUE THREAD

**Issue by emlai** [yannickcr/eslint-plugin-react#2481]
Consider renaming [react/no-multi-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-multi-comp.md)'s `ignoreStateless` option, since function components can now have state. It could be renamed to e.g. `ignoreFunctionComponents`.

This would be a breaking change so probably best to leave support for the `ignoreStateless` name for  backwards compatibility, but deprecate it.

**Comment by ljharb** [comment]
`useState` is not, in fact, a function component having state; it's conceptually something else :-)

I don't see much value in renaming it when "SFC" will remain a community-used and understood term for years.

**Comment by ljharb** [comment]
I don't think this is worth the churn.

**Comment by sKopheK** [comment]
hi, bumped into this and seems to be an actual question once again: https://stackoverflow.com/questions/76904232/eslint-rule-react-no-multi-comp-does-not-detect-multiple-components-using-hooks
