### ISSUE TITLE
Recommend using StrictMode component

### ISSUE THREAD

**Issue by nickmccurdy** [yannickcr/eslint-plugin-react#2492]
I recently came across this Twitter pole, and was surprised to see that 70% of users haven't even tried using StrictMode: https://twitter.com/sebmarkbage/status/1177593546087395328

![image](https://user-images.githubusercontent.com/927220/68532930-54205380-02f1-11ea-8e87-21bfd390a904.png)

StrictMode is very useful for following good Rect practices (just like JavaScript's strict mode), but it's easy to forget (I often do myself even though I've used it previously). As a result, I think it would be helpful to have a rule that requires its usage at the top of the app (since it only affects child components) in the recommended config. Note that this would require checking all files and not just the current file in isolation, so I'm not sure if ESLint plugins are capable of this.

**Comment by ljharb** [comment]
While eslint plugins are capable of this, eslint-plugin-import is one of the only ones I know of that does.

However, given the complexity of this - for example, someone could do `const SM = React.StrictMode; ReactDOM.render(<SM><App /></SM>)` - I think this is the sort of thing that's best done in code review.

**Comment by nickmccurdy** [comment]
You have a good point that it can technically be renamed, but I still think it's valuable to check in cases where it isn't (as long as it isn't too much effort to implement the plugin). As far as I understand, these existing rules only work if you don't rename elements:
- https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md
- https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md
- https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-elements.md
- https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/void-dom-elements-no-children.md

I also just noticed what that purple thing on your avatar was, nICE 😆

**Comment by ljharb** [comment]
I'm not sure it is that valuable; and it won't actually be practical for every app to render in strict mode, since they may be relying on behaviors that don't work in strict mode.

**Comment by ljharb** [comment]
I believe React has moved away from this pattern entirely, so it's a good thing we never built a rule for it.

**Comment by VeikkoLehmuskorpi** [comment]
> I believe React has moved away from this pattern entirely, so it's a good thing we never built a rule for it.

What do you mean? Isn't Strict Mode especially useful in React 18 with concurrency and whatnot?
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

**Comment by nickmccurdy** [comment]
Yea, it's still used, though it enforces some additional things in React 18. `create-react-app` and `create-vite` also still generate it by default.
