### ISSUE TITLE
react-hooks/exhaustive-deps in an if statement?

### ISSUE THREAD

**Issue by maniac0s** [yannickcr/eslint-plugin-react#2493]
I create a canvas object from another library and store it in a ContextProvider's state to pass it down to components. I also use components to set certain modes of that object, but that only works after the canvas has been initialized, because I cant access canvas.someMode on null, so I have to check if the canvas has been created to decide whether to set another state.

eslint is complaining about react-hooks/exhaustive-deps when I have a state in an if statement. Why is this? No one changes a value in an if clause.

    useEffect(() => {
        if(canvas) {
            canvas.isDrawingMode = drawMode;
            console.log("canvas.isDrawingMode: ", canvas.isDrawingMode);
        }
    }, [drawMode]); //complains 'canvas' is not in the deps

I can not put canvas into deps here, because I gonna have multiple useEffect calls on different mode changes and I only want that useEffect call to be ran that has the right mode change in deps.

**Comment by ljharb** [comment]
This is eslint-plugin-react, not eslint-plugin-react-hooks.

**Comment by maniac0s** [comment]
I was send here by eslint. Can't you just leave me alone?
