### ISSUE TITLE
react/no-deprecated: Serious perf concern when version="detect"

### ISSUE THREAD

**Issue by octogonz** [yannickcr/eslint-plugin-react#2497]
If the React version is specified as `"detect"`, the `react/no-deprecated` seems to perform a very expensive detection.

If I'm reading the code correctly, _each time the rule checks a line of code_ that contains a React API call, the following things happen:

- [`checkDeprecation()`](https://github.com/yannickcr/eslint-plugin-react/blob/97a9f397d2a8a3ce3b2af893bdbb86bb2c1d4480/lib/rules/no-deprecated.js#L115) calls [`getDeprecated()`](https://github.com/yannickcr/eslint-plugin-react/blob/97a9f397d2a8a3ce3b2af893bdbb86bb2c1d4480/lib/rules/no-deprecated.js#L48) which rebuilds the entire table of deprecated APIs

- `testReactVersion()`  calls [`getReactVersionFromContext()`](https://github.com/yannickcr/eslint-plugin-react/blob/61c79716e6d18cf07997eab3bd6b27941c7e8d3a/lib/util/version.js#L35) which calls `detectReactVersion()`

- `detectReactVersion()` calls [`resolve.sync()`](https://github.com/yannickcr/eslint-plugin-react/blob/61c79716e6d18cf07997eab3bd6b27941c7e8d3a/lib/util/version.js#L19) which walks up the directory tree, probing repeatedly for `node_modules/react/package.json` in every parent folder until a match is found.  Seems like potentially nontrivial disk I/O.

- `detectReactVersion()` then uses NodeJS `require()` to load the development bundle of the entire React library into memory, merely so it can read `react.version`.  NodeJS `require()` is fortunately cached, but the first call increases my `process.memoryUsage().heapTotal` by ~700k.

Suggestions:

- Shouldn't this detection be cached somehow, at least for nodes belonging to the same source file?  
- Also should we be reading `package.json` to get the version number?  This seems to be how [`detectFlowVersion()`](https://github.com/yannickcr/eslint-plugin-react/blob/61c79716e6d18cf07997eab3bd6b27941c7e8d3a/lib/util/version.js#L57) approached it.

**Comment by ljharb** [comment]
We should be able to cache it for a particular directory, yes.

React probably needs to be loaded into memory anyways, but it’d also be fine to switch it to read the version number. The difference is that folks might be using something like yarn PnP which might not have a file system on disk.

**Comment by octogonz** [comment]
> The difference is that folks might be using something like yarn PnP which might not have a file system on disk.

PnP must provide some way to find the `package.json` file without loading the bundle into memory.

> We should be able to cache it for a particular directory, yes.

How/when would you propose to invalidate the cache?  Ironically I discovered this while working on a different plugin that also needs a cache. It occurred to me that `eslint-plugin-react`'s `"version": "detect"` must have solved it somehow. 🤭

**Comment by ljharb** [comment]
I wouldn't expect it to be that slow to find the closest requireable `react`.

If a per-directory cache is needed, there's no need to invalidate it - nothing would be modified while eslint is running, and then it would exit.

**Comment by octogonz** [comment]
That's true for the CLI, but when ESLint is invoked by the VS Code add-in, the same ESLint instance runs endlessly and processes files as you are writing code.  So for example if I edit `package.json`, it would be counterintuitive if the person had to kill and restart their editor in order for the change to be recognized.

**Comment by ljharb** [comment]
That's an orthogonal problem that many eslint plugins cause, that the vscode plugin has to fix on its own.

**Comment by octogonz** [comment]
Hrmm...  Is it true that ESLint was fundamentally designed to be single invocation command-line tool? With no architectural provision for acting as a long-running service in an editor (the way that the TypeScript compiler does, for example)?  So the VS Code extension would need to sandbox the ESLint process and awkwardly kill/restart it periodically, since ESLint and its rules are unable to participate in this scenario.

If so that's a bit surprising, given the popularity of editor integration and `webpack --watch` these days.

Or if I'm misunderstanding, what kind of fix were you envisioning for the VS Code extension?

**Comment by ljharb** [comment]
Yes, that is true. eslint is a "run once then exit" tool, and always has been.

**Comment by ljharb** [comment]
I believe version detection is now cached.
