### ISSUE TITLE
Why does `React.unmountComponentAtNode` yield a warning?

### ISSUE THREAD

**Issue by kylemh** [yannickcr/eslint-plugin-react#2499]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-deprecated.md

https://reactjs.org/docs/react-dom.html#unmountcomponentatnode

I see no documentation on the method being deprecated or unsafe.

**Comment by ljharb** [comment]
The error message implies it was deprecated in 0.14.0. The react changelog ( https://github.com/facebook/react/blob/master/CHANGELOG.md#removed-deprecations-1 ) says it was removed from React in v15. 

Perhaps ReactDOM.unmountComponentAtNode is not deprecated, and only React.unmountComponentAtNode was?

If that's the case, then we should be sure that the React method is warned in 0.14+, but the ReactDOM method is not warned.

**Comment by kylemh** [comment]
Should I make an issue in the React issue to see if it is or is not being removed in the future?

**Comment by ljharb** [comment]
Can't hurt, but based on the commits it seems the deprecation was just so they could move it to ReactDOM.

**Comment by kylemh** [comment]
I see. So, a PR to remove this specific method from the lint rule is in order?

**Comment by ljharb** [comment]
Not to remove - it should always warn when called on React, just not ReactDOM

**Comment by kylemh** [comment]
Ah! Awesome. Thanks for the explanation.
