### ISSUE TITLE
react/jsx-handler-names: saying array prop should begin with 'handle'

### ISSUE THREAD

**Issue by Auchindoun** [yannickcr/eslint-plugin-react#2502]
I have the following component:
```
export default class ServiceOnCallQuery extends React.PureComponent {
  static propTypes = {
    serviceID: p.string.isRequired,
  }

  render() {
    return (
      <Query
        query={query}
        variables={{ id: this.props.serviceID }}
        render={({ data }) => (
          <ServiceOnCallList onCallUsers={data.service.onCallUsers} />
        )}
      />
    )
  }
}
```
where `onCallUsers` is an array:
```
onCallUsers: p.arrayOf(
    p.shape({
      stepNumber: p.number.isRequired,
      userID: p.string.isRequired,
      userName: p.string.isRequired,
  }),
),
```

However, when I run my fmt I get the output:
```
/web/src/app/services/ServiceOnCallQuery.js
  31:30  error  Handler function for onCallUsers prop key must begin with 'handle'  react/jsx-handler-names
```

Is anyone able to assist? Feels like a bug. Here's a link to the file in question: https://github.com/target/goalert/blob/eslint-standard-jsx/web/src/app/services/ServiceOnCallQuery.js

---

Edit: It looks like it's happening because the prop starts with `on`, and it's not checking that the type of the prop is a function.

**Comment by Auchindoun** [comment]
We ended up renaming to `items` (aligns with how we name arrays in some other components within our app), but users being "on call" is pretty big within our app, so something like this could certainly pop up again.

Might have to end up disabling this rule though, since it's not actually checking if a prop is a function..

**Comment by ljharb** [comment]
It's not possible to check the types of things in a linter rule :-)

The convention and assumption is a common one in the ecosystem, but you're right that for your use case, you may want to disable the rule.
