### ISSUE TITLE
react/jsx-props-no-spreading: Exclude some files for this rule 

### ISSUE THREAD

**Issue by JulienKode** [yannickcr/eslint-plugin-react#2506]
I want to use **react/jsx-props-no-spreading** rule but I do not want to apply it to my test file `*.test.js` and my stories `*.stories.js`. I saw that we can have exception based on components name but see nothing based on file name

- Anyone have an idea to setup it by filter files or applying a regex ? 🤔
- if not are you open to have that feature ?

**Comment by ljharb** [comment]
eslint itself allows you to use `overrides` to apply rules to globs; there's no need for any plugin or rule to have that feature directly.

**Comment by JulienKode** [comment]
Thank you @ljharb
