### ISSUE TITLE
react/no-unused-state triggered when optional chaining is used

### ISSUE THREAD

**Issue by gustavolaux** [yannickcr/eslint-plugin-react#2515]
eslint: 6.5.1
eslint-plugin-react: 7.16.0
babel-eslint: 10.0.3

in constructor:
```
this.state = {
  downloading: false,
}
```

but when `this.state?.downloading` is used i got this message:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/20214425/70291249-5cb55e00-17b9-11ea-839d-4cae1ecee566.png">

**Comment by ljharb** [comment]
Presumably you're using babel-eslint since optional chaining just got stage 4 within the last 10 hours; it seems reasonable to modify all the rules that check for dotted and bracketed things to also check for optionally dotted and bracketed things.

**Comment by gustavolaux** [comment]
edited with babel-eslint version

**Comment by JoshuaKGoldberg** [comment]
Sorry to nitpick, but is this an `enhancement` or a `bug`?

**Comment by ljharb** [comment]
Actually I'm not sure it's either.

`this.state?.downloading` doesn't make any sense to me - when would `this.state` be nullish?

**Comment by JoshuaKGoldberg** [comment]
State is `null` by default, so this is something you need to do if you don't give it an initial value.

https://codesandbox.io/s/react-state-null-initially-ui5rp:

```jsx
class App extends React.Component {
  render() {
    return (
      <div>{JSON.stringify(this.state)}</div>
    );
  }
}
```

**Comment by ljharb** [comment]
well sure, but you're always supposed to give it an initial value - does `this.setState` even work if you don't?

**Comment by JoshuaKGoldberg** [comment]
Yup, it works! React doesn't give any warning or indication, so I'd assume there are many (like me) who relied on the behavior.

**Comment by ljharb** [comment]
Oof, that sounds awful :-/ hopefully #2588 will resolve this, either way.
