### ISSUE TITLE
Eslint complains about `react/jsx-fragments` rule syntax

### ISSUE THREAD

**Issue by gdepouilly** [yannickcr/eslint-plugin-react#2518]
`eslint@6.7.2` throws an error related to this rule :
```
"react/jsx-fragments" : "element"
```

```
Error: .eslintrc.js:
        Configuration for rule "react/jsx-fragments" is invalid:
        Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"element"').

    at validateRuleOptions (/xxx/node_modules/eslint/lib/shared/config-validator.js:138:19)
```

However, there is no `severity` setting for this rule, see https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md
I'm using `eslint-plugin-react@7.17.0`

**Comment by ljharb** [comment]
There is a severity setting for every eslint rule. The docs include “<enabled>”.
