### ISSUE TITLE
Repository history off ???

### ISSUE THREAD

**Issue by stefanbuck** [yannickcr/eslint-plugin-react#2525]
Somehow the git history seems to be totally off for this repo. According to repo page on GitHub, the last commit to master was made 3 years ago. 

![image](https://user-images.githubusercontent.com/1393946/70867348-d34e1a80-1f74-11ea-9c1e-e1937f9d8c03.png)

However, a click on [commit](https://github.com/yannickcr/eslint-plugin-react/commits/master) shows all recent merged commits.

A local checkout of the repo contains the same head from three yeas ago 😕 

What is going on here?

**Comment by ljharb** [comment]
That’s totally normal; git history is not chronological. GitHub just shows the commit order in a confusing way.
