### ISSUE TITLE
react/jsx-sort-props + {ignoreCase: false} now ignores case when sorting props

### ISSUE THREAD

**Issue by hawkrives** [yannickcr/eslint-plugin-react#2530]
I've found an unexpected(?) change that stems from #2391.

```jsx
<Hello name="John" Number="2" />
``` 

With `{ignoreCase: false}`, which according to the docs [should take case into account](https://github.com/yannickcr/eslint-plugin-react/blob/8671f054191ad5e5cedf91c7c76999bea9b7bf7b/docs/rules/jsx-sort-props.md#ignorecase) when sorting the props, the above example now expects `name` to be sorted before `Number`.

I know _why_ it sorts the way it does: #2391 switched to using `String#localeCompare`, which does…

```sh
> 'name'.localeCompare('Number')
-1
```

Looking at the `lib/rules/jsx-sort-props.js` code, I'm not sure what changes would be required to accommodate both this issue and #2381, unfortunately.

So, the crux of this issue is: is this an unexpected change, or should I alter my expectations and update the documentation to reflect this behavior?

**Comment by ljharb** [comment]
This definitely seems like an unexpected change.

**Comment by ljharb** [comment]
Specifically, we should probably only use localeCompare when ignoreCase is true?

**Comment by jcarty** [comment]
@ljharb any news on this one?

**Comment by ljharb** [comment]
No, "help wanted" means it's awaiting a PR.

**Comment by tanmoyopenroot** [comment]
We can't depend on `localeCompare` as it is not reliable.
Example:

<img width="245" alt="Screenshot 2020-01-28 at 12 30 03 PM" src="https://user-images.githubusercontent.com/25791025/73242187-3a90f880-41ca-11ea-96f7-8c8a7d3b6032.png">

Therefore, we need to replace `localeCompare` from [line](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-sort-props.js#L75) and [line](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-sort-props.js#L345).

**Comment by tanmoyopenroot** [comment]
Hi @hawkrives ,
I have added a PR, Can you check the test cases?

**Comment by ljharb** [comment]
@tanmoyopenroot we *must* depend on localeCompare whenever possible since english isn't the only language in the world.

**Comment by tanmoyopenroot** [comment]
@ljharb  But each character in a string in any language will be compared in `Unicode order` for comparison operator.
In `Unicode` everything is ordered alphabetically.

**Comment by ljharb** [comment]
If that were true, there'd be no point in the localeCompare method existing.

**Comment by tanmoyopenroot** [comment]
I will try to fix it using `localeCompare `.
