### ISSUE TITLE
react/no-unknown-proprties rule doesn't auto fix xmlns:xlink

### ISSUE THREAD

**Issue by moT01** [yannickcr/eslint-plugin-react#2531]
I think I found the right repo for this.

The image below shows three errors that need to be changed to camel case.
<img width="367" alt="Screen Shot 2019-12-23 at 7 46 54 AM" src="https://user-images.githubusercontent.com/20648924/71361554-ece4f880-2558-11ea-9c29-ada5cc53ed01.png">

Using this `fix all react/no-unknown-property problems` option...
<img width="444" alt="Screen Shot 2019-12-23 at 7 47 47 AM" src="https://user-images.githubusercontent.com/20648924/71361583-05551300-2559-11ea-81e2-47e41162acc1.png">

Fixes all but this one...
![Screen Shot 2019-12-23 at 7 47 35 AM](https://user-images.githubusercontent.com/20648924/71361665-44836400-2559-11ea-8992-5156bb0296bd.png)

It should be auto changed to `xmlnsXlink`

**Comment by ljharb** [comment]
To be clear, it's totally fine for autofixes to not be exhaustive and to leave behind things you need to manually fix.

That said, it's possible this is a special case that we could handle.

**Comment by ljharb** [comment]
@moT01 you only provided a screenshot; can you provide the actual code in text form?

**Comment by ljharb** [comment]
Closing pending a repro.
