### ISSUE TITLE
case sensitive props duplicate-props check problem

### ISSUE THREAD

**Issue by ahmetcaglayan** [yannickcr/eslint-plugin-react#2543]
https://github.com/eslint/eslint/issues/12781

**Comment by ljharb** [comment]
Per [the docs](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-duplicate-props.md), there's an `ignoreCase` option. It defaults to `false`. Perhaps you have it set to `true`?

The comment in the eslint repo linked you to the same docs.
