### ISSUE TITLE
react/prop-types: Wrong stateless component detection

### ISSUE THREAD

**Issue by stpiech** [yannickcr/eslint-plugin-react#2551]
I have following piece of code inside my component function: 
```
{
  header: "Header",
  Cell: ({ label }) => <TableCell label={label} />
}
```
Running eslint with `react/prop-types` rule, results its error: `'label' is missing in props validation(react/prop-types)`. It is probably caused by detecting line with `Cell` key definition as stateless component.

**Comment by ljharb** [comment]
An SFC is exactly what it is - it's a function that takes props, and returns jsx, and even has a capitalized name.
