### ISSUE TITLE
Module '"../@types/prop-types"' has no exported member 'PropTypes'

### ISSUE THREAD

**Issue by combstraight** [yannickcr/eslint-plugin-react#2555]
Use of `Import { PropTypes } from 'prop-types';` as suggested in this page:

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-deprecated.md

throws `Module '"../@types/prop-types"' has no exported member 'PropTypes'`

However,

`Import * as propTypes from 'prop-types'`

works fine.

**Comment by ljharb** [comment]
That means your typescript config is incorrect. You have to enable synthetic imports and esModuleInterop, or else typescript has a broken module system.
