### ISSUE TITLE
eslint-plugin-react@7.18.1 break eslint check

### ISSUE THREAD

**Issue by im6** [yannickcr/eslint-plugin-react#2561]
Hi, I just found `v7.18.1` break my eslint check.
Below link there is error message, i revert the version back to 7.18.0 to fix my build.
https://github.com/im6/vp/actions
no sure if this only happen to me, but I tried cross multiple OS and both happening on NPM and Yarn.

![Screen Shot 2020-02-01 at 6 21 22 PM](https://user-images.githubusercontent.com/5487482/73600558-c040db00-451f-11ea-86ee-e4965952e328.png)

**Comment by ljharb** [comment]
Thanks; any chance you know what code is causing the crash?

**Comment by im6** [comment]
@ljharb  seems every time when there is `null` in my code, then eslint got break. I tried to replace `null` in my code with `{}`, then it works fine and passes.

**Comment by mjamado** [comment]
I've found the same problem. It seems to me that everywhere there's a `null`, it crashes.

Replacing by `undefined` works, as well as _something_, but sometimes we really need the `null` there.

**Comment by jakeleventhal** [comment]
Encountering the same issue

**Comment by igor-lemon** [comment]
Found a temporary solution:
`'react/jsx-indent': 0`

**Comment by ljharb** [comment]
cc @toshi-toma, from #2542.

I've got a fix ready; i'll publish a patch once tests pass.

**Comment by ljharb** [comment]
v7.18.2 released.

**Comment by toshi-toma** [comment]
I'm very so sorry...
This bug is caused by my mistake.

@ljharb Thank you for the fix.
