### ISSUE TITLE
function-component-definition auto fix uses var instead of const

### ISSUE THREAD

**Issue by joaopslins** [yannickcr/eslint-plugin-react#2566]
Just added `function-component-definition` rule to an existing project but it's auto fix uses `var Component` instead of `const Component`. This is very frustrating because `no-var` rule activated, and `var` -> `const` transformation is not auto fixable. Not sure if this is intended.

Relevant code:
https://github.com/yannickcr/eslint-plugin-react/blob/0a717a52730c2a360ba8448e89cd5ac519ad0ee3/lib/rules/function-component-definition.js#L22

**Comment by ljharb** [comment]
Generally speaking, rule autofixes don't try to accommodate other rules; `var` is the safest choice, and a better issue to file would be on eslint to make `no-var` autofixable.

**Comment by joaopslins** [comment]
Thanks for the quick reply! 

That makes sense. Unfortunately for this reason, it makes auto fixing it not helpful for us. Is there a way to disable it locally only for this rule? Otherwise every time someone tries to use `--fix` it will conflict with our other rules.

**Comment by ljharb** [comment]
No, there's not. The user can manually fix the issue, though.

**Comment by joaopslins** [comment]
Got it. Thanks.
