### ISSUE TITLE
JSX open html tag flow with space 

### ISSUE THREAD

**Issue by seeliang** [yannickcr/eslint-plugin-react#257]
it may not fully related to this, but i just found out that in React
if you render ```html <h1> {'here is my react demo'}</h1> ``` (with a space after ```html<h1>```), this will render a empty span, 

is there any rule to warning this? many thanks

**Comment by yannickcr** [comment]
Duplicate of #191.

There is no rule for now, but I would accept a PR for this ;)

**Comment by seeliang** [comment]
thanks for the update
