### ISSUE TITLE
eslint crash because of react/no-adjacent-inline-elements

### ISSUE THREAD

**Issue by CleyFaye** [yannickcr/eslint-plugin-react#2575]
Versions:
- eslint-plugin-react: 7.18.3
- eslint: 6.8.0
- react: 16.12.0

When enabling the rule "react/no-adjacent-inline-elements", the following code causes eslint to crash:

```JavaScript
React.createElement(a, b);
```

Minimal .eslintrc.js that trigger the issue:
```JavaScript
module.exports = {
  plugins: ["react"],
  rules: {"react/no-adjacent-inline-elements": ["warn"]},
};
```
(setting react version does not change the issue)

Output:
```
$ npx eslint index.js 
Cannot read property 'elements' of undefined
Occurred while linting …/index.js:1
```

Expected:
Not crashing eslint, even if something's wrong with the code :)

**Comment by ljharb** [comment]
Ouch, definitely a bug (altho i have no idea how you'd run into this)
