### ISSUE TITLE
Rule conflict between `react/jsx-closing-{tag,bracket}-location` rules and the built-in `indent` rule

### ISSUE THREAD

**Issue by dead-claudia** [yannickcr/eslint-plugin-react#2576]
With the following config:

```js
{
  "plugins": ["react"],
  "rules": {
    "indent": ["error", 2],
    "react/jsx-closing-bracket-location": ["error", "tag-aligned"],
    "react/jsx-closing-tag-location": "error"
  }
}
```

Lint this file:

```jsx
const eslint1 = <Message
/>
const eslint2 = <Message
  someProp='some value'
/>

const eslint3 = <>
  some text
</>

const eslint4 = <Foo>
  some text
</Foo>

const eslint5 = <Foo
  someProp='some value'
>
  some text
</Foo>

const react1 = <Message
               />
const react2 = <Message
                 someProp='some value'
               />

const react3 = <>
                        some text
               </>

const react4 = <Foo>
                        some text
               </Foo>

const react5 = <Foo
                 someProp='some value'
               >
                        some text
               </Foo>
```

I would expect either all the `eslintN` ones (this plugin's rules taking precedence) or all the `reactN` ones (ESLint's built-in `indent` taking precedence) to have errors, but not both groups to have errors.

FYI, `react/jsx-indent-props` will move the props on the `reactN` variants down to match the `eslintN` variants if applied with `["error", 2]`, so it might be better to have the built-in `indent` take precedence to match this behavior.

-----

In some situations (not a 100% repro for me), I've had the corresponding fixes for the warnings also execute, indicating a possible ESLint bug in the mix.

**Comment by ljharb** [comment]
eslint's `indent` rule only works properly with jsx when you configure it to ignore jsx, and use `react/jsx-indent` instead.

The airbnb config handles this for you: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L312 + https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L146.
