### ISSUE TITLE
BUG "jsx-key"  should warning when iterate element with optional chaining syntax

### ISSUE THREAD

**Issue by JonathanLee-LX** [yannickcr/eslint-plugin-react#2594]
Iterate jsx element with optional chaining syntax, `react/jsx-key` rule don't show  warnings.

Just like this

![new-react-jsx](https://user-images.githubusercontent.com/20569396/76747410-0b533c80-67b4-11ea-8af9-751ca2531cf8.png)

**Comment by JonathanLee-LX** [comment]
Maybe this example will be more accurate
![no-react-key](https://user-images.githubusercontent.com/20569396/76783243-79b3f100-67ec-11ea-9217-4c0100477022.png)

**Comment by ljharb** [comment]
(in general, please post code samples as text; images of text are not accessible, can't be copy-pasted, and difficult to read in many circumstances)

That second example would never happen in real code, of course, but yes, I agree that in that case it should show a warning.

**Comment by JonathanLee-LX** [comment]
Thank you first, yes, in the second example, the initial value of `arr` is normally set to `[]` instead of `undefined`, so this rule is generally not a problem.

**Comment by JonathanLee-LX** [comment]
I cloned this repository, and try to add a test case like below
`    {
      code: '[1, 2, 3]?.map(x => <App />)',
      parser: parsers.TYPESCRIPT_ESLINT,
      errors: [{message: 'Missing "key" prop for element in array.'}]
    }
`
This test case will fail, if add `key` in `App`,  this case will pass。
So，`TYPESCRIPT_ESLINT` parser has already implemented this use case.

**Comment by ljharb** [comment]
perhaps - is that the parser you're using? only the typescript parser, and babel-eslint, currently support optional chaining,

**Comment by JonathanLee-LX** [comment]
I'm using `@typescript-eslint/parser`, the version is `^2.7.0`.

**Comment by ljharb** [comment]
TYPESCRIPT_ESLINT is the old parser; you'll need `'@TYPESCRIPT_ESLINT'` for your failing test case. Want to make a PR with it?

**Comment by JonathanLee-LX** [comment]
Yes, I want, but I can't make this use case pass the test with `@typescript-eslint/parser`.

**Comment by ljharb** [comment]
That’s fine, a PR with a failing test is still much easier for me to work with than issue comments :-)
