### ISSUE TITLE
react/no-deprecated add SFC

### ISSUE THREAD

**Issue by Maxim-Mazurok** [yannickcr/eslint-plugin-react#2597]
`React.SFC` is [deprecated](https://stackoverflow.com/questions/53885993/react-16-7-react-sfc-is-now-deprecated)
Not sure since which version, but probably `16.7`.
Needs to be added to the list, thanks!

**Comment by ljharb** [comment]
That looks like a TypeScript type, which isn't part of React. Separately, tho the React team may wish to deprecate a community-invented term like "SFC", that's not up to them.

`React.SFC` isn't a thing, as far as JavaScript is concerned; as such, there's nothing actionable in this plugin.
