### ISSUE TITLE
React is defined but never used (no unused vars) on CodeSandbox

### ISSUE THREAD

**Issue by fkhan698** [yannickcr/eslint-plugin-react#2600]
I am trying to import React on[ CodeSandbox](https://codesandbox.io/s/hacker-news-g3g2o) but I am getting an error saying that React is defined but never used. I imported React successfully on my other components but for my api.js I get the error message

**Comment by ljharb** [comment]
That file doesn’t use React, because it doesn’t have any jsx, which implicitly uses React.createElement.
