### ISSUE TITLE
[bug] undefined variable `name` does not trigger errors or warnings in JSX.

### ISSUE THREAD

**Issue by JustFly1984** [yannickcr/eslint-plugin-react#2613]
I'm crosslinking the issue, as I do not know where it could belong to:
https://github.com/eslint/eslint/issues/13127
I'm not sure which rule is failing, but if I had a component which had prop name and used it in JSX, while refactoring and renaming prop to title, the leftovers of name prop iN JSX slept unnoticed, and caused errors in production, even with typescript.

my `.eslintrc.js`:
```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "standard-react",
    "plugin:cypress/recommended",
    "plugin:jest/recommended",
    "plugin:import/typescript",
    "plugin:jsx-a11y/recommended",
    "plugin:react/recommended",
    "plugin:react-perf/all",
    "plugin:react-redux/recommended",
    "plugin:promise/recommended",
    "stylelint",
    // Prettier always last
    "prettier",
    "plugin:prettier/recommended",
    "prettier/@typescript-eslint",
    "prettier/react",
    "prettier/standard",
  ],
  plugins: [
    "chai-expect",
    "import",
    "@typescript-eslint",
    "react",
    "jsx-a11y",
    "react-hooks",
    "react-perf",
    "react-redux",
    "jest",
    "no-inferred-method-name",
    "optimize-regex",
    "promise",
    "cypress",
    "prettier",
    "standard",
    "markdown",
    "json",
    "xss",
    "perf-standard",
    "es",
    "babel",
    "formatjs",
  ],
  settings: {
    react: {
      version: "detect",
    },
    node: {
      allowModules: ["src"],
      resolvePaths: [__dirname],
      tryExtensions: [".ts", ".tsx", ".js", ".jsx", ".json"]
    },
  },
  env: {
    "cypress/globals": true,
    browser: true,
    node: true,
    es6: true,
  },
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018, // Allows for the parsing of modern ECMAScript features
    sourceType: "module", // Allows for the use of imports
  },
  rules: {
    "node/no-missing-import": "off",
    "node/no-missing-require": "off",
    "node/no-unsupported-features/es-syntax": "off",
    "sort-requires/sort-requires": "off",
    "no-console": ["error", { allow: ["warn", "error", "info"] }],
    "no-unused-vars": "off",
    "@typescript-eslint/explicit-function-return-type": [
      "warn",
      { allowExpressions: true },
    ],
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/no-use-before-define": [
      "error",
      { functions: false, classes: false, typedefs: false },
    ],
    "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    "react-redux/prefer-separate-component-file": "off",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "optimize-regex/optimize-regex": "warn",
    "es/no-async-iteration": "error",
    "es/no-malformed-template-literals": "error",
    "es/no-regexp-lookbehind-assertions": "error",
    "es/no-regexp-named-capture-groups": "error",
    "es/no-regexp-s-flag": "error",
    "es/no-regexp-unicode-property-escapes": "error",
    "chai-expect/missing-assertion": 2,
    "chai-expect/terminating-properties": 1,
  },
  overrides: [
    // Override some TypeScript rules just for .js files
    {
      files: ["*.js"],
      rules: {
        "semi": ["error", "never"],
        "jsx-quotes": ["error", "prefer-single"],
        "@typescript-eslint/no-var-requires": "off",
        "@typescript-eslint/explicit-function-return-type": "off",
      },
    },
  ],
}
```

this is how it looks in the code:
<img width="880" alt="Screenshot 2020-04-01 14 38 16" src="https://user-images.githubusercontent.com/2255993/78116378-6466d580-742e-11ea-8495-d9da017e95c3.png">

as you can see variable name is not defined, but somehow not highlighted. Had this slipped in to the code base 3 times this year

**Comment by ljharb** [comment]
That's because `name` is a global in browsers; it is, in fact, defined.

**Comment by JustFly1984** [comment]
@ljharb 
well, in this case it is not defined, cos we have Sentry bug tracking software, and it gives us a type error in code covered by typescript. This is very tricky issue, cos it leads to bugs. 
Is there somewhere on a web a list of this kind of variables which is not recommended to use in everyday code?
It is definitely DX bug, and it needs to be solved somehow. I've met it 3 times in a year in different codebases, but yesterday it was a reason to fail an issue here.

**Comment by ljharb** [comment]
It's definitely defined in every browser - `name` is `window.name`, which is always defined. The same problem occurs with things like `Text`, or any other browser global.

Perhaps TypeScript is renaming that variable in your build output? In that case, it would appear to be defined at lint time (the lack of error here is correct) but the renamed variable wouldn't exist.

**Comment by JustFly1984** [comment]
@ljharb so what can we do about it? create an issue in typescript repo?

**Comment by ljharb** [comment]
If you can confirm the tsc output is mangling the variable name, causing it to break at runtime even tho the types are valid, then yes that seems like the right path to me.

**Comment by ljharb** [comment]
Closing pending confirmation.
