### ISSUE TITLE
no-did-mount-set-state on async function

### ISSUE THREAD

**Issue by NoamDev** [yannickcr/eslint-plugin-react#2629]
using `setState` in `componentDidMount` should not be a problem when `componentDidMount` is an async function and `setState` is being called somewhere after an `await`-ed statement, it should be as the same as calling setState from a callback function.

**Comment by NoamDev** [comment]
it could be based on this https://github.com/eslint/eslint/blob/master/lib/rules/require-await.js

**Comment by ljharb** [comment]
I"m always open to PRs that make too-tight rule prohibitions more correct.

`require-await`, however, is a terrible rule that shouldn't exist; `async function` is always fine with no `await`s in it.

Closing this for now.

**Comment by NoamDev** [comment]
> require-await, however, is a terrible rule that shouldn't exist; async function is always fine with no awaits in it.

You know that's irrelevant. The fact the someone believe a rule is should not exist, does not mean he cannot base another on its implementation.

What do you think about that? using a stack in order to track any await statements in any method with the function name that should not contain setState?
Then, when a setState is called, to check whether there was an await statement so far.

**Comment by ljharb** [comment]
Ah, I misunderstood what you meant :-) of course we can use the implementation to inform a new rule.

I think that if you can provide a PR with sufficient test cases to cover all the things we can think of, that would be worth reviewing.
