### ISSUE TITLE
peerDependency warning with eslint@7.0.0

### ISSUE THREAD

**Issue by AviVahl** [yannickcr/eslint-plugin-react#2639]
eslint@7.0.0 [has been released](https://github.com/eslint/eslint/releases/tag/v7.0.0) yesterday. `eslint-plugin-react` gets a peerDependency warning:

```
npm WARN eslint-plugin-react-hooks@4.0.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```

ref: https://github.com/facebook/react/issues/18876

**Comment by ljharb** [comment]
Yes, thats because it doesn’t support eslint 7 yet, which means you can’t use it yet.

Closing in favor of #2635.
