### ISSUE TITLE
`jsx-no-target-blank` does not properly detect rel value if there are braces

### ISSUE THREAD

**Issue by rococode** [yannickcr/eslint-plugin-react#2641]
Example:

`<a href="https://edpb.europa.eu/about-edpb/board/members_en" target="_blank" rel={"noopener noreferrer"}>Link</a>`

Shows warning:
`Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank`

Removing the braces removes the warning:

`<a href="https://edpb.europa.eu/about-edpb/board/members_en" target="_blank" rel="noopener noreferrer">Link</a>`

**Comment by ljharb** [comment]
We have specific tests to cover that: https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/jsx-no-target-blank.js#L40-L41 what version of eslint-plugin-react and eslint are you using?

**Comment by rococode** [comment]
Ah yes I was on an outdated version (7.12.4), looks like this was already fixed in 7.18.0 my bad! https://github.com/yannickcr/eslint-plugin-react/commit/e69b1136745df6267d9d5ee35112b5ffffc9d438
