### ISSUE TITLE
no-string-literals possibly has an error in default values docs

### ISSUE THREAD

**Issue by yarynakorduba** [yannickcr/eslint-plugin-react#2645]
Looks like there is an error in documentation for `react/jsx-no-literals`:
 default value for `noStrings` option is set to `false`, by documentation.
Looks, like in fact it's set to `true` 

Linting with this config: ` "react/jsx-no-literals": ["error", {"noStrings": false}]` gives different results from this config ` "react/jsx-no-literals": "error" `

**Comment by ljharb** [comment]
What version of the plugin? The [rule code](https://github.com/yannickcr/eslint-plugin-react/blob/25bf6cc4860429849e1fc7397f83bc788a2c1ba4/lib/rules/jsx-no-literals.js#L50) is pretty clear that false is the default.

I suspect you’re inheriting config from somewhere else; if you only provide the severity, it doesn’t override that from a shared config.

**Comment by yarynakorduba** [comment]
@ljharb it was v7.20.0. But you are right, I really did not pay attention to the rule code and that's probably my issue. Sorry for disturbing.
