### ISSUE TITLE
Lint to encourage pure components

### ISSUE THREAD

**Issue by kentcdodds** [yannickcr/eslint-plugin-react#265]
As [thought originally](https://twitter.com/dan_abramov/status/656585498488647680) by @gaearon:

> React 0.14 [pure components](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components) do wonders to clarity. Can't believe we tolerated living so long without them!
> We should lint for that. “You’re not using refs, lifecycle hooks, or state, so turn this class into a function please.”

I believe this is totally possible, but I've never written a custom rule before, so I wouldn't know where to start... Thoughts?

**Comment by gaearon** [comment]
This is similar but encourages you to use ES6 class over `createClass`:

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-es6-class.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/prefer-es6-class.js
https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/prefer-es6-class.js

You might use this as starting point, but of course this rule will be more complex.

**Comment by kentcdodds** [comment]
Now that I think of it, the opposite would be handy as well. If you reference `this.state` in a pure component of course it wouldn't actually work, but to have that linted would be helpful I think.

**Comment by yannickcr** [comment]
I'm agree, this could be a very useful rule. The actual [`display-name`](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/display-name.js) one could be a good starting point imho (but instead of searching for `displayName` we'll be searching for `this.refs`, `this.state` and lifecyle methods.

**Comment by gaearon** [comment]
Whoops, seems like duplicate of #214.

**Comment by kentcdodds** [comment]
Ah, yes, my bad. Appears to be identical. Closing
