### ISSUE TITLE
Config for optional chaining

### ISSUE THREAD

**Issue by CHPrado** [yannickcr/eslint-plugin-react#2652]
Sorry to ask but I didn't find it anywhere. 

I can't set up my eslint to use es2020 optional chaining with react. It gives me the error:

> Parsing error: Unexpected token . eslint

Then the lint stops working in this file. How to fix it?

**Comment by ljharb** [comment]
This isn't an eslint-plugin-react question; it's a regular eslint one.

However, you need to set `parserOptions.ecmaVersion` to `2020`.
