### ISSUE TITLE
`detect` does not consider `NODE_PATH` environment variable

### ISSUE THREAD

**Issue by shanemcquillan** [yannickcr/eslint-plugin-react#2653]
`detect` assumes you're executing eslint from your project's root directory. It should also check if react is installed in a provided `NODE_PATH`

This appears to be the problematic line:

https://github.com/yannickcr/eslint-plugin-react/blob/2598b1ee64df6f1814a5084075da9cd45deb8b8f/lib/util/version.js#L19

**Comment by ljharb** [comment]
I don't think it should; `NODE_PATH` is deprecated and discouraged and a very very bad idea to set and use (ESM will never support it, for example).

**Comment by shanemcquillan** [comment]
It looks like it was decided against deprecating it - https://github.com/nodejs/node/issues/1627

While use is generally discouraged there are some valid use cases for it, so I think it’s worth considering.

**Comment by ljharb** [comment]
That it's not officially deprecated doesn't mean it's not widely discouraged. I'm not aware of any valid use cases for it; node modules you require should always be in the local node_modules folder.

**Comment by ljharb** [comment]
Avoid using NODE_PATH; it's a bad practice.
