### ISSUE TITLE
Forbid certain types of defaultProps

### ISSUE THREAD

**Issue by thany** [yannickcr/eslint-plugin-react#2659]
I would like to forbid in my project the presence of certain types of defaultProps. For instance, I want to forbid creating `undefined` or `null` defaultProps, because that's useless (in our project at least, we can't imagine how that'd be useful).

So just like it's possible to forbig certain propTypes, maybe something like this:

```json
"react/forbid-default-props": [ "error", { "forbid": [ "null", "undefined" ] } ]
```

I can also imagine folks might want to forbid functions, function calls, NaN, Infinity, empty object, etc.

**Comment by ljharb** [comment]
`undefined` as a defaultProp is pretty useless, but `null` isn't, since defaultProps only kick in for `undefined`.

I'm not clear on how it would make sense as a general rule tho - there's nothing wrong with having any of the values listed as a defaultProp.

**Comment by thany** [comment]
I know `null` isn't useless, but in most cases in our codebase, `null` is used interchangeably with `undefined`. Prohibitin `null` prevents that, and ESLint exceptions can be put in to allow them where absolutely neccesary.

Those other values, you're right that they aren't useless either. I'm just thinking some folks might want to avoid specifying them for all kinds or weird and exotic reasons. I mean, if we're prohibiting `undefined`, why stop there?

**Comment by ljharb** [comment]
Sure, but I'm also not clear on why you'd want to prohibit `undefined`. If you have an optional prop, it's good explicit documentation to indicate clearly that it stays `undefined` when omitted.

**Comment by thany** [comment]
That's true as well. As always, it depends. Some prefer it one way, others prefer it the other way round.

**Comment by ljharb** [comment]
I don't think this holds its weight as a custom rule; rules and options shouldn't exist for every preference, only reasonable and common ones - and I don't think this one meets either bar.

**Comment by thany** [comment]
Unfortunately, that's opinionated. I thought ESLint was supposed to be opposite 😥

**Comment by ljharb** [comment]
No, eslint's *entire purpose* is to be opinionated, as is that of an eslint plugin.

However, you can create your own plugin and author any rules you like, and then that can be *your* opinions.

**Comment by thany** [comment]
It depends on how you look at it. ESLint itself should not impose *its* opinions, but rather its users should impose *their* opinions.

Anyway, I'll have a think about it. For now this issue can be left closed, I suppose.
