### ISSUE TITLE
Please Re-open 1753

### ISSUE THREAD

**Issue by machineghost** [yannickcr/eslint-plugin-react#2660]
Please re-open https://github.com/yannickcr/eslint-plugin-react/issues/1753.

Two years ago ESLint decided to mark perfectly valid JSX as invalid, with no flag to escape.  In 2020 can we please revisit that decision, and instead provide a way to allow *perfectly valid* JSX?

**Comment by ljharb** [comment]
Please don't post new issues asking to reopen old ones; that's what commends on old issues are for.

**Comment by machineghost** [comment]
My apologies: I meant no disrespect. Please understand though that this culture is not universal:L on other repos closed issues with new comments languish without ever being addressed, so on them it's normal to raise attention with a fresh issue.

**Comment by ljharb** [comment]
Thanks, I appreciate the explanation, and no disrespect was received.
