### ISSUE TITLE
currentState v prevState

### ISSUE THREAD

**Issue by joetidee** [yannickcr/eslint-plugin-react#2668]
In this lint rule if references `prevState`, but at the time the state is used it is actually the current state, no? If so, should we update this page to say `currentState`?

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md

**Comment by ljharb** [comment]
The setState callback runs after the previous state is valid, and before the next state is valid. It's "between" time, so there's no "current" then.

This is react's own terminology.
