### ISSUE TITLE
Discuss: disable react/style-prop-object by default and deprecate

### ISSUE THREAD

**Issue by brentvatne** [yannickcr/eslint-plugin-react#2669]
If users want to catch type errors they should be using a type checker. This limits the ability for components in the ecosystem to use the `style` prop name even when it is the most reasonable choice.

**Comment by brentvatne** [comment]
My mistake, this is not part of the recommended preset

**Comment by ljharb** [comment]
Bear in mind, that type systems are nowhere near as powerful as propTypes (although there's a few things they can check that propTypes can't), and you should *always* use propTypes, especially when using a type system.
