### ISSUE TITLE
Just put this onn .eslintrc.js (rules)

### ISSUE THREAD

**Issue by ThiagoFelippi** [yannickcr/eslint-plugin-react#2674]
'react/button-has-type': ['off'],

**Comment by ljharb** [comment]
I'm not sure what this issue is saying.

**Comment by ljharb** [comment]
Sorry, fat-fingered the button.

The rule isn't currently enabled in the recommended ruleset, so if you've got this excellent and important rule enabled, and you want to disable it for some reason I can't fathom, you need to do that in your own config.
