### ISSUE TITLE
react/no-unsafe not work

### ISSUE THREAD

**Issue by alanhg** [yannickcr/eslint-plugin-react#2675]
## package

![image](https://user-images.githubusercontent.com/9245110/84719325-a7583400-afad-11ea-8643-1fce9385479c.png)

### package.json
```
    "react": "16.8.3",
    "eslint": "^6.8.0",

```

```js

module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: [
    '@typescript-eslint'
  ],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended'
  ],
  ignorePatterns: ['webpack/*.js'],
  settings: {
    react: {
      version: 'detect'
    }
  },
  rules: {
    'react/no-unsafe': ['error']
}
```

## now

not warning for componentWillReceiveProps

## want to be 
check unsafe method

**Comment by ljharb** [comment]
What version of react are you using? That's not in your screenshot.

**Comment by alanhg** [comment]
> What version of react are you using? That's not in your screenshot.

I paste it     

    "react": "16.8.3",

**Comment by ljharb** [comment]
You need to configure this option to `true`: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unsafe.md#checkaliases-default-false or else it won't warn on them.

**Comment by alanhg** [comment]
> You need to configure this option to `true`: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unsafe.md#checkaliases-default-false or else it won't warn on them.

I think the option is just for checkAlias. now I write componentWillReceiveProps not Unsafe_componentWillReceiveProps

**Comment by alecmolloy** [comment]
i'm curious if anyone else can get this rule to work? we're unable to figure this one out despite all other rules from this list working perfectly fine. have tried a bunch of variations to coax it into throwing an error but no luck.

**Comment by ljharb** [comment]
We have lots of tests that prove it works. If you're still having trouble, please file a new issue.
