### ISSUE TITLE
Disabling jsx-props-no-spreading does not work

### ISSUE THREAD

**Issue by sarawinter** [yannickcr/eslint-plugin-react#2681]
I am trying to configure `jsx-props-no-spreading` for test purposes (at the moment), but it does not want to work. I have added the following code to my package.json file:

    "eslintConfig": {
        "extends": [
        "prettier"
      ],
      "rules": {
          "react/jsx-props-no-spreading": 0
        }
    },

This is my whole package.json file:

    {
      "name": "xxx",
      "version": "1.0.0",
      "private": true,
      "dependencies": {
        "@date-io/date-fns": "^1.3.13",
        "@material-ui/core": "^4.9.14",
        "@material-ui/icons": "^4.9.1",
        "@material-ui/pickers": "^3.2.10",
        "@microsoft/applicationinsights-react-js": "^2.5.4",
        "@microsoft/applicationinsights-web": "^2.5.4",
        "agentkeepalive": "^4.1.2",
        "core-js": "^3.6.5",
        "date-fns": "^2.13.0",
        "enzyme": "^3.11.0",
        "enzyme-adapter-react-16": "^1.15.2",
        "file-saver": "^2.0.2",
        "formik": "^2.1.4",
        "http-proxy-middleware": "^1.0.3",
        "immer": "^7.0.1",
        "moment": "^2.25.3",
        "mui-datatables": "^2.14.0",
        "react": "^16.13.1",
        "react-app-polyfill": "^1.0.6",
        "react-dom": "^16.13.1",
        "react-redux": "^7.2.0",
        "react-router-dom": "^5.2.0",
        "react-scripts": "3.4.1",
        "redux": "^4.0.5",
        "redux-logger": "^3.0.6",
        "redux-thunk": "^2.3.0",
        "shortid": "^2.2.15",
        "yup": "^0.29.1"
      },
      "jest": {
        "setupFiles": [
          "<rootDir>/src/setupTests.js"
        ],
        "transformIgnorePatterns": [
          "<rootDir>/node_modules/?!(@material-ui)/"
        ]
      },
      "husky": {
        "hooks": {
          "pre-commit": "lint-staged",
          "pre-push": "npm test"
        }
      },
      "lint-staged": {
        "*.+(js|jsx)": [
          "eslint --fix"
        ],
        "*.+(json|css|md)": [
          "prettier --write"
        ]
      },
      "scripts": {
        "start": "react-app-rewired start",
        "build": "react-app-rewired build",
        "test": "react-app-rewired test --transformIgnorePatterns \"node_modules/?!(@material-ui)/\" --watchAll=false --silent --forceExit --env=jsdom",
        "test:dev": "react-app-rewired test --transformIgnorePatterns \"node_modules/?!(@material-ui)/\" --env=jsdom",
        "eject": "react-scripts eject",
        "analyze": "source-map-explorer build/static/js/*.js"
      },
      "eslintConfig": {
        "extends": [
          "prettier"
        ],
        "rules": {
          "react/jsx-props-no-spreading": 0
        }
      },
      "browserslist": [
        ">0.2%",
        "not dead",
        "not ie <= 11",
        "not op_mini all"
      ],
      "devDependencies": {
        "babel-core": "^6.26.3",
        "babel-eslint": "^10.1.0",
        "babel-plugin-import": "^1.13.0",
        "babel-preset-react": "^6.24.1",
        "customize-cra": "^0.9.1",
        "eslint-config-airbnb": "^18.1.0",
        "eslint-config-prettier": "^6.11.0",
        "eslint-plugin-import": "^2.20.2",
        "eslint-plugin-jsx-a11y": "^6.2.3",
        "eslint-plugin-prettier": "^3.1.3",
        "eslint-plugin-react": "^7.20.0",
        "eslint-plugin-react-hooks": "^4.0.2",
        "eslint": "^6.2.0",
        "husky": "^4.2.5",
        "lint-staged": "^10.2.3",
        "prettier": "^2.0.5",
        "react-app-rewired": "^2.1.6",
        "react-test-renderer": "^16.13.1",
        "redux-devtools-extension": "^2.13.8",
        "redux-immutable-state-invariant": "^2.1.0",
        "redux-mock-store": "^1.5.4"
      }
    }

**Comment by ljharb** [comment]
What do you mean by "doesn't seem to work"? What error are you getting on what code?

**Comment by sarawinter** [comment]
I am getting the error on compilation: Prop spreading is forbiddeneslint(react/jsx-props-no-spreading)

When triying:

      <label className="checkbox">
        <input type="checkbox" {...field} {...props} />
        {children}
      </label>

**Comment by ljharb** [comment]
And if run `npx eslint --print-config path/to/file` what shows up?

If you're unable to disable a rule, that's not an issue with the plugin, it's an issue with your eslint config.

**Comment by rdelgatte** [comment]
I wanted to disable it as well and fixed it with: `"react/jsx-props-no-spreading": "off"`

**Comment by saadusufzai** [comment]
I was facing the same issue .  
add this in your eslintrc.json 

`"react/jsx-props-no-spreading": "off"`

restart the dev server 

`npm start`
