### ISSUE TITLE
no-unused-prop-types: Crashes on indexable TypeScript prop declarations

### ISSUE THREAD

**Issue by taion** [yannickcr/eslint-plugin-react#2687]
This is an issue with https://github.com/yannickcr/eslint-plugin-react/pull/2661 that makes it crash in certain cases. cc @eltonio450 

Consider something like https://astexplorer.net/#/gist/dea688bfbbfb2b2a2ffc3b4e293e0a01/63d1542090fe4a6545194562b88ffa34d7b22c83.

The interface body here consists of a `TSPropertySignature` and a `TSIndexSignature`. The `foundDeclaredPropertiesList` is thus not actually a list of declared properties: https://github.com/yannickcr/eslint-plugin-react/pull/2661/files#diff-3ed4052fa9471077711e82f482c3f819R304

When iterating through them, attempting to access `tsPropertySignature.key.name` on the index signature in https://github.com/yannickcr/eslint-plugin-react/pull/2661/files#diff-3ed4052fa9471077711e82f482c3f819R317 fails, because the index signature has no `key` property.

**Comment by ljharb** [comment]
Thanks, the repro helped a lot. Will release a patch tomorrow.

**Comment by eltonio450** [comment]
whoah, it's been fast 😃  !

Thank you, and sorry for missing it :(

**Comment by ljharb** [comment]
v7.20.3 is released.
