### ISSUE TITLE
Feature Request: detect unused styles

### ISSUE THREAD

**Issue by gre** [yannickcr/eslint-plugin-react#270]
When using with React Native, it would be great to detect a styles is not used to prevent dead code.

```
var styles = StyleSheet.create({
  a: {},
  b: {} // b is not used
});


<View style={styles.a} />
```

not sure if it is easy to implement or not

**Comment by Intellicode** [comment]
I would like to use this feature too, probably I could have a go at a plugin if more people are interested!

**Comment by yannickcr** [comment]
Not in my priorities for now, but if you want to submit a PR for this I'll be happy to add it to the plugin :)

**Comment by Intellicode** [comment]
I have created a separate plugin for this since its react-native specific.

**Comment by yannickcr** [comment]
> I have created a separate plugin for this since its react-native specific. 

Great! If you don't mind I'll add it to the Readme :)

**Comment by Intellicode** [comment]
Sure! Thanks for the link :) I'm pointing them right back to the generic React plugin as well for non-react-native specific rules.
