### ISSUE TITLE
react/no-did-mount-set-state should not happen in callbacks

### ISSUE THREAD

**Issue by gre** [yannickcr/eslint-plugin-react#272]
<img width="691" alt="screen shot 2015-10-23 at 19 25 53" src="https://cloud.githubusercontent.com/assets/211411/10700131/049481e6-79bc-11e5-9ec8-47cb08fba56b.png">

I think setState is perfectly fine for callbacks.

**Comment by yannickcr** [comment]
You can use the [`allow-in-func` option](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md#allow-in-func-mode) for this case.
