### ISSUE TITLE
Make react/jsx-no-duplicate-props Case Sensitive on Custom JSX

### ISSUE THREAD

**Issue by teamtofu** [yannickcr/eslint-plugin-react#2726]
# Issue Description
[Material UI](https://material-ui.com/api/text-field/#textfield-api) implements both `inputProps` and `InputProps` props on their TextField. When both are specified, `react/jsx-no-duplicate-props` is triggered.

## Proposed Solution
For components (e.g. `<Capitalized>`), props are kept in their original case. For native JSX elements (e.g. `<div>`), props are still considered case-insensitive.

**Comment by ljharb** [comment]
@teamtofu what version of eslint and eslint-plugin-react do you have? Current tests pass for what you're referring to, unless `ignoreCase` is set to `true`.

**Comment by teamtofu** [comment]
On further inspection the `{ignoreCase: true}` from `eslint-config-airbnb` overrode the one in my root config. Thanks for your help.
