### ISSUE TITLE
Browser Build

### ISSUE THREAD

**Issue by curran** [yannickcr/eslint-plugin-react#2732]
Has anyone tried or succeeded in building `eslint-plugin-react` to run in the browser?

Use case: linting inside a browser-based IDE https://vizhub.com/curran/c3b14112dae34ef395999cef5783324f?edit=files&file=index.js

Thanks in advance!

**Comment by ljharb** [comment]
Linting requires filesystem access at times - in particular, eslint-plugin-import, but also this plugin detects the react and flow versions, and also needs to load the TypeScript config.

I don't think it's realistic to lint in the browser, I'm afraid.

**Comment by curran** [comment]
Thanks @ljharb for your response!

FWIW I have got linting working in the browser using this package for now https://www.npmjs.com/package/eslint4b

Assuming no Flow and no Typescript, and an explicit React version passed in rather than detected from the file system, in theory it should be possible to run `eslint-plugin-react` in the browser. There may be some rules that have a fundamental incompatibility and strictly depend on file system access (indeed as you mention `eslint-plugin-import`), but I suspect many React-specific rules could work in a browser environment. I understand there are technical hurdles, but I think it is feasible, at least conceptually.

I suppose the question is, is this feature something that the team behind `eslint-plugin-react` would be interested in supporting? I could take a crack at a PR for a browser build.

**Comment by ljharb** [comment]
What changes do you anticipate being needed, in that constrained scenario?

**Comment by curran** [comment]
I'm imagining a different flow for the browser build that stubs out or otherwise disables the `fs` and dynamic `require` calls.

Rollup does this quite elegantly, as a reference:
 * https://github.com/rollup/rollup/blob/master/browser/fs.ts
 * https://github.com/rollup/rollup/blob/0fa9758cb7b1976537ae0875d085669e3a21e918/rollup.config.js#L142

**Comment by ljharb** [comment]
Sure, but you can do that already in every JS bundler, including browserify, webpack, etc.
