### ISSUE TITLE
no-undef rule for component class methods

### ISSUE THREAD

**Issue by leusrox** [yannickcr/eslint-plugin-react#2738]
Is it possible detect undefined method in this case?

```
export default class Test extends Component {
  render() {
    return (
      <Example
        onClick={this.undefinedMethod}
      />
    );
  }
}
```

P. S. Sorry if the question has already been asked, I didn't find.

**Comment by ljharb** [comment]
No, it's not possible to statically detect this without a type system. This is the domain of unit tests.
