### ISSUE TITLE
Rule proposal: react/no-unstable-nested-components

### ISSUE THREAD

**Issue by AriPerkkio** [yannickcr/eslint-plugin-react#2749]
I'd like to introduce a new rule for detecting React components which are declared inside another component or inside class component's render block. I was surprised to see this rule doesn't exist yet.

I've named this rule `react/no-unstable-nested-components` - if anyone can come up with a better name I'm open for it.

I'll set up the PR soon. Here's the implementation [AriPerkkio/eslint-plugin-react/tree/react/no-unstable-nested-components](https://github.com/AriPerkkio/eslint-plugin-react/tree/react/no-unstable-nested-components).

## Use case
Prevent developers from creating components inside another components.

### 1. Performance
```jsx
function Component() {
  function UnstableNestedComponent() {
    return <div />;
  }

  return (
    <div>
      <UnstableNestedComponent />
    </div>
  );
}
```

When `Component` re-renders (e.g. parent state updates) the `UnstableNestedComponent` is recreated. React reconciliation will compare the previous render's `UnstableNestedComponent` and the current one using [reference equality](https://github.com/facebook/react/blob/v16.13.1/packages/react-reconciler/src/ReactChildFiber.js#L407). Since the reference does not match, the element will be completely recreated - not to be confused with re-rendering. I guess this is a small performance optimization, especially in cases where this pattern is used on application root level.

Since all the children of the nested component are also recreated on each re-render, optimization provided by `React.PureComponent` is gone. The `PureComponent` is recreated on each re-render.
```jsx
class PureComponent extends React.PureComponent {
  render() {
    return <div />;
  };
};

function Component(props) {
  function Wrapper() {
    return <div>{props.children}</div>;
  };

  return (
    <div>
      <Wrapper />
    </div>
  )
};

...

<Component>
  <PureComponent />
</Component>
```

### 2. Prevent unnoticeable bugs

This is the most important use case of this rule. In addition to performance optimization this rule will prevent [possible bugs](https://codepen.io/ariperkkio/pen/vYLodLB).

In cases where the nested component is rendering given **stateful** children, each re-render will reset the children's state back to the initial state. Without this rule these cases are easily unnoticeable and cause weird behavior in apps.

```jsx
function Accordion(props) {
  const [isOpen, toggle] = React.useReducer(s => !s, false);

  return (
    <>
      <button onClick={toggle}>Toggle</button>
      <div style={{ opacity: isOpen ? 1 : 0 }}>
        {props.children}
      </div>
    </>
  );
};

function Menu(props) {
  function MenuWrapper() {
    return <div>{props.children}</div>;
  };

  return (
    <div>
      <h2>Menu</h2>
      <MenuWrapper />
    </div>
  );
};

export default function Navigation() {
  return (
    <nav>
      <button onClick={React.useReducer(() => [], [])[1]}>
        Force render
      </button>
      <Menu>
        <Accordion>About us</Accordion>
        <Accordion>Contact</Accordion>
      </Menu>
    </nav>
  );
};
```

In example above:

1. Click About us to open the "accordion"
2. Click force render to update parent state and to trigger re-render

- Expected: Accordion stays open
- Actual: Accordion closes. Component is recreated and initial state is set.

## Rule Details

The following patterns are considered warnings:

```jsx
function Component() {
  function UnstableNestedComponent() {
    return <div />;
  }

  return (
    <div>
      <UnstableNestedComponent />
    </div>
  );
}
```

```jsx
class Component extends React.Component {
  render() {
    function UnstableNestedComponent() {
      return <div />;
    }

    return (
      <div>
        <UnstableNestedComponent />
      </div>
    );
  }
}
```

The following patterns are **not** considered warnings:

```jsx
function OutsideDefinedComponent(props) {
  return <div />;
}

function Component() {
  return (
    <div>
      <OutsideDefinedComponent />
    </div>
  );
}
```

```jsx
function Component() {
  const MemoizedNestedComponent = React.useCallback(() => <div />, []);

  return (
    <div>
      <MemoizedNestedComponent />
    </div>
  );
}
```

## Rule Options

```js
...
"react/no-unstable-nested-components": "off" | "warn" | "error"
...
```

**Comment by ljharb** [comment]
While I agree with the principle of this rule, component detection is very difficult, and this will likely result in a lot of false positives.

**Comment by AriPerkkio** [comment]
I'm starting to realize the difficulty of component detection now. At first I though the `Components.detect(..` would detect most cases, but no.

I've ran this linter to material-ui, ant-design and some other big repositories. I still need to add rule for detecting components declared inside props, e.g. `<Component footer={() => <div />} />`.

Also it seems that renderProps have to be excluded from the rule. I'm not exactly sure how React is handling the renderProps but for some reason they are not causing the _children losing state_ issue.

```jsx
function Menu(props) {
    const Footer = props.footer;
    return (
        <div>
            <h2>Menu</h2>
            {props.children({})}
            <Footer />
        </div>
    );
};

export default function Navigation() {
    return (
        <nav>
            <button onClick={React.useReducer(() => [], [])[1]}>
                Force render
        </button>
            <Menu footer={() => <Accordion>Footer</Accordion>}>
                {(renderProps) => {
                    return (
                        <>
                            <Accordion>About us</Accordion>
                            <Accordion>Contact</Accordion>
                        </>
                    );
                }}
            </Menu>
        </nav>
    );
};
```

In the example above only Footer will hide when force render is clicked. Components inside renderProps remain their state.

**Comment by ljharb** [comment]
render props aren't components, and are usually *called*, not used in an element context, so they don't *have* any state.

**Comment by AriPerkkio** [comment]
>  _called_, not used in an element context.

Thanks, that was exactly the case here. The returned element will always be the same React.Fragment as _a stable reference_.

After adding detection for component inside prop (`<Component footer={() => <div />} />`), a lot of errors came out from various repositories. Now the detection will exclude props which names are prefixed with render, e.g. `<Component renderFooter={() => <div />}`. This seems to be quite common pattern. 

There's also an option which can be used to disable "component in prop" warnings.

---

## Rule Options

```js
...
"react/no-unstable-nested-components": [
  "off" | "warn" | "error",
  { "allowAsProps": true | false }
]
...
```

You can allow component creation inside component props by setting `allowAsProps` option to true. When using this option make sure you are **calling** the props in the receiving component and not using them as elements.

The following patterns are **not** considered warnings:

```jsx
function SomeComponent(props) {
  return <div>{props.footer()}</div>;
}

function Component() {
  return (
    <div>
      <SomeComponent footer={() => <div />} />
    </div>
  );
}
```
---

I've tested this plugin with following repositories successfully.

- [Ant design](https://github.com/ant-design/ant-design)
- [Material UI](https://github.com/mui-org/material-ui)
- [Jira Clone](https://github.com/oldboyxx/jira_clone)
- [Reach UI](https://github.com/reach/reach-ui)
- [React Bootstrap](https://github.com/react-bootstrap/react-bootstrap/)

@ljharb can you think of any edge cases where these false positives could easily happen? I've added quite many test cases to the PR now.

**Comment by ljharb** [comment]
It very much will *not* always be a "stable reference"; a new fragment is created every time it's called, and a new function is passed to the `Menu` component every time `Navigation` renders. In other words, you have the most unstable reference you could possibly create.

**Comment by AriPerkkio** [comment]
I think we are not talking about the same thing here, at least in this context. The only thing that matters is that element type is stable. 

```jsx
function Menu(props) {
  const Footer = props.footer;
  return (
    <div>
      {props.children()}
      <Footer />
    </div>
  );
}

function Component() {
  return (
    <Menu
      footer={function SomeFooter() {
        return <>Footer</>;
      }}
    >
      {() => (
        <>
          <div>About</div>
          <div>Contact</div>
        </>
      )}
    </Menu>
  );
}
```

React reconciler will compare Footer as

- `function SomeFooter() === function SomeFooter()` -> False
- Element type has changed, lets create element again. Remove all children and start over.

And the `props.children` as

- React.Fragment === React.Fragment -> True
- Reuse same element, no need to destroy children.

It doesn't really matter how many times new fragment is recreated. As long as the element type keeps stable.
```js
current.elementType === element.type
```
https://github.com/facebook/react/blob/da834083cccb6ef942f701c6b6cecc78213196a8/packages/react-reconciler/src/ReactChildFiber.js#L407

**Comment by ljharb** [comment]
OK - so by "stable" or "unstable" here, you mean, you want a rule that will warn on any element type (ie, something used as the tag name in jsx, or as the first arg to `React.createElement`) whose identity can change across renders?

**Comment by AriPerkkio** [comment]
Yes, exactly. I'm not sure how `React.createElement` could be detected though. I've never been using that API directly. 
The current PR will detect these cases from JSX only.

**Comment by ljharb** [comment]
There's a bunch of examples of existing rules that do that; rules must only be jsx-specific whenever possible.

**Comment by AriPerkkio** [comment]
Support for `React.createElement` cases added. Tested rule against same repositories mentioned earlier.

**Comment by AriPerkkio** [comment]
In order to identify false positives I've created [a tool](https://github.com/AriPerkkio/eslint-remote-tester) for linting 100's of repositories easily. After scanning [165 repositories](https://github.com/AriPerkkio/eslint-plugin-react/blob/react/no-unstable-nested-components-test/eslint-remote-tester.config.js#L2-L169) against this rule I've identified one false positive caused by `useEffect`'s clean-up function, [link](https://github.com/AriPerkkio/eslint-plugin-react/blob/react/no-unstable-nested-components-test/eslint-remote-tester-results/dnote.md). 
Also it looks like `allowAsProps` detection could be improved. Some components created inside props are not marked with correct error message at the moment. 

Here are all the results, [link](https://github.com/AriPerkkio/eslint-plugin-react/tree/react/no-unstable-nested-components-test/eslint-remote-tester-results).

**Comment by DaniAkash** [comment]
Another common issue we faced while working on nested components is that hooks of the parent component are sometimes used directly in the nested component. This caused a very hard to identify [issue](https://github.com/react-hook-form/react-hook-form/discussions/1744#discussioncomment-20578) in our component

```jsx
const App = () => {

  const [count, setCount] = useState(0)

  const myInternalComponent = () => {
    return ( <div>{count}</div> ) // this will cause issues in some scenarios
  }

  return (
    <div>
      {myInternalComponent()}
    </div>
  )
}
```

**Comment by AriPerkkio** [comment]
Thanks for the comment @DaniAkash. These real-world examples are really valuable.

Based on the [codesandbox example](https://codesandbox.io/s/stupefied-poitras-11y82?file=/src/App.js) there is a nested component `<EditModal />`. This rule will flag that as invalid pattern and mark it as error. Without studying the issue thoroughly, my guess is that the state of `<EditModal />`'s children is reset during every re-render. 

But the pattern of your comment would not be marked as error since element type returned from `{myInternalComponent()}` is always `div`. React will not re-construct the component tree when element type is stable.  Component below however would be considered as an error:

```js
const App = () => {
  const [count, setCount] = useState(0)

  const MyInternalComponent = () => <div>{count}</div>;

  return (
    <div>
      <MyInternalComponent />
    </div>
  )
}
```

**Comment by DaniAkash** [comment]
Yeah, If the internal component has its own state, it leads to a messy situation

```jsx
const App = () => {
  const [count, setCount] = useState(0)

  const MyInternalComponent = () => {
    const [internalCount, setInternalCount] = useState(0) // will reset to zero on re-render of App
    return <div>{internalCount}</div>
  };

  return (
    <div>
      <MyInternalComponent />
    </div>
  )
}
```

**Comment by markerikson** [comment]
Obviously it's going to be about impossible to detect cases where a new component type is being passed in as a prop, but this looks like a very useful rule overall.

**Comment by AriPerkkio** [comment]
The initial post is not up-to-date with current implementation of the PR. 

By default this rule will warn if a component is passed as prop and the prop name doesn't start with `render`, e.g. `renderHeader`. If component name doesn't start with render it is expected that developer is using the prop as element, e.g. `({ header: Header }) => <Header />`. 

Here's the current implementation of rule documentation:  

> By default component creation is allowed inside component props only if prop name starts with `render`. See `allowAsProps` option for disabling this limitation completely.

```jsx
function SomeComponent(props) {
  return <div>{props.renderFooter()}</div>;
}
function Component() {
  return (
    <div>
      <SomeComponent renderFooter={() => <div />} />
    </div>
  );
}
```

## Rule Options

```js
...
"react/no-unstable-nested-components": [
  "off" | "warn" | "error",
  { "allowAsProps": true | false }
]
...
```

> You can allow component creation inside component props by setting `allowAsProps` option to true. When using this option make sure you are **calling** the props in the receiving component and not using them as elements.

**Comment by kylemh** [comment]
It may be easier to implement something with fewer false-negatives in some TS-only equivalent of this plugin? Or maybe we could begin making some rules that are only valid in TS environments?

**Comment by gaurav5430** [comment]
Just to clarify better:

this is a problem:

`const MyComponent = () => <SomeStatefulComponent>`

but this is not a problem:

`const getMyComponent = () => <SomeStatefulComponent>`

**Comment by AriPerkkio** [comment]
@gaurav5430 that's correct. The first one can be used as React Element in JSX, the second one cannot. This rule will only pick up the first one.

**Comment by remus-selea** [comment]
In your example would the `renderCell` function have to be moved outside of the component? If we kept it inside the component and used useCallback, would it be [the same scenario that it warns about in the rule details (described with the uppercase WARNING)](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md#rule-details)?

**Comment by ljharb** [comment]
alternatively, just use concise method syntax instead of an arrow function.
