### ISSUE TITLE
error PropTypes must be placed after render …?

### ISSUE THREAD

**Issue by maketroli** [yannickcr/eslint-plugin-react#275]
All I can say is: WHAT?

How this error is asking me to put PropTypes after the render method ?

Look at the error

    src/components/ChatForm/index.js
       7:3   error  PropTypes must be placed after render                       react/sort-comp
      44:16  error  'onAddMessage' is missing in props validation for ChatForm  react/prop-types

**first PropTypes in the line 7**

      static PropTypes = {
        'onAddMessage' : React.PropTypes.func.isRequired,
      }

I put `.func` because `onAddMessage` is a function...

**then in the line 44**

      _addMessage () {
        this.props.onAddMessage(input.value); // LINE 44
      }

**Comment by epmatsw** [comment]
Do any of the suggestions in [this issue](https://github.com/yannickcr/eslint-plugin-react/issues/43) help?

**Comment by maketroli** [comment]
@epmatsw mmm but how do I adapt it to my code ? sorry, I am very new on this.

**Comment by epmatsw** [comment]
Although I haven't used `static` in my code before, that thread indicates you'll need to use [babel-eslint](https://github.com/babel/babel-eslint) as your parser, and will need to enable es7 features within it. I would refer to the eslint and babel-eslint documentation for instructions on that, although it appears that there are some snippets in the other issue that could be helpful.

Also, it's totally possible that I'm barking up the wrong tree. Just seemed like a similar issue :)

**Comment by maketroli** [comment]
@epmatsw yes I am using babel-eslint. Thanks.

**Comment by yannickcr** [comment]
Actually, this is not `PropTypes` with a "P" but `propTypes` with a "p".

So in your component `PropTypes` is detected as a custom property, and according to your configuration it should be placed after `render`.

Also, since `propTypes` was not defined, `onAddMessage` is missing in props validation.

**Comment by zerkms** [comment]
I also meant `PropTypes` capitalisation at http://stackoverflow.com/questions/33378699/error-proptypes-must-be-placed-after-render?noredirect=1#comment54551612_33378699 but OP mentioned it changes nothing.

**Comment by yannickcr** [comment]
After testing, no more problems after remplacing `PropTypes` with `propTypes`

```js
class Hello extends Component {
  static propTypes = {
    'onAddMessage': React.PropTypes.func.isRequired
  }
  _addMessage() {
    this.props.onAddMessage(input.value);
  }
  render() {
    return <div onCLick={this._addMessage}>Hello</div>;
  }
}
```


Tested with eslint `1.7.1` and eslint-plugin-react `3.6.3`.
