### ISSUE TITLE
Rule idea: Enforce using property destructructuring when properties are referred to N > 1 times

### ISSUE THREAD

**Issue by Intellicode** [yannickcr/eslint-plugin-react#278]
A common pattern that I often see (and like) is to use property destructors in render methods.

React Native:

``` jsx
render() {
  const {
    firstName,
    lastName,
    photo,
  } = this.props;

  return <View>
    <Text>{firstName}</Text>
    <Text>{lastName}</Text>
    <Image source={photo} />
  </View>;
}
```

**Comment by lencioni** [comment]
Since object destructuring is a JavaScript feature and not specific to React, I think this rule would be more appropriate in something more general than a React-specific plugin.

**Comment by ljharb** [comment]
However, #556 and #216 are related, and I could definitely see the value in a rule that required all props and state to always be destructured at the top of component methods.

**Comment by lencioni** [comment]
Yes, definitely.
