### ISSUE TITLE
Extract JSX rules to a new package

### ISSUE THREAD

**Issue by jsphstls** [yannickcr/eslint-plugin-react#2794]
This package is very busy with open issues. Would it help to extract all JSX rules that are non-react specific to a new package? There may not be many candidates but the idea is that any support for those rules and the addition of new rules could be handled elsewhere.

**Comment by ljharb** [comment]
I don't think it would help; having one place with 400 open issues isn't any worse than two places each with 200 open issues.

It would also make it much harder for a jsx-only rule to be enhanced to support React.createElement in the future.
