### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by kawikabader** [yannickcr/eslint-plugin-react#2806]
We are running into an issue that began with `v7.21.0`.

The issue is that when we attempt to run `eslint . --fix`, we get the following error: `TypeError: Cannot read property 'type' of undefined. Occurred while linting /file/to/be/linted`.

If we revert back to `v7.20.x`, we no longer have this issue.

**Comment by viglucci** [comment]
Looks like [this commit](https://github.com/yannickcr/eslint-plugin-react/commit/39307b46783f016892ef999410e87a6755b5426e) was intended to fix this issue but somehow didn't make it into `v7.21.1`?

**Comment by viglucci** [comment]
Oh, I see... that commit is marked as unreleased.

**Comment by ljharb** [comment]
Indeed; duplicate of #2804.
