### ISSUE TITLE
Rule proposal: Sort defaultProps static property

### ISSUE THREAD

**Issue by roadhump** [yannickcr/eslint-plugin-react#281]
It would be nice to force the same order for `propTypes` and `defaultProps` inside class. New rule for this seems like the copy of `jsx-sort-prop-types`, so probably it would be better to extend `jsx-sort-prop-types` to apply to `defaultProps`.

**Comment by b0gok** [comment]
@roadhump it's a very good proposal! 👍 
@lencioni should it be a separate rule or just extension for `jsx-sort-prop-types`?

**Comment by ljharb** [comment]
@b0gok A separate rule, that ideally shares code. A rule called "sort prop types" wouldn't make sense applied to default props - so maybe `jsx-sort-default-props`

**Comment by b0gok** [comment]
@ljharb ok, I'll try to implement it

**Comment by ljharb** [comment]
Fixed in #1483.
