### ISSUE TITLE
Fail fast: Invalid count value

### ISSUE THREAD

**Issue by InsOpDe** [yannickcr/eslint-plugin-react#2819]
I've encountered following error
```bash
npx eslint test.tsx --fix-dry-run --ext .ts,.js,.tsx,.jsx -c .eslintrc.json --no-eslintrc

Oops! Something went wrong! :(

ESLint: 7.10.0

RangeError: Invalid count value
Occurred while linting /home/marcel/Documents/fiddles/eslint-tsx/test.tsx:1
    at String.repeat (<anonymous>)
    at Object.fix (/home/marcel/Documents/fiddles/eslint-tsx/node_modules/eslint-plugin-react/lib/rules/jsx-wrap-multilines.js:167:136)
    at normalizeFixes (/home/marcel/Documents/fiddles/eslint-tsx/node_modules/eslint/lib/linter/report-translator.js:178:28)
    at /home/marcel/Documents/fiddles/eslint-tsx/node_modules/eslint/lib/linter/report-translator.js:343:49
    at Object.report (/home/marcel/Documents/fiddles/eslint-tsx/node_modules/eslint/lib/linter/linter.js:920:41)
    at report (/home/marcel/Documents/fiddles/eslint-tsx/node_modules/eslint-plugin-react/lib/rules/jsx-wrap-multilines.js:130:15)
    at check (/home/marcel/Documents/fiddles/eslint-tsx/node_modules/eslint-plugin-react/lib/rules/jsx-wrap-multilines.js:162:13)
    at ArrowFunctionExpression:exit (/home/marcel/Documents/fiddles/eslint-tsx/node_modules/eslint-plugin-react/lib/rules/jsx-wrap-multilines.js:237:11)
    at /home/marcel/Documents/fiddles/eslint-tsx/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
```
And could narrow it down to following configuration:
```json
//.eslintrc.json
{
	"parser": "@typescript-eslint/parser",
	"plugins": [
		"react",
		"@typescript-eslint"
	],
	"rules": {
		"react/jsx-wrap-multilines": [
			1,
			{
				"arrow": "parens-new-line"
			}
		],
		"no-extra-parens": 0,
		"@typescript-eslint/no-extra-parens": [
			1,
			"all",
			{
				"ignoreJSX": "single-line"
			}
		]
	}
}
```
```tsx
//test.tsx
export const Test = () => (
	<div>
	</div>
)
```
```json
//package.json
{
  "name": "eslint-tsx",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Marcel Michelfelder",
  "license": "MIT",
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.3.0",
    "@typescript-eslint/parser": "^4.3.0",
    "eslint": "^7.10.0",
    "eslint-plugin-react": "^7.21.2",
    "typescript": "^4.0.3"
  }
}
```

Now **after** i figured out what it caused, I found out about the `ignoreJSX` setting in "@typescript-eslint/no-extra-parens".
If I use 
```json
{
	"ignoreJSX": "single-line"
}
```
it works of course. 

But I spent too much time finding this issue - so I thought maybe there is a better solution. Is it possible to display a warning or anything if the `ignoreJSX` setting of the `@typescript-eslint/no-extra-parens` rule is not utilized while the `react/jsx-wrap-multilines` is active?

If not you may close this issue. At least it exists now for others to learn from.

**Comment by ljharb** [comment]
I'm a bit confused. if you only enable jsx-wrap-multilines, and disable all the other rules, what happens?

**Comment by InsOpDe** [comment]
I guess it works as expected.

To clarify, this is not a bug im describing. There are solutions to this problem, im only posting this issue, because it took me a long time to figure out, which would not be the case if the errors would have been more verbose or when either part would have detected that there is a configuration mismatch.

**Comment by ljharb** [comment]
I agree that a better error message would be nice; but suggesting things about an unrelated eslint plugin does not seem appropriate. Do you have a suggestion?

**Comment by InsOpDe** [comment]
For starters we could clarify which rule threw the error.
Then we could add a notice that it might be conflicting with other plugins/rules

**Comment by ljharb** [comment]
That seems like a fine suggestion for eslint itself; there’s nothing a plugin can do about that.

**Comment by InsOpDe** [comment]
Oh I see. Then ill close this :see_no_evil:
