### ISSUE TITLE
`no-unused-vars` warning will not turn off

### ISSUE THREAD

**Issue by jcreamer898** [yannickcr/eslint-plugin-react#282]
I can't seem to get the unused vars warning to go away.

Here's my `.eslintrc`

```json
{
  "parser": "babel-eslint",
  "globals": {
    "$": true,
    "Modernizr": true
  },
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "rules": {
    "quotes": [1, "double"],
    "eol-last": [0],
    "no-mixed-requires": [0],
    "no-underscore-dangle": [0],
    "strict": [0, "never"],
    "no-var": [1],
    "no-unused-vars": [1],
    "react/jsx-uses-vars": 0
  },
  "plugins": [
    "eslint-plugin-react"
  ],
  "ecmaFeatures": {
    "jsx": true
  }
}
```

**Comment by pascalpp** [comment]
@jcreamer898 did you figure this out? i'm having this issue as well.

**Comment by yannickcr** [comment]
@pascalpp I don't know what was the @jcreamer898 solution, but in his configuration the `no-unused-vars` rule is still enabled.

`react/jsx-uses-vars` only "patch" `no-unused-vars` to detect variables used in JSX and has no effect if that last rule is not enabled.
