### ISSUE TITLE
need rule [no-react-default-imports]

### ISSUE THREAD

**Issue by yoyo837** [yannickcr/eslint-plugin-react#2829]
After upgrade to new jsx transform:  https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Comment by ljharb** [comment]
We don't need that rule at all - all you'd need is to disable the `jsx-uses-react` rule and `no-unused-vars` would handle it.

**Comment by merrywhether** [comment]
I think the idea is that developers might be used to doing the following since they had to have the React namespace rollup available to the output of the transform. Now that they `React` is not necessary, it would be nice to enforce this namespace import and push people into destructuring.
```ts
import React from 'react';  // or `import * as React...`

const Foo: React.FC: () => {
  const [bar, setBar] = React.useState();
  ...
```

**Comment by yoyo837** [comment]
Yes, that is what I mean.

**Comment by ljharb** [comment]
That will be automatic once React no longer provides a default export - eslint-plugin-import will catch it. There's no benefit in addressing that before then.

**Comment by yoyo837** [comment]
Got it. Thanks for your reply,

**Comment by merrywhether** [comment]
For anyone looking to write this rule themselves, it's pretty trivial:
```js
ImportDefaultSpecifier(node) {
        if (node.local.name === 'React') {
          context.report(
            node,
            'Do not import React, use import deconstruction instead',
          );
        }
      },
```

Additionally, you can add this if you're using TypeScript (since at least in my repo something has made the React types global):
```js
TSQualifiedName(node) {
        if (node.left.name === 'React') {
          context.report(
            node,
            'Do not use React qualifier, use import deconstruction instead',
          );
        }
      },
```

**Comment by hieuhoangtrung** [comment]
@merrywhether can you please elaborate how to config the rule in typescript?

**Comment by valerii15298** [comment]
You can do it with eslint:
https://stackoverflow.com/questions/75959049/enable-linter-rules-to-use-useeffect-instead-of-react-useeffect-named-expor/75959420#75959420
