### ISSUE TITLE
Enhancement: added option checkKeyMustBeforeSpread of `react/jsx-key`

### ISSUE THREAD

**Issue by morlay** [yannickcr/eslint-plugin-react#2830]
`jsx-runtime` landed. but there have different transform results when key before or after props spread

https://github.com/facebook/react/issues/20031

```jsx
<div key="key "{...props} />;

<div {...props} key="key"/>;

// will convert to 

import { createElement } from "react"
import { jsx } from "react/jsx-runtime"

jsx("div", props, "key")
createElement("div", { ...props, key: "key" }) // only key after props spread do the fallback 
```

to avoid the fallback to using `createElement`, 
need a rule to limit the key before spread.

**Comment by ljharb** [comment]
https://github.com/facebook/react/issues/20031#issuecomment-709559893 suggests the opposite - that the key must be *after* the spread so react can statically know which one will "win".

**Comment by ljharb** [comment]
Let's wait until that issue gets some resolution before implementing anything here.

**Comment by morlay** [comment]
@ljharb Yes. we need waiting. Just put the issue here for tracking.

babel and typescript already have implemented this logic. So i'm not optimistic to they will change it.

and typescript and babel have diffrent fallback results. 

https://www.typescriptlang.org/play?ts=4.1.0-dev.20201015#code/PQKhAIAECsGcA8CSBbADgewE4BcDK6BXTAYwFMpTl1sBLdAO2E1IENjtwRgAobgHlioW9cAG8AdJNSZ0qWAF9wwAHy8BQkRKky5igNakAngF4ARABMWsU0uVA

typescript is not use `createElement` of `@jsxImportSource`, but `React.createElement` direclty.

if nothing changed. This eslint rule is really needed.

**Comment by morlay** [comment]
> [facebook/react#20031 (comment)](https://github.com/facebook/react/issues/20031#issuecomment-709559893) suggests the opposite - that the key must be _after_ the spread so react can statically know which one will "win".

@ljharb they prefer to use `key` _before_  the `spread`. 
see https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-spreading-key-from-objects

When key after the spread, the codes will transformed to using old `createElement` for maybe compatible reason.

**Comment by morlay** [comment]
seems this may a temporary rule until react evolution completed.

maybe as a option of `react/jsx-key`

**Comment by ljharb** [comment]
I like that better.
