### ISSUE TITLE
Some questions on rule/jsx-no-bind.

### ISSUE THREAD

**Issue by tianzhich** [yannickcr/eslint-plugin-react#2831]
Hi all, I understand the purpose of use `jsx-no-bind` rule. And the [pro-tip](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md#lists-of-items) solved most common cases. That was great!

But I also have a case below:

```tsx
interface FormValue {
  name: string;
  phone: string;
  // ... think there are more of formFiled
}

interface MyFormProps {
  value: FormValue
  onChange(value: FormValue): void
}

const MyForm = ({}: { value: FormValue }) => {
  const handleFieldChange(val: any, key: keyof FormValue) {
    onChange({...value, [key]: val})
  }

  return <form>
    <FormItem value={value.name} onChange={handleFieldChange.bind(null, 'name')}>name: </FormItem>
    <FormItem value={value.phone} onChange={handleFieldChange.bind(null, 'phone')}>phone: </FormItem>
    {/* ... */}
  </form>
}
```

Without the arrow function or bind, is there any way to use a single handler for all of the input fields?

**Comment by ljharb** [comment]
Yes - use a class component, and create the handlers in the constructor.

**Comment by tianzhich** [comment]
> Yes - use a class component, and create the handlers in the constructor (or, use the `useCallback` hook).

Thanks for the quick reply. Do you mean to use `useCallback` to wrap the `handleFieldChange`? But I want to use one handler to handle all the inputs change. You may not fully understand my intention.

**Comment by ljharb** [comment]
Yes, you need to use `useCallback` for *each* bound handler, since each one is a distinct callback.

**Comment by tianzhich** [comment]
I definitely agreed with your idea. But it was not good for code reusing.

**Comment by ljharb** [comment]
I'm not sure why you think it's not good, but that's also irrelevant - it's how both JavaScript and React work.

**Comment by tianzhich** [comment]
> Yes, you need to use `useCallback` for _each_ bound handler, since each one is a distinct callback.

I understand what you said about distinct callback to avoid unnecessary rerender, what I mean is the change from this: 

```tsx
interface FormValue {
  name: string;
  phone: string;
  // ... 
}

interface MyFormProps {
  value: FormValue
  onChange(value: FormValue): void
}

const MyForm = ({ onChange, value }: MyFormProps) => {
  const handleFieldChange = useCallback(( key: keyof FormValue, val: string) => {
    onChange({...value, [key]: val})
  }, [onChange])

  return <form>
    <FormItem value={value.name} onChange={handleFieldChange.bind(null, 'name')}>name: </FormItem>
    <FormItem value={value.phone} onChange={handleFieldChange.bind(null, 'phone')}>phone: </FormItem>
    {/* ... */}
  </form>
}
```

which I can reuse the handler for all of the form fields.

to this: 

```tsx
interface FormValue {
  name: string;
  phone: string;
  // ... 
}

interface MyFormProps {
  value: FormValue
  onChange(value: FormValue): void
}

const MyForm = ({ onChange, value }: MyFormProps) => {
  const handleNameChange = useCallback((val: string) {
    onChange({...value, name: val})
  }, [onChange])

  const handlePhoneChange = useCallback((val: string) => {
    onChange({...value, phone: val})
  }, [onChange])

  return <form>
    <FormItem value={value.name} onChange={handleNameChange}>name: </FormItem>
    <FormItem value={value.phone} onChange={handlePhoneChange}>phone: </FormItem>
    {/* ... */}
  </form>
}
```

which I must use two(or more) distinct handlers for that.

**Comment by ljharb** [comment]
Yes, that's true, but that's also ideal from both a programming perspective (single-responsibility principle) and a react rendering perspective (potentially rerendering fewer things).

**Comment by tianzhich** [comment]
Yes, I'm agree with the SRP. Thank you Jordan. I closed this.
