### ISSUE TITLE
Include links to documentation in all lint messages

### ISSUE THREAD

**Issue by Daniel15** [yannickcr/eslint-plugin-react#284]
It would be good to include a link to the documentation in all the lint errors. Currently, the text of the lint rules is very short, and users need to know to go to this repo to view the documentation. ESLint does this well, every lint rule has a page on their site (eg. http://eslint.org/docs/rules/no-self-compare) which makes it easy to link to them.

**Comment by lencioni** [comment]
@Daniel15 I might not be looking in the right place, or I might not be running thins in the right way, but I don't see links to documentation on any ESLint errors when I run eslint in my terminal. Can you give us an example of the command you are running and the output you see?

**Comment by ljharb** [comment]
This is something I think eslint itself should do (if it doesn't already), since eslint rules have a `docs.url` config item, and all of our rules populate that.

**Comment by Daniel15** [comment]
@ljharb - Good catch. I don't think ESLint had that at the time this issue was opened though :)

**Comment by ljharb** [comment]
It surely didn't :-) but it does now!
