### ISSUE TITLE
Examples for react/jsx-indent checkAttributes parameter usage are identical

### ISSUE THREAD

**Issue by ghm-salvarado** [yannickcr/eslint-plugin-react#2845]
In the [documentation for `react/jsx-indent`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md), the correct and incorrect examples for `checkAttributes` usage are identical and one of them needs to be updated:

![image](https://user-images.githubusercontent.com/56175751/97192750-37856180-1776-11eb-9389-bd134db84efe.png)

**Comment by ljharb** [comment]
What I'm seeing in the docs is that one is correct with "false", and the other is incorrect with "true" - which is correct.

**Comment by ghm-salvarado** [comment]
Ah I understand now, thanks for pointing that out. The other examples of correct vs incorrect use the same options between the examples — would it make sense to update the docs to show an incorrect example using `false` and/or a correct example using `true` for consistency?

**Comment by ljharb** [comment]
Sure, that seems reasonable (ie, adding one example for each of true/false to correct/incorrect respectively)

**Comment by framerate** [comment]
Hey guys, I know i'm late to the party but aren't those examples the same?

I'm trying to understand `checkAttributes ` and `indentLogicalExpressions` and this one just isn't clear to me, but I have been staring at lint code for 2 days...

**Comment by ljharb** [comment]
PRs to improve the docs are always welcome, but since they're not incorrect as-is, I'll close this.
