### ISSUE TITLE
Configuration for rule "extends" is invalid

### ISSUE THREAD

**Issue by alanyong91** [yannickcr/eslint-plugin-react#2858]
I got this error:

`.eslintrc: Configuration for rule "extends" is invalid: Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"plugin:react/recommended"')`

How to solve?

**Comment by ljharb** [comment]
Seems like your eslint config is incorrect - `extends` is a sibling of `rules`, not a child of it.

Happy to reopen if it's relevant to this plugin.
