### ISSUE TITLE
react/function-component-definition: add possibility to use "const" instead of "var" for arrow function definition

### ISSUE THREAD

**Issue by sullenor** [yannickcr/eslint-plugin-react#2864]
This one is a feature request. The original implementation uses "var" for an arrow component definition. Thus, when you use this rule to fix existing code, this one will generate replacements with "var" definition https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/function-component-definition.js#L22-L23.

Partially it can be address by adding "no-var" and "prefer-const" rules. But when you apply the transformation manually (like with VSCode), you have to do it multiple times.

Would be nice to add a param to customise this behaviour.

**Comment by ljharb** [comment]
It's not possible for this rule to know what folks have configured - whether they prefer `var`, `const`, `let`, etc - and it's both a best and a common practice to defer things to other rules, especially autofixable ones.

That editors like VSCode often require multiple passes (something the CLI does by default) to autofix everything is a flaw in their implementation, and not something that individual rules can or should address.

**Comment by ianpaschal** [comment]
Disagree. This is a case of a rule being opinionated. And multiple passes don't fix it because of course the second pass tries to change it back to `var`. IMO almost all eslint rules have some configuration available, the ability to define what your preference is, etc. This is _exactly_ such a case.

**Comment by ljharb** [comment]
@ianpaschal any choice is the rule being opinionated. This rule will change it to var - the safest, most backwards compatible choice - and then prefer-const or no-var will tell you to change it again, and you’ll do so, and everything will be fine.
