### ISSUE TITLE
Single component breaks no-multi-comp rule (at 3.7.0)

### ISSUE THREAD

**Issue by tschaub** [yannickcr/eslint-plugin-react#287]
After the 3.7.0 upgrade, we're getting `react/no-multi-comp` errors from files with a single component.

Here is one example in a gist: https://gist.github.com/tschaub/93ca1224ea51140eae30

I'll can try to pare it down to a simpler case, but wanted to create an issue in case it was something obvious.

**Comment by nickstamas** [comment]
3.7.1 fixed https://github.com/yannickcr/eslint-plugin-react/issues/286 for me, but now I'm seeing this error. Throwing the error on this file https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/containers/App/App.js

**Comment by yannickcr** [comment]
I see 2 components in your file `NavbarLink` and `App` so I believe the rule is working.

But an option will be added to `no-multi-comp` to ignore stateless components like `NavbarLink`.
