### ISSUE TITLE
react/jsx-curly-brace-presence autofix removes comments

### ISSUE THREAD

**Issue by blixt** [yannickcr/eslint-plugin-react#2885]
The autofix probably shouldn't delete comments just because the curly braces wouldn't be necessary if the comment wasn't there.

```typescript
{
    /* This is a very important note on the use of the below component. */
    <Component />
}
```

becomes

```typescript
<Component />
```

**Comment by ljharb** [comment]
I agree; I’d say that in this case, the comment makes the curly braces necessary.
