### ISSUE TITLE
New/extended rule: display name --fix for forwardRef

### ISSUE THREAD

**Issue by dantman** [yannickcr/eslint-plugin-react#2898]
When wrapping a component arrow function in forwardRef your component will not get a name. The `react/display-name` rule already gives you a lint error for this issue. However it does not help you auto-fix the issue.

This is also worse in TypeScript because you don't have the option of writing `MyComponent = forwardRef(MyComponent);`. Your only option is to use a function expression or `displayName`, both of which introduce the possibility of giving the component a wrong name which `eslint-plugin-react` will not fix or warn you about.

I would like to propose either a new rule, or an extension to `react/display-name` and/or `react/function-component-definition` that will auto-fix display name issues in forwardRef (and memo) usage.

A wrong display name is a hard to catch mistake. It can be introduced when copy-pasting forwardRef using code, using vscode's F2 variable rename feature which will not rename displayName or function expressions, and simply making a typo when manually writing the display name of a component. And it can be a problem causing error, e.g. if you create a `CurrencyInput` by copy-pasting code from `NumberInput` and forget to update the displayName, then DevTools will list the `<CurrencyInput>` as `<NumberInput>` and when a bug happens in it later you will likely try identifying the bug in the wrong component (I vaguely recollect a scenario like this happening in a real project). But it would be very easy for a lint rule to auto-fix.

I can see the rule auto-fixing these mistakes without any configuration.

```ts
export const A = forwardRef(function B(props: AProps, ref: Ref<unknown>) {
  return null
})

export const A = forwardRef((props, ref) => {
  return null
});
A.displayName = 'B';
```

Additionally when you wrap a component with forwardRef later on. It would be nice if `eslint-plugin-react` auto fixed your now unnamed arrow-function to something with the correct name, like how `react-hooks/exhaustive-deps` helps you.

For example given this component:

```js
export const A = (props) => {
  return null
};
```

If the user wrapped it in forwardRef like so:

```js
export const A = forwardRef((props, ref) => {
  return null
});
```

I would like to see the rule warn and offer to auto-fix it to one of the following (depending on a configuration param):

```js
export const A = forwardRef(function A(props, ref) {
  return null
});

export const A = forwardRef((props, ref) => {
  return null
});
A.displayName = 'A';
```

At which point the component name mistake auto-fixing would help ensure that the user renaming `export const A` to `export const C` won't result in the auto-fixed introduced name duplication being left with the wrong name.

As an aside. `react/function-component-definition` should probably be updated with one more configuration option, what style of function to use in inline forwardRef (and I guess memo) components.

e.g. In my projects I would likely use `namedComponents: arrow-function` but for forwardRef components expect them to be `function-expression` with a name instead of `arrow-function` with a `displayName` .

**Comment by ljharb** [comment]
The challenges include:
 - one rule can’t know about another rule’s config, and the preference for normal or arrow function components can’t be shared
 - forwardRef doesn’t take a component, it takes a render function (function components don’t get a “ref” argument)
 - it’s very uncommon for rules to take autofix-specific configuration
 
 That said, if there’s a way to safely and non-annoyingly make a warning autofixable, I’m happy to do so.

**Comment by dkim-thomas** [comment]
@dantman im having build issues with using React.forwardRef. Can I ask how you are approaching your functional components in typescript?

If I dont use a displayName when using forwardRef I get an eslint error and when I use the displayName property I get a build issue:

**error TS2339: Property 'displayName' does not exist on type**

```
// Sample Component

interface Props {
    id: string,
    className: string,
    onClick: ()=> void
}

const MyComponent = React.forwardRef<
  HTMLUListElement,
  Props
>(({className, id, onClick}, ref) => {
  return (
    <ul ref={ref} className={className} id={id} onClick={onClick}>
        // some code here
    </ul>
  );
});

MyComponent.displayName = "MyComponent";

export { MyComponent };

```

**Comment by dantman** [comment]
> @dantman im having build issues with using React.forwardRef. Can I ask how you are approaching your functional components in typescript?

This has been the only workable solution I could come up with in TypeScript. Using a named function expression.

```ts
export const A = forwardRef(function A(props, ref) {
  return null
});
```

**Comment by dkim-thomas** [comment]
That is what im doing now and it feels slightly dirty. Appreciate the prompt response @dantman

**Comment by davidkim10** [comment]
@dantman circling back on this... not sure if this is a better implementation but seems less dirty

// Component File
interface SomeProps {
  id: string;
  className?: string;
}

const ComponentFwdRef: React.ForwardRefRenderFunction<
  HTMLDivElement,
  SomeProps
> = (props, ref) => <div ref={ref}>Some HTML</div>;

export const MyComponent = React.forwardRef(ComponentFwdRef);

// Usage
const ref = useRef(null);
<MyComponent ref={ref}/>

**Comment by dkim-thomas** [comment]
@dantman circling back on this... not sure if this is a better implementation but seems less dirty

// Component File
interface SomeProps {
  id: string;
  className?: string;
}

const ComponentFwdRef: React.ForwardRefRenderFunction<
  HTMLDivElement,
  SomeProps
> = (props, ref) => <div ref={ref}>Some HTML</div>;

export const MyComponent = React.forwardRef(ComponentFwdRef);

// Usage
const ref = useRef(null);
<MyComponent ref={ref}/>

**Comment by dantman** [comment]
@dkim-thomas In that example your `<MyComponent>`'s name in DevTools is actually `<ComponentFwdRef>`.

**Comment by ljharb** [comment]
> That said, if there’s a way to safely and non-annoyingly make a warning autofixable, I’m happy to do so.

Closing, but always happy to accept a PR for this.

**Comment by deerawan** [comment]
Another alternative syntax is using `export as`

```tsx
// This will be the component name displayed in React dev tools
const Button = () => {}

const ButtonWithRef = forwardRef<HTMLButtonElement, ButtonProps>(Button);

// Rename the export to `Button` for consumers <Button />
export { ButtonWithRef as Button }
```
