### ISSUE TITLE
New Rule Proposal: `component-complexity`

### ISSUE THREAD

**Issue by lessenadam** [yannickcr/eslint-plugin-react#2902]
Hey! 

This isn't a new rule per se, but I was looking for a convenient way (or suggestion) to enable the existing [ESLint Complexity](https://github.com/eslint/eslint/blob/master/lib/rules/complexity.js) rule, but only within functions that return JSX. The thought process is that I would like some objective indicator to help developers on my team write simpler, more testable components, without having to turn on complexity for the whole codebase.

I just need a way to check that a `node` is a `component`, which is possible with `components.get(node)`, and then can apply the same root logic that exists within the complexity rule.

I thought about selectively applying the complexity rule to only directories where components are expected to live, but I've found that to not be sustainable :) 

Grateful for your thoughts, thanks!

**Comment by ljharb** [comment]
Generally i disable the complexity rule, as it does not, in my experience, help people produce simpler, more readable/testable code.

Component detection is tricky, so you’d surely want such a rule to leverage this plugin’s detection code. However, I’m very skeptical that it would have the desired effect.

**Comment by lessenadam** [comment]
Ok, those are fair points. I also go back and forth about the efficacy of the rule, but I have seen it prevent rather egregious components with a good signal to noise ratio.

As far as I can tell, the component detection methods aren't exported. I'll go ahead and close the issue, and look at adding this to a personal eslint plugin. 

Thanks for the consideration!

**Comment by ljharb** [comment]
They’re files on disk, which means they’re part of the api - like any other package, you can deep import whatever you like.

**Comment by lessenadam** [comment]
Whoa, TIL about deep imports - not a particularly well documented aspect of npm modules. This will help a ton, thanks!
