### ISSUE TITLE
Feature request: autofix jsx-no-bind by wrapping target function with React.useCallback()

### ISSUE THREAD

**Issue by buhichan** [yannickcr/eslint-plugin-react#2907]
After add jsx-no-bind to my .eslintrc, I find myself write a lot React.useCallback, but the task is really simple, just 3 steps:

- step1: wrap the inline function by a layer of useCallback.
- step2: use plugin:react-hooks's autofix to autofill the deps array.
- step3: if the useCallback is called conditionally, move it up to a none conditional location.

So I think maybe it's helpful if there is an autofix to automatically complete step1, which is just repetitive and simple.

**Comment by ljharb** [comment]
That wouldn’t be useful unless someone is using a new enough react that it has hooks, and unless it was in a function component, since only SFCs can have hooks. I don’t think that’d be broadly useful enough to be a rule, and i also am very skeptical such a large refactor would be safe to do as an autofix.

**Comment by buhichan** [comment]
> That wouldn’t be useful unless someone is using a new enough react that it has hooks, and unless it was in a function component, since only SFCs can have hooks. I don’t think that’d be broadly useful enough to be a rule, and i also am very skeptical such a large refactor would be safe to do as an autofix.

I think eslint-plugin-react already knows current react version, because there is `setting.react.version = "detect" | string` in .eslintrc, I don't know if I am right.

And eslint can know if the current callback is in React Functional Component or Class Component, just like how eslint-plugin-react-hooks did.

It's unsafe if I use `eslint --fix ./src`, yes, but if the autofix cause any invalid syntax, like conditional hook call, or missing deps array, it will be caught by eslint-plugin-react-hooks.

So maybe this autofix could be a feature of eslint-plugin-react-hooks? But it's also related to jsx-no-bind rule.

It's only useful if user use new enough react that has hooks and also has eslint-plugin-react-hooks enabled

**Comment by ljharb** [comment]
That is true that we know the version, as well as what kind of component it is.

We can't assume people are using eslint-plugin-react-hooks - any autofix that would break things absent that plugin isn't safe outside that plugin. It seems like this might be a better fit for that plugin.

**Comment by buhichan** [comment]
> That is true that we know the version, as well as what kind of component it is.
> 
> We can't assume people are using eslint-plugin-react-hooks - any autofix that would break things absent that plugin isn't safe outside that plugin. It seems like this might be a better fit for that plugin.

You are right.
