### ISSUE TITLE
[react/no-array-index-key] Case is described in the doc is not accurate.

### ISSUE THREAD

**Issue by SyMind** [yannickcr/eslint-plugin-react#2909]
> In cases where the array is sorted or an element is added to the beginning of the array, the index will be changed even though the element representing that index may be the same. This results in unnecessary renders.

In React, to prevent unnecessary renders is depend on `shouldComponetUpdate` or `memo`.

In this issue https://github.com/facebook/react/issues/1342#issuecomment-39230939,

> key is not really about performance, it's more about identity (which in turn leads to better performance). randomly assigned and changing values are not identity.

When the array is sorted or an element is added to the beginning of the array and the element has it's own state, the element will render unexpectedly. I think that's the point.

**Comment by ljharb** [comment]
Rendering unexpectedly is an unnecessary render. The docs seem correct to me.
