### ISSUE TITLE
Relay Mutations getting linted as React Components

### ISSUE THREAD

**Issue by joshthecoder** [yannickcr/eslint-plugin-react#291]
Seeing lint errors mainly for prop-types and sort-comp rules
for classes that extend Relay.Mutation.

Started happening with 3.7 release.

**Comment by tylermcginnis** [comment]
I'm getting errors on both of those as well but without extending Relay.Mutation, just normally with `createClass`.

**Comment by yannickcr** [comment]
Can you give me a code sample that trigger invalid lint errors ?

**Comment by tylermcginnis** [comment]
I don't want to highjack this issue so I'll open a different issue.

**Comment by joshthecoder** [comment]
This snippet seems to trigger the issue:

```
import { Mutation } from 'react-relay';

export default class MyMutation extends Mutation {
  static fragments = {
  }

  getVariables() {
    this.props.foo;  // This seems to trigger the issue.
  }
}
```

**Comment by taion** [comment]
Possibly related to #295.

**Comment by taion** [comment]
Thanks!
