### ISSUE TITLE
Rule messages not defined in meta properties

### ISSUE THREAD

**Issue by acdvs** [yannickcr/eslint-plugin-react#2915]
Is there a reason some rule messages aren't defined through the meta properties, or is this just a small oversight? For example, `jsx-indent` and `jsx-indent-props` have their messages defined in the `create` function.

Is there any interest in converting these to use the meta message property to make writing tests easier in the future?

**Comment by ljharb** [comment]
If this works (or gracefully degrades) in all supported eslint versions (v3 through v7), then it's an oversight that it's not everywhere.

If it doesn't work, it's a bug that it's used anywhere.

A PR to fix it would be most appreciated.

**Comment by acdvs** [comment]
Ok great. I can probably get a PR up for this within a day or two.

**Comment by ljharb** [comment]
Turns out this further broke eslint < v4.15, since v4.15 added `messageId` support, but we weren't testing on eslint 3 so we didn't catch it. #2562 will restore support for it.
