### ISSUE TITLE
Default values for the React /jsx-filename-extension rule 

### ISSUE THREAD

**Issue by 97Yates05** [yannickcr/eslint-plugin-react#2919]
TSX files and JSX files should be equivalent, shouldn't TSX files contain JSX syntax for granted.Every time I need this configuration，'react/jsx-filename-extension': [1, { extensions: ['.tsx', '.jsx'] }].Is this unnecessary behavior

**Comment by ljharb** [comment]
Perhaps you’re asking about the airbnb config?

Either way, defaults for a react plugin imply jsx, they do not imply typescript.
