### ISSUE TITLE
Missing brackets on "jsx-indent" readme page

### ISSUE THREAD

**Issue by Evolveye** [yannickcr/eslint-plugin-react#2922]
Hello, I found small typo (missing curly bracket) on "jsx-indent" page.
I cannot fix it by myself, so I'm writing here about it

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md

```jsx
// some content...
// and then...


// [2, 2, {checkAttributes: true}]
<App render={
  <Hello render={
    (bar) => <div>hi</div>
}
  />
</App>

// [2, 2, {indentLogicalExpressions: true}]
<App>
  {condition && (
  <Hello />
  )}
</App>
```

**Comment by ljharb** [comment]
thanks, you're correct.
