### ISSUE TITLE
react/jsx-no-target-blank should allow noreferrer when allowReferrer is true

### ISSUE THREAD

**Issue by edemaine** [yannickcr/eslint-plugin-react#2924]
[The spec](https://html.spec.whatwg.org/multipage/links.html#link-type-noreferrer) says that `noreferrer` implies `noopener`, so it should always suffice to write just `rel="noreferrer"`.

However, if you configure rule `react/jsx-no-target-blank` to `allowReferrer`, then links with `rel="noreferrer"` specified fail, even though it's equivalent to `rel="noreferrer noopener"`.

Confusingly, the error message says `Using target="_blank" without rel="noreferrer" is a security risk` which makes it particularly tricky to figure out what's going on.  (In my case, I forgot that I'd turned on `allowReferrer`.)  I imagine it's not possible to configure the error message depending on the configuration?

Related discussion in #2054.

**Comment by ljharb** [comment]
I think configuring the error message should be trivial; as for allowing noreferrer to exist alone, that was very intentionally disallowed, but was relaxed in #2043.
