### ISSUE TITLE
Disable jsx-uses-react and react-in-jsx-scope when React 17.0

### ISSUE THREAD

**Issue by araujogui** [yannickcr/eslint-plugin-react#2928]
The `jsx-uses-react `and `react/react-in-jsx-scope` rules are no longer necessary after React's 17.0.0 release. Thereafter, it's compiler's `JSX Transform` job to automatically import the applicable React entry point.
 
Read: [Introducing the New JSX Transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)

**Comment by ljharb** [comment]
Just because someone is using react 17 doesn’t mean they’re using the new transform, and just because someone is using react 16 doesn’t mean they’re not using the new transform.

Perhaps a plugin-global setting could be used for this, but it’d have to be explicit.

**Comment by lexanth** [comment]
The docs could at least have "when using the new transform" in the "when not to use it" section.

**Comment by ljharb** [comment]
@lexanth that sounds like a great improvement; want to make a PR to those rules' docs?

**Comment by ljharb** [comment]
This is done.
