### ISSUE TITLE
new rule react/fc-props-destructuring

### ISSUE THREAD

**Issue by Kepro** [yannickcr/eslint-plugin-react#2938]
Controlling The Flow In Props With Destructuring And Spread Attributes
What are the benefits in using props.something versus something?

Without destructuring
```typescript
const Display = (props) => <div>{props.something}</div>
```
With destructuring
```typescript
const Display = ({ something }) => <div>{something}</div>
```
With destructuring, you're not only making your code more readable for yourself and others but you're also making straight forward decisions on what goes in and what goes out. When other developers edit your code in the future, they don't have to scan through each line of code in your render method to find all of the props that the component is using.

You also benefit from the ability to declare a default props right from the beginning without having to add any more lines of code:
```typescript
const Display = ({ something = 'apple' }) => <div>{something}</div>
```

**Comment by ljharb** [comment]
I’m not sure what this issue is asking for.

Sometimes destructuring is not clearer to read, although usually i find it to be. A rule that forces this is worth considering.

Using default arguments instead of default props, however, is not a good thing - defaultProps can be read from the outside, default arguments can not - and i would be strongly against any rule that pushed people away from .defaultProps.

**Comment by Kepro** [comment]
to force "destructing of props" for functional components if it's possible, about defaultProps it's just another reason, why do it, not replace defaultProps

**Comment by ljharb** [comment]
Because defaultProps is better than default arguments.

**Comment by Kepro** [comment]
okay, but stick to the original idea about destructing props (side note: default props are at the end of the file, so need to scroll down to see them, but different discussion)

**Comment by ljharb** [comment]
The title says “spreading” but there’s no spread being used here, so i was confused by the initial post.

I would be in support of a rule that required all props, state, and context to be destructured at the top of the function/method in which they are used, or in the signature for SFCs. I would not be interested in a rule that only targets SFCs.

**Comment by Kepro** [comment]
sorry destructing 🤦  well that sounds interesting for all props, state, and context to be destructed and must be on top

**Comment by ljharb** [comment]
SFCs also take a second `context` argument, so you might want to destructure that too when it’s used.

**Comment by Kepro** [comment]
yes, but it's also a legacy API (I never used it), but why not

**Comment by RaddishIoW** [comment]
I was just investigating writing my own ESLint rule for this very thing when I came across this proposal!
I'd be very much in favour of this, although I think keeping it to destructuring props in FC signatures makes sense. If there was another rule enforcing destructuring of state, context, etc. then so be it - but keeping a rule simple and precise in target makes more sense to me. IMHO.

**Comment by RaddishIoW** [comment]
I would add that there is this rule: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md
It is *almost* the same?

**Comment by ljharb** [comment]
Thanks; I _thought_ we had one that did that :-)
