### ISSUE TITLE
Is there a rule to catch implicitAnys in TypeScript useCallbacks

### ISSUE THREAD

**Issue by charliematters** [yannickcr/eslint-plugin-react#2939]
The @types/react package declares the useCallback method in a way that stops it being checked by TSC's `noImplicitAny` check. Is there a linting rule to catch these methods?

```typescript
 const callback = React.useCallback((implicitlyAny) => { // <- No Error
    console.log(implicitlyAny)
  }, [])

  const func = (implicitlyAny) => { // <- Error
    console.log(implicitlyAny)
  }
```
[Link to Typescript Playground](https://www.typescriptlang.org/play?ssl=11&ssc=4&pln=5&pc=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQLABQ9BArgHb7AQtwBir7nAYRKQWWFjAAUASjgBvevThxcnVPFzIANpoBGeANZwAvJiowAdE1RYBW3QYkTQYTcFzAYmgJ4BBFl5kjAD45RSVlVQhNLHNNCABzJ3BXd09ffykwgF8AGjgAbQBdTIY6JRUWNThmNmM4JJc3D28-AOMQ+TLwitQomLjE5xTm9IDs+iygA)

**Comment by ljharb** [comment]
We do not generally make rules that are useless to people using JavaScript.

If the types are causing an issue, I’d file a PR on DT to fix them.

**Comment by charliematters** [comment]
Fair enough - thanks!
