### ISSUE TITLE
babel-eslint is deprecated

### ISSUE THREAD

**Issue by muuvmuuv** [yannickcr/eslint-plugin-react#2940]
Can you bump this to `@babel/eslint-parser`?

**Comment by ljharb** [comment]
You mean in the tests? I’m sure we could add the new one (we can’t drop the old one, of course, as that would be a breaking change).

Is there a case you know of where it would produce a different result?

**Comment by muuvmuuv** [comment]
I just see the deprecation warning when installing through pnpm, so I just wanted to tell you ^^. Since it's only for testing why would it be a breaking change? It does not affect the code, only the test environment, right?

**Comment by ljharb** [comment]
That sounds like a pnpm bug then - babel-eslint is a dev dep, and the only time dev deps should be installed is when you're developing this package itself.

It would be a breaking change because we'd no longer be regression-testing for babel-eslint users.

**Comment by muuvmuuv** [comment]
Yes, you are totally right. I have really overseen that point :D I will create an issue on pnpm
