### ISSUE TITLE
jsx-max-props-per-line rull works without tabs

### ISSUE THREAD

**Issue by NIRumiantsev** [yannickcr/eslint-plugin-react#2942]
Hi everybody! 
I have a problem with jsx-max-props-per-line and jsx-first-prop-new-line eslint rulls. I have this config and everything actullly works correct: 

`{
  "extends": [
    "react-app",
    "prettier"
  ],
  "rules": {
    "jsx-quotes": [
      1,
      "prefer-double"
    ],
    "react/jsx-first-prop-new-line": [1, "multiline"],
    "react/jsx-max-props-per-line": [1, {"maximum": 1}],
    "react/jsx-closing-bracket-location": 1
  },
  "plugins": [
    "prettier"
  ]
}`

BUT! When my linter creates new lines for multiple props it doesnt use tabs as I expected. For example:
![image](https://user-images.githubusercontent.com/57686430/110240089-44ebfd00-7f5b-11eb-9ccf-a68b2a117de1.png)

And I expect something like: 
![image](https://user-images.githubusercontent.com/57686430/110240105-533a1900-7f5b-11eb-844c-2efc18d070f7.png)

Have you ever deal with such issue?

**Comment by ljharb** [comment]
Tabs vs spaces is handled by the indent and react/jsx-indent rules.

Rules can’t access other rules’ settings, and autofixes are expected to work in concert.

**Comment by NIRumiantsev** [comment]
> react/jsx-indent-props
Thanks a lot!

**Comment by EricWong1994** [comment]
add these code below in your eslintrc file's rule part will resolve your problem.
`  'react/jsx-indent': [2, 2], `
`    'react/jsx-indent-props': [2, 2],`
