### ISSUE TITLE
Optional Chaining report destructuring-assignment

### ISSUE THREAD

**Issue by yoyo837** [yannickcr/eslint-plugin-react#2956]
`"eslint": "7.23.0"`
`"eslint-plugin-react": "7.23.1"`

```jsx
render: val => {
  //
  //
  //
  //
  if (val?.url) {
    return (
      <a href={val.url} rel="noopener noreferrer" target="_blank">
        {val.fileName || 'PDF'}
      </a>
    );
  }
  return null;
},
```
Screenshot:

![image](https://user-images.githubusercontent.com/6134547/112786322-9124eb80-9088-11eb-9c86-9f1854e3dfbe.png)

However, if change it to the following, there is no such problem as above:

```jsx
render: val => {
  //
  //
  //
  //
  if (val?.url) {
    return (
      <a href={val.url} rel="noopener noreferrer" target="_blank">
        {val.fileName || 'PDF'}
      </a>
    );
  }
  // return null; Comment this line
},
```
Screenshot:

![image](https://user-images.githubusercontent.com/6134547/112786511-fe388100-9088-11eb-8fb4-ee59a03d3733.png)

**Comment by ljharb** [comment]
I'm a bit confused. Why do you have a render _arrow function_, ever?

What's the context here? Is this a class component? Class components' render functions never, ever get called with a single argument.

**Comment by yoyo837** [comment]
I’m sorry. The background is to use a react ui library component, which has a render api. https://ant.design/components/table/#components-table-demo-basic

**Comment by ljharb** [comment]
I'm afraid that doesn't help me. A component either is a function, or is a class that has a `render` method. `render` takes no arguments.

Can you please provide the entire code that surrounds this `render` function? Like, the entire contents of the file?

**Comment by yoyo837** [comment]
Does this link help you: https://codesandbox.io/s/ll33o ?

**Comment by ljharb** [comment]
Yes, thank you. In that case, those `render` functions shouldn't be detected as components, despite returning jsx, since they're not defined as part of a createClass or a class component.

**Comment by randyshoopman** [comment]
I'm also seeing this issue.  Wasn't a problem in 7.22.0.  Appeared when upgrading to 7.23.1
