### ISSUE TITLE
Problem with finding the right rules for jsx identation

### ISSUE THREAD

**Issue by sanstream** [yannickcr/eslint-plugin-react#2981]
Right now our current configuration accepts this as OK style for jsx code:

```
      {title &&
        (
          <Title
            tag="label"
            htmlFor={id || name}


            type="menu"
            text={`${title}:`}
          />
        )} // aligns with the '(' above...
```

This code does not neat (in our opinion ;-) )

And needs to look like this:
```
{title && ( // all { and ( on the same line..
  <Title
    tag="label"
    htmlFor={id || name}
    type="menu"
    text={`${title}:`}
  />
)} // all { and ( on the same line..
```

but we can't figure out the eslint config for this.
Can anyone help?

This is the [current config](https://gist.github.com/sanstream/e8a04af7b5b14cf637e3bde5c09cf396) that we've got applied.

**Comment by sanstream** [comment]
Yes, airbnb is what was used before and nobody liked it. 😂, but thanks for the suggestion.

**Comment by ljharb** [comment]
Sure, but you can override what you like, or you could copy the parts of its config that you like, if it indents the way you like.

**Comment by ljharb** [comment]
This seems answered.
