### ISSUE TITLE
`jsx-no-target-blank` does not accept `noopener` keyword

### ISSUE THREAD

**Issue by meeq** [yannickcr/eslint-plugin-react#2983]
The rule enforces `noreferrer`, but it should also accept `noopener`.

As per the [HTML Living Standard on Links (§4.6.6.13 Link type "noopener")](https://html.spec.whatwg.org/multipage/links.html#link-type-noopener):

> The [`noopener`] keyword indicates that any newly created top-level browsing context which results from following the hyperlink will not be an auxiliary browsing context. E.g., its `window.opener` attribute will be null.

> [`noreferrer`] indicates that no referrer information is to be leaked when following the link and also implies the `noopener` keyword behavior under the same conditions.

As per the [OWASP Cheatsheet on Reverse Tabnabbing](https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#tabnabbing):

> To summarize, it's the capacity to act on parent page's content or location from a newly opened page via the back link exposed by the opener JavaScript object instance.

> To cut this back link, add the attribute `rel="noopener"` on the tag used to create the link from the parent page to the child page. 

While OWASP does _suggest_ also adding `noreferrer`, there are legitimate scenarios where sending the referrer is intended.

The purpose of this rule is to mitigate a security risk. If the maintainers wish to provide a means to enforce `noreferrer`, there should be an option or a separate rule.

**Comment by ljharb** [comment]
Duplicate of #2924. Fixed in #2925.
