### ISSUE TITLE
eslint-plugin-react不支持实验性语法proposal-class-properties？

### ISSUE THREAD

**Issue by Camille7782** [yannickcr/eslint-plugin-react#2984]
在create-react-app中，运行npx eslint --init生成eslintrc文件过程中，会要求安装eslint-plugin-react，安装完成后就不支持proposal-class-properties语法了，怎么解决？安装@babel/eslint-parser？

**Comment by ljharb** [comment]
Class Fields are only recently stage 4, which means eslint itself doesn't support them yet.

Once it does, this plugin will already support it, and if you use the babel or typescript parsers, it supports it already as well.

**Comment by ljharb** [comment]
It means you don't need the eslintrc file, yes - CRA handles that for you.

**Comment by Camille7782** [comment]
> It means you don't need the eslintrc file, yes - CRA handles that for you.

but what if I'm using prettier and eslint-config-prettier at the same time, where should I config my prettier settings override eslint settings without eslintrc file

**Comment by Camille7782** [comment]
thanks for sharing your experiences, they are helpful to me and i'll try

**Comment by Camille7782** [comment]
correct solution:
`"parser": "babel-react",`

**Comment by Camille7782** [comment]
> correct solution:
> `"parser": "babel-react",`

actually, which parser should be used depends on what parser has been installed.
currently project create by `create-react-app` should config the parser like this:
`parser: 'babel-eslint',`
