### ISSUE TITLE
[Docs] react/no-unescaped-entities docs don't mention all forbidden characters

### ISSUE THREAD

**Issue by Slapbox** [yannickcr/eslint-plugin-react#2995]
Single quotes are seemingly forbidden by default, but not listed https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md#forbid

**Comment by ljharb** [comment]
It is indeed listed - `'\''` under https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md#forbid, and also under "The preferred way to include one of these characters is to use the HTML escape code.".

**Comment by Slapbox** [comment]
Whoops I'm blind. Thanks @ljharb and sorry for the garbage issue.
