### ISSUE TITLE
Non Empty component  violating self-closing-comp

### ISSUE THREAD

**Issue by BerkeleyTrue** [yannickcr/eslint-plugin-react#3]
eslint 0.14
eslint-plugin-react 1.2.1

unless my eyes deceive me, this shouldn't be a problem.
![1__tmux](https://cloud.githubusercontent.com/assets/6775919/6098686/86de9a24-af9b-11e4-8a5a-8a7987281fed.png)
![1__tmux](https://cloud.githubusercontent.com/assets/6775919/6098744/c54c2730-af9c-11e4-9e11-c0c47ea33bb1.png)

this works
![1__tmux](https://cloud.githubusercontent.com/assets/6775919/6098725/438906e6-af9c-11e4-88d1-7ea2ee5a43e2.png)

but this doesn't
![1__tmux](https://cloud.githubusercontent.com/assets/6775919/6098743/af1bacc4-af9c-11e4-994b-72c94c2b6853.png)

seems like this rule is checking for white space not true emptiness. 
sanity check
![1__tmux](https://cloud.githubusercontent.com/assets/6775919/6098708/05092180-af9c-11e4-986b-7456ad672e02.png)

**Comment by yannickcr** [comment]
Thanks for the report, the rules did not check correctly the node children.

This should be fixed in v1.2.2

**Comment by BerkeleyTrue** [comment]
Wow! Thanks for the quick response!
