### ISSUE TITLE
Not detecting react key in props spreading.

### ISSUE THREAD

**Issue by peymil** [yannickcr/eslint-plugin-react#3010]
```
  const Example = () => {
    const obj = {
      key: 14 as React.Key,
      className: 'element',
    };
    const elements = ['javascript', 'golang', 'ruby'];
    return elements.map((lang) => <div {...obj}>{lang}</div>);
  };
```
![image](https://user-images.githubusercontent.com/28509859/122884715-1433a600-d347-11eb-90a0-af5a57cb9dc0.png)

I wanted to give key to my mapped JSX element's using object spreading but eslint couldn't recognize the key inside the object.

**Comment by ljharb** [comment]
That's because eslint is doing static analysis. You shouldn't be spreading `key` in, for this reason, but also, you shouldn't be spreading that object in anyways. It's better if those are all defined inline.

**Comment by peymil** [comment]
> That's because eslint is doing static analysis. You shouldn't be spreading `key` in, for this reason, but also, you shouldn't be spreading that object in anyways. It's better if those are all defined inline.

I'm using lots of props in my component so defining them inline will take up a lot of space.I worked around defining only key prop, inline.


As i understand analysis of spread props is only possible with update of eslint. So this issue is out of project's scope. I'm closing the issue.

**Comment by ljharb** [comment]
It should take an identical amount of space if it's only got the one usage site - a multiline jsx element takes up the same space as a multiline object, but without the runtime overhead of creating and spreading an object.
