### ISSUE TITLE
eslint does not report that CSS file is not included or not used

### ISSUE THREAD

**Issue by slimandslam** [yannickcr/eslint-plugin-react#3017]
1. In React, you often create a component in a JS file, e.g. MyComponent.js, and then create a companion CSS file, e.g. MyComponent.css . I was surprised that eslint does not report anything if you fail to import your CSS file in your MyComponent.js file:

`import "./MyComponent.css"; `

This can be obvious sometimes, but often life can go on for a while before you realize that you never actually imported the CSS file.  :-)

2.  I was surprised that I could have CSS files in my React project that were not included by any JS file, but eslint did not report  "MyComponent.css is not included in a JS file" .

**Comment by ljharb** [comment]
This approach is "CSS Modules", and is very much not universal. It would not make any sense whatsoever for this general-purpose React plugin to have any special handling of imports of something node itself doesn't support.

You should not be surprised by that - CSS files are not actually *importable*, so it wouldn't make sense to warn on a non-imported CSS file.

**Comment by slimandslam** [comment]
It’s the method suggested in the official React docs and seems to be, by far, the dominant approach.

`React does not have an opinion about how styles are defined; if in doubt, a good starting point is to define your styles in a separate *.css file as usual and refer to them using className`

**Comment by ljharb** [comment]
“Refer to them using className” is in no way “import them using nonstandard webpack-only loaders”.

**Comment by slimandslam** [comment]
Ok. What about reporting if className=“foo” actually actually has access to foo?

**Comment by ljharb** [comment]
That’s impossible, since the source of that css could be from literally anywhere - again, you’re assuming that a local .css file has any necessary affect on the resulting page.
