### ISSUE TITLE
[feature request] no-inline-styles

### ISSUE THREAD

**Issue by fgblomqvist** [yannickcr/eslint-plugin-react#3019]
The rule that's implemented here:
https://github.com/buythewhale/eslint-plugin-react-extra/blob/master/docs/rules/no-inline-styles.md
Would be a great addition to this lib I think. The above lib is unmaintained and only adds that single rule.

There's an up-to-date fork here that should make it very easy to integrate the rule here:
https://github.com/sgtsquiggs/eslint-plugin-react-extra

Thoughts?

**Comment by ljharb** [comment]
That link has no rationale - what is the difference between an inline object and an object referenced by a variable close by?

**Comment by fgblomqvist** [comment]
I can agree on that. We mainly use it as a "don't use inline styles at all" rule, but I realize now that it does allow using a variable 🤷‍♂️. How about a rule that simply prohibits use of the `styles` prop?

**Comment by ljharb** [comment]
That already exists: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-dom-props.md

**Comment by fgblomqvist** [comment]
Excellent, missed that. Thank you!
