### ISSUE TITLE
Remove "react/react-in-jsx-scope" from recommendations

### ISSUE THREAD

**Issue by fractionalJoe** [yannickcr/eslint-plugin-react#3021]
As of React 17, this is no longer needed and the recommendation is that this import be removed. https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports

**Comment by ljharb** [comment]
Those using the new jsx transform - which react 17+ users still might not use - should extend `react/jsx-runtime`.

Removing this from the recommended config would break users who aren’t using the jsx runtime.

**Comment by fractionalJoe** [comment]
Thanks @ljharb. I'm new to this plugin and can't find this answer in the readme, but looking at the [code](https://github.com/yannickcr/eslint-plugin-react/blob/c8917b0885094b5e4cc2a6f613f7fb6f16fe932e/index.js#L163) the `react/jsx-runtime` config appears to be an "override" of `react/recommended`. Is the recommendation to those using the new JSX transform to use the following?

```json
{
  "extends": ["eslint:recommended", "plugin:react/recommended", "plugin:react/jsx-runtime"]
}
```

**Comment by ljharb** [comment]
Yes, precisely that.

**Comment by fractionalJoe** [comment]
@ljharb Thanks again.
