### ISSUE TITLE
RFC: Warn on ref/useref in dependency array

### ISSUE THREAD

**Issue by qpwo** [yannickcr/eslint-plugin-react#3030]
(Searched for this and couldn't find it.)

Would be helpful if `react-hooks/exhaustive-deps` rule warned you when you put a ref as a dependency to `useEffect`, because this is a common error:

```jsx
function App() {
    const ref = React.useRef()
    React.useEffect(() => { if (ref.current != null) console.log("div rendered!") }, [ref])
    return <div ref={ref}>Contents</div>
}
```

https://jscomplete.com/playground/s732434

**Comment by ljharb** [comment]
That's `eslint-plugin-react-hooks`, not this project.
