### ISSUE TITLE
Is missing in props validation

### ISSUE THREAD

**Issue by ruddi10** [yannickcr/eslint-plugin-react#3031]
I have defined the interface of props of a functional component in a separate file and was trying to use it, but the "Is missing in props validation" error was thrown.

```
const RouteList: React.FC<routeListProps> = ({
  routes,
  error,
}: routeListProps) => {
  const styles = useStyleConfig("ReactWindow", {});
  const {
    globalState: { selectedRoutePath },
    changeRoute,
  } = GlobalStore.useContainer();
  const Row = ({ index, style }: rowParameters) => {
    if (routes.length == 0) return null;
    const { entity_name, chain_name, status } = routes[index];
    const rowStyles = useStyleConfig("Row", {
      variant: selectedRoutePath == chain_name ? "active" : "",
    });
    );
  
  );
};
export default RouteList;

```
```
export interface routeResponse {
  chain_name: string;
  entity_name: string;
  status: string;
}
export interface routeListProps {
  routes: routeResponse[];
  error: string | undefined;
}
```

Error -
![Screenshot from 2021-08-05 01-24-48](https://user-images.githubusercontent.com/56596436/128246198-d3a99680-f029-48a1-9257-b286a1736a21.png)

**Comment by ruddi10** [comment]
Any way to fix this

**Comment by ljharb** [comment]
Nope, there's no way to fix it. Static analysis and eslint is generally limited to only in-file definitions. As such, you can either override the rule, or explicitly reference every propType inline in the file.

**Comment by ruddi10** [comment]
But even for some other files I am having external definitions and it's working fine only this is the file that is throwing error. Also can you please tell me how can I override the rule as you stated above

**Comment by ljharb** [comment]
Ah, in this case it's TypeScript types - so, the typescript parser should be providing those types. I'm not sure if this is a bug, or something expected (I don't really use TS).

`/* eslint-disable-line react/prop-types */` is a standard eslint disable comment.
