### ISSUE TITLE
"Component definition is missing display name" when using `as`

### ISSUE THREAD

**Issue by tu4mo** [yannickcr/eslint-plugin-react#3032]
I'm getting false missing display name error when using `as` typecasting.

```tsx
const Comp = React.forwardRef((props, ref) => <div />) as SomeComponent
Comp.displayName = 'MyCompName'
```

**Comment by ljharb** [comment]
What happens if you do `const Comp: SomeComponent = React.forwardRef((props, ref) => <div />)`? What type is `SomeComponent`?

If you remove the `as SomeComponent`, you don't see the warning?

**Comment by tu4mo** [comment]
I noticed this when I tried [Radix UI Polymorphic](https://www.radix-ui.com/docs/primitives/utilities/polymorphic#basic-example). Unfortunately using `as` is the only way it currently works with TypeScript. Warning goes away when I remove the `as` part.
