### ISSUE TITLE
[feature request] jsx-no-constructed-context-values but for all props

### ISSUE THREAD

**Issue by rhalaly** [yannickcr/eslint-plugin-react#3035]
It will be very helpful to prevent non-stable values for **all** kinds of props to prevent mistakes that can cause needless re-renders. 

For example, to prevent such things:
```
<MySuperHeavyComponent options={{ foo: 'bar'}} />
```

**Comment by ljharb** [comment]
Seems like this is #3037 (formerly #2024), which would make this a duplicate of #1633?

**Comment by rhalaly** [comment]
Yes, it seems to be a duplicate of #1633. Closing

**Comment by vedadeepta** [comment]
ignore my pr here, tagged the wrong issue accidentally, meant to tag 3045.
