### ISSUE TITLE
What does "extend react/jsx-runtime in your eslint config to disable the relevant rules" mean?

### ISSUE THREAD

**Issue by jcollum** [yannickcr/eslint-plugin-react#3052]
I can't tell if I'm missing something or those instructions are unclear. To me that means: 

1. go to your eslintrc.js file 
2. find the `extends` array
3. add the string `"react/jsx-runtime"` to that array

But I tried that and I got 

```
ESLint: 7.32.0

ESLint couldn't find the config "react/jsx-runtime" to extend from. Please check that the name of the config is correct.
```

Tried     "plugin:react/jsx-runtime" and it worked, but the docs don't say anything about it being a plugin. Docs are a little confusing here.

**Comment by pgarciacamou** [comment]
I just want to leave a note for other people.

If you are encountering that adding `plugin:react/jsx-runtime` doesn't work. Make sure it is added after `plugin:react/recommended` in the extends array.

**Comment by beizhedenglong** [comment]
> I just want to leave a note for other people.
> 
> If you are encountering that adding `plugin:react/jsx-runtime` doesn't work. Make sure it is added after `plugin:react/recommended` in the extends array.

Thanks, that works

**Comment by dcherino** [comment]
> I just want to leave a note for other people.
> 
> If you are encountering that adding `plugin:react/jsx-runtime` doesn't work. Make sure it is added after `plugin:react/recommended` in the extends array.

Thanks for this. 
I would like also to add that if you are using 'airbnb-typescript', you need to make sure to add it after this one too.

**Comment by MatiSera** [comment]
Hi. I'm having this error even with the recommendations of the other comments
Here's my extends array
`extends: ["next/core-web-vitals", "eslint:recommended", "plugin:react/recommended", "plugin:react/jsx-runtime"],`

**Comment by chetbox** [comment]
For anyone stuck, I also had to update `eslint-plugin-react`:

    yarn add --dev eslint-plugin-react

**Comment by emorenoSM** [comment]
hmmm still seeing this error

```
$ npx eslint . --fix

Oops! Something went wrong! :(

ESLint: 8.31.0

ESLint couldn't find the config "plugin:react/jsx-runtime" to extend from. Please check that the name of the config is correct.
```

Specifically,
```
// package.json
"devDependencies": {
    ...
    "eslint": "^8.31.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-flow": "^2.29.1",
    "eslint-plugin-jsx": "^0.1.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.4.0",
    "eslint-plugin-standard": "^5.0.0",
    "eslint-plugin-typescript": "^0.14.0",
    ...
```

```
// .eslintrc.json

{
  "parser": "@babel/eslint-parser",
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "env": {
    "node": true,
    "browser": true,
    "es2021": true
  },
  "globals": {
    "Office": true
  },
  "parserOptions": {
    "ecmaVersion": 9,
    "requireConfigFile": false,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": ["react", "jsx", "flow", "typescript"],
  "rules": {
    "quotes": ["error", "single"],
    "react/jsx-uses-react": "warn",
    "react/jsx-uses-vars": "warn",
    "no-console": "off",
    "no-extra-semi": ["off"],
    "semi": ["warn", "always"],
    "no-unused-vars": ["warn"],
    "no-unused-expressions": [
      0,
      {
        "allowTernary": true,
        "allowShortCircuit": true,
        "allowTaggedTemplates": true
      }
    ]
  },
  "extends": [
    "plugin:react/recommended",
    "plugin:react/jsx-runtime",
    "plugin:prettier/recommended"
  ]
}

```

**Comment by ljharb** [comment]
@emorenoSM do `npm install --save eslint-plugin-react`, 7.4 is way too old.
