### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [yannickcr/eslint-plugin-react#3055]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

**Comment by ljharb** [comment]
Support will wait until an actual release (betas don’t count).

**Comment by UziTech** [comment]
Actual release has happened.

**Comment by skedwards88** [comment]
Until this is resolved, it would be helpful to update the installation instructions on https://www.npmjs.com/package/eslint-plugin-react. (Right now, they do not mention that eslint version 8 is not supported, so if you follow the installation instructions as given, you get an error.)

**Comment by ljharb** [comment]
@skedwards88 sure, done in bf089982, but it won't likely be published until we support eslint 8 anyways.

**Comment by silkfire** [comment]
@ljharb Will you push a release soon?

**Comment by ximex** [comment]
@silkfire i would say the will: https://github.com/yannickcr/eslint-plugin-react/commit/21e01b61af7a38fc86d94f27eb66cda8054582ed

**Comment by ximex** [comment]
on npm already released: https://www.npmjs.com/package/eslint-plugin-react/v/7.27.0

**Comment by gajus** [comment]
Thank you everyone 🤗
