### ISSUE TITLE
jsx-no-target-blank -> hasExternalLink does not handle attr.value of null

### ISSUE THREAD

**Issue by gaz77a** [yannickcr/eslint-plugin-react#3066]
### Scenario
Add the following test to the valid section of **test/lib/rules/_jsx-no-target-blank.js_**
`{code: '<a href target="_blank"/>'},`

### Symptoms
The following error occurs
**_TypeError: Cannot read property 'type' of null_**

### Resolution
Add` attr.value &&` before `attr.value.type === 'Literal'`

here is the updated function
`function hasExternalLink(node, linkAttribute, warnOnSpreadAttributes, spreadAttributeIndex) {
  const linkIndex = findLastIndex(node.attributes, (attr) => attr.name && attr.name.name === linkAttribute);
  const foundExternalLink = linkIndex !== -1 && ((attr) => attr.value && attr.value.type === 'Literal' && /^(?:\w+:|\/\/)/.test(attr.value.value))(
    node.attributes[linkIndex]);
  return foundExternalLink || (warnOnSpreadAttributes && linkIndex < spreadAttributeIndex);
}`

**Comment by ljharb** [comment]
Thanks!

**Comment by gaz77a** [comment]
my pleasure
