### ISSUE TITLE
New rule: reverse of forbid-component-props to enforce props on components

### ISSUE THREAD

**Issue by pke** [yannickcr/eslint-plugin-react#3072]
We often forget to add a `style` property to our React Native components and a rule to enforce component props would really help.

Kind of like a reverse of `forbid-component-props` to specify which property (and type) needs to at least present on components.

Does this make sense?

**Comment by ljharb** [comment]
That's what PropTypes are already for.

**Comment by pke** [comment]
And those work in typescript JSX components too?

**Comment by ljharb** [comment]
Of course they do. TypeScript is a build-time thing, as is jsx - they all produce the same JS React element objects.

**Comment by pke** [comment]
Irrc PropTypes are kind of deprecated and they not enforce that a certain prop is defined on a component. They print a warning in the console during runtime, when someone missed to hand in the prop, but not when someone forgot to define the prop on the component.

Maybe I need to provide an example.

**Comment by ljharb** [comment]
If you configure your tests so that console warnings fail them, then they serve that purpose perfectly. `PropTypes.exact` can be used to ensure no *extra* props are passed, and `.isRequired` definitely enforces that a certain prop is defined.

**Comment by pke** [comment]
My goal is to catch missing props during commit (linting). So could I find code that omits `.isRequired` props?

**Comment by ljharb** [comment]
That’s not possible to do reliably and statically, unless you’re using typescript.

PropTypes handle this at runtime, which is the only reliable means in JS.

**Comment by pke** [comment]
I am using typescript. So I just have to make a basetype every component must accept
