### ISSUE TITLE
react-scripts build unable to load 'plugin:react/jsx-runtime'

### ISSUE THREAD

**Issue by fkhan77** [yannickcr/eslint-plugin-react#3079]
**eslint-plugin-react** has been installed to dev dependencies.
I have extended both **plugin:react/recommended** and **plugin:react/jsx-runtime** to allow for JSX transforms.
My .eslintrc.js extends section currently looks like this
``` 
extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:react/jsx-runtime'
  ]
```

When running **react-scripts build** I get the following error:
```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to load config "plugin:react/jsx-runtime" to extend from.
Referenced from: C:\Projects\Work\web-app\.eslintrc.js

error Command failed with exit code 1.
```

Any solutions or advice would be very much appreciated.

**Comment by ljharb** [comment]
What version of eslint-plugin-react are you using?

CRA incorrectly omits the ^ from its deps, so it might be pegged to an older version of the plugin that lacks the jsx-runtime config.

**Comment by mmnoo** [comment]
I've got the same problem. My eslint-plugin-react version is 7.26.0

**Comment by ljharb** [comment]
@mmnoo what does `npm ls | grep eslint-plugin-react` print out? Do you maybe have more than one copy, one at the root and one under react-scripts?

**Comment by fkhan77** [comment]
@ljharb I just had a check and it turns out react-scripts has ``eslint-plugin-react "^7.21.5"`` and in my package.json under dev dependencies I have ``    eslint-plugin-react": "^7.25.2``

**Comment by ljharb** [comment]
Ok, in that case it should be deduping.

If someone can provide a repro repo, id be happy to take a look.

**Comment by mmnoo** [comment]
https://github.com/mmnoo/eslint-plugin-react-troubleshoot

**Comment by ljharb** [comment]
@mmnoo that's because you put it in the "plugins" array. it goes in the "extends" array. When I fix that, it works fine.

**Comment by ljharb** [comment]
@fkhan77 can you provide a repro repo? if not, i'll close this.

**Comment by mmnoo** [comment]
> @mmnoo that's because you put it in the "plugins" array. it goes in the "extends" array. When I fix that, it works fine.

Lol, isnt it always something like that? Thanks @fkhan77

**Comment by ljharb** [comment]
Closing, pending a repro.

**Comment by mikegrima** [comment]
I'm still seeing this. I have the following:
```
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:react/jsx-runtime"
    ],
```

And when running `yarn start`, I get:
```
Failed to compile.

Failed to load config "plugin:react/jsx-runtime" to extend from.
```

My project has the following configuration (if this helps):
```
    "dependencies": {
        "@material-ui/core": "^4.12.3",
        "@material-ui/icons": "^4.11.2",
        "@types/node": "^12.0.0",
        "@types/react": "^17.0.0",
        "@types/react-dom": "^17.0.0",
        "@types/react-helmet": "^6.1.2",
        "@types/react-router-dom": "^5.1.8",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-helmet": "^6.1.0",
        "react-router-dom": "^5.3.0",
        "react-scripts": "4.0.3",
        "typescript": "^4.1.2"
    },
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject",
        "lint": "eslint 'src/**'",
        "lint:fix": "eslint 'src/**' --fix"
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "devDependencies": {
        "babel-eslint": "^10.1.0",
        "eslint": "^7.32.0",
        "eslint-plugin-react": "^7.26.0"
    },
```

It's not open source yet so I can't really  provide more.

**Comment by ljharb** [comment]
@mikegrima if you do `yarn why eslint-plugin-react`, what do you get?

**Comment by mikegrima** [comment]
```
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "eslint-plugin-react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "eslint-plugin-react@7.26.0"
info Has been hoisted to "eslint-plugin-react"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "6.2MB"
info Disk size with unique dependencies: "17.33MB"
info Disk size with transitive dependencies: "23.19MB"
info Number of shared dependencies: 44
=> Found "react-scripts#eslint-plugin-react@7.22.0"
info This module exists because "react-scripts" depends on it.
info Disk size without dependencies: "1.68MB"
info Disk size with unique dependencies: "8.12MB"
info Disk size with transitive dependencies: "13.88MB"
info Number of shared dependencies: 39
✨  Done in 0.95s.
```

**Comment by ljharb** [comment]
As you can see, react-scripts depends on v7.22, without the proper semver range. So, by virtue of using CRA, you're screwed unless either eject, or unless you can update react-scripts, and unless react-scripts provides a version that depends on a late-enough eslint-plugin-react.

**Comment by mikegrima** [comment]
I am not a JS expert and typically do backend Python development, so ... I ... don't... know what that means...

**Comment by ljharb** [comment]
It means create-react-app made choices that prevent you from using the latest version of eslint-plugin-react automatically. You can either “eject” (a CRA idiom, you’ll have to read the docs); or update your dependencies (if the react-scripts dependency has a later version available that allows the latest version of eslint-plugin-react); or, you have no recourse.

If you’re having trouble, I’d file an issue on create-react-app - if they’d used a semver range inside react-scripts, you wouldn’t be running into this problem.

**Comment by mikegrima** [comment]
That's helpful. Thank you!
