### ISSUE TITLE
[Question] - how to define a custom rule where specific html elements are forbidden

### ISSUE THREAD

**Issue by AndrejGajdos** [yannickcr/eslint-plugin-react#3087]
I would like to know how is it possible to create a custom rule, where I can define fobidden html elements in jsx syntax.

For example, I want to be sure that only `<Button />` and `<Input />` compontents from my ui library are used. If `<input>` or `<button>` html elements are used in jsx, eslint should throw an error.

**Comment by ljharb** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/forbid-elements.md exists.
