### ISSUE TITLE
Activate JSX support for ESLint

### ISSUE THREAD

**Issue by nestorllamas91** [yannickcr/eslint-plugin-react#3095]
Hello,

If I set your default preset in `eslintrc.json` which can be seen below:
```
{
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended"
  ]
}
```
then I don't need to set manually the JSX support for ESLint in the `parserOptions` property in `.eslintrc.json` as it can be seen below?
```
{
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  }
}
```
Or I must do both things in order to set the JSX support?

Regards,
Néstor Llamas

**Comment by ljharb** [comment]
That's correct, as you can see here: https://github.com/yannickcr/eslint-plugin-react/blob/master/index.js#L128
