### ISSUE TITLE
how to disable react/destructuring-assignment?

### ISSUE THREAD

**Issue by scvd03** [yannickcr/eslint-plugin-react#3096]
"react/destructuring-assignment": [true, { "extensions": [".jsx"] }] 

Not only does it not work, but it also stops the eslint operation of the vcode.
How can I turn this off? (eslintrc.json)

**Comment by ljharb** [comment]
That's not how eslint works. The first config item is the "severity", and it can be set to either `0`, `1`, or `2` - or `"off"`, `"warn"`, or `"error"`. It's never a boolean.
