### ISSUE TITLE
jsx-quotes: Value "double" must be an enum value.

### ISSUE THREAD

**Issue by doque** [yannickcr/eslint-plugin-react#311]
Using this config:

    "jsx-quotes": [1, "double"]     // Double quotes in JSX

Was this changed recently? It worked before.

**Comment by doque** [comment]
Got it. Should be `prefer-double`.

**Comment by yannickcr** [comment]
Yep, the [react/jsx-quotes](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-quotes.md) rule has been deprecated for the ESLint [jsx-quotes](http://eslint.org/docs/rules/jsx-quotes.html) rule which does not have exactly the same options.
