### ISSUE TITLE
[jsx-no-target-blank] Option `enforceDynamicLinks` is described twice in docs

### ISSUE THREAD

**Issue by gebsh** [yannickcr/eslint-plugin-react#3123]
In docs of the `react/jsx-no-target-blank` rule, the option `enforceDynamicLinks` is mentioned twice with almost exactly the same description.

I believe it may be a mistake introduced by subsequent changes to rule options, since descriptions of some options follow slightly different formatting.

**Comment by ljharb** [comment]
Thanks, a PR to fix that would be appreciated.

**Comment by gebsh** [comment]
Sure, I'll take a look at it and send a PR soon.
