### ISSUE TITLE
`button-has-type` does not recognize logical operands

### ISSUE THREAD

**Issue by igorpupkinable** [yannickcr/eslint-plugin-react#3125]
The following two buttons throw `The button type attribute must be specified by a static string or a trivial ternary expression  react/button-has-type` error:
```tsx
export type BaseButtonProps = {
  type?: 'button' | 'submit';
};

const BaseButton: FC<BaseButtonProps> = ({ children, type })> (
  <>
    <button type={type || 'button'}>
      {children}
    </button>
    <button type={type ?? 'button'}>
      {children}
    </button>
  </>
);
```

Both seem like valid cases.

**Comment by ljharb** [comment]
Unfortunately they’re not - that can’t be statically resolved to a potential type value, unlike a ternary where both sides are string literals.
