### ISSUE TITLE
Configuration conflict with 7.27.0

### ISSUE THREAD

**Issue by DavidHenri008** [yannickcr/eslint-plugin-react#3128]
After updating from 7.26.1 to 7.27.0 I am getting an error when launching my application in debug.

I am getting the following error:

> ERROR in Plugin "react" was conflicted between "..\..\package.json » ./config/eslint.js » eslint-config-airbnb » C:\MyProject\node_modules\eslint-config-airbnb\rules\react-a11y.js" and "BaseConfig » C:\MyProject\node_modules\eslint-config-react-app\base.js".
>
>webpack compiled with 1 error

Reverting to 7.26.1 fixes the issue.

**Comment by ljharb** [comment]
It’s likely that CRA doesn’t use a semver range when depending on this plugin - if so, you simply can’t upgrade until CRA does.

**Comment by DavidHenri008** [comment]
I am using a long ago ejected CRA.

**Comment by ljharb** [comment]
That doesn’t matter if it’s still using react-scripts, which is the thing that incorrectly pins its dependency versions.

**Comment by DavidHenri008** [comment]
Oh I see, sorry. I will try to check on there repo and post an update.
Thanks.

**Comment by DavidHenri008** [comment]
Since I am ejected I am not using react-scripts package.
However, here is what I found:
- may application uses "eslint-config-react-app": "7.0.0-next.91"
- eslint-config-react-app (main version) does depends on "eslint-plugin-react": "^7.20.3"

So again I do not understand the issue here.

**Comment by ljharb** [comment]
In that case it should be fine. You may need to dedupe eslint-plugin-react in your lockfile.

**Comment by YChalfari** [comment]
Which file did you clear to fix this issue?  I'm now having serious issues with this conflict 
Just delete the package-lock.json ? The main one?

**Comment by DavidHenri008** [comment]
I am using yarn and relatively frequently, the .lock file becomes corrupted after some ```yarn upgrade-interactive```. So I deleted only my yarn .lock file and run the ```yarn install``` command. As a note, I did NOT have to delete my node_module folder.
I do not know if npm lock file has the same issue.

**Comment by shivanya-chandra** [comment]
> I am using yarn and relatively frequently, the .lock file becomes corrupted after some `yarn upgrade-interactive`. So I deleted only my yarn .lock file and run the `yarn install` command. As a note, I did NOT have to delete my node_module folder. I do not know if npm lock file has the same issue.

it's still showing the error even after deleting the lock file and running `npm i` after that.

**Comment by Dgoss16** [comment]
I am also still having the same issue after deleting the package-lock and running `npm i`

**Comment by MartijnGevaert** [comment]
I am also having this issue, but removing the lock files only temporarily solves the issue, error for me looks like this:

> ERROR in Plugin "react" was conflicted between ".eslintrc.js » @react-native-community/eslint-config" and "BaseConfig » C:\Users\*******\Desktop\****************\react_frontend\node_modules\react-scripts\node_modules\eslint-config-react-app\base.js".

**Comment by ljharb** [comment]
@MartijnGevaert if you’re using CRA, you’re forced to stick with whatever version they use.

**Comment by MartijnGevaert** [comment]
> @MartijnGevaert if you’re using CRA, you’re forced to stick with whatever version they use.

Thanks for your reply.
I have tried to find out what version ARC uses but have been unable to do so (assuming I should match the version in my package.json to the one used in ARC).

Failing to do this I realised that you might mean removing `"@react-native-community/eslint-config": "^2.0.0",` from my package.json and letting ARC install it as a dependency.
The issue with this approach is that it then also needs to be removed from the eslintrc.js and then errors are no longer thrown for things such as unused imports.

**Comment by ljharb** [comment]
The unfortunate reality with CRA is that you need to eject to do anything meaningful.

**Comment by brayanmf** [comment]
I am with the same problem, the funny thing is that when you save it from the package.json it executes the normal server but if I save it from a component it sends me the same error

**Comment by crud-engr** [comment]
Removing package-lock.json and re-installing does not seem working. Please what is the way forward as this is a very serious blocker in my current app.

**Comment by ljharb** [comment]
@crud-engr if you’re using CRA, then the blocker is CRA itself. If not, then please file a new issue.

**Comment by illume** [comment]
Had this issue too with CRA 5.

Used `npm list --depth=3` to check the versions of the plugin installed.

Then I set the exact version and got happy-happy-joy-no-error.
`npm install --save --save-exact eslint-plugin-react@7.28.0`

I can understand why nuking the package-lock.json and doing it again could fix it, because then it sorts the version numbers out so they match. But then all your other dependencies may need rejigging... and that might not be possible for some.

So I guess it's perhaps ultimately an issue with npm dependency resolution when you add something which uses peer dependencies and there's a conflict. Or maybe now it's warning us, and before it didn't. Mystery.

**Comment by AlexMachin1997** [comment]
Hmm I've just worked through this thread but nothing seemed to help sadly.

Not sure what else to do.

It works fine in another project, though the front-end is all in the root of the project and not seperate into a /client and /server

**Comment by ljharb** [comment]
@AlexMachin1997 if you're using a "workspaces" setup, make sure that the plugin and eslint versions are the same throughout the repo.

**Comment by AlexMachin1997** [comment]
What do you mean by "workspaces" ? Are you refering to Yarn because I'm not using those at the moment.

I'm just using plain Yarn with the following setup:

![image](https://user-images.githubusercontent.com/29917195/152254609-86f01804-9723-4154-ac9d-31103ac297b2.png)

**Comment by ljharb** [comment]
I meant yarn, or npm, or lerna, or any other monorepo tool.

You're doing that in the sense that you have a root package.json, and two subfolders each with their own package.json.

If you use the real terminal - the one inside your editor doesn't count - and run the eslint command directly inside `client` or `server`, what happens?

Unless you're using a workspaces tool, you can't really lint the subprojects from the root, which is usually what editor integrations do.

**Comment by AlexMachin1997** [comment]
Ah.

Yeah I've organised them like that just to seperate them.

I can't do that, all of the linting is done in the root of the project, basically in the root package.json I have some commands to manually lint the code see [here](https://github.com/AlexMachin1997/react-scripts-with-express-server)

**Comment by ljharb** [comment]
In that case, `client` and `server` MUST have all their eslint things listed as peer deps, so that npm forces them to match the versions in the root.

**Comment by AlexMachin1997** [comment]
Wold you mind providing an example with how that would work ? Seems like duplication but I'm probably missing something to fully understand it.

I didn't need to do this in a previous version of react-scripts and it worked fine hmm strange.

**Comment by JustFly1984** [comment]
Ok, so the issue is conflicting versions. I use resolutions field in package.json with yarn, or overrides field in package.json for npm projects to force the only package version in the repo.

**Comment by ljharb** [comment]
@AlexMachin1997 yes, it’s duplication, but that’s the choice you made by making a monorepo and also not using the available tooling for that.

**Comment by AlexMachin1997** [comment]
I didn't intentionally make the choice, I did it by accieent by just wanting to reorganise my project though I see an area I can invetigate further. 

Monorepos seems really cool, I just need to learn more about them and set up a dummy project with whatever tools are available.

For now I've moved all the react stuff into the root and it works perfectly, I'll add that to the list of improvements for the arcitecture.

**Comment by boahs** [comment]
This issue :

`Plugin "react" was conflicted between "package.json » eslint-config-react-app`

Is happening now with all my CRA applications.

**Comment by boahs** [comment]
https://github.com/facebook/create-react-app/issues/11825#issuecomment-1030693411 

This has fixed my issue - Please refer to this other thread relating to the this issue

**Comment by iphyman** [comment]
Removing `"plugin:react/recommended",` from .eslintrc config file `"extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/recommended",
"plugin:react/recommended",
      "plugin:react-hooks/recommended",
      "plugin:prettier/recommended"
    ],` seems to clear the error for me.

**Comment by mahfuz0498** [comment]
add  ` "root": true` in eslintrc.json file , it will ignore searching out of the root folder.

**Comment by wjureczka** [comment]
Adding `"root": true` and `--resolve-plugins-relative-to .` does not work for me. I am using `yarn 3.2.0` with workspaces functionality with config like this:

```
yarnPath: .yarn/releases/yarn-3.2.0.cjs

nodeLinker: node-modules

pnpFallbackMode: all
pnpMode: loose

```

**Comment by curtvict** [comment]
This should be reopened. It seems like this plugin is no longer compatible with `eslint 8.15.0`.

**Comment by ljharb** [comment]
@curtvict please file a new issue.

**Comment by tommyspot** [comment]
Don't need to delete yarn.lock file.
In yarn.lock, I just saw **2 "eslint-plugin-react"** existing (as picture below). So, only delete them and "yarn install" again.

<img width="815" alt="Screen Shot 2022-06-02 at 09 20 31" src="https://user-images.githubusercontent.com/7645519/171539017-c8db5219-23f5-4ac4-ba62-193df4786503.png">

**Comment by fedebaez** [comment]
It may not be the most technical solution, but when i had this issue, it got fixed when i stopped the compilation in the console and then ran it again

**Comment by fedebaez** [comment]
> After updating from 7.26.1 to 7.27.0 I am getting an error when launching my application in debug.
> 
> I am getting the following error:
> 
> > ERROR in Plugin "react" was conflicted between "....\package.json » ./config/eslint.js » eslint-config-airbnb » C:\MyProject\node_modules\eslint-config-airbnb\rules\react-a11y.js" and "BaseConfig » C:\MyProject\node_modules\eslint-config-react-app\base.js".
> > webpack compiled with 1 error
> 
> Reverting to 7.26.1 fixes the issue.

It may not be the most technical solution, but when i had this issue, it got fixed when i stopped the compilation in the console and then ran it again

**Comment by dannypk** [comment]
this worked for me

https://stackoverflow.com/questions/70449712/create-react-app-error-in-plugin-react-was-conflicted-between-eslintrc-jso

**Comment by sadie100** [comment]
Just opening the package.json and saving once worked for me. Don't know why


https://stackoverflow.com/a/72064249/27479682
