### ISSUE TITLE
fixed-data-table 0.6 styling fails

### ISSUE THREAD

**Issue by bartvde** [yannickcr/eslint-plugin-react#313]
Any idea why this currently fails?

```
const TextCell = ({rowIndex,col, layer, ...props}) => (
  <Cell {...props}>
    {FeatureStore.getFieldValue(layer, rowIndex, col)}
  </Cell>
);
```

```
/Users/bartvandeneijnden/opengeo/git/sdk/js/components/FeatureTable.jsx
  62:43  error  Parsing error: Unexpected token ..
```

https://github.com/facebook/fixed-data-table/blob/master/examples/ObjectDataExample.js#L34:L38

**Comment by yannickcr** [comment]
I'm not sure, but maybe you forget to enable [experimentalObjectRestSpread](http://eslint.org/docs/user-guide/configuring#specifying-language-options) in your ESLint configuration?

**Comment by bartvde** [comment]
thanks, that was part of the problem. Then I ran into https://github.com/eslint/eslint/issues/4102 but not an issue for here.

Thanks again for pointing me in the right direction.
