### ISSUE TITLE
react/no-unused-class-comp-methods support getChildContext

### ISSUE THREAD

**Issue by yoyo837** [yannickcr/eslint-plugin-react#3135]
`getChildContext` is an outdated API.

**Comment by ljharb** [comment]
I'm not sure what you're asking for.

`getChildContext` is not deprecated; it's the way class components are supposed to provide context.

**Comment by yoyo837** [comment]
Sorry for my poor english.

See this:
![image](https://user-images.githubusercontent.com/6134547/141515923-f8b45c1f-4963-4081-9ae0-37098328478c.png)

**Comment by yoyo837** [comment]
I think it should not report lint related with that rule.

**Comment by ljharb** [comment]
You're right, this is a bug.
