### ISSUE TITLE
Unexplained claim that "using target='_blank' is a severe security vulnerability"

### ISSUE THREAD

**Issue by jameshfisher** [yannickcr/eslint-plugin-react#3150]
[This page](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md) claims that

> When creating a JSX element that has an `a` tag, it is often desired to have the link open in a new tab using the `target='_blank'` attribute. Using this attribute unaccompanied by `rel='noreferrer'`, however, is a severe security vulnerability ([see here for more details](https://html.spec.whatwg.org/multipage/links.html#link-type-noopener))

However, [the page that it links to for more explanation](https://html.spec.whatwg.org/multipage/links.html#link-type-noopener) says absolutely nothing about any vulnerability.

What is the actual vulnerability? Is this really a valid claim?

**Comment by ljharb** [comment]
Hmm, the page must have been updated, that's unfortunate.

Here's an article about it: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

We might need to track down the PR that changed the whatwg docs so we can reclaim the original content.

**Comment by jameshfisher** [comment]
Whoa. That is actually a serious vuln. TIL
