### ISSUE TITLE
Is there lint rule for disallow props drilling?

### ISSUE THREAD

**Issue by ryota-murakami** [yannickcr/eslint-plugin-react#3151]
I'm struggling excessive props drilling current project, because there is no state management library and Context adoption.
Every component receiving too many props, but the component only using a few prop, many of rest props are just passing child component as a props.

If there is no such as rule currently, can I write rule myself?
I'm not familiar ESLint rules implementation, so I'd like to know Lint system able to detect `component receiving unused props and passing child component as a props over x times  hierarchy`.

My concern is we can create react lint rule that understanding component contexts across multiple levels.

**Comment by ljharb** [comment]
How would you expect this rule to work? Naively forbidding any prop from being passed as a prop seems problematic, since folks might work around it by needlessly wrapping the prop in something.

Lint rules do not generally work across files.

**Comment by ryota-murakami** [comment]
> since folks might work around it by needlessly wrapping the prop in something.
Yeah, might be I can't create effective this rule for react developers around the world via public npm.

My first goal is create rule simply deny `passing unused props value as a child components props`.
And use it on my OSS project, my paid job project.

> Lint rules do not generally work across files.
Thank you for tell me about it!
I have to learn how to create ESlint rule from basics even though I'll do my best!

**Comment by ljharb** [comment]
I'm going to close this, but I'm always happy to discuss further.
