### ISSUE TITLE
New rule: Use ternaries rather than && in JSX

### ISSUE THREAD

**Issue by MichaelDeBoey** [yannickcr/eslint-plugin-react#3153]
Inspired by @kentcdodds' [article](https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx), It would be awesome to have an ESLint rule that supports this.

**Comment by ljharb** [comment]
Now that `??` exists, there's not really a need to use ternaries here.

I think this is a duplicate of #2073.

**Comment by MichaelDeBoey** [comment]
This got fixed by #3203

Huge thanks @Belco90! 🤩
