### ISSUE TITLE
`react/display-name`: false positive with `forwardRef()` since 7.27.1

### ISSUE THREAD

**Issue by AprilArcus** [yannickcr/eslint-plugin-react#3161]
https://github.com/yannickcr/eslint-plugin-react/issues/3144 / https://github.com/yannickcr/eslint-plugin-react/commit/893dbff9dccf08316e9084e201cd1845e255cff7 introduce a false positive `react/display-name` error when used with `forwardRef()`.

**Comment by ljharb** [comment]
Can you elaborate? If you can provide specific repro code, then it can be easily fixed.

**Comment by ljharb** [comment]
Closing, pending repro code.
