### ISSUE TITLE
`react/no-invalid-html-attribute` seems to report false positives

### ISSUE THREAD

**Issue by Primajin** [yannickcr/eslint-plugin-react#3172]
Hey there, I've got an automatic lint bump in my repo that introduces `react/no-invalid-html-attribute` as a new rule and it fails with two/three errors:

https://github.com/Primajin/eyesbound/runs/4760311505?check_suite_focus=true

> Error - “home” is never a valid “rel” attribute value.

By adding rel="home" to a hyperlink, a page indicates that the destination of that hyperlink is the homepage of the site [...]
https://microformats.org/wiki/rel-home
This is a draft from 2005... Not sure if it was ever official?

> Error - “shortcut” is never a valid “rel” attribute value.

If I read https://mathiasbynens.be/notes/rel-shortcut-icon correctly this is not according to specification but older IE need it when the file is not exactly called `favicon.ico`, is that correct?

So are these arguably false positives, or instead everyone is just using it wrong and it was never a specification - thus I still wonder if everyone uses it kind of makes it a default 🤔 😅 
Thanks for looking into it folks.

**Comment by ljharb** [comment]
I'm pretty sure a rel of "home" was never official; that link is to a draft.

If you choose not to name the file `favicon.ico` for some reason, then you should use an override comment to disable the rule - but it's far easier to just name the file that.

**Comment by Primajin** [comment]
Alright fair enough, thanks for checking 👍🏻

**Comment by Primajin** [comment]
OK I will just remove that line entirely. 👍🏻 

For future people stranding here it might also be worth mentioning:
> For historical reasons, the HTML specification now allows the use of shortcut as a link relation if it’s immediately followed by a single U+0020 space character and the icon keyword. Of course, it’s still better not to use any HTML at all.

**Comment by ljharb** [comment]
If the html specification allows it, then we should also, to be clear.

**Comment by Primajin** [comment]
Yeah I just wonder how much "quirks mode" that is 😅

**Comment by ljharb** [comment]
Very, but if it’s valid, then it can’t hurt to support it.

**Comment by Primajin** [comment]
Then I can offer you https://github.com/yannickcr/eslint-plugin-react/pull/3174 😄
