### ISSUE TITLE
Got a validation issue using react/jsx-no-target-blank

### ISSUE THREAD

**Issue by MatteoGauthier** [yannickcr/eslint-plugin-react#3187]
<img width="815" alt="Capture d’écran 2022-01-25 à 16 05 26" src="https://user-images.githubusercontent.com/32040951/151002883-7b2cd631-794f-443e-837a-5bd6fe2b039f.png">

Apparently it don't works when the `rel` attribute value is wrapped in a jsx expression

**Comment by ljharb** [comment]
theres no reason to prefer js value interpolation when jsx literal notation is available, but indeed, this rule should support string literals (and template literals sans interpolations) directly inside curly braces.

**Comment by MatteoGauthier** [comment]
@ljharb I agree with you, but a user may want the two rules

**Comment by karlhorky** [comment]
I think this is already working as you're asking for @MatteoGauthier:

https://user-images.githubusercontent.com/1935696/151709636-5fc5a7ac-2006-4108-b30a-891b867e48c1.mp4

Maybe you're on an older version?

The rule already supports both template literals and string literals:

https://github.com/yannickcr/eslint-plugin-react/blob/74634488e8682bc74e8d93e03b5ad70cf47551a9/lib/rules/jsx-no-target-blank.js#L74-L77
