### ISSUE TITLE
`no-invalid-html-attribute`: “sitemap” is never a valid “rel” attribute value

### ISSUE THREAD

**Issue by CanRau** [yannickcr/eslint-plugin-react#3196]
I think `<link rel="sitemap" />` shouldn't error (anymore)?

Relevant SO [answer](https://stackoverflow.com/questions/13327527/how-to-make-a-sitemap-link-in-the-page-head-pass-the-w3c-validator)

Edit: Just read further and realized it's actually still a proposal 🤦🏻‍♂️

**Comment by ljharb** [comment]
Indeed; since it's still a draft. Once it's shipped in browsers, or standardized, then we can and should add it here.

https://caniuse.com/?search=rel%3Dsitemap suggests nobody ships it.

For now, I'll close this tho.

**Comment by CanRau** [comment]
Agree 💯
