### ISSUE TITLE
It seems commented code isn't ignored

### ISSUE THREAD

**Issue by steida** [yannickcr/eslint-plugin-react#32]

**Comment by yannickcr** [comment]
Hi,

Can you be more specific about the code, the rules and your .eslintrc configuration ?

**Comment by steida** [comment]
My configuration is here github.com/steida/este

**Comment by yannickcr** [comment]
Can you provided a reduced test case ([like this issue for example](https://github.com/yannickcr/eslint-plugin-react/issues/29)) ?

**Comment by steida** [comment]
I don't remember the case maybe it works already.
