### ISSUE TITLE
new rule: props as an object

### ISSUE THREAD

**Issue by xand3r40r93** [yannickcr/eslint-plugin-react#3212]
Hello.
I prefer using props as an object in JSX, it's visually comfortable.

bad:
```
<Button
  theme='text'
  container={{style: {marginVetical: 16}}}
  children={m('connect/demoMode)}
  onPress={handleDemo}
/>
```

good:
```
<Button {...{
  theme: 'text',
  container: {style: {marginVertical: 16}},
  children: m('connect/demoMode'),
  onPress: handleDemo,
}}/>
```
Can you create a rule for this trick? Thanks.

**Comment by ljharb** [comment]
That’s an antipattern for a bunch of reasons: performance, clarity, it encourages more dynamism, etc - that would be a harmful rule.

**Comment by xand3r40r93** [comment]
@ljharb can you explain, why this is antipattern, please?

**Comment by ljharb** [comment]
It created an extra object, for one, so there’s a performance overhead.

Because it’s a js object, it allows for all sorts of extra dynamism - you can have computed keys, you’re more likely to spread in other objects, etc, which makes code harder to understand and to lint.

You’re using jsx - you should use jsx syntax.

**Comment by xand3r40r93** [comment]
@ljharb performance - do you have any numbers, benchmarks?

**Comment by ljharb** [comment]
None are needed. “an object” versus “no object” is obviously not better. Performance is the least important consideration tho; it’s indirection, which makes it objectively worse even if it were somehow faster.

**Comment by xand3r40r93** [comment]
Any attributes in JSX converting to object. I think that performance is the same. Clarity in JSX is worse (JSX attributes vs object), just compare.

**Comment by ljharb** [comment]
Yes, one object - your approach creates two.

jsx attributes are clearer.

**Comment by xand3r40r93** [comment]
@ljharb for example, this
```
const Test1 = () => <div data='test'/>
const Test2 = () => <div {...{data: 'test'}}/>
```
will be converted to
```
"use strict";
const Test1 = () => React.createElement("div", { data: 'test' });
const Test2 = () => React.createElement("div", { ...{ data: 'test' } });
```
I agree, there is a drop in performance, but it is not significant. 
<img width="923" alt="Screenshot 2022-02-20 at 18 43 09" src="https://user-images.githubusercontent.com/65961104/154853786-01bdc57e-ec8a-4fa7-abbb-a547d8ffdc82.png">
It's 226 vs 280 **nano**seconds

And I think an object is more readable. I have some big projects and using this trick for the last 2 years.
<img width="417" alt="Screenshot 2022-02-20 at 18 36 53" src="https://user-images.githubusercontent.com/65961104/154853963-a764e756-6466-4a8a-baa2-3b1a5c3bccb3.png">
<img width="419" alt="Screenshot 2022-02-20 at 18 36 59" src="https://user-images.githubusercontent.com/65961104/154853974-2e792a4b-2e5c-4955-9162-c623671c295d.png">

I don't see any critical facts, that this trick is an antipattern.

**Comment by ljharb** [comment]
The drop in performance isn’t the important part - i disagree that it’s more readable; i find it far less readable. The most readable thing with jsx syntax is *jsx syntax* which includes html-like attributes.

**Comment by xand3r40r93** [comment]
How many people - so many opinions. For me, it's more readable. I think that eslint's power is customizing.
<img width="636" alt="Screenshot 2022-02-20 at 19 13 13" src="https://user-images.githubusercontent.com/65961104/154855124-9eee0e3a-a219-4f44-8b6f-f28dc2a54f67.png">
<img width="630" alt="Screenshot 2022-02-20 at 19 13 21" src="https://user-images.githubusercontent.com/65961104/154855126-17957f79-81df-4615-ab4c-78010593ac8e.png">

**Comment by ljharb** [comment]
An eslint rule to choose between two styles makes sense when they're equivalent, or when one is objectively better than another.

The only rule that would thus make sense here is to force the former pattern, so I'll stick with no rule at all.

**Comment by xand3r40r93** [comment]
Open your mind )
