### ISSUE TITLE
breaks with ESlint 1.10.0

### ISSUE THREAD

**Issue by BerkeleyTrue** [yannickcr/eslint-plugin-react#323]
Breaks with eslint 1.10.0
Runs fine with eslint 1.9.0
![1__tmux](https://cloud.githubusercontent.com/assets/6775919/11309006/2613ec42-8f76-11e5-9b3c-e056166dc02d.png)

eslint-plugin-react 3.9.0
node 4.2.1
npm 2.14.7

**Comment by lukekarrys** [comment]
It looks like a performance improvement PR (https://github.com/eslint/eslint/pull/4428) is now freezing `context` in a few places which creates this error.

If I run the tests with the following lines commented out in `eslint`, the tests pass:
- https://github.com/eslint/eslint/blob/be2c000ad0c1ee5ebd04e26e89678cd0ba659201/lib/testers/rule-tester.js#L293
- https://github.com/eslint/eslint/blob/be2c000ad0c1ee5ebd04e26e89678cd0ba659201/lib/rule-context.js#L85

It seems like [this line](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/util/Components.js#L111) is the only place mutating `context`, but being unfamiliar with eslint plugins I'm not sure what changes need to be made.

**Comment by jayphelps** [comment]
Seeing this as well. Adding this simply for SEO: `Error while loading rule 'react/no-multi-comp': Can't add property react, object is not extensible`

**Comment by machadogj** [comment]
@jayphelps +1, I ended up here while trying to report the issue!

**Comment by Simproduction** [comment]
Hi I have lastest version of plugin and I have same issue
```
Error while loading rule 'react/no-multi-comp': Can't add property react, object is not extensible
TypeError: Error while loading rule 'react/no-multi-comp': Can't add property react, object is not extensible
    at Function.componentRule (/usr/lib/node_modules/eslint-plugin-react/lib/util/Components.js:111:17)
    at /usr/lib/node_modules/eslint/lib/eslint.js:692:28
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/usr/lib/node_modules/eslint/lib/eslint.js:671:16)
    at processText (/usr/lib/node_modules/eslint/lib/cli-engine.js:230:27)
    at CLIEngine.executeOnText (/usr/lib/node_modules/eslint/lib/cli-engine.js:686:26)
    at Object.cli.execute (/usr/lib/node_modules/eslint/lib/cli.js:162:36)
    at /usr/lib/node_modules/eslint/bin/eslint.js:41:28
    at ConcatStream.<anonymous> (/usr/lib/node_modules/eslint/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
```

**Comment by nzakas** [comment]
FWIW, ESLint pushed out an update - we unintentionally introduced this breaking change (well, we intentionally made the change, just didn't realize it would break anything). We won't reintroduce the change until ESLint v2.0.0 so as to avoid any further compatibility issues. We're also going to look into adding `eslint-plugin-react` to our automated testing so we can find compatibility issues faster.

**Comment by yannickcr** [comment]
Great, I also published `eslint-plugin-react@3.10.0` with the fix to stop extending the `context` object. So everything should be fine now :)

**Comment by paulmartinezatdocker** [comment]
Just tested the latest version and my issue has now been resolved.

Thanks guys!

**Comment by machadogj** [comment]
Awesome work guys!

**Comment by langri-sha** [comment]
Hey, I woke up this morning and everything works! Thank you.
