### ISSUE TITLE
incorrect prop-types error for VFC

### ISSUE THREAD

**Issue by dlech** [yannickcr/eslint-plugin-react#3230]
This is essentially the same issue as #3090 except that the `VFC` abbreviation was also overlooked in the fix that closed that issue. Basically the same changes need to be made as in #3092 except replace `VoidFunctionComponent` with `VFC`.

**Comment by ljharb** [comment]
Presumably both `VFC` and `VoidFunctionComponent` are provided as types?

**Comment by dlech** [comment]
Yes. See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f3875116e52fe94338292fc418c89b2ef8216c4c/types/react/index.d.ts#L557.

**Comment by dlech** [comment]
This does not seem to be fixed after updating to v7.29.4.

Maybe we missed adding `VFC` here?

https://github.com/yannickcr/eslint-plugin-react/blob/d9531c3bc539e292eb297a04c7b9312e8b63a223/lib/util/propTypes.js#L104-L113

**Comment by ljharb** [comment]
@dlech seems plausible :-) can you file a new issue, or better, a PR with a failing test case?
