### ISSUE TITLE
Question about the default value for "version" in the "settings"

### ISSUE THREAD

**Issue by krisztianb** [yannickcr/eslint-plugin-react#3245]
In the README I see this config example:

```json
{
  "settings": {
    "react": {
      "createClass": "createReactClass", // Regex for Component Factory to use,
                                         // default to "createReactClass"
      "pragma": "React",  // Pragma to use, default to "React"
      "fragment": "Fragment",  // Fragment to use (may be a property of <pragma>), default to "Fragment"
      "version": "detect", // React version. "detect" automatically picks the version you have installed.
                           // You can also use `16.0`, `16.3`, etc, if you want to override the detected value.
                           // It will default to "latest" and warn if missing, and to "detect" in the future
```

Now what does this mean:

> It will default to "latest" and warn if missing, and to "detect" in the future.

Could someone clarify this for me? What is the default value for "version"? Thank you.

**Comment by ljharb** [comment]
The string "latest" is the default value.

**Comment by krisztianb** [comment]
Thanks. And what does this part mean:

> and to "detect" in the future.

**Comment by ljharb** [comment]
In the next major version, we'll change the default from the string "latest" to the string "detect" (which automatically looks up your currently installed react version).

**Comment by krisztianb** [comment]
Ok, got it. Thank you.
