### ISSUE TITLE
`eslint --init` does not add `settings` as required by #1955

### ISSUE THREAD

**Issue by AlbinoGeek** [yannickcr/eslint-plugin-react#3256]
Hello!

So, why does `eslint --init` ask me if I'm using React, if it doesn't bother to add `settings` as required by #1955 ?

Maybe this issue belongs in `eslint` repository itself? But why does it have options for `React`? Who's responsible for that piece?

It literally only needs to add the following:

```json
  "settings": {
    "react": {
      "version": "detect"
    }
  }
```

I expect initializers to give you a known-good/working configuration, it currently does not.

**Comment by ljharb** [comment]
That is not a reasonable expectation, but yes, I’d file it on eslint itself.

**Comment by AlbinoGeek** [comment]
> That is not a reasonable expectation, but yes, I’d file it on eslint itself.

I'd like to understand what you mean by this.

`eslint --init` configures your project based on an interactive questionaire

One of the questions has you select `React` as your framework, and it changes your generated configuration.

Why and how would it be unreasonable to expect it, when it generates configuration, to generate one extra directive to make it work out of the box?

I will lodge the issue over there.
