### ISSUE TITLE
[jsx-no-bind] Should allow arrow functions in ref property

### ISSUE THREAD

**Issue by stoiet** [yannickcr/eslint-plugin-react#330]
React documentation suggests using callbacks instead of string value in ref:
https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute

**Comment by Daniel15** [comment]
You can make the callback a method on your component and then do `ref={this._foo}`.

**Comment by stoiet** [comment]
Good point. Thanks!

**Comment by IanVS** [comment]
Issue should probably be closed.
