### ISSUE TITLE
Definition for rule 'react/jsx-handler-names' was not found

### ISSUE THREAD

**Issue by gajus** [yannickcr/eslint-plugin-react#334]
It appears that the latest release (3.10.0) does not include this rule.

**Comment by yannickcr** [comment]
Right, the latest release on npm does not include this rule for now.

A new release with this rule should be published this week-end.

**Comment by gajus** [comment]
@yannickcr still in the plan to release this over the weekend?

**Comment by yannickcr** [comment]
This rule is now available in `v3.11.0`.
