### ISSUE TITLE
v3.11.0 ESLintError: Unknown property 'cx' found, use 'cx' instead

### ISSUE THREAD

**Issue by oliviertassinari** [yannickcr/eslint-plugin-react#338]
I have this following issue since the latest release.

(this is the travis task that fail https://travis-ci.org/callemall/material-ui/builds/93803631)

**Comment by oliviertassinari** [comment]
Might be linked to https://github.com/yannickcr/eslint-plugin-react/commit/0b0e4fb867b074f90ea66f41739426f2def8f7e6

**Comment by yannickcr** [comment]
Yes, sorry for that. I will publish a patch release with the fix.

**Comment by oliviertassinari** [comment]
Ok, thanks!
