### ISSUE TITLE
How to pass JSX files to eslint correctly?

### ISSUE THREAD

**Issue by bebraw** [yannickcr/eslint-plugin-react#34]
I'm not sure if this is the right place (might be more of a core question). Anyway, is there a neat way to pass jsx files to eslint? Now I'm doing something like `eslint lib/*.jsx`. Globstar (**/*) doesn't appear to be supported and this crashes if no jsx files are found. Is it possible to set `.eslintrc` to look for certain formats for instance? How do you deal with this problem?

**Comment by yannickcr** [comment]
You have a few options to pass your JSX files to ESLint:
* `eslint lib/*.jsx` : check all .jsx files in lib, excluding subdirectories
* `eslint lib/**/*.jsx` : check all .jsx files in lib, including subdirectories
* `eslint lib` : check all .js files in lib, including subdirectories
* `eslint --ext .jsx lib` : check all .jsx files in lib, including subdirectories
* `eslint --ext .js --ext .jsx lib` : check all .js and .jsx files in lib, including subdirectories

You can found more informations in the [ESLint Command line Interface documentation](http://eslint.org/docs/user-guide/command-line-interface).

**Comment by bebraw** [comment]
@yannickcr Thanks a lot! I ended up using a combination of `.eslintignore` and `eslint --ext .jsx --ext .js`.
