### ISSUE TITLE
prop-types should throw max one error per property, per function

### ISSUE THREAD

**Issue by gajus** [yannickcr/eslint-plugin-react#350]
Now I am getting `'styles' is missing in props validation` error for every reference to `this.props.styles` in the function body. That requires me to surround each instance using `/* eslint-disable react/prop-types */`.

I think `prop-types` error should be thrown max one error per property, per function, and the error line/column should refer to the function declaration, not the property reference itself.

**Comment by lencioni** [comment]
@gajus instead of disabling the rule, why not add a propType for this prop?

**Comment by gajus** [comment]
> @gajus instead of disabling the rule, why not add a propType for this prop?

I wish I'd remember. There was a reason, I cannot think what it was off top my head.

**Comment by lencioni** [comment]
Ok! I'm going to close out this issue then. Please feel free to re-open if you can think of a good reason for this. :D
