### ISSUE TITLE
[Bug]: react/jsx-max-props-per-line does not honor indentation

### ISSUE THREAD

**Issue by electriquo** [yannickcr/eslint-plugin-react#3549]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

[react/jsx-max-props-per-line](md) does not honor indentation per the docs.

Given
```jsx
    <button className="name" type="button">
      button
    </button>
```
when running with `--fix`, each prop appear in a separate line, but does not respect indentation

```jsx
    <button
className="name"
type="button">
      button
    </button>
```

### Expected Behavior

```jsx
    <button
      className="name"
      type="button"
    >
      button
    </button>
```

### eslint-plugin-react version

7.32.2

### eslint version

8.36.0

### node version

18.15.0

**Comment by ljharb** [comment]
That's handled by the `jsx-indent` rule. You're expected to have multiple rules enabled - that way, this rule doesn't have to keep track of your desired indentation (tabs, or how many spaces).

**Comment by ljharb** [comment]
The `react/jsx-indent-props` rule, in particular, can turn:
```jsx
    <button
className="name"
type="button">
      button
    </button>
```
into
```jsx
    <button
      className="name"
      type="button">
      button
    </button>
```
I'd suggest using the airbnb config instead of the plugin directly, as it enables the right rules with mostly the right settings.

**Comment by ljharb** [comment]
I'm not sure why not - there's only upsides, no downsides - but ok: https://github.com/airbnb/javascript/blob/5c01a1094986c4dd50a6ee4d9f7617abdfabb58a/packages/eslint-config-airbnb/rules/react.js#L90
