### ISSUE TITLE
sort-comp: Support ReactTransitionGroup LifeCycle methods

### ISSUE THREAD

**Issue by spudly** [yannickcr/eslint-plugin-react#363]
Sure would be nice if the sort-comp rule supported ReactTransitionGroup lifecycle methods.

componentWillAppear
componentDidAppear
componentWillEnter
componentDidEnter
componentWillLeave
componentDidLeave

See http://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup

**Comment by yannickcr** [comment]
We can add them if this does not break the current configuration.

Meanwhile, you can still [configure the rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md#rule-options) to customize the lifecycle methods.

**Comment by ljharb** [comment]
This isn't a part of mainline React anymore, so I think it's best if you configure it yourself.
