### ISSUE TITLE
no-unused-vars issue when using ReactDOM (ES6)

### ISSUE THREAD

**Issue by MrBenJ** [yannickcr/eslint-plugin-react#387]
I'm running into an issue with ESLint throwing a no-unused-vars issue when using ReactDOM.

I'm currently using React 0.14.5

```javascript
import React from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(
    <MyComponent data="foo" />,
    document.getElementById('bar')
);

```
This code generates this error is ESLint:
React is defined but never used - no-unused-vars

I have to import React for ReactDOM to work. This issue is a bit annoying with ESLint shooting off warnings every time I work on this file. 

I've been hunting around for a fix, but I just can't seem to find one after extensive Googling and browsing documentation. Anyone know of a fix? I appreciate it. Thanks in advance!

**Comment by yannickcr** [comment]
Hi, you must enable the [react/jsx-uses-react](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md) rule to avoid this problem.

**Comment by MrBenJ** [comment]
@yannickcr  - Thank you so much! I was looking around for this and I couldn't find it.

Appreciate all your help with this. You are the best!
