### ISSUE TITLE
[jsx-handler-names] Document or remove undocumented special case for ref

### ISSUE THREAD

**Issue by arild-haugstad** [yannickcr/eslint-plugin-react#396]
With the current documentation, the resolution to #375 that enforces that callbacks for `ref` have prefix `handle` is somewhat surprising.  It is currently not mentioned and not configurable; and I would argue that `ref` is not an event, hence its inclusion does not match the overall intent of the rule:
"Ensures that any component or prop methods used to handle events are correctly prefixed."

**Comment by yannickcr** [comment]
That's a bug, `ref` should be completely ignored.
