### ISSUE TITLE
prop-types gives error when creating a Component with `class ... extends`

### ISSUE THREAD

**Issue by georgemillo** [yannickcr/eslint-plugin-react#397]
The following code gives me an eshint error:

```
        import React, { Component, PropTypes } from "react";

        class AdminUsersTableRow extends Component {

          static propTypes: {
            user: PropTypes.object.isRequired,
          }

          render() {
            return (
error:         <tr><td>{this.props.user.name}</td></tr>
            );
          }
        }

        export default AdminUsersTableRow;

```

The error in question is `'user' is missing in props validation.`. When I refactor the class to use `var AdminUsersTableRow = React.createClass({...` syntax ([like in the docs](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md)), the error disappears.

Is this a bug, or a feature?

Here's my eslintrc:

```
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "globals": {
    "__DEV__": true
  },
  "rules": {
    "comma-dangle" : [1, "always-multiline" ],
    "jsx-quotes":  [1, "prefer-double"],
    "key-spacing": [1, { "align" : "value" }],
    "no-multi-spaces" : [
      1,
      {
        "exceptions" : {
          "VariableDeclarator" : true,
          "ImportDeclaration"  : true
        }
      }
    ],
    "no-multiple-empty-lines" : 1,
    "no-nested-ternary" : 0,
    "quotes": [1, "double", "avoid-escape"],
    "react/jsx-quotes": 0,
    "semi" : 1
  }
}
```

Other than that, my setup is more or less unchanged from the [react-starter-kit](https://github.com/kriasoft/react-starter-kit)

**Comment by yannickcr** [comment]
Same error as #203, property declaration must be followed by a `=`, not a `:`.

See https://github.com/yannickcr/eslint-plugin-react/issues/203#issuecomment-136501080 for explanation.
