### ISSUE TITLE
jsx-indent-props for aligned indentation

### ISSUE THREAD

**Issue by davegomez** [yannickcr/eslint-plugin-react#398]
It would be nice if this rule would allow to set an option to lint all the props declarations one below the other just like the next snippet shows.

``` jsx
<div styleName='content'>
  <TableOfContents content={props.model.tableOfContents} />
    <ContentView content={props.model.contents}
                 editing={props.model.editing}
                 actions={props.actions}
                 bind={this.props.bind} />
</div>
```

**Comment by mediarss** [comment]
+1

**Comment by erezcohen** [comment]
+1

**Comment by miraage** [comment]
+1

**Comment by shendepu** [comment]
+1

**Comment by ljharb** [comment]
I'm going to delete these `+1` comments, and any further ones - please follow GitHub etiquette and express that emotion with a reaction on the original post. Thanks!

**Comment by klimashkin** [comment]
Currently such indentation is default one in WebStorm - it's clear and convenient.

Really want to have rule config like
```javascript
'react/jsx-indent-props': [2, 2],
```
and for example
```javascript
'react/jsx-indent-props': [2, 'tag-name'],
```

**Comment by klimashkin** [comment]
Also similar to eslint `indent` rule 
```javascript
indent: [2, 2, {
  'FunctionDeclaration': {
    'parameters': 'first',
    'body': 1,
  },
}]
```
we can call it `first`
```javascript
'react/jsx-indent-props': [2, 'first'],
```
