### ISSUE TITLE
No definition for react/no-deprecated

### ISSUE THREAD

**Issue by jasonkuhrt** [yannickcr/eslint-plugin-react#399]
Why would this happen?

<img width="697" alt="screen shot 2016-01-19 at 12 25 05 pm" src="https://cloud.githubusercontent.com/assets/284476/12426447/bb2cb876-bea7-11e5-9447-363c639761ea.png">

**Comment by yannickcr** [comment]
The `no-deprecated` rule was introduced in `v3.12.0`, so you may need to upgrade `eslint-plugin-react`.

**Comment by jasonkuhrt** [comment]
I am using `"^3.15.0"`. Hm..

**Comment by yannickcr** [comment]
Do you correctly load `eslint-plugin-react` ? Can you past your `.eslintrc` config file ?

**Comment by jasonkuhrt** [comment]
I think this is all the info you need/are asking for:

* https://github.com/littlebits/code-standards-js/blob/master/package.json#L33-L36
* https://github.com/littlebits/react-popover/blob/master/package.json#L59-L63

Let me know.

**Comment by justin808** [comment]
I just hit this. Problem was my global eslint was used and not the project specific one.

**Comment by ndreckshage** [comment]
I also get this simply by extending airbnb by only extending eslint-config-airbnb

**Comment by ljharb** [comment]
@ndreckshage `eslint-plugin-react` is a peer dependency of `eslint-config-airbnb` - npm 2 will install it automatically, but npm 3 will just give you a warning that you need to install it manually.

**Comment by lencioni** [comment]
This seems to have been an issue with peer dependencies and npm 3, and can likely be closed out.
