### ISSUE TITLE
Will you add the requirement of adding semi colons for react class properties?

### ISSUE THREAD

**Issue by Dindaleon** [yannickcr/eslint-plugin-react#403]
https://github.com/babel/babel/pull/3225
https://github.com/LKay/react-bootstrap-datetimepicker/pull/2

**Comment by yannickcr** [comment]
No, since it's related to the parser and the ES6 classes, and not related to React at all.

**Comment by ziemkowski** [comment]
Not to mention that commit is in error and needs to be reverted, since it isn't actually a requirement anyways.
