### ISSUE TITLE
A "class"/ "React.createClass" component with no state/refs/lifecycle methods should be stateless

### ISSUE THREAD

**Issue by ljharb** [yannickcr/eslint-plugin-react#405]
Feature request! Per https://github.com/airbnb/javascript/issues/612#issuecomment-173135008, it'd be great if a component that does not reference `this.state` or `this.refs` (including `{ state } = this`/ `{ refs } = this`/`var foo = this; foo.state` etc), and that has no lifecycle methods, should instead be a functional stateless component.

**Comment by yannickcr** [comment]
Duplicate of #214, but yes it could be a very useful rule, I need to work on it.
