### ISSUE TITLE
jsx-max-props-per-line: different value for oneline tags and multiline tags

### ISSUE THREAD

**Issue by janmarek** [yannickcr/eslint-plugin-react#410]
Hi, I write JSX like this.

```js
// ok
<Component prop1="val" prop2="val" />
<Component 
    prop1="val" 
    prop2="val" 
/>

// not ok
<Component 
    prop1="val" prop2="val" 
/>
```

Currently it is not possible to set jsx-max-props-per-line differently for multiline tags.

**Comment by nevir** [comment]
I would also be interested in this

**Comment by ljharb** [comment]
this seems totally reasonable - i also require either all props + component on one line, or, never more than one thing on the same line.

**Comment by rjokelai** [comment]
+1 I'd like to see this, too

**Comment by mwilliamson-healx** [comment]
I've probably missed something, but I'm still not sure how to enforce this. `jsx-first-prop-new-line` makes sure that the first prop is on a new line, but doesn't enforce anything about later props. `jsx-max-props-per-line` still applies equally to single-line and multi-line tags.

**Comment by van-nguyen** [comment]
+1 IMO this is a very reasonable rule to have, any multiline props with more than 1 is not scannable
