### ISSUE TITLE
Even when using this plugin I get  "React" is defined but never used at line error

### ISSUE THREAD

**Issue by THPubs** [yannickcr/eslint-plugin-react#415]
I added this plugin to eslint and still get the error saying `"React" is defined but never used at line error`. Im using Atom and here's my `.eslintrc.js` :

    module.exports = {
      "extends": "airbnb",
      "extends": "meteor",
      "parser": "babel-eslint",
      "plugins": ["react"],
      "ecmaFeatures": {
        "jsx": true
      }
    };

Am I doing anything wrong? :-)

**Comment by yannickcr** [comment]
Hi, you must enable the [react/jsx-uses-react](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md) rule to avoid this problem.

**Comment by THPubs** [comment]
Great thanks :-)
