### ISSUE TITLE
'react/wrap-multilines': undefined is not a function

### ISSUE THREAD

**Issue by acthp** [yannickcr/eslint-plugin-react#437]
Getting this with 3.16.1. I tried several versions of babel-eslint, the latest 4 version, plus 5 betas 6 and 10, all of which fail in the same way. Any suggestions?

**Comment by yannickcr** [comment]
Can you post more details? (stacktrace, .eslintrc config file and code that trigger the error?)

It will help us to fix the problem. Thanks.

**Comment by acthp** [comment]
It's something to do with running from npm. Outside of npm I hit a different error. :-p  I checked the global & node_modules eslint versions, both of which are 0.20.0. Running from npm with this script config:

    "lint": "eslint --no-color js/*.js test/*.js"

gives me the error. The input js file doesn't matter. All of them fail in the same way.

Running the same command in bash gives a different error, which depends on the input file. Most input files are fine when running from bash.

[eslintrc.txt](https://github.com/yannickcr/eslint-plugin-react/files/125552/eslintrc.txt)
[stack.txt](https://github.com/yannickcr/eslint-plugin-react/files/125557/stack.txt)

**Comment by ljharb** [comment]
fwiw, the stack trace points to https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/wrap-multilines.js#L23 - which suggests that `context` doesn't have a `getSourceCode` function.

**Comment by yannickcr** [comment]
> I checked the global & node_modules eslint versions, both of which are 0.20.0

If you are really using eslint@0.20.0 this can explain the error.

I suggest you to upgrade to latest eslint version and retry.

**Comment by acthp** [comment]
Upgrade of eslint and eslint-babel resolves it, thanks.
