### ISSUE TITLE
JSX spread operator not supported?

### ISSUE THREAD

**Issue by rocketraman** [yannickcr/eslint-plugin-react#44]
eslint 0.18.0 with eslint-react-plugin 2.0.1 returns `Unexpected token ..` with a JSX spread operator:

spread.js:

```javascript
let { aprop, ...other } = this.props
```

.eslintrc:

```javascript
{
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "ecmaFeatures": {
    "modules": true,
    "jsx": true,
    "destructuring": true,
    "spread": true,
    "arrowFunctions": true,
    "blockBindings": true
  },
  "plugins": [
    "react"
  ],
  "rules": { // 0=off, 1=warning, 2=error
    // Strict mode
    "strict": [2, "global"],

    // React (eslint-plugin-react)
    "react/jsx-no-undef": 1,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-unknown-property": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 1,
    "react/self-closing-comp": 1,
    "react/wrap-multilines": 1,
  }
}
```

```
$ eslint spread.js

spread.js
  1:14  error  Unexpected token ..
```

```
$ eslint --version
v0.18.0
```

```
$ grep "version" node_modules/eslint-plugin-react/package.json
  "version": "2.0.1",
```

**Comment by yannickcr** [comment]
The error comes from ESLint and not the plugin.

Seems it's parser [Espree](https://github.com/eslint/espree) does not support the spread operator in destructuring assignment.

**Comment by rocketraman** [comment]
> Seems it's parser Espree does not support the spread operator in destructuring assignment.

Espree is supposed to support both the destructuring and spread operators. I will raise an issue there. Thanks.

**Comment by rocketraman** [comment]
FYI: https://github.com/eslint/espree/issues/116

**Comment by rocketraman** [comment]
Based on the comments in https://github.com/eslint/espree/issues/116, it doesn't look like espree will be supporting this until the notation is standardized. However `babel-eslint` does handle this case without issue.

**Comment by yannickcr** [comment]
Ok, I try to support the `babel-eslint` parser (since a lot of React developers are using it) but for now I only run the tests with the default parser Espree. I need to improve this. 

Also, since #46 is fixed, you should be able to fully use the spread operator while destructuring props.

**Comment by rocketraman** [comment]
:+1:
