### ISSUE TITLE
Add note that "extends": "plugin:react/recommended" is only available with 4.0.0-rc

### ISSUE THREAD

**Issue by joeytrapp** [yannickcr/eslint-plugin-react#451]
I spent a good while trying to figure out why the README setup instructions were not working. Then realized that there was a 4.0.0-rc available that implements the features available in the README.

Please mention this in the top of the README if the project is going to remain in rc.

**Comment by ThaJay** [comment]
thank you for this post

**Comment by wyze** [comment]
Looks like there is a plan to publish a final version tomorrow: https://github.com/yannickcr/eslint-plugin-react/issues/436#issuecomment-185827479

**Comment by joeytrapp** [comment]
Perfect.

**Comment by dawncold** [comment]
+1

**Comment by yannickcr** [comment]
`4.0.0` is now published
