### ISSUE TITLE
Better formatting for jsx ternary operator 

### ISSUE THREAD

**Issue by steida** [yannickcr/eslint-plugin-react#452]
Simple rule: One line can contain only JS or HTML exclusively.

``` jsx
{viewer ?
  <b>foo</b>
:
  <b>bar</b>
}
```

Related to https://github.com/este/este/issues/724

**Comment by palnes** [comment]
I kinda like:
```
{
foo
? <b>bar</b>
: <b>baz</b>
}
```

**Comment by lencioni** [comment]
I generally prefer to avoid the ternary altogether:

```jsx
{foo && <b>bar</b>}
{!foo && <b>baz</b>}
```

**Comment by ljharb** [comment]
I'm not sure if this is still relevant, but if the latest version of the plugin still doesn't meet your needs, please file a new issue.
