### ISSUE TITLE
Support Flow Prop/State syntax

### ISSUE THREAD

**Issue by mmermerkaya** [yannickcr/eslint-plugin-react#453]
Is it possible for you to support this:
`class MyComponent extends React.Component<void, Props, void> {`

which does the same thing as this:

```
class MyComponent extends React.Component {
  props: Props
```

Also described [here](https://www.reddit.com/r/reactjs/comments/44yqge/fyi_proptypes_are_on_their_way_out/czuflhe).

**Comment by ljharb** [comment]
See https://github.com/facebook/react/issues/1833#issuecomment-182539474 - propTypes aren't going anywhere.

**Comment by mmermerkaya** [comment]
I know, I just linked the thread because someone working on React provided an example of declaring props using Flow.

**Comment by yannickcr** [comment]
We already support flow annotations for props (see https://github.com/yannickcr/eslint-plugin-react/pull/382) but not the syntax you described.

I do not know Flow very well (I do not use it), but maybe adding support for this will not be very difficult.

**Comment by MoOx** [comment]
With babel-eslint, it seems to be working fine.

**Comment by thejameskyle** [comment]
Should eslint-plugin-react add babel-eslint somehow to people's configs? Seems pretty standard in the React community

**Comment by ljharb** [comment]
Requiring `babel-eslint` means it has to be a peer dependency, so that would add some burden on everyone wishing to use the plugin.

However, if we want rules that support flow types, it's possible we might need to require that parser.

**Comment by jomasti** [comment]
I believe this was resolved by #1377.
