### ISSUE TITLE
Do not require 'children' as missing prop

### ISSUE THREAD

**Issue by seekshiva** [yannickcr/eslint-plugin-react#458]
When the `prop-types` rules is on, don't ask 'children' to be declared in propType. It is provided by React by default.

**Comment by yannickcr** [comment]
It as already been discussed in #7, see ["As for exceptions"](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md#as-for-exceptions) section in documentation.

If you do not want to declare a propType for `props.children` you can still add it to the `ignore` list (see [rules options](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md#rule-options))

**Comment by seekshiva** [comment]
Thanks
