### ISSUE TITLE
Definition for rule 'react/jsx-key' was not found

### ISSUE THREAD

**Issue by awestroke** [yannickcr/eslint-plugin-react#463]
`Definition for rule 'react/jsx-key' was not found  react/jsx-key`

Is this rule not published?

.eslintrc:

```json
{
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true,
      "modules": true
    },
  },
  "env": {
    "browser": true,
    "node": true,
    "mocha": true,
    "es6": true
  },
  "parser": "babel-eslint",
  "rules": {
    "react/jsx-key": 2
  },
  "plugins": [
    "react"
  ]
}
```

devDependencies:

```json
{
	"babel-eslint": "5.0.0",
	"eslint": "2.1.0",
	"eslint-plugin-react": "4.1.0"
}
```

**Comment by yannickcr** [comment]
This rule was added in `v3.9.0` so you should be able to use it.

Be sure to have eslint and eslint-plugin-react at the same place (both in local or both in global) and 
that they are correctly updated.

**Comment by awestroke** [comment]
Like you suggested, the issue was that I had a global eslint installed that was used instead of the local one. Works now. Thanks!
