### ISSUE TITLE
jsx-no-bind circumventable via Short-Circuit Evaluation 

### ISSUE THREAD

**Issue by iilei** [yannickcr/eslint-plugin-react#474]
example code `myHandler={true && this.myHandler.bind(this, key)}` results in *no warnings*, while I would expect it to throw *error  JSX props should not use .bind()  react/jsx-no-bind*

Is this a bug or am I missing something?

**Comment by ljharb** [comment]
Similarly, I've noticed that `const foo = this.whatever.bind(this);` and then `prop={foo}` doesn't seem to warn either.

**Comment by iilei** [comment]
@ljharb I assume  `const foo = this.whatever.bind(this);` resides outside of the returned block jsx, right? I don't think that is related

**Comment by ljharb** [comment]
@iilei yes it is - no functions should be created in the entire render path and passed as props, which is what this rule is attempting to prevent.

**Comment by iilei** [comment]
I see ... @petersendidit :+1:
