### ISSUE TITLE
reusable proptypes: missing props

### ISSUE THREAD

**Issue by luisrudge** [yannickcr/eslint-plugin-react#476]
This is my component:

``` jsx
import React from 'react';
import {formPropTypes} from 'utils/form';

export default class Test extends React.Component {
  static propTypes = {
    ...formPropTypes
  };
  render() {
    return (
      <div>test</div>
    );
  }
}
```

Eslint says all my proptypes from `formPropTypes` are missing :( 

``` json
"babel-eslint": "4.1.7",
"eslint": "1.10.3",
"eslint-friendly-formatter": "1.2.2",
"eslint-loader": "1.2.1",
"eslint-plugin-react": "3.16.1",
```

**Comment by nuschk** [comment]
Is this being considered? Seems a bit far-reaching for a linter, no?

**Comment by ljharb** [comment]
I think this is basically impossible for a linter - it would have to dynamically evaluate the `utils/form` file in order to know what the prop types are.

**Comment by nuschk** [comment]
Seems very plausible, thanks for the explanation. 

Do you guys have other strategies for preventing re-typing proptypes then? Specifically, in our code, there are many redux-form components, which always use the same 8 to 10 props, which are injected by a decorator. While perfectly doable, it is a bit tedious to repeat them for every form.

**Comment by kumar303** [comment]
One solution is to use [Flow](https://flowtype.org/) instead of PropType (it's a lot of work to switch though). Flow lets you [import type objects](https://flowtype.org/docs/modules.html#type-imports--exports) so that the definitions can be re-used.

**Comment by ljharb** [comment]
@kumar303 the same issues would happen with imported Flow type objects, because linters can not follow imports.

**Comment by kumar303** [comment]
Flow supports the import statement for types. You can pass around type "objects" just like any other JavaScript object. Being able to import a custom type is useful for sharing it among many different functions. [Here's an example of how I've used it](https://github.com/mozilla/web-ext/blob/a25c04fcd6179421282fd0336ffb84751413acf2/src/cmd/build.js#L24) -- this isn't React code though.

**Comment by ljharb** [comment]
We've made tons of improvements to propTypes detection in the last 6 years. I'm going to close this; if there's still issues, please file a new issue and we'll address it ASAP.
