### ISSUE TITLE
New Rule Proposal: enforce return in render() method

### ISSUE THREAD

**Issue by silvenon** [yannickcr/eslint-plugin-react#482]
It sometimes happens to me that I forget to `return` JSX content in the `render` method. This rule would warn if the `return` statement is missing.

**Comment by bsbeeks** [comment]
I run into this use case as well. It's fairly easy to catch with the React errors in the browser, but having a rule to help catch it before hand would be great. @yannickcr I can put together a PR for this if it's a rule we want to add.

Proposed Rule Name: `require-render-return`

**Comment by ljharb** [comment]
What about returning `null`? What about returning the contents of a function call (which may or may not contain jsx)?

If this is just ensuring that a render method returns *something*, that's fine, but I'm skeptical about the value it will add.

**Comment by bsbeeks** [comment]
In my mind the rule would just check for a `return` statement in the `render` method. It wouldn't care about what it's returning. The value add would probably depend on the project and the component. I'm not sure how to measure that value, but I know it'd be useful for our projects at MX (especially for newbie devs)

**Comment by yannickcr** [comment]
> If this is just ensuring that a render method returns something, that's fine, but I'm skeptical about the value it will add.

Same for me, but if you send a PR for this @bsbeeks don't really see reasons to refuse it.

**Comment by silvenon** [comment]
You can always bypass certain rules in some way, you can do `const { props } = this` and now using `props.foo` won't check if `foo` is defined in `propTypes`.

If a component returns an invalid value, there's not much the plugin can do about it. This rule is a faster way to see that you forgot to return the JSX. If the user returns something which does not resolve to JSX, that's on them. This distinction is clear to me.
