### ISSUE TITLE
Rule 'jsx-uses-vars': why not on by default?

### ISSUE THREAD

**Issue by banderson** [yannickcr/eslint-plugin-react#49]
Thanks for this plugin! Very cool.

I'm thinking about adopting this for my default setup across the org, but just wondering why `jsx-uses-vars` wouldn't be turned on by default (maybe to 'warn')? I guess the real question is: what's the use case for _not_ wanting to mark them used?

Also, I'm totally willing to PR a change, but just wanted to get your feedback first. And if the consensus is no rule should be on by default, can we invert the language of the rule to something like `jsx-ignore-var-usage`?

**Comment by yannickcr** [comment]
Hi, there is no particular reason why this rule turned off by default.

It's just historical: I progressively added rules to the plugin and all new rules were added off by default. 

We could totally turn it on by default since this rule has no effect if the `no-unused-vars` ESLint rule is not enabled.

**Comment by jv-PintoBobcat** [comment]
:+1: for this turned on by default

**Comment by banderson** [comment]
@yannickcr would you like me to PR this change?

**Comment by yannickcr** [comment]
You can do a PR for this :)

**Comment by schickling** [comment]
I would even go a step further an switch on all features that "make sense" by default and release a new version with those "breaking changes". I find my self copying all those config stuff in the `.eslintrc` files currently.

**Comment by banderson** [comment]
@schickling that's definitely a good conversation to have with @yannickcr , but I just PR'd this one change for now. I'd be glad to help out with further changes if that's what's decided.
