### ISSUE TITLE
[prefer-stateless-function] false position with this case

### ISSUE THREAD

**Issue by tleunen** [yannickcr/eslint-plugin-react#499]
Most issues around `prefer-stateless-function` are fixed. Thanks a lot for that, but I'm still having a few cases when it's warning wrong classes.

For example, this one. The class has a `constructor`, but also `componentDidMount` and other lifecycles functions, so it should not be compatible with a SFC.
<img width="924" alt="screen shot 2016-03-13 at 10 16 48 pm" src="https://cloud.githubusercontent.com/assets/1972567/13733427/5e01a228-e969-11e5-8a41-e933007a5e18.png">

**Comment by yannickcr** [comment]
Did you test on `master` ? Since the fixed `prefer-stateless-function` is not yet released on npm.

**Comment by tleunen** [comment]
Oh my bad, I thought it was on 4.2.1

**Comment by tleunen** [comment]
@yannickcr I'm reopening, because I just tested with 4.2.2 and I still have the issue.
Funny thing though, if I have `this.id = 2` or a property `id` on any object, the error is not reported.

Here a quick small example:
<img width="551" alt="screen shot 2016-03-14 at 7 52 18 pm" src="https://cloud.githubusercontent.com/assets/1972567/13763668/595b12a8-ea1e-11e5-90ce-d3b1b3623129.png">

Looks like the error is not reported only when `this` is used.

**Comment by yannickcr** [comment]
Ok, there is a small bug on how we retrieve the class properties, so we do not catch `componentDidMount`. I will publish a patch release tomorrow.
