### ISSUE TITLE
react/jsx-uses-react (react/react-in-jsx-scope) doesn't work

### ISSUE THREAD

**Issue by asakura** [yannickcr/eslint-plugin-react#50]
Hi! I'm using "eslint-plugin-react": "^2.0.2" and have some weird issues with it on one specific file. In other cases it working great, thank you :)

Eslint output:
```sh-session
src/routes.js
   3:4  error    React is defined but never used          no-unused-vars
   7:4  error    Route is defined but never used          no-unused-vars
   8:4  error    DefaultRoute is defined but never used   no-unused-vars
  30:2  warning  'React' must be in scope when using JSX  react/react-in-jsx-scope
  31:4  warning  'React' must be in scope when using JSX  react/react-in-jsx-scope
  33:4  warning  'React' must be in scope when using JSX  react/react-in-jsx-scope
```

In .eslintrc
```
        "no-unused-vars": [2, {"vars": "all", "args": "after-used"}],
        "react/jsx-uses-react": [1],
        "react/jsx-uses-vars": [1],
        "react/react-in-jsx-scope": [1],
```

In src/routes.js:
```
'use strict';

var React = require('react');

var Router = require('react-router');

var Route = Router.Route,
    DefaultRoute = Router.DefaultRoute;

var App = require('./components/app/app'),
    Dashboard = require('./components/dashboard/dashboard'),
    Search = require('./components/search/search');

var UserList = require('./components/user/list'),
    UserView = require('./components/user/view'),
.....skipped......

module.exports = (
  <Route path="/ui" handler={App}>
    <Route name="dashboard" path="/ui" handler={Dashboard} />

    <Route name="users" handler={UserList} />
    <Route name="user" path="/ui/users/:id" handler={UserView} />

.....skipped......
    <DefaultRoute handler={Dashboard} />
  </Route>
);
```

I hope I just overlooked something in configuration, but what exact?

**Comment by yannickcr** [comment]
Hi, do you use the `babel-eslint` parser ? Seems there is a bug when using `react-in-jsx-scope` and this parser.

**Comment by asakura** [comment]
Hi
Yes, I do. Is there exist any workarounds?

**Comment by yannickcr** [comment]
I am not aware of any workarounds, except disabling the rule or using the default parser.

I'll try to fix this bug during this week-end.

**Comment by asakura** [comment]
Great, thank you.

**Comment by asakura** [comment]
Now it's working as expected, thanks.

**Comment by creynders** [comment]
Could it be this regressed? Updated `eslint` and `eslint-plugin-react` but it still complains about React being unused.

**Comment by creynders** [comment]
A bit more info: If I set `"react/jsx-uses-react": 0` it reports 37 `React is defined but never used` errors, but if I set it to 1, it only reports 15, so it appears that it does work somewhat, but inconsistently.

**Comment by yannickcr** [comment]
Can you provide a reduced test case with the `.eslintrc` configuration file ?

I tested with one of the files you patched (https://github.com/keystonejs/keystone/blob/master/fields/types/geopoint/GeoPointField.js) with this configuration:

.eslintrc

```json
{
    "env": {
        "es6": true
    },
    "ecmaFeatures": {
        "jsx": true
    },
    "parser": "babel-eslint",
    "plugins": [
      "react"
    ],
    "rules": {
        "no-unused-vars": 1,
        "react/jsx-uses-react": 1
    }
}
```

And I only got a warning about `Note` being unused (which is correct)

```bash
$ eslint --reset GeoPointField.js

GeoPointField.js
  3:4  warning  Note is defined but never used  no-unused-vars

✖ 1 problem (0 errors, 1 warning)
```

Tested with eslint `0.20.0` , eslint-plugin-react `2.2.0` and babel-eslint `3.0.1`

**Comment by creynders** [comment]
Tomorrow I'll dig up the ones that definitely fail on my system when I drop the ignore blocks. Hope it'll tell us some more.

**Comment by creynders** [comment]
These definitely fail with `React is defined but never used`:

- https://github.com/keystonejs/keystone/blob/master/fields/types/url/UrlField.js
- https://github.com/keystonejs/keystone/blob/master/fields/types/text/TextField.js
- https://github.com/keystonejs/keystone/blob/master/fields/types/key/KeyField.js

Yeah, it's less than I reported, got a few mixed up.

It's run with these settings:

https://github.com/keystonejs/keystone/blob/master/.eslintrc

**Comment by yannickcr** [comment]
Actually ESLint is right, `React` is imported at the top of theses files but not used thereafter.

**Comment by creynders** [comment]
Ah, then I _totally_ misunderstand the purpose of this rule. I'm a real noob when it comes to react. Sorry about this then. Thanks for taking your time to check it out.
