### ISSUE TITLE
Documentation request/question: please note how to configure the rules somewhere

### ISSUE THREAD

**Issue by anyong** [yannickcr/eslint-plugin-react#503]
Is everywhere it says <enabled> in the documentation the same as 0, 1, 2 or "off" / "warn" / "error"? Some rules don't even say anything about how to configure it, i.e. [jsx-key](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md)

This is a pretty easy oversight to correct...

**Comment by ljharb** [comment]
@anyong this is part of `eslint` itself, and shouldn't be documented on an arbitrary plugin. http://eslint.org/docs/user-guide/configuring might be helpful.
