### ISSUE TITLE
Warning: Cannot read config package: eslint-config-plugin:react/recommended

### ISSUE THREAD

**Issue by villesau** [yannickcr/eslint-plugin-react#536]
By following the instructions in readme, i'm getting the error in the title. I'm running at the time of writing latest eslint-plugin-react(4.3.0), and latest eslint(2.7.0).

the line where i'm trying to import defaults:
"extends": ["plugin:react/recommended"]

**Comment by yannickcr** [comment]
Seems you're not using the latest ESLint but an older version (pre v2.0.0) that does not support config in plugins (this error message was removed from ESLint in v2.0.0-beta.3 https://github.com/eslint/eslint/commit/e3f2683e3698f2be248ef5b1a2508b988203a875).

I suspect you to have an old ESLint installed globally and the v2.7.0 locally (or the opposite).

**Comment by villesau** [comment]
Doh. Stupid mistake: Our project used oldish grunt-eslint which depended on old eslint. Thus it didn't matter which version of eslint was in our package.json. Sorry for disturbing you with this!

**Comment by ryancole** [comment]
I'm encountering this issue, myself. I've checked my eslint versions, and everything seems to be the most recent. I don't have eslint globally installed, either.

```
C:\Users\Ryan\Projects\league>npm ls --global
C:\Users\Ryan\AppData\Roaming\npm
`-- (empty)


C:\Users\Ryan\Projects\league>npm ls eslint
league@0.0.1 C:\Users\Ryan\Projects\league
+-- eslint@2.10.2
`-- UNMET PEER DEPENDENCY graphql@0.6.0

npm ERR! peer dep missing: graphql@^0.5.0, required by express-graphql@0.5.1
npm ERR! peer dep missing: graphql@~0.5.0, required by graphql-relay@0.4.1

C:\Users\Ryan\Projects\league>npm ls eslint-plugin-react
league@0.0.1 C:\Users\Ryan\Projects\league
+-- eslint-plugin-react@5.1.1
`-- UNMET PEER DEPENDENCY graphql@0.6.0

npm ERR! peer dep missing: graphql@^0.5.0, required by express-graphql@0.5.1
npm ERR! peer dep missing: graphql@~0.5.0, required by graphql-relay@0.4.1
```

Don't mind the unmet deps for graphql, they're unrelated.

**Comment by ryancole** [comment]
Blargh. Nevermind. I think Atom editor was keeping around an old version, or something. I just closed everything out, deleted all node_modules dirs, and started over. Works now.

**Comment by vettukal** [comment]
I had a global eslint and package.json eslint(1.10.3). What worked for me:

remove the `"eslint": "^1.10.3",` from package.json.

Then 
`rm -rf node_modules && npm uninstall -g eslint eslint-plugin-react`

and 

`npm install --save-dev eslint eslint-plugin-react && npm install`
