### ISSUE TITLE
require-render-return needs one exception

### ISSUE THREAD

**Issue by richard-lopes** [yannickcr/eslint-plugin-react#539]
Hi,

I was using the new `require-render-return` rule and found a couple of cases in our big codebase where it was causing some grief.
If instead of returning something you throw an error like such: `throw new NotImplementedException();` then the rule will underline that as an error. However throwing is what we want in those cases.
Could it be possible to add that exception to the rule ?

Thanks.

**Comment by ljharb** [comment]
@richard-lopes if you simply omit the method in your base class definition, you'll get an exception anyways. Why do you find you need this Java-like pattern in JS?

**Comment by richard-lopes** [comment]
I understand what you mean and this is true. Like you pointed out this is inherited by habits from .Net and Java developers. But these days they are coming en masse to JS and tend to replicate practices they have had for years.
In that case I will push a PR to change this in our project.

**Comment by ljharb** [comment]
To answer your original question, I think if you preserve this pattern, then the proper response is to use inline eslint comments to disable the rule in your base classes.

**Comment by richard-lopes** [comment]
Yes that could be another option. But I try to avoid eslint-disable as much as possible. I think your first answer is reasonable.
