### ISSUE TITLE
Proposition: add some defaults for prop-types to ignore

### ISSUE THREAD

**Issue by AlexKVal** [yannickcr/eslint-plugin-react#54]
As in [React.Children](https://facebook.github.io/react/docs/top-level-api.html#react.children) said:
> React.Children provides utilities for dealing with the this.props.children opaque data structure.

`props.children` has an `opaque` type.

So maybe it would be wise to add it into some kind of `defaults` list to ignore.

For now it needs to be added
```javascript
"react/prop-types": [1, { ignore: [children] }]
```
into `.eslintrc`.

Same is true for `className` (and maybe for some more, that I'm not aware of yet).

I am new to `React` development and I believe I just don't know something related to written above,
so I'm looking for help with this idea.

If it turns up the idea is right one, I could try to implement it (with tests and docs of course).

**Comment by yannickcr** [comment]
In first implementation `children` was always ignored since defining some propTypes for it is not a very common practice. But as @AsaAyers pointed out, there is no particular reason to document all props but not `children`. Same for `className`.

In think you can discuss it in #7.

**Comment by AsaAyers** [comment]
IMO if `children` is difficult to figure out which type, you can always use `React.PropTypes.any`.

**Comment by AlexKVal** [comment]
I knew I wasn't first who noticed. :smile:
So I think it would be logical to add notice about this situation into docs for future developers.
My possible solution for this is #55.
English is not my native, so I'm apologise for any errors. ( fixes are appreciated ;) )

**Comment by yannickcr** [comment]
Thanks! Documentation improvement is always welcome :)
