### ISSUE TITLE
jsx-sort-props with out alphabetical sort

### ISSUE THREAD

**Issue by chrishoage** [yannickcr/eslint-plugin-react#541]
I apologize for posting a question here, but is there any way to use `jsx-sort-props` with out alphabetical sort? 

I really really want the `callbacksLast` rule but have no desire to enforce alphabetical prop order? Is this currently possible or would it require a source change?

**Comment by yannickcr** [comment]
Currently no, there is no way with the current rule to do this without enforcing the alphabetical order.

**Comment by chrishoage** [comment]
Bummer, well feel free to close this ticket if it's not of scope for the rule. Otherwise, feel free to use this ticket to track the feature. 

Thank's so much!
