### ISSUE TITLE
Remove deprecated jsx-sort-prop-types rule?

### ISSUE THREAD

**Issue by ljharb** [yannickcr/eslint-plugin-react#549]
It'd be nice to remove the https://github.com/yannickcr/eslint-plugin-react/blob/e3c27f9ecea4d71e5fa6d0aa9131fdd1f5c1db75/lib/rules/jsx-sort-prop-types.js rule at some point - probably missed the boat on v5, but maybe in v6?

**Comment by yannickcr** [comment]
Oups, totally forgot this one :|

Too late for the `v5.0.0`, but yeah, it should definitively be removed in `v6.0.0`
