### ISSUE TITLE
missing props validation -validation only for exported functions?

### ISSUE THREAD

**Issue by villesau** [yannickcr/eslint-plugin-react#557]
Hi!

I have a stateless component which consists of multiple smaller functions within the same module. Now every single function needs prop types which is super verbose. Is there a way to enforce the prop types only to the exported one or am i just missing something? I think it would make sense to have an option to enforce only the exported function to contain proptype validations.

here is an example code:

``` javascript

import React, {PropTypes} from 'react';
import Stuff from './Stuff';

const MyComponent = (props) => (
        <div >
            <div className="grid-col">
                {getStuff(props)}
            </div>
            <div className="grid-col">
                {getOtherStuff(props)}
            </div>
        </div>
);

function getStuff(props) {
    const props = {
        stuff: props.someStuff
    };
    return <Stuff {...props} />;
}
//the above function is OK because of the defined proptypes
getStuff.propTypes= {someStuff: PropTypes.string}; //this could contain many many more of these which bacomes very verbose.

function getOtherStuff(props) {
    const props = {
        stuff: props.someOtherStuff // Missing props validation :(
    };
    return <Stuff {...props} />;

}

MyComponent.propTypes = {
    someStuff: PropTypes.string.isRequired, // imo it would make sense to define them only once per module, not for every single function
    someOtherStuff: PropTypes.string.isRequired,
    ...lotsOfProps
};

export default MyComponent;

```

**Comment by daisymark** [comment]
i want konw  too...

**Comment by daisymark** [comment]
I konw that!~  https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md

you can add this :
Rank.propTypes = {
  stuff: React.PropTypes.string.isRequired
}

**Comment by rhys-vdw** [comment]
> I think it would make sense to have an option to enforce only the exported function to contain proptype validations.

Yes, I'm interested in this feature too. Although I'd be happy with either of these options:

 - Enforce prop types *only* on exported components.
 - Ignore stateless components (whose definition is typicaly shorter and more self explanatory)

I have no experience with ESLint source, but I'm willing to have a shot at submitting a PR.

**Comment by rhys-vdw** [comment]
btw, this is probably obvious to most people using ESLint, but you can just prefix simpler components like this:

```js
// eslint-disable-next-line react/prop-types
function SimpleComponent({ propA, propB }) {
  return (/* */)
}
```

```js
function SimpleComponent(props) {
  // eslint-disable-next-line react/prop-types
  const { propA, propB } = props
  return (/* */)
}
```

I think this is perhaps preferable to the proposal in this thread, since it's opt-in per component.

**Comment by mjhm** [comment]
@rhys-vdw FWIW -- I disagree -- the proposal as stated is preferable. Disabled eslint rules are a yellow flag for our code reviews.

Without this rule some of our developers are opting to avoiding the PropTypes verbosity and eslint errors by just inserting components with `{...}` instead of JSX.  So we get code looking like

```
  <ul>
    {MyInput.bind(null, { label: 'name' })}
    {MyInput.bind(null, { label: 'city' })}
  </ul>
```
instead of
```
  <ul>
    <li><MyInput label={name}></li>
    <li><MyInput label={city}></li>
  </ul>
```
It's hard to argue with them that the cleaner JSX is worth the verbosity of obvious propTypes declarations for local mini-components.

**Comment by ljharb** [comment]
Invoking SFCs directly comes with caveats; in particular, contextTypes and defaultProps won't work as you expect.

It's not verbosity, it's the minimum required explicit declaration. If they think propTypes aren't required, then clearly they don't think it's worth being in a component, and they should inline everything.

**Comment by mjhm** [comment]
@ljharb I dunno about that.  Using lots of inline functions instead of SFCs seems pretty ugly to me. But beyond aesthetics it also adds friction to the refactoring process.  For example when `MyInput` grows up to be a more significant component in it's own component file, I would need to change the inline statements to actual JSX components.  That's not bad in isolated cases, but in the aggregate of a big, fast moving project, it's one more avenue for developer errors that I'd like to avoid.

**Comment by ljharb** [comment]
@mjhm i completely agree - which is why i think SFCs should always have propTypes, no exceptions.

**Comment by ljharb** [comment]
The biggest benefit of factoring things out to separate components is that you can provide propTypes (and/or TS types) on all of them. Whether they're exported or not is irrelevant.
