### ISSUE TITLE
react/display-name rule firing of regular classes

### ISSUE THREAD

**Issue by globexdesigns** [yannickcr/eslint-plugin-react#57]
When defining plain Javascript classes (not React component classes), the display-name still fires. It shouldn't.

```
class Test {
	constructor() {
	}
}
```

```
// From ESlint
App component definition is missing display name [react/display-name] class App {
```

**Comment by AlexKVal** [comment]
I cannot reproduce your bug.
https://github.com/AlexKVal/ch_r_display_name

**Comment by yannickcr** [comment]
Cannot reproduce neither.

Can you give us your eslint / eslint-plugin-react versions ? And do you have a real-world class that trigger the bug ?

**Comment by globexdesigns** [comment]
Looks like i can't reproduce this anymore either. Not sure what was causing it. Sorry for wasting your time.
