### ISSUE TITLE
react/jsx-handler-names should not trigger on "only"

### ISSUE THREAD

**Issue by Lapixx** [yannickcr/eslint-plugin-react#571]
The rule was triggered for a property `only`. I assume it checks for any prop key starting with `on`, but it would maybe make sense changing this to match `on[A-Z]` (i.e. camelcased keys) instead?

**Comment by yannickcr** [comment]
Yep, maybe it would be more convenient to use a regex (and make it customizable) to check the handler names instead of using a simple prefix like today.

**Comment by mik01aj** [comment]
+1. I often use `_.noop` as a handler in my tests. I'd like to ignore this specific case.

**Comment by mik01aj** [comment]
should I open another issue for making this regex configurable so that I can exclude `_.noop`?

**Comment by ljharb** [comment]
@mik01aj yes, I think that's a good idea
