### ISSUE TITLE
Proposal: Solidify jsx-no-bind to avoid "work-arounds"

### ISSUE THREAD

**Issue by lukeapage** [yannickcr/eslint-plugin-react#577]
related: https://github.com/yannickcr/eslint-plugin-react/issues/474
https://github.com/yannickcr/eslint-plugin-react/issues/473

It seems too do this

```
render() {
   const click = () => { console.log('click'); };
   return <a onClick={click}></a>;
}
```

I think that it would be useful to prevent any function that returns jsx to not either contain a function declaration, an arrow function or a bind.

Would you be interested if I had time to do a PR?

Would you prefer this as just an extension of the current rule or via a new option e.g. `disallow-in-all-jsx-functions` ?

**Comment by ljharb** [comment]
This seems like an extension of the current rule to me.

**Comment by ljharb** [comment]
I'm happy to reopen this if someone wants to submit a PR for it, but it doesn't seem like there's been much demand in the last 6 years, so I'll close this for now.
