### ISSUE TITLE
linting propTypes in separate file

### ISSUE THREAD

**Issue by d7h** [yannickcr/eslint-plugin-react#580]
Is it possible to lint propTypes which are defined in a separate file ? 

We often have a situation where we outsource the propTypes in a separate file and then import them in the actual Component like this:

```
import propTypes from './test.propTypes';

class test extends React.Component {

    static propTypes = propTypes;

```

In context with the forbid-prop-types rule.

This would be awesome :smiley:

**Comment by ljharb** [comment]
Linters don't have the context of other files - they're meant to do static analysis, not simulate runtime execution by traversing the dependency graph. I agree it would be awesome, but I don't think it's practically possible.

**Comment by d7h** [comment]
Yea, I also thought so. In this case, this issue can be closed.
