### ISSUE TITLE
Webpack Loader Lint

### ISSUE THREAD

**Issue by willin** [yannickcr/eslint-plugin-react#585]
```
render((
  <Router history={brwoserHistory}>
    <Route path="/" component={require('react-router?name=default!./modules/App')} />
    <Route path="/repos" component={require('react-router?name=user!./modules/Repos')} />
    <Route path="/about" component={require('react-router?name=admin!./modules/About')} />
  </Router>
), document.getElementById('app'));
```

Error 1: global-require

http://eslint.org/docs/rules/global-require

Error 2: import/no-unresolved

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md

how to fix it?

**Comment by yannickcr** [comment]
`global-require` is a ESLint rule and `import/no-unresolved` is a rule from the eslint-plugin-import plugin. Sorry, but I do not see anything related to `eslint-plugin-react` here :|

Also, if you have difficulties to fix the issues reported by ESLint (and no problem with ESLint by itself) I suggest you to ask your questions in the [ESLint mailing list](https://groups.google.com/forum/#!forum/eslint) or in the [ESLint chat](https://gitter.im/eslint/eslint).
