### ISSUE TITLE
Rule Proposal: no-dupe-keys equivalent for JSX

### ISSUE THREAD

**Issue by Zacqary** [yannickcr/eslint-plugin-react#593]
In ESLint, `no-dupe-keys` will trigger on something like:
```
var obj = { x: 1, x: 2}
```
But there's nothing that will trigger on:
```
<Component x={1} x={2} />
```

A case like that just gave me a 4-hour headache trying to debug, because apparently PhantomJS is a lot stricter about duplicate keys than browsers are. So I'm hoping we can get a rule to detect duplicate keys in JSX like that.

**Comment by yannickcr** [comment]
I think you're looking for the [jsx-no-duplicate-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-duplicate-props.md) rule ;)
