### ISSUE TITLE
Add ability to ignore certain props from jsx-sort-props

### ISSUE THREAD

**Issue by sohkai** [yannickcr/eslint-plugin-react#605]
Useful when using React built-ins (ie. `key`, `ref`), or when you want a group of props to be together but the rest to be alphabetically sorted. For instance, I prefer having `key` and `ref` props to declared at the top before any other props, but all other props should be alphabetized.

Looking at the [implementation](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-sort-props.js), this looks like it should be fairly easy and I can make a PR soon, but I was wondering if there was any other feedback (maybe I missed something that already allows you to do this?).

**Comment by ljharb** [comment]
`key` and `ref` are controllable with the `reservedFirst` option, added in #1134.
