### ISSUE TITLE
Definition not found: jsx-first-prop-new-line

### ISSUE THREAD

**Issue by Gattermeier** [yannickcr/eslint-plugin-react#607]
Any idea why I would get the following error:

> Definition for rule 'jsx-first-prop-new-line' was not found? 

Installed:
```
    "eslint": "^2.10.2",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-plugin-babel": "^3.1.0",
    "eslint-plugin-import": "^1.8.0",
    "eslint-plugin-jsx-a11y": "^1.2.0",
    "eslint-plugin-react": "^4.3.0",
```

**Comment by ljharb** [comment]
What does `npm ls` say? I suspect it will tell you you need `v5.1.1` of `eslint-plugin-react`

**Comment by nshoes** [comment]
I was having the same issue, ran:

`npm install eslint-plugin-react@5.1.1`

and the error went away.

**Comment by ljharb** [comment]
@Gattermeier please reopen if that doesn't fix your problem.

**Comment by alayii** [comment]
same issue here, already updated to eslint-plugin-react@5.1.1

**Comment by ljharb** [comment]
@alayii what does `npm ls` say? Are you running a local or global eslint?

**Comment by alayii** [comment]
running local eslint. It's ok for now, I think is atom problem? I upgraded eslint and eslint-react-plugin, but I'm not close atom, then I reopen it, the warning is gone.

thanks for reply.

**Comment by ljharb** [comment]
Ah, gotcha. Thanks for clarifying.
