### ISSUE TITLE
"Parsing error: Unexpected token = "  When i'm using an arrow function inside a component class

### ISSUE THREAD

**Issue by eladcandroid** [yannickcr/eslint-plugin-react#627]
![error_arrow_function](https://cloud.githubusercontent.com/assets/13297000/15858490/6e62d760-2cc9-11e6-9b42-62a1f0da6996.png)

**Comment by ljharb** [comment]
@eladcandroid what's your `.eslintrc` look like? it looks like you're not enabling ES6 parsing (ES5 is eslint's default)

**Comment by didaquis** [comment]
Something similar to me. Two arrow functions in code, one of them is marked as `Parsing Error: Unexpected token =`

![captura de pantalla 2018-03-10 a las 16 25 20](https://user-images.githubusercontent.com/6883041/37243807-b9c71bee-247f-11e8-8753-7e845064ba78.png)

![captura de pantalla 2018-03-10 a las 16 25 38](https://user-images.githubusercontent.com/6883041/37243808-b9ee2108-247f-11e8-8eda-e8c452aa877c.png)

**Comment by ljharb** [comment]
@didaquis that’s also expected; class properties aren’t in the language yet, so eslint doesn’t parse them. You need babel-eslint.

Closing, since both of these questions are answered.

**Comment by didaquis** [comment]
@ljharb Thanks for the information!
