### ISSUE TITLE
jsx-no-bind without jsx

### ISSUE THREAD

**Issue by forresto** [yannickcr/eslint-plugin-react#629]
I'm trying to root out `bind`s in renders in my (non-jsx) components:

``` js
import React, {createElement as el} from 'react'

class ButtonYay extends React.Component {
  render () {
    return el('button'
    , { onClick: this.onClick.bind(this) }
    , 'Yay'
    )
  }
  onClick: (event) {
    console.log(this)
  }
}
```

Can the `jsx-no-bind` rule flag those, or would it be a new rule?

**Comment by ljharb** [comment]
you'd want `() => this.onClick()` rather than `.bind`. However, what's `el` and why isn't it a React compontnt?

**Comment by forresto** [comment]
@ljharb I thought the point was to avoid creating functions in renders?

So I've ended up with:

``` js
import React, {createElement as el} from 'react'

class ButtonYay extends React.Component {
  constructor (props) {
    super(props)
    this.boundOnClick = this.onClick.bind(this)
  }
  render () {
    return el('button'
    , { onClick: this.boundOnClick }
    , 'Yay'
    )
  }
  onClick: (event) {
    console.log(this)
  }
}
```

**Comment by ljharb** [comment]
@forresto yes, but `.bind` is far worse than creating an arrow function. Your approach is fine too (although it optimizes better if you do `this.onClick = this.onClick.bind(this)`, because the overall shape of the instance doesn't change)

**Comment by ljharb** [comment]
I think `jsx-no-bind` already covers this. See also the discussion on #1761.
