### ISSUE TITLE
jsx-handler-names triggers when using ES7 bind operator.

### ISSUE THREAD

**Issue by rodoabad** [yannickcr/eslint-plugin-react#630]
Example:

`onClick={props::handleCreateDealerHistoryReportClick}`

Which is the same as `handleCreateDealerHistoryReportClick.bind(props)` assuming `this` is `props` in a stateless function component.

**Comment by ljharb** [comment]
That should actually be erroring out on the `jsx-no-bind` rule :-p but this should still be fixed.

**Comment by rodoabad** [comment]
@ljharb if you have `jsx-no-bind` turned off and have `jsx-handler-names` turned on this will error out.

**Comment by rodoabad** [comment]
@evcohen did you submit a PR for this?

**Comment by evcohen** [comment]
@rodoabad I PR'ed for reporting error on `jsx-no-bind` using ES7 bind operator.
