### ISSUE TITLE
propTypes not validating on classes that extend a subclass of React.Component

### ISSUE THREAD

**Issue by cktechnology** [yannickcr/eslint-plugin-react#632]
Hello,

We have subclassed React.Component in order to expose intl functionality to all our React components:

```javascript
export default class TranslatedComponent extends React.Component {
    constructor(...args) {
        super(...args);
        this.intl = this.intl.bind(this);
    }
...
}
```
When we create a new React component it would look like this:
```javascript
export default class FileContainer extends TranslatedComponent {
    constructor(props) {
        super(props);
    }
render() {
    <Input name={ this.props.name } />
  };
}
FileContainer.propTypes = {
       // name: React.PropTypes.string.isRequired,
  };
```
Since I have purposefully commented out the propType that is required, I expect ESLint to give me an error saying "'name' is missing in props validation". However, it does not.

Only if I change the class to directly extend React.Component will ESLint show us the error.

```javascript
export default class FileContainer extends React.Component {
```
Any ideas on how we could still get this linting rule to apply to our classes that extend TranslatedComponent?

Thanks so much.

**Comment by ljharb** [comment]
There's no way for a linter to know that your superclass extends `React.Component` - I believe you can use jsdoc to annotate it with something like `/* @extends React.Component */`?

However, I'd recommend using composition instead of inheritance to share behavior, and encourage `require`ing `intl` where you need it rather than attaching it to every component.

**Comment by yannickcr** [comment]
> There's no way for a linter to know that your superclass extends React.Component - I believe you can use jsdoc to annotate it with something like `/* @extends React.Component */` ?

👍 But support for JSDoc is not released yet, it should be in the next `eslint-plugin-react` release.

**Comment by yannickcr** [comment]
Released in `v5.2.0`

**Comment by seavan** [comment]
does it actually work with /* @extends React.Component */ now?

I am trying with the current release and I cannot get eslint to verify PropTypes for a component which extendds subclass of React.Component, even if I add that jsdoc line.

**Comment by ljharb** [comment]
It should work. If it's not, please file a new issue with a test case.
