### ISSUE TITLE
Definition for rule "jsx-curly-spacing" was not found

### ISSUE THREAD

**Issue by jaysig** [yannickcr/eslint-plugin-react#645]
I'm having an issue getting the jsx curly spacing rule to work. The rest of the rules work fine, except I get the error above when I'm trying to lint. 

```
{
    "extends": ["plugin:meteor/recommended","airbnb"],
    "env": {
        "browser": true,
        "node": true,
        "es6": true,
        "jquery": true,
        "mongo": true,
        "meteor": true
    },

    "plugins": [
        "react",
        "meteor"
    ],
    "rules":{
      "prefer-const": 0,
      "new-cap": 0,
      "one-var": 0,
      "array-bracket-spacing": [2, "always"],
      "jsx-curly-spacing": [2, "always"],
      "func-names": 0,
      "no-else-return": 0,
      "no-underscore-dangle": 0,
      "import/no-unresolved": [
        2, { "ignore": ["^meteor/"] }
      ],
      }
}
```

**Comment by ljharb** [comment]
Are you running a global or local `eslint`? What does `npm ls` print out?

**Comment by jaysig** [comment]
i'm trying to run it within atom which I would assume means local. Here's what I have installed via npm

```
  "devDependencies": {
    "eslint": "^2.8.0",
    "eslint-config-airbnb": "^8.0.0",
    "eslint-plugin-import": "^1.6.0",
    "eslint-plugin-jsx-a11y": "^1.0.3",
    "eslint-plugin-meteor": "^3.5.2",
    "eslint-plugin-react": "^5.2.1"
  },
```

**Comment by yannickcr** [comment]
A rule from a plugin must be prefixed by the plugin name, see [ESLint documentation](http://eslint.org/docs/user-guide/configuring#configuring-rules) about rules configuration.

In your case:
```js
"rules":{
      ...
      "react/jsx-curly-spacing": [2, "always"]
      ...
}
```

**Comment by jaysig** [comment]
That fixed it, thank you.

**Comment by sun1211** [comment]
just update : "react-scripts": "^3.1.2",
This problems is solved

**Comment by soheilous** [comment]
Im using `turborepo`. I had to duplicate these lines to make it work. I don't know why 😕

![image](https://github.com/jsx-eslint/eslint-plugin-react/assets/64070394/8eadbd82-4d4e-4dd2-9340-1edd2b704a70)
