### ISSUE TITLE
jsx-curly-spacing autofix deletes comments

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#648]
If I have some JSX like:

``` jsx
<div>
  { /* comment */ }
</div>
```

the autofixer will change it to:

``` jsx
<div>
  {}
</div>
```

but it should change it to:

``` jsx
<div>
  {/* comment */}
</div>
```

**Comment by ahstro** [comment]
Title should probably be changed to "jsx-curly-spacing doesn't account for comments" since things like `{something /* comment */}` triggers an error.

**Comment by s-h-a-d-o-w** [comment]
@yannickcr Your commit unfortunately doesn't seem to fix this issue. The example provided by @lencioni still produces the buggy result of removing the comment (tested using 7.3.0). 

So I would argue that this issue should be re-opened.

**Comment by ljharb** [comment]
The commit includes automated tests that should verify it's working.

Can you open a PR that includes a failing test case?

**Comment by s-h-a-d-o-w** [comment]
Was that what you had in mind?

**Comment by ljharb** [comment]
Thanks, that's appreciated! I'll take a look soon.

**Comment by s-h-a-d-o-w** [comment]
Cool, thanks for the update!
(Essentially my first PR on a major project, so I just wanted to make sure I did it properly and understood you correctly :) )
