### ISSUE TITLE
Support ESLint 3 and new rule format

### ISSUE THREAD

**Issue by paazmaya** [yannickcr/eslint-plugin-react#661]
The new rule format, introduced in the ESLint version 3, is explained here http://eslint.org/blog/2016/07/eslint-new-rule-format

Any chance of converting the rules in that format and making a new major release which support ESLint 3 and up?

**Comment by ljharb** [comment]
The only point of doing so would be to ensure compatibility with a future eslint v4, and doing so would break compatibility with eslint v2.

What's the hurry?

**Comment by paazmaya** [comment]
Living on the edge....

**Comment by MoOx** [comment]
The cool part is that there is a tool for that http://eslint.org/blog/2016/07/eslint-new-rule-format#automatic-transformation

**Comment by ljharb** [comment]
I've recently learned that both eslint v2 and v3 support this new rule format - so I think that the sooner we convert all the rules, the better.

**Comment by paazmaya** [comment]
Thanks for pointing that out @MoOx, I have seem not to read that far...
