### ISSUE TITLE
Rule Proposal: Error for using `this` in stateless function

### ISSUE THREAD

**Issue by nickstanish** [yannickcr/eslint-plugin-react#672]
Would be great to catch these errors faster especially when converting classes to stateless functions

**Comment by Kovensky** [comment]
Wouldn't `no-invalid-this` catch this?

**Comment by ljharb** [comment]
That's a good point - that's a core rule that prevents use of `this` in a standalone function.

**Comment by nickstanish** [comment]
That rule allows `this` if the function looks like a constructor, and the criteria for that is the name is capitalized or is actually a class constructor. Since SFCs begin with capital letter then that rule would allow it.

One possible solution is to add-on to that rule by determining if the function is a SFC.
The criteria for that could be something similar to:

- returns jsx or React.createElement/cloneElement
- has 1 function arg
- sets propTypes/defaultProps
