### ISSUE TITLE
Enable all rules

### ISSUE THREAD

**Issue by cristian-sima** [yannickcr/eslint-plugin-react#674]
How do I do this?

**Comment by ljharb** [comment]
At the moment, manually list them out with all settings.

I think it might be useful to add, alongside ["recommended"](https://github.com/yannickcr/eslint-plugin-react/blob/master/index.js#L54-L77), an "all" preset.

**Comment by pfhayes** [comment]
I have submitted a PR that addresses this: https://github.com/yannickcr/eslint-plugin-react/pull/683

**Comment by cristian-sima** [comment]
Thanks
