### ISSUE TITLE
no-multi-component bug

### ISSUE THREAD

**Issue by cristian-sima** [yannickcr/eslint-plugin-react#675]
I have this code https://gist.github.com/cristian-sima/f30307147c2efaa526c19ac2579e7f0e

It produces an error, but there is only one component in the file

:strange

**Comment by petersendidit** [comment]
`renderSuggestion` is a stateless functional component.

**Comment by cristian-sima** [comment]
Yes, it is. But is not a component :)

**Comment by cristian-sima** [comment]
@petersendidit any workaround to keep it in the same file?

**Comment by petersendidit** [comment]
```javascript
  // eslint-disable-next-line react/no-multi-component
  renderSuggestion = (suggestion) => {
    return (
      <span>{suggestion.name}</span>
    );
  };
```

**Comment by cristian-sima** [comment]
Tx mate
