### ISSUE TITLE
Parse extended class to read some informations

### ISSUE THREAD

**Issue by MoOx** [yannickcr/eslint-plugin-react#68]
```js
import React, {Component} from "react"

class A extends Component {

  static propTypes = {
    whatever: PropTypes.isRequired,
  }

  render() {
    return {this.props.whatever}
  }
}

class B extends A {
  render() {
    return {this.props.whatever}
  }
}
```

B gets an error on propTypes undefined on this component.

**Comment by yannickcr** [comment]
Mmm, I think we can only have a limited support for this case.

We can handle the above script but not this one for example:
```js
import A from "a"

class B extends A {
  render() {
    return {this.props.whatever}
  }
}
```
In this case the extended class is in another file and we cannot know if the propTypes property is defined in it or not.

**Comment by MoOx** [comment]
I think the fs read might be a problem. But it's doable right ?
Maybe disabled by default but that can be handled when set to true ?

**Comment by yannickcr** [comment]
Linting is only made on the current file content, starting to jump from file to file, resolving imports and finding how the class is constructed will be very complicated (but I accept PR :wink: ).

I can handle the original case and if you encounter the second one I think the best way to handle it should be to ignore the `prop-types` rule for this class:

```js
import A from "a"

class B extends A { // eslint-disable-line react/prop-types
  render() {
    return {this.props.whatever}
  }
}
```

**Comment by gausie** [comment]
Is there a way we could do a decorator-style comment above a class manually to inform the parser that the class is a descendent of a Component and lint it thusly?
