### ISSUE TITLE
is jsx-no-bind & no-multi-comp conflict?

### ISSUE THREAD

**Issue by zombieJ** [yannickcr/eslint-plugin-react#682]
Hi, I have a doubt with `jsx-no-bind` & `no-multi-comp`.
In `jsx-no-bind`, arrow function will be separated in sub-component: [jsx-no-bind](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md)

and when using `no-multi-comp` will said multi component defined in one file. I think sub component need not move to another file cause its only used by parent component and not export to others.

What can I do for this case?
`eslint-disable`, move out or close the `no-multi-comp` rule?

**Comment by ljharb** [comment]
The location of the component returned in the arrow function is irrelevant - `jsx-no-bind` would complain here anyways, unless you disabled it for arrow functions.

In other words, `no-multi-comp` doesn't change the situation at all. Whether it's `const Foo = /* the definition of foo */` or `const Foo = /* something that imports/requires Foo */` it would complain the same.

**Comment by ljharb** [comment]
Can you provide a code sample where you think they're related?

**Comment by zombieJ** [comment]
for example, I have a group buttons:

``` jsx
class Button extends Component {
	constructor() {
		this.onClick = this.onClick.bind(this);
	}
	
	onClick() {
		const { type, onSelect } = this.props;
		onSelect(type);
	}
	
	render() {
		return <button onClick={this.onClick}>{type}</button>;
	}
}


class GroupButtons extends Component {
	constructor() {
		this.select = this.select.bind(this);
	}
	
	select(type) {
		const { select } = this.props;
		select(type);
	}
	
	render() {
		const { types } = this.props;
	
		return (
			<div>
				{types.map((type, index) => (
					<Button key={index} type={type} onSelect={this.select} />
				))}
			</div>
		);
	}
}
```

Since the class `Button` is only used as sub component of `GroupButtons` which needn't make as export. Some of the grouping component has the sub component helping to replace the arrow function. I guess component `Button` could be ignore if is only used as sub component by `no-multi-comp`?

**Comment by ljharb** [comment]
You'll get a `no-multi-comp` warning even if you just have one hardcoded `<Button>` inside `<GroupButtons>` - `jsx-no-bind` is not related.

**Comment by zombieJ** [comment]
Yes. I want to fix `jsx-no-bind` arrow function so that create a sub component to handle it.  Is there an option of `no-multi-comp`  such as:
```javascript
"no-multi-comp": [<enabled>, { "ignoreSubComponent": <boolean> }]
```
or 
```javascript
"no-multi-comp": [<enabled>, { "ignoreNoExport": <boolean> }]
```

to ignore the component which is used as sub component inside or the component will not be exported.

**Comment by ljharb** [comment]
There's already an option to ignore stateless components. If you need a more complex component than that, why wouldn't you want it in a separate file, where it can be properly tested?

**Comment by zombieJ** [comment]
This sub component is only used for the component(which simple handle only like `click` function) and I don't want to make it as export cause it's so tiny.

But for testing, yes, I guess all of component should be fully tested. Youve talked me into it. 

Thanks for your patience :smiley:
