### ISSUE TITLE
Update sort-comp defaults to include props for es6

### ISSUE THREAD

**Issue by AlexJuarez** [yannickcr/eslint-plugin-react#697]
props is missing from https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md#rule-options

**Comment by lencioni** [comment]
Are you referring to [class property declarations](https://github.com/jeffmo/es-class-public-fields)? That feature is currently only a stage 1 proposal and is not yet part of the standard. You can see the list of active proposals here: https://github.com/tc39/proposals

More info on what stage 1 means here: https://tc39.github.io/process-document/

**Comment by ljharb** [comment]
We now have `instance-variables` and `instance-methods`.
