### ISSUE TITLE
this.props.children and `react/prop-types` rule

### ISSUE THREAD

**Issue by remitbri** [yannickcr/eslint-plugin-react#7]
Using `this.props.children` triggers the rule (_"'children' is missing in props validation"_). 

Shouldn't it be an exception?

**Comment by yannickcr** [comment]
Right, we should add an exception for `this.props.children`

**Comment by AsaAyers** [comment]
Why should children be an exception? I think you should document when one does accept or require children.

**Comment by yannickcr** [comment]
You're right, but I rarely seen some propTypes for `this.props.children` so it dot not seems to be a common practice to me.

Maybe we can introduce an option to `prop-types` to re-include children in the props list to check?

**Comment by AsaAyers** [comment]
It seems to me like most components don't need `this.props.children`, so to me that makes it extra important to document `children` in the `propTypes`.

I think the option idea is fine. I'm interested in hearing why anyone would want to run this against all other prop types, but never against children. It seems not well thought out to me, but I kind of hope I'm just missing something.

**Comment by sebastienbarre** [comment]
All good points. 
@AsaAyers Now considering ```this.props.children``` can be an an array of components *or* a single child component itself *without the array wrapper* (see [React doc](https://facebook.github.io/react/tips/children-props-type.html)), this prop type might get verbose. Which one do you use at the moment?

**Comment by remitbri** [comment]
I ended up with `React.PropTypes.node` to solve my issues…

**Comment by AsaAyers** [comment]
It looks like I have a combination of `element`, `node`, a few `string`s, and an `arrayOf(...shape(...))`.

**Comment by sebastienbarre** [comment]
@remitbri thanks, I updated my comment above accordingly. What's your default prop value? ```null```?

**Comment by AsaAyers** [comment]
`React.PropTypes.any` is also an option. If I really had a component that could support 0, 1, or more children I'd probably just stick with `.any` to document that `children` is used.

**Comment by remitbri** [comment]
Hmmm, my component is a wrapper, which could stand on its own, so I didn't set a default prop value. Bad practice? I guess if I had to set one then it should be `null`

**Comment by yannickcr** [comment]
Since 2.0.0 `children` is no longer ignored for props validation.

If you still want to ignore it you can use [the `ignore` option](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md#rule-options).

**Comment by matthewwithanm** [comment]
@AsaAyers Won't `node` handle those cases too?

**Comment by AsaAyers** [comment]
yes, I think `node` is a better option than `any`, I just hadn't used it much at the time I commented.

**Comment by matthewwithanm** [comment]
👍 Thanks, just making sure.

**Comment by reggi** [comment]
Just to clarify, `children` should be defined as type `node, like this:

```js
propTypes: {
  children: React.PropTypes.node
}
```

**Comment by resistdesign** [comment]
I know this is closed, but wouldn't `children` be inherited from `Component`? Or is OOP not a thing anymore?

**Comment by AsaAyers** [comment]
Not all Components have children. In a couple of my projects I have an `<Avatar user={userObject} />`

**Comment by joaomilho** [comment]
@resistdesign actually yeah, OOP is not _the main_ thing anymore, at least in React's world.

**Comment by ramasilveyra** [comment]
My solution:

```javascript
import React, { PropTypes } from 'react';
...
MyComponent.propTypes = {
  children: PropTypes.oneOfType([
    PropTypes.node,
    PropTypes.string,
    PropTypes.element,
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.arrayOf(PropTypes.string),
    PropTypes.arrayOf(PropTypes.element)
  ]).isRequired
};
```

**Comment by lencioni** [comment]
Why do you need `oneOfType` here? The `node` propType is defined as "Anything that can be rendered: numbers, strings, elements or an array (or fragment) containing these types." https://facebook.github.io/react/docs/reusable-components.html

You should use `children: PropTypes.node`.

**Comment by markalfred** [comment]
Any general opinions on this type of conditional rendering?

```jsx
<MyComponent>
  { showAlert && <div className='alert'>Heads up!</div> }
</MyComponent>
```

Would you add `bool` and arrays of them to the proptype, always use a ternary, or is there some better solution I'm unaware of?

**Comment by jdanilov** [comment]
Justin case you're wondering how to do that in Flow, use React.Node as described here:
https://flow.org/en/docs/react/types/#toc-react-node

```js
type Props = {
  children: React.Node,
};
```

**Comment by Denly** [comment]
PropTypes.node can be an array, so no need the React.PropTypes.arrayOf(React.PropTypes.node) @sebastienbarre 
```
// Anything that can be rendered: numbers, strings, elements or an array
  // (or fragment) containing these types.
  optionalNode: PropTypes.node,
 
```
