### ISSUE TITLE
SVG attributes linted incorrectly

### ISSUE THREAD

**Issue by kostasmanionis** [yannickcr/eslint-plugin-react#718]
There was an issue created asking for native attribute support on svg elements https://github.com/yannickcr/eslint-plugin-react/issues/490

This was based on `React v15.0 Release Candidate`, but that change has since been reverted in [React v15.0 Release Candidate 2](https://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html). And it never made it to the final release.

Soooo right now svg attribute linting is kinda broken 😢

**Comment by yannickcr** [comment]
Ho! Seems we missed that 😞

**Comment by the21st** [comment]
I'm on `7.17.0` and seeing this issue too. Assuming this is the same issue as #490
