### ISSUE TITLE
Add configuration to react/jsx-handler-names (e.g. whitelist some name)

### ISSUE THREAD

**Issue by mik01aj** [yannickcr/eslint-plugin-react#732]
In my case, I often use `_.noop` as event handler in my unit tests. I'd like to whitelist this case.

Perhaps this could be solved in some generic way, i.e. since [the rule uses RegExps anyway](https://github.com/lencioni/eslint-plugin-react/blob/master/lib/rules/jsx-handler-names.js), these RegExps could be configurable.

This was originally reported by me in https://github.com/yannickcr/eslint-plugin-react/issues/571#issuecomment-233586806

**Comment by sheshbabu** [comment]
Would also be useful for some react native props like `onTintColor`

https://facebook.github.io/react-native/docs/switch.html#ontintcolor

**Comment by ljharb** [comment]
Using things like `_.noop` has become pretty discouraged in the ecosystem, since `() => {}` is supremely optimized and much clearer.

@sheshbabu `onTintColor` should just work fine, because of the "on" prefix.
