### ISSUE TITLE
`sort-comp` rule treats methods beginning with `get.*` as es6 getters

### ISSUE THREAD

**Issue by thenickcox** [yannickcr/eslint-plugin-react#733]
Here is the relevant part of my component:

``` jsx
class TypeToFilter extends Component {
  constructor(props) {
    super(props);
    this.beginFilter = this.beginFilter.bind(this);
    this.clearInput = this.clearInput.bind(this);
    const { data } = props;
    this.state = {
      data: data.map(d => d.name),
      filteredData: data.map(d => d.name),
      inputVal: '',
    };
  }

  filterData(data, regex) {
    return data.filter(d => d.search(regex) > -1);
  }

  ...
  getFilterIdFromName(name) {
    return find(this.props.filterOptions, o => o.name === optName).id;
  }

  handleClickMulti(optName) {
    this.props.selectMulti(getFilterIdFromName(optName));
  }

  handleClickSingle(optName) {
    this.props.select(getFilterIdFromName(optName));
  }

  render() {
  }
```

I get `filterData should be placed after getFilterIdFromName`.  Looking at the rules (and the source for `sort-comp`, I believe it's matching against a regex that thinks `getFilterIdFromName` is a static property getter?

Here's my `.eslintrc`:

``` JSON
{
  "extends": "airbnb",
  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  }
}
```

**Comment by ljharb** [comment]
I believe the intent is that all getters - syntactic or conceptual - should be grouped together. `getFilterIdFromName` is a getter, just not a syntactic one.

**Comment by thenickcox** [comment]
I think I agree philosophically, but it's being used as a helper method here, and it seems most practical to keep it close in proximity to the methods employing it. In that sense, it feels like it should fall into the [everything else](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md#rule-options) category.

**Comment by ljharb** [comment]
PRs improving documentation are always welcome! However, let's wait until @yannickcr has confirmed that indeed that was the intent of the rule.

**Comment by ljharb** [comment]
I'm comfortable sticking with my claim as to the intent. A PR to improve the docs would still be welcome.
