### ISSUE TITLE
Allow legacy allow-in-func setting for no-did-mount-set-state

### ISSUE THREAD

**Issue by alangpierce** [yannickcr/eslint-plugin-react#734]
It looks like https://github.com/yannickcr/eslint-plugin-react/commit/376dc53656f78059fb405d9e30c2f402717f6882 changed the no-did-mount-set-state rule so that allow-in-func is now the default and the only allowed option now is disallow-in-func. This ends up breaking an existing set of rules I'm using ( https://github.com/1hella/eslint-config-airbnb-es5 ) that is still specifying allow-in-func.

Maybe the rule could be changed to still accept allow-in-func (which would do nothing, since it's the default)? It looks to me like it's just a matter of adding allow-in-func to the schema, so keeping backcompat should be really easy in this case.

If breaking backcompat is intentional here, I can try updating/forking that other set of rules, but it seems like it would be nice to keep compatibility with old configs at least for a little while.

**Comment by ljharb** [comment]
@alangpierce that change was made in a semver-major version - so `eslint-config-airbnb-es5` (which isn't an official airbnb config, fwiw) needs to update itself in order to work with it.

I'd recommend filing a pull request on that config to update itself.

**Comment by alangpierce** [comment]
Ok, I'll take that approach (either get eslint-config-airbnb-es5 updated and released, fork it, or find a way to stop depending on it). Yeah, I understand that the major version bump means that breaking changes are expected. This was more of a feature request/inquiry than a bug report.

In general I do think it would be nice if breaking changes were done in a two-phase way (when possible/reasonable) to give other packages time to update rather than having to do everything in lockstep. But I understand that that can be difficult or undesirable sometimes, and admittedly I don't have enough experience with npm and peer dependencies to know exactly how all of that would work out.

Thanks!
