### ISSUE TITLE
Rule proposal: Split jsx-sort-props into separate rules

### ISSUE THREAD

**Issue by brenoc** [yannickcr/eslint-plugin-react#738]
I love the options of jsx-sort-props like callbacksLast, but the alphabetical thing is not what I'm looking for.

I think it would be great to split the options into separate rules, like:
- jsx-sort-props-callbacksLast
- jsx-sort-props-shorthandFirst
- jsx-sort-props-shorthandLast
- jsx-sort-props-alphabetical (the jsx-sort-props we have today)

**Comment by ljharb** [comment]
It seems like this would be better solved by an option on the main rule to disable alphabetical sorting. I don't think it's a good idea to have multiple rules that directly conflict/overlap.

**Comment by brenoc** [comment]
@ljharb that's a good option. I would be happy with that

**Comment by HenriBeck** [comment]
#786
