### ISSUE TITLE
[4.2.3] The package miss the _all_ configuration

### ISSUE THREAD

**Issue by fabienjuif** [yannickcr/eslint-plugin-react#743]
Hi,

I wanna use the `all` configuration because I love linters, but here is the problem : 
```
Cannot convert undefined or null to object
Referenced from: [...]/.eslintrc.json
TypeError: Cannot convert undefined or null to object
Referenced from: [...]/.eslintrc.json
```

The configuration file looks like this : 
```
{
  "parser": "babel-eslint",
  "extends": ["airbnb", "plugin:react/all"],
  "rules": {
      "semi": [2, "never"],
      "arrow-body-style": 0
  },
  "plugins": ["react"]
}
```

So I investigate a bit, and I found out that the `index.js` of the `eslint-plugin-react` package doesn' have `all` configuration but only have `recommended` one : 
```
'use strict';

module.exports = {
  rules: {
    'jsx-uses-react': require('./lib/rules/jsx-uses-react'),
    // [...]
    'prefer-stateless-function': require('./lib/rules/prefer-stateless-function')
  },
  configs: {
    recommended: {
      parserOptions: {
        ecmaFeatures: {
          jsx: true
        }
      },
      rules: {
        'react/display-name': 2,
        // [...]
        'react/react-in-jsx-scope': 2
      }
    }
  }
};
```

**Comment by fabienjuif** [comment]
I saw that the `index.js` in master have it.
And I saw the package is at `6.0.0` version now.
I'll try that and reopen if I still have the problem.

**Comment by battaile** [comment]
I'm seeing it on line 91: https://github.com/yannickcr/eslint-plugin-react/blob/master/index.js#L91

**Comment by fabienjuif** [comment]
Yeah I didn't see I had an old version :/
