### ISSUE TITLE
Add no-string-refs to recommended configuration

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#749]
The [React documentation says](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute):

> Although string refs are not deprecated, they are considered legacy, and will likely be deprecated at some point in the future. Callback refs are preferred.

It seems like it might be a good idea to add this rule to the recommended configuration. What do folks think?

I'm adding this to the 7.0.0 milestone so we don't forget to do this for our next major version bump.

**Comment by ljharb** [comment]
SGTM
