### ISSUE TITLE
Add jsx-key to recommended configuration

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#750]
The `jsx-key` rule ensures that JSX has a key prop when in an array or iterator. If you don't use a key prop here, React will issue warnings. Given that this is a runtime warning, it seems reasonable to add this rule to the recommended configuration. What do folks think?

I'm adding this to the 7.0.0 milestone so we don't forget to do this for our next major version bump.

**Comment by ljharb** [comment]
SGTM

**Comment by ljharb** [comment]
There seem to be some issues with this rule, so I'm going to hold off adding it to the recommended configuration just yet.
