### ISSUE TITLE
Add jsx-no-comment-textnodes to recommended configuration

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#751]
This rule prevents comments from being accidentally injected as text nodes in JSX. This seems like a nice protection to have on and unlikely that it would catch very many legitimate uses, so I think it should be added to the recommended configuration.

I'm adding this to the 7.0.0 milestone so we don't forget to do this for our next major version bump.

**Comment by ljharb** [comment]
SGTM
