### ISSUE TITLE
Add jsx-no-target-blank to recommended configuration

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#752]
This rule prevents use of `target='_blank'` without an accompanying `rel='noreferrer noopener'` to prevent security vulnerabilities. It seems like this should perhaps be enabled in the recommended config. What do folks think?

I'm adding this to the 7.0.0 milestone so we don't forget to do this for our next major version bump.

**Comment by ljharb** [comment]
SGTM
