### ISSUE TITLE
disable

### ISSUE THREAD

**Issue by stoplion** [yannickcr/eslint-plugin-react#758]
How do you disable `prop-types`? 
Read [this](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md) but it still is not clear 
"prop-types": 0,
or 
"prop-types": [0]

either one does not work

**Comment by ljharb** [comment]
`"react/prop-types": 0`?

**Comment by yannickcr** [comment]
Also see [ESLint documentation on how to configure rules](http://eslint.org/docs/user-guide/configuring#configuring-rules).
