### ISSUE TITLE
Deprecated option handling

### ISSUE THREAD

**Issue by webOS101** [yannickcr/eslint-plugin-react#760]
Is there any thought about supporting the deprecation of options?  The sort of change that https://github.com/yannickcr/eslint-plugin-react/commit/376dc53656f78059fb405d9e30c2f402717f6882 introduced breaks configs and the warning messages are totally unhelpful.  This is exacerbated by the fact that the docs update does not reference the older value and suggest a migration path.  A library-wide option to support deprecated options might ease this pain.  Or, is this an issue to push further up the eslint chain?

**Comment by ljharb** [comment]
Certainly if eslint itself had a way to specify, in the rule schema, that there was a removed option, it would work. In this case, for example, we could have said something like `'allow-in-func': 'The allow-in-func option has been removed, and there is now a disallow-in-func option.'`.

Regardless, if there's better documentation we could do, we should do it.

**Comment by webOS101** [comment]
To be fair, it is listed in the changelog, which I didn't bother reading. :)

**Comment by ljharb** [comment]
I think that the proper path forward here is to propose eslint add a way for rules to mark an option as "deprecated", with a suggested alternative config.

Once that exists, I'd use it extensively here and in other plugins.
