### ISSUE TITLE
Rule proposal: Allow unused array elements in a destructured argument

### ISSUE THREAD

**Issue by brennie** [yannickcr/eslint-plugin-react#763]
The following code will trigger the `no-unused-vars` rule:

```javascript
const m = new Map([['foo', 'bar'], ['baz', 'qux']]);
const onlyBars = new Map(
  Array.from(m.entries)
    .filter([k, v] => v === 'bar')
);
```

This is less than ideal. We already have a `{args: 'after-used'}` setting for the case of:
`(k, v) => v === 'bar';` and it would be handy to have the same sort of option here.

**Comment by brennie** [comment]
I filed this against the wrong repo! Oops!

**Comment by ljharb** [comment]
@brennie `.filter(([, v]) => v === 'bar')` will fix your problem, fwiw.

**Comment by brennie** [comment]
@ljharb I wasn't aware of that syntax. Thanks!
