### ISSUE TITLE
[self-closing-comp] Only void elements should omit end tags

### ISSUE THREAD

**Issue by IanVS** [yannickcr/eslint-plugin-react#765]
I might be reading [the HTML5 spec](https://www.w3.org/TR/html5/syntax.html#void-elements) incorrectly, but it seems that only certain end tags can/must be omitted.  The new default behavior of `self-closing-comp` is to force all empty elements to omit their end tag.

The spec says:

> Raw text, escapable raw text, and normal elements have a start tag to indicate where they begin, and an end tag to indicate where they end. The start and end tags of certain normal elements can be omitted, as described below in the section on optional tags. Those that cannot be omitted must not be omitted. Void elements only have a start tag; end tags must not be specified for void elements.

Void elements are `area, base, br, col, embed, hr, img, input, keygen, link, meta, param, source, track, wbr`, and most other elements like `span` and `div` are "normal elements."  The list of optional tags in the spec is fairly limited, and none apply to `div` or `span`, for example.

From this reading, it would seem that `<div />` is not valid HTML5, and yet that is what this rule enforces by default.  I like the idea of the rule, but it seems a bit over-eager.  

That said, I'm eager to hear the thoughts of those with more knowledge in this area than myself.

**Comment by ljharb** [comment]
JSX approximates XHTML, not HTML - and in XHTML every tag can be self-closed.

**Comment by IanVS** [comment]
Ah, I see, I was missing that step.  And react generates valid DOM nodes with start/end tags when necessary.  Thanks for explaining!

**Comment by lencioni** [comment]
Perhaps we should add a note to the documentation?
