### ISSUE TITLE
Rule proposal: Keep simple ref callback on a single line

### ISSUE THREAD

**Issue by tleunen** [yannickcr/eslint-plugin-react#774]
String refs are "deprecated" in favor of the callback version. I wonder if it would be a good idea to have a rule to enforce the style of the ref callback? Maybe a rule to enforce the single line only when an assignation is found inside? Or give the choice...

Like having it on a single line: 

``` jsx
<MyComponent
  ref={n => { this.myComponentNode = n; }}
  sth={2}
/>
```

or maybe on multiple lines:

``` jsx
<MyComponent
  ref={n => { 
    this.myComponentNode = n;
  }}
  sth={2}
/>
```

**Comment by ljharb** [comment]
Apparently by using a non-`===` ref callback, the callback will be called extra times, sometimes with `null`. I've thus been led to believe that the best practice is to use a bound-in-the-constructor instance method, not an arrow function, for ref callbacks.

I think generic rules to govern arrow function styling could apply here, without needing to special-case them to ref callbacks (although making the ref callback be a one-arg function might be a useful rule)

**Comment by tleunen** [comment]
> Apparently by using a non-=== ref callback, the callback will be called extra times
Could you elaborate on this?

And yes, maybe a generic rule would be best instead of limiting it to refs.
