### ISSUE TITLE
The react/require-extension rule is deprecated.

### ISSUE THREAD

**Issue by Darmody** [yannickcr/eslint-plugin-react#775]
The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.

**Comment by ljharb** [comment]
I'm not sure what you're posting about - we're quite aware that it's deprecated :-)

**Comment by Darmody** [comment]
@ljharb Sorry! I thought that it was warnning by this package!

**Comment by Darmody** [comment]
But the rule is still showing on the README

**Comment by yannickcr** [comment]
@Darmody I removed it from the README since we do not	usually list the deprecated rules in it.
