### ISSUE TITLE
enable configuration for jsx-no-target-blank

### ISSUE THREAD

**Issue by travi** [yannickcr/eslint-plugin-react#776]
Would it be reasonable to make this rule a bit more configurable?

My team currently has some links using `target=_blank` that are to other internal properties (but external to the application they are linked from). Referrers are important bits of information that we want to maintain the ability to track between these internal properties (and we've lost the don't use `target=_blank` argument). Even with https enabled, we are still able to track referrers across sub-domains under our domain.

However, to keep that ability we need to completely disable this rule and lose its protections that we would like to keep for cross-origin links.

Could there be configurations to:
- only apply the rule to cross-origin links (i would not consider cross-subdomain to be cross-origin in this case)?
- include `noopener` but not `noreferrer`?

**Comment by ljharb** [comment]
The rule docs talk about the security issue, but I only this is also a UX issue. It's very rude to open new tabs/windows on a user.

As it relates to the security issue, however, either you get the full protection of it, or you get none, so I'm not sure what the advantage would be to weaken it. Can you not override the rule specifically on each of the links in question?

**Comment by travi** [comment]
I won't argue the UX issue at all as I fully agree. Unfortunately though, as I mentioned above, our team has lost that battle, at least for now.

While we may be able to disable per link, my goal with further config is to more explicitly capture our reasoning for disabling some of the rule in certain cases. In our case we know that links to internal properties are safe enough to at least not include the `noreferrer` so that we can still track those analytics across internal properties. I see no reason not to still include `noopener` for those internal links and think a reminder for that part from this rule would be helpful.

Just some thoughts for situations when use of `target=_blank` can't be avoided but still carry the desire to track referrer internally.

**Comment by ljharb** [comment]
There's an `allowReferrer` option now.
