### ISSUE TITLE
Proposal: Allow react/sort-prop-types to only sort by callbacks and required properties and not alphabetically

### ISSUE THREAD

**Issue by HenriBeck** [yannickcr/eslint-plugin-react#786]
## Proposal

Add another option to `sort-prop-types` called `noSortAlphabetically` that will allow disabling sorting the props by alphabet when the user wants it.

I would be happy to create a pull request.

**Comment by ljharb** [comment]
Or, alternatively, `noSortAlphabetically` - boolean option absence, and a value of `false`, should always have the same effect.

**Comment by HenriBeck** [comment]
Probably would even be better for better backward compatibility.
