### ISSUE TITLE
rule issue for react/jsx-space-before-closing

### ISSUE THREAD

**Issue by mvolkmann** [yannickcr/eslint-plugin-react#787]
I set this rule to "never", but when I run eslint it says
Configuration for rule "react/jsx-space-before-closing" is invalid:
Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"never"').

The docs say the valid values are "always" and "never".

**Comment by lencioni** [comment]
The docs say that the rule takes one argument, which can be either "always" or "never". Although it isn't very clear here, the options for eslint rules come after the severity. In this case you probably want to do something like `"react/jsx-space-before-closing": [2, "never"]` or `"react/jsx-space-before-closing": ["error", "never"]`.

More info: http://eslint.org/docs/user-guide/configuring#configuring-rules

It would be great to improve our docs though. Would you be interested in submitting a PR that makes this clearer?

**Comment by mvolkmann** [comment]
Ah yes. I should have caught that. Thanks for the info!
I created this pull request:
https://github.com/yannickcr/eslint-plugin-react/pull/788
