### ISSUE TITLE
Allow setting jsx pragma value in eslintrc

### ISSUE THREAD

**Issue by dominicbarnes** [yannickcr/eslint-plugin-react#80]
I'm using `jsxPragma: 'dom'` with my babel config. (so I don't need to manually add that pragma to each file) However, now my `dom` var appears unused, and there doesn't appear to be any config to set this value in the `.eslintrc`.

I'm not using React, but since the jsx pragma itself is supported for what appears to be other non-React users, I'm hoping this can be done. :)

**Comment by yannickcr** [comment]
I was not aware of this possibility with babel, I think we can add an option for jsx-uses-react like:

```json
{
  "jsx-uses-react": [1, {
    "pragma": "dom"
  }]
}
```

**Comment by dominicbarnes** [comment]
That would be amazing! Thanks :)

**Comment by kevinrenskers** [comment]
I'm also not using React, but this project is still extremely useful. One more rule that could benefit from the same sort of config would be "react-in-jsx-scope". Instead of having a hardcoded id of "React", it would be great to make this configurable as well.
