### ISSUE TITLE
Link new rules in change log to rule docs

### ISSUE THREAD

**Issue by sapegin** [yannickcr/eslint-plugin-react#805]
For example instead of this:

> - Adds `no-unused-prop-types` rule (#226 @EvNaverniouk)

do this:

> - Adds [no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md) rule (#226 @EvNaverniouk)

Would make updating the library much easier.

**Comment by lencioni** [comment]
Thanks for the feedback. I'd be happy to review a PR that improves the changelog like this!

**Comment by sapegin** [comment]
Do you generate them now?

**Comment by sapegin** [comment]
Awesome! Thanks!

**Comment by yannickcr** [comment]
Thanks for the suggestion. I linked all the rules names to the documentation, it should help to navigate to the documentation when we add/update a rule.

> Do you generate them now?

No, I make the changelog by hand at each release.
