### ISSUE TITLE
jsx-quotes does not catch errors in strings wrapped in {...}

### ISSUE THREAD

**Issue by deniseli** [yannickcr/eslint-plugin-react#808]
I have react/jsx-quotes configured with [2, "prefer-single"] and it cannot catch the case where I have some code that looks like this:
`<SomeComponent someProp={"asdf"} />`

For a sanity check, I verified that it does catch the default case:
`<SomeComponent someProp="asdf" />`

**Comment by ljharb** [comment]
In that case, `{"asdf"}` is a javascript string, not a jsx string, so the eslint core rule `quotes` should apply to that. This is working correctly.
