### ISSUE TITLE
Linting the React props: props.hasOwnProperty.call('x') -> Error: react/prop-types

### ISSUE THREAD

**Issue by webmato** [yannickcr/eslint-plugin-react#828]
I have this issue with **ESLint** and **React props / propTypes** 
```javascript
...
this.props.hasOwnProperty('modelConfig');   /* =>  ESLint error: "no-prototype-builtins"   */
this.props.hasOwnProperty.call(this.props, 'modelConfig');   /*  => ESLint error: "react/prop-types"  (underlined is the "call" word) */
...
MyClass.propTypes = {
  modelConfig: ImmutablePropTypes.map,
};
```
How to solve it?

**Comment by ljharb** [comment]
`const { hasOwnProperty } = this.props;` and then call it that way.

You don't want to call functions directly off of `this.props` anyways, since that will set `this.props` as the `this` value in the function.

**Comment by ljharb** [comment]
Alternatively, if that's not a prop, `Object.prototype.hasOwnProperty.call(this.props, 'modelConfig');`

**Comment by webmato** [comment]
@ljharb Thank you! I love this, it is so easy with ES6 :-)
