### ISSUE TITLE
No support for dynamic tag names

### ISSUE THREAD

**Issue by 1999** [yannickcr/eslint-plugin-react#831]
```javascript
({header, children}) => {
  const Tag = header ? 'h1' : 'div';

  return <Tag>{children}</Tag>
}
```

This code produces an error when checking it with eslint due to `no-used-variables` rule.
But it shouldn't: http://stackoverflow.com/questions/33471880/dynamic-tag-name-in-jsx-and-react

**Comment by yannickcr** [comment]
You must enable the [`react/jsx-uses-vars`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md) rule for ESLint to detect variables used in JSX.

**Comment by 1999** [comment]
Thanks, I missed this.
