### ISSUE TITLE
Gives error on next props

### ISSUE THREAD

**Issue by ButuzGOL** [yannickcr/eslint-plugin-react#840]
```js
const { container, ...props } = this.props;
let { category, icon } = props;
```

for category, icon gives error

**Comment by lencioni** [comment]
Hi @ButuzGOL! Can you tell us specifically which rules give you an error here? It might be helpful to include the full output of an ESLint run along with a copy of your ESLint configuration.

**Comment by ButuzGOL** [comment]
Config: 'react/no-unused-prop-types': 1,
Example:
```
import React, { PropTypes, Component } from 'react';

export default class Checkbox extends Component {
  constructor() {
    super();
    this.a = 'a';
  }

  render() {
    const { container, ...props } = this.props;
    const { category, icon } = props;

    return (
      <div>
        {container} {category} {icon}
      </div>
    );
  }
}

Checkbox.propTypes = {
  container: PropTypes.string,
  category: PropTypes.string,
  icon: PropTypes.bool,
};
```
Output: 
src/scripts/Checkbox.js
24:13  warning  'category' PropType is defined but prop is never used  react/no-unused-prop-types
25:9   warning  'icon' PropType is defined but prop is never used      react/no-unused-prop-types
