### ISSUE TITLE
Add no-unescaped-entities to recommended configuration

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#841]
This rule was added by #681 and I think it should be added to the recommended configuration for the next major version bump.

**Comment by rauchg** [comment]
@ljharb I'm curious what the downsides are to not escaping `'`? Makes writing stuff pretty difficult, but I'm sure there's a good reason

**Comment by ljharb** [comment]
@rauchg The rule documentation should explain it; basically, it's highly likely there's a bug.

Separately, it shouldn't impact "writing stuff" at all, since straight quotes are typographically incorrect, and you don't need to escape curly quotes.
