### ISSUE TITLE
Add no-children-prop to recommended configuration

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#842]
This rule prevents children from being passed in as a `children` prop and will be added by #722. It might be nice to add it to the recommended configuration. Thoughts?

**Comment by ljharb** [comment]
I don't think this should be recommended. I feel that nested children are the entire value proposition of jsx, and if one is not using them, one should not be using jsx either.

**Comment by lencioni** [comment]
I think you misunderstand what the rule does. It prevents using `<div children={foo}>` in favor of requiring you to use `<div>{foo}</div>` (similarly for non-JSX).

**Comment by ljharb** [comment]
Whoops, you're right. In that case, I'm 👍
