### ISSUE TITLE
UNMET PEER DEPENDENCY eslint@^2.0.0 || ^3.0.0

### ISSUE THREAD

**Issue by heldrida** [yannickcr/eslint-plugin-react#848]
Error after installing eslint-plugin-react, there's an unmet peer dependency for eslint, which I have installed and is the latest. Here's the command line:

`helder@Helders-MBP:~$ npm install -g eslint
/Users/helder/.nvm/versions/node/v6.6.0/bin/eslint -> /Users/helder/.nvm/versions/node/v6.6.0/lib/node_modules/eslint/bin/eslint.js
/Users/helder/.nvm/versions/node/v6.6.0/lib
└── eslint@3.5.0

helder@Helders-MBP:~$ npm install -g eslint-plugin-react
/Users/helder/.nvm/versions/node/v6.6.0/lib
├── UNMET PEER DEPENDENCY eslint@^2.0.0 || ^3.0.0
└── eslint-plugin-react@6.2.2

npm WARN eslint-plugin-react@6.2.2 requires a peer of eslint@^2.0.0 || ^3.0.0 but none was installed.`

**Comment by ljharb** [comment]
I wouldn't recommend installing eslint globally.

**Comment by yannickcr** [comment]
It's a false warning by `npm`, everything should be working as expected after the installation.

**Comment by gluons** [comment]
But Atom Linter member (#514) say
> If you are using a global eslint, you will need to install eslint configs and plugins globally as well.

---
However, it's not critical problem. I still use it with Atom Linter.

**Comment by mherodev** [comment]
Seeing this when trying to `npm install eslint -g` and then `npm install eslint-plugin-react -g`.

I suppose I can just install the project to avoid Atom's errors, but often times I am pulling a project not to run it, but to browse the source. It'd be nice if this didn't fail so Atom wouldn't yell at me for not running `npm install` on every project I clone.

**Comment by ljharb** [comment]
That seems like something worth filing on Atom itself - ideally you should have only locally installed eslints, and Atom should be able to silently ignore repos without an eslint config.

**Comment by mherodev** [comment]
The issue is that almost every repo these days that I'm pulling has an eslintrc file, so Atom tries to use it and fails. I suppose alternatively I could delete these configs when I'm browsing source but not feeling like installing.

**Comment by ljharb** [comment]
Are you not running `npm install` in these repos prior to interacting with the source? If you are, why would Atom be failing?

**Comment by mherodev** [comment]
Sorry, that's what I referenced above:

> I suppose I can just install the project to avoid Atom's errors, but often times I am pulling a project not to run it, but to browse the source. It'd be nice if this didn't fail so Atom wouldn't yell at me for not running `npm install` on every project I clone.

**Comment by ljharb** [comment]
Ah, gotcha.

In that case I'd submit a bug to Atom to be silent when `eslint` isn't found :-)
