### ISSUE TITLE
prefer-stateless-function should allow components with childContextTypes

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#853]
If you try to set `childContextTypes` on a stateless functional component, React will give you the following warning:

> childContextTypes cannot be defined on a functional component.

https://github.com/facebook/react/blob/2058d47e7bfaccf0983aaf673d86acd89d7918ce/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L60

The prefer-stateless-function rule should allow this.

Related #501.

**Comment by lencioni** [comment]
I wonder if we should also add a rule that warns you if you are trying to add `childContextTypes` on a SFC. Probably should.

**Comment by ljharb** [comment]
Yes, both `prefer-stateless-function` should skip over comps with childContextTypes, and we should have a separate rule that prevents childContextTypes on an SFC.
