### ISSUE TITLE
Linting proptype shape, does not recognize deconstructed props attributes

### ISSUE THREAD

**Issue by nwikstrand** [yannickcr/eslint-plugin-react#866]
Linting proptype shape, does not recognize deconstructed props attribute.

`'bar.baz' PropType is defined but prop is never used react/no-unused-prop-types`

Failing example with deconstructed props:
```
const Foo = ({ bar }) => (
  <div>
    {bar.baz}
  </div>
);

Foo.propTypes = {
  bar: React.PropTypes.shape({
    baz: React.PropTypes.string,
  }),
};
```

Working example with non deconstructed props:
```
const Foo = (props) => (
  <div>
    {props.bar.baz}
  </div>
);

Foo.propTypes = {
  bar: React.PropTypes.shape({
    baz: React.PropTypes.string,
  }),
};
```

**Comment by nwikstrand** [comment]
Closing this, got a head of my self and missed that

**Comment by ljharb** [comment]
Did you figure this out?
