### ISSUE TITLE
Why is rule named "jsx-sort-prop-types"?

### ISSUE THREAD

**Issue by matthewwithanm** [yannickcr/eslint-plugin-react#87]
Sorry if this is a dumb question, but why does the "jsx-sort-prop-types" rule contain "jsx" in the name? It seems to me that it's just about component definitions.

**Comment by AlexKVal** [comment]
https://github.com/yannickcr/eslint-plugin-react/pull/72

There was already `jsx-sort-props` rule in the plugin
and then was request https://github.com/yannickcr/eslint-plugin-react/issues/38 about sorting types of props, based on https://github.com/yannickcr/eslint-plugin-react/issues/16 `jsx-sort-props` sorted props.

So I've just named it as a sequel.

**Comment by yannickcr** [comment]
Yes, there is no reason to have `jsx-` in this rule name since it is not related to JSX.
But I think we have some cleaning to do in rules names (only JSX related rules should be prefixed with `jsx-`, `jsx-uses-react` do not always use React since we now handle custom pragma, etc.)

**Comment by pwmckenna** [comment]
@yannickcr if someone were to whip up a PR for this, should it be backwards compatible with regards to rule setting in .esslintrc etc?

**Comment by yannickcr** [comment]
@pwmckenna I think we should rename the rule and keep the current one as an alias for now, but with a deprecation warning (like `jsx-quotes`).

Then, in a later time, remove it in a new major release.
