### ISSUE TITLE
react/jsx-filename-extension and parsing only .JSX files

### ISSUE THREAD

**Issue by LucianoGraziani** [yannickcr/eslint-plugin-react#875]
When I used this rule, I thought eslint wouldn't throw errors or warnings about other react rules. But my guess was wrong: I have a .js file that use `this.setState`, but isn't a React Component, is a homemade method BUT it throws `react/no-set-state` warning.

It would be nice if eslint could filter what rules he use when parsing a .js file, .jsx file, or any kind.

Thanks.

**Comment by ljharb** [comment]
That would require rules knowing about other rules' settings, which isn't possible in eslint.

Also, you can have React components without using any JSX at all (`React.createClass`, `class`) so that wouldn't make sense as a default behavior.
