### ISSUE TITLE
no-unused-prop-types - count all properties as used when met {...this.props}

### ISSUE THREAD

**Issue by victor-homyakov** [yannickcr/eslint-plugin-react#879]
Suppose one of components has a bunch of properties, and just passes them to child component `<SomeChild {...this.props} />`. In this case `no-unused-prop-types` rule will mark all properties as unused. Although rule could be manually disabled for the component, I'd like to see that rule can handle that situation, maybe with an additional option in configuration.

**Comment by ljharb** [comment]
That goes far beyond what a linter is capable of. Spread props are dynamic at runtime and defy static analysis.

**Comment by victor-homyakov** [comment]
- linter could just mark all properties as used when it sees `{...this.props}`
- linter could use sort of weak warning or info when some property is unused explicitly but is passed to child component with `{...this.props}`, e.g. "Potentially unused property foo" or "Property foo is not used explicitly"

**Comment by ljharb** [comment]
The rule's severity is all or nothing - either it's an error (when the rule is configured as an error), or it doesn't report at all.

**Comment by victor-homyakov** [comment]
IMO configured severity is sort of upper bound, and linter may report some issues with lower severity

**Comment by ljharb** [comment]
@victor-homyakov that's not how eslint works. Rules only have one "report" function, and everything matches the configured severity.

**Comment by victor-homyakov** [comment]
:(
OK, what about adding new option to silence this rule when spread operator `{... this.props}` is used?

**Comment by ljharb** [comment]
I think only when the entire props object is spread, it makes sense to mark all properties as used.

**Comment by SavePointSam** [comment]
I hope there is a chance this could be explored deeper.

The only false positives I get anymore are from using `{ ...this.props }`.

**Comment by haasDev** [comment]
I am also running into this.  Having to turn off that rule around my proptypes fairly frequently.

**Comment by DianaSuvorova** [comment]
@ljharb this issue can be closed. Fixed in #1303.

The test case discussed in the thread is line 1319 [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/no-unused-prop-types.js)
