### ISSUE TITLE
installting plugin

### ISSUE THREAD

**Issue by jesmarquez** [yannickcr/eslint-plugin-react#881]
Hi, I have this error
npm -v
3.10.6
node -v
4.5.0

$ npm install eslint-plugin-react
meanjs@0.5.0-beta D:\jamarquez\comovalatest
`-- UNMET PEER DEPENDENCY eslint-plugin-react@6.3.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint-plugin-react@^4.0.0 but none was installed.
npm WARN grunt-istanbul@0.6.2 requires a peer of grunt@~0.4.5 but none was installed.
npm ERR! code 1

Any help!

**Comment by ljharb** [comment]
Since you're using `eslint-config-airbnb`, install the latest version of it (up to 12 now) using the specific install command in the readme, so that it updates all the peer dependencies also. That will include the latest eslint-plugin-react.

**Comment by jesmarquez** [comment]
I run this command:
npm install --save-dev eslint-config-airbnb eslint@^12.0.0 eslint-plugin-jsx-a11y@^12.0.0 eslint-plugin-import@^12.0.0 eslint-plugin-react@^12.0.0
but i got this message:
No compatible version found: eslint@^12.0.0
npm ERR! Valid install targets:
npm ERR! 3.7.0, 3.6.1, 3.6.0

**Comment by ljharb** [comment]
Not that command. The multiline shell script [here](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnb-1)

**Comment by RoboBurned** [comment]
I have an error while installing the plugin with eslint globally..
```
D:\react\book\hello-world>npm i -g eslint-plugin-react
+-- UNMET PEER DEPENDENCY eslint@^2.0.0 || ^3.0.0
`-- eslint-plugin-react@6.10.3
npm WARN eslint-plugin-react@6.10.3 requires a peer of eslint@^2.0.0 || ^3.0.0 but none was installed.
```
The command shows that I have eslint of required version.
```
D:\react\book\hello-world>npm ls -g eslint
`-- eslint@3.0.0
```

**Comment by ljharb** [comment]
I believe when installing globally everything has to be installed on the same command; however, nothing should ever be installed globally. If you install eslint per-project, it should work fine.

Closing since this original issue seems resolved.
