### ISSUE TITLE
Cannot read property 'length' of undefined in lib/rules/prop-types.js line 51

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#9]
After upgrading from 1.3.0 to 1.4.1, I am getting this error message:

```
/path/to/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:51
        for (var i = 0, j = property.value.properties.length; i < j; i++) {
                                                     ^
TypeError: Cannot read property 'length' of undefined
    at /path/to/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:51:54
    at Array.forEach (native)
    at EventEmitter.ObjectExpression (/path/to/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:46:23)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/path/to/project/node_modules/eslint/lib/eslint.js:683:25)
    at Controller.__execute (/path/to/project/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/path/to/project/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/path/to/project/node_modules/eslint/lib/eslint.js:676:24)
    at processFile (/path/to/project/node_modules/eslint/lib/cli-engine.js:172:23)
    at /path/to/project/node_modules/eslint/lib/cli-engine.js:271:26
    at /path/to/project/node_modules/eslint/lib/util/traverse.js:61:17
```

**Comment by yannickcr** [comment]
I'll have a look at it. Can you share the code that trigger this error?

**Comment by lencioni** [comment]
I'll try to whittle it down. Might take a bit.

**Comment by lencioni** [comment]
Ah, it looks like it happens when I am defining an object outside of the component to hold the propTypes, and then assigning it to that variable.

Something like:

```javascript
const myPropTypes = {
  ...
};

const MyComponent = React.createClass({
  propTypes: myPropTypes,

  ...
});
```

**Comment by yannickcr** [comment]
Ok, I see. I can fix the crash but I am not sure how to check propTypes definition in this case. I need to figure that out.

**Comment by lencioni** [comment]
Even if I try disabling this rule for the affected file via `/* eslint-disable react/prop-types */` or even `/* eslint-disable */`, I still see the crash. If I disable it via `.eslintignore`, the crash is avoided.

I've refactored my code so I don't need this anymore, but it would be nice to be able to at least disable this rule on a per-file basis using the comments.

**Comment by josiasds** [comment]
The same error is happening here: https://github.com/shakacode/react-webpack-rails-tutorial/blob/cd35765c0a0d1a755c30944b4879bc12ca8e8163/client/app/stores/commentsStore.js#L8

[This](https://github.com/shakacode/react-webpack-rails-tutorial/pull/168) fixes the error, but I don't know exactly why. Any ideas?
