### ISSUE TITLE
jsx-indent wrong ternary indend

### ISSUE THREAD

**Issue by klimashkin** [yannickcr/eslint-plugin-react#901]
Hi again!
After updating from 6.3.0 to 6.4.0/6.4.1 this code generates error:
<img width="359" alt="screen shot 2016-10-10 at 3 52 59 pm" src="https://cloud.githubusercontent.com/assets/576077/19253665/a6aba5e4-8f01-11e6-9f47-da3a6b7d2154.png">

And this:
<img width="410" alt="screen shot 2016-10-10 at 3 54 14 pm" src="https://cloud.githubusercontent.com/assets/576077/19253687/d48a164e-8f01-11e6-8ebf-ebcf73fa14b9.png">

It wants one more indent before second ternary expression

**Comment by klimashkin** [comment]
Config the same: https://github.com/yannickcr/eslint-plugin-react/issues/897

**Comment by chentsulin** [comment]
It seems have a regression between `v6.6.0` and `v6.7.0`. Test failed again on `v6.7.0`, but passed with `v6.6.0`.

Could we reopen this issue?
