### ISSUE TITLE
[Q] prop-types rule treats all functions as React fn

### ISSUE THREAD

**Issue by tleunen** [yannickcr/eslint-plugin-react#908]
Probably more a question than everything else but... When declaring a function returning a react element, the function requires to have prop types defined.

Does it mean we shouldn't have function call to render something?
Like, having `<Badge sth={sth} />` instead of `{renderBadge(sth)}`?

Is there a perf gain/loss of one way vs the other?

**Comment by ljharb** [comment]
Yes, you should prefer SFCs there. However, the propType rule shouldn't be triggering on those functions - it's just hard to tell the difference.

**Comment by ljharb** [comment]
Note the reasons are for maintainability; perf is the least important consideration.
