### ISSUE TITLE
more accurate location for require-render-return violations

### ISSUE THREAD

**Issue by kevinbarabash** [yannickcr/eslint-plugin-react#927]
I noticed that `require-render-return` returns the `ClassDeclaration` or `ObjectExpression` when the `render()` method doesn't have a return.  With some tweaking I was able to get it to return the node for the `render()` method itself.  I was wondering if you'd be interested in a PR for such a change?

**Comment by yannickcr** [comment]
Yes, we are totally interested for that kind of improvements :)

**Comment by ljharb** [comment]
In general, please do send PRs for this kind of thing :-)
