### ISSUE TITLE
What does <enabled> mean?!?

### ISSUE THREAD

**Issue by pavlelekic** [yannickcr/eslint-plugin-react#940]
I want to thank everyone involved for the effort in this project, this is really important stuff, however I must say that the pages here are horrible. I don't know who wrote the documentation but it's one of the worst I've seen.

I'm really frustrated because I've spent some time looking at these pages, I can't find what is implied by <enabled>?!? How can you write some symbol, and not write what does it mean, should I write boolean true/false, 1, or string "enabled"?!? It's not clear at all.

Also here are the options for the jsx-no-bind rule:

"jsx-no-bind": [<enabled>, {
  "ignoreRefs": <boolean> || false,
  "allowArrowFunctions": <boolean> || false,
  "allowBind": <boolean> || false
}]

1. like I already said, it's not clear what is <enabled>, and how does it differ from <boolean> since it seems it should be something like a boolean
2. option value: <boolean> || false ?!?
If a value is a boolean, of course it can only be true or false, what do you mean by `|| false`?!? Did you mean true || false?

**Comment by pavlelekic** [comment]
In the end I figured it out, I found in the docs on the eslint website that <enabled> can be 0, 1 or 2 (which are also horrible names, because when someone encounters 0, 1 or 2 he/she will not know what they mean, he/she will have to waste time googling for the meaning). I know it's not your fault, and I'm sorry I've been a bit harsh.

**Comment by tleunen** [comment]
You can also use `off, warn and error`. (See [docs](http://eslint.org/docs/user-guide/configuring#configuring-rules))

**Comment by ljharb** [comment]
It is assumed that when reading eslint plugin docs, the user is already familiar with how eslint, and all eslint rules, are configured.
