### ISSUE TITLE
Activating eslint-react makes eslint ignore some other rules.

### ISSUE THREAD

**Issue by sassanh** [yannickcr/eslint-plugin-react#942]
When I activate `eslint-react` in `.eslintrc` file, eslint ignores rules such as `semi`. So a line like this for example:
```
    const a = 1
```
doesn't get fixed when I run `eslint --fix <filename>` (the fix is to add a semicolon at the end.)

**Comment by ljharb** [comment]
Can you share your two eslintrc files?

**Comment by sassanh** [comment]
Trying to prepare eslintrc files I found out the problem is related to `eslint-plugin-babel`. Sorry for taking your time one this. Closing.
