### ISSUE TITLE
Arrow function should not return assignment

### ISSUE THREAD

**Issue by TaurusWood** [yannickcr/eslint-plugin-react#948]
In my code if I write `ref={arg => this.deleteBtn = arg}`, the ESLint will show error;
`  <button
            type="button"
            className="btn btn-xs close"
            onClick={this.deleteTask}
            ref={arg => this.deleteBtn = arg}
          >
`
The ESLint : Arrow function should not return assignment.(no-return-assign)

So , If that is:
` <button
            type="button"
            className="btn btn-xs close"
            onClick={this.deleteTask}
            ref={(arg) => { this.deleteBtn = arg; }}
          >`

Then the ESLint has no error show

**Comment by ljharb** [comment]
Sounds like the error is doing the right thing! Your corrected code is indeed better.

**Comment by hazratgs** [comment]
Try it like this
`ref={arg => (this.deleteBtn = arg)}`

**Comment by ljharb** [comment]
That's still returning an assignment. If the eslint rule allows that, it's a bug in the rule.

**Comment by ljharb** [comment]
Ah, it turns out `no-return-assign` defaults to an option of "except-parens". I strongly encourage you to set that to "always" instead.

**Comment by chotalia** [comment]
this worked for me
`ref={arg => { this.deleteBtn = arg; } }`

**Comment by bimalgrg519** [comment]
Small change....
ref={(arg) => {this.deleteBtn = arg; }}
