### ISSUE TITLE
Faulty infix operator warning when no space after variable definition

### ISSUE THREAD

**Issue by BlockChange** [yannickcr/eslint-plugin-react#954]
When:

`let foo= bar + ' thing'`

It will throw the `Infix operators must be spaced` warning.

While it should throw a warning that there is no space after variable, but i'm not sure that even exists.

**Comment by yannickcr** [comment]
This is an error from [ESLint's `space-infix-ops` rule](http://eslint.org/docs/rules/space-infix-ops) and has nothing to do with `eslint-plugin-react`.

If you think this is a bug in the `space-infix-ops` rule please open an issue in the [ESLint repository](https://github.com/eslint/eslint).
