### ISSUE TITLE
@jsx pragma matching limitations

### ISSUE THREAD

**Issue by zertosh** [yannickcr/eslint-plugin-react#962]
A few issues I noticed:

* The pragma can change throughout the linting of a file if subsequent matches are found. IMHO, the way babel treats it makes sense: The first pragma found controls.

* The regex is pretty strict. Babel allows for `@jsx` in block as well as line comments. It also need not be the only thing in a block comment. For example, this is ok:

```
/**
 * Copyright ....
 * @jsx Foo
 */
```

**Comment by ljharb** [comment]
Not sure when this was fixed, but it's all working fine now (see the linked test cases).
