### ISSUE TITLE
`prop-types` should cover `props` in `setState()` too

### ISSUE THREAD

**Issue by daltones** [yannickcr/eslint-plugin-react#963]
As specified in [React docs](https://facebook.github.io/react/docs/react-component.html#setstate):

> It's also possible to pass a function with the signature `function(state, props) => newState`.

So when we use something like `this.setState((state, props) => {})`, that `props` argument must be covered by rule `prop-types` too.

**Comment by michaeljota** [comment]
I just going to made another useless comment just to point out this is badly needed, as sometimes you need to access to props to set the state or something, and the linter will show this as an error (For your point, I realice that I did not actually use the props to set the state, but for resolve the state value). 

However, with #943 this would be necessary.
