### ISSUE TITLE
i have an installation problem

### ISSUE THREAD

**Issue by hackereg35** [yannickcr/eslint-plugin-react#964]
i have eslint v3.10.2 installed globaly and it's working good,
but trying to install the react plugin i get this error
`/usr/lib
├── UNMET PEER DEPENDENCY eslint@^2.0.0 || ^3.0.0
└── eslint-plugin-react@6.7.1 

npm WARN eslint-plugin-react@6.7.1 requires a peer of eslint@^2.0.0 || ^3.0.0 but none was installed.
`

**Comment by ljharb** [comment]
Nothing should be installed globally; install everything locally and it will work fine.

**Comment by hackereg35** [comment]
i tried but i keep getting the same problem, and on the plugin npm page they say i can install it globally [https://www.npmjs.com/package/eslint-plugin-react](url)

**Comment by ljharb** [comment]
That's true, but it's still best to never install anything globally.

**Comment by hackereg35** [comment]
but i want to install it globally, so i don't have to install it on every project

**Comment by ljharb** [comment]
It's supposed to be installed on every project, and explicitly listed in every project's dependency list.

**Comment by snkshukla** [comment]
@hackereg35 did you find any solution for this?

**Comment by montrealist** [comment]
Also wondering the same thing as above.

**Comment by yannickcr** [comment]
Same as #848, it's a false warning by npm, everything should be working as expected after the installation.
