### ISSUE TITLE
deprecation of jsx-space-before-closing

### ISSUE THREAD

**Issue by remitbri** [yannickcr/eslint-plugin-react#967]
I'm using eslint@3.10.2 and eslint-plugin-react@6.7.1
It's possible to write a configuration such as
```js
{
  "react/jsx-space-before-closing" : [ "error", "never" ],
  "react/jsx-tag-spacing" : [ "error", {
    closingSlash : "never",
    beforeSelfClosing : "always",
    afterOpening : "never",
  }]
}
```
meaning code such as
```jsx
const test = () => (
  <div>
    <br/>
    <br />
  </div>
)
```
gets an error for both having (2nd br) and not having (1st br) a space before the closing bracket.
The `jsx-space-before-closing` rule should be deprecated since `jsx-tag-spacing` handles its scope and more.

**Comment by ljharb** [comment]
That's exactly the plan. https://github.com/yannickcr/eslint-plugin-react/issues/693#issuecomment-234842809

**Comment by remitbri** [comment]
Cool :)
