### ISSUE TITLE
sort-comp: constructor must be placed after componentWillUnmount

### ISSUE THREAD

**Issue by tleunen** [yannickcr/eslint-plugin-react#97]
With `sort-comp` enabled and ES6 classes, the plugin reports that `constructor` should be after `componentWillUnmount`. It should be an exception...

Here's a simple example with the issue:
```js
export default class MyClass extends React.Component {
    constructor(props) {
        super(props);
    }

    componentDidMount() {
    }

    componentWillUnmount() {
    }

    render() {
        return <div></div>;
    }
}
```

**Comment by yannickcr** [comment]
Currently the [default configuration](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md#rule-details) is:

1. Lifecycle methods
2. Custom methods
3. `render` method

`constructor` is not specified in any group, so it is considered as a custom method and the rule asks you to place it after `componentWillUnount`(the last lifecycle method).

I think I will update the default configuration to get:

1. `constructor` method
2. Lifecycle methods
3. Custom methods
4. `render` method

For now you can set up a custom configuration in your .eslintrc:

```json
...
"react/sort-comp": [1, {
  "order": [
    "constructor",
    "lifecycle",
    "everything-else",
    "render"
  ]
}]
...
```

**Comment by tleunen** [comment]
Sounds great! And thanks for the workaround
