### ISSUE TITLE
Unexpected token in pure functions

### ISSUE THREAD

**Issue by ninahaack** [yannickcr/eslint-plugin-react#975]
Hi, I'm having troubles with pure functions but I don't know if it's really a bug or not. I'm new in React.

I have this pure function:
```js
import React from 'react'
import { Header } from 'supernova-inloco'

const PanelHeader = props => (
  document.title = 'PubFin - Pagamento de publishers'
  <Header>
    Pagamento de publishers
  </Header>
  )

PanelHeader.propType = {
  children: PropTypes.node
}

export default PanelHeader
```

And I'm getting this error: Parsing error: Unexpected token, expected ,
```
document.title = 'PubFin - Pagamento de publishers'
<Header>
  Pagamento de publishers
            ^
</Header>
```

But if it's a class component there's no problem. Just it saying to transform to a pure function:

```js
import React from 'react'
import { Header } from 'supernova-inloco'

class PanelHeader extends React.Component {
  render() {
    document.title = 'PubFin - Pagamento de publishers'

    return (
      <Header>
        Pagamento de publishers
      </Header>
    )
  }
}

export default PanelHeader
```

I'm using: eslint-plugin-react: 6.7.1 and eslint: 3.10.2

Thank you for your help

**Comment by ljharb** [comment]
You've got a few problems there.

1, you don't want to have side effects in a render - specifically setting document.title. 2 tho, you're using an implicit return arrow function, but you have two statements. Change it to an explicit return arrow function and you won't have a syntax error:
```jsx
const PanelHeader = (props) => {
  document.title = 'Blah';
  return <Blah />;
};
```

**Comment by ljharb** [comment]
You may want to look into https://www.npmjs.com/package/react-document-titlefor setting the document title.

**Comment by ninahaack** [comment]
Thank you very much for your help!
