### ISSUE TITLE
react/jsx-uses-react not working 

### ISSUE THREAD

**Issue by agalazis** [yannickcr/eslint-plugin-react#993]
even though the plugin is condigured and react/jsx-uses-react  is enabled i get:
'React' is defined but never used

I am using eslint 3.11.1

**Comment by ljharb** [comment]
Can you share the file on which this is erroring?

**Comment by ljharb** [comment]
(note that it's JSX syntax that requires use of `React`, not a `.jsx` extension)

**Comment by lencioni** [comment]
It might also help to share your eslint configuration as well as check to make sure that there aren't any overriding .eslintrc files in intermediary directories.

**Comment by agalazis** [comment]
```
// @flow
import React, {PropTypes} from 'react';
// more imports here...
const Component = (props: Object) => {
//more code here
     return (<div></div>)
//therre is more jsx in the above
}
//more code here
export default Component;
```

**Comment by agalazis** [comment]
@lencioni  I am using eslint -c to specify configuration 

```
...
 "extends": ["eslint:recommended", "plugin:react/recommended", "plugin:flowtype/recommended"],
  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "jsx": true
    },
    "sourceType": "module"
  },
  "plugins": [
    "react",
    "flowtype"
  ]
...
```
I have also tired manually enabling the rule but sill the same

**Comment by ljharb** [comment]
@agalazis what about the file this is erroring out on?

**Comment by ljharb** [comment]
If you remove the flow syntax from the file, does the error still happen?

**Comment by lencioni** [comment]
It would be helpful if you could create a repo that has a minimal reproduction of the issue.

**Comment by agalazis** [comment]
Sorry for not getting back earlier couldn't get it replicated in any other project after playing with build /linting scripts (changing order) it worked. thanks!
