### ISSUE TITLE
forbid-prop-types doesn't work outside Component.proptypes

### ISSUE THREAD

**Issue by burabure** [yannickcr/eslint-plugin-react#997]
if you have something like
```js
const propTypes = {
  foo: any,
  bar: object,
  baz: array,
}

...

MyComponent.propTypes = propTypes
```

forbid-prop-types won't error out because it checks only for proptypes directly declared on `MyComponent.propTypes`

**Comment by ljharb** [comment]
It should definitely follow in-file propType declarations like that.

Can you try using `PropTypes.object` etc, rather than destructuring things off of `PropTypes`, to confirm whether that's the issue instead or not?

**Comment by burabure** [comment]
yeah it's the import destructuring:

```js
import React, { PropTypes } from 'react'

const { string, any } = PropTypes // doesn't work
const { string, any } = React.PropTypes // works
...
```

**Comment by thomsta** [comment]
Is there something new about this issue?

**Comment by golopot** [comment]
This is already fixed. https://github.com/yannickcr/eslint-plugin-react/blob/e835aaf52019db06f16342f44fffb12d75e79856/tests/lib/rules/forbid-prop-types.js#L784-L790
