### ISSUE TITLE
Array.prototype.find and node < 4

### ISSUE THREAD

**Issue by sigorilla** [yannickcr/eslint-plugin-react#999]
Hi!

In [`package.json`](https://github.com/yannickcr/eslint-plugin-react/blob/master/package.json#L40) it is written that the plugin supports the version of node `>= 0.10`. But `Array.prototype.find` isn't supported for node `<4`.

List of files using `find` method:
1. [style-prop-object 1](https://github.com/yannickcr/eslint-plugin-react/blob/e1697996ff494bf584057418e2974ece7f3d99d8/lib/rules/style-prop-object.js#L50)
1. [style-prop-object 2](https://github.com/yannickcr/eslint-plugin-react/blob/e1697996ff494bf584057418e2974ece7f3d99d8/lib/rules/style-prop-object.js#L28)
1. [no-children-prop](https://github.com/yannickcr/eslint-plugin-react/blob/3f393a2893db4976115806da0206dd18dab59cc4/lib/rules/no-children-prop.js#L56)

I think it's need to add polyfill or to drop support for node `<4`

**Comment by ljharb** [comment]
In order to retain eslint v2/node 0.10 compat, this definitely needs to be fixed.
